// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/geow/Community",["dijit","dojo","dojox","dojo/require!arcgisonline/sharing/util,arcgisonline/sharing/dijit/dialog/NotificationsDlg"],function(f,d,g){d.provide("arcgisonline.sharing.geow.Community");d.require("arcgisonline.sharing.util");d.require("arcgisonline.sharing.dijit.dialog.NotificationsDlg");arcgisonline.sharing.geow.Community={util:arcgisonline.sharing.util,i18n:function(){if(this._i18n)return this._i18n;this._i18n=d.i18n.getLocalization("arcgisonline","arcgisonline").common;
d.mixin(this._i18n,d.i18n.getLocalization("arcgisonline","arcgisonline").community);return this._i18n},getProfile:function(a,c,b){if(null===a)return d.publish("globalMessage",[{message:this.i18n().noUser,type:"error",duration:0}]),null;this.util.getJson(esriGeowConfig.restBaseUrl+"community/users/"+a,c,null)},getProfileThumbnailUrl:function(a,c){if(null!==a.thumbnail){var b=this.util.getToken();if(c){var e=esriGeowConfig.restBaseUrl;esriGeowConfig.useDefaultIdentityStore&&(e=!1!==esriGeowConfig.useSSL?
this.util.getSecureUrl(e):e);return e+"community/users/"+a.username+"/info/"+a.thumbnail+(null===b||0===b.length?"":"?token\x3d"+b)}return esriGeowConfig.restBaseUrl+"community/users/"+a.username+"/info/"+a.thumbnail+(null===b||0===b.length?"":"?token\x3d"+b)}return null},updateProfile:function(a,c,b){b=this.util.getUser();null==b&&d.publish("globalMessage",[{message:this.i18n().mustLogIn,type:"error",duration:0}]);b=this.util.getSecureUrl(esriGeowConfig.restBaseUrl)+"community/users/"+b.email+"/update";
this.util.postForm(a,b,c)},updateProfileByUser:function(a,c,b){null!=this.util.getUser()&&(b=this.util.getSecureUrl(esriGeowConfig.restBaseUrl)+"community/users/"+a.username.value+"/update",this.util.postForm(a,b,c))},getUserGroups:function(a,c){var b=this.util.getUser();b&&b.email?b=this.getUserGroupsByUser(b.email,a,c):(b=new d.Deferred,b.resolve());return b},getUserGroupsByUser:function(a,c,b){a=esriGeowConfig.restBaseUrl+"community/users/"+a;var e=new d.Deferred;this.util.request({url:a}).then(d.hitch(this,
function(b){e.resolve(b);c&&c(b)}),d.hitch(this,function(a){e.reject(a);b&&b(a)}));return e},getGroup:function(a,c,b){this.util.getJson(esriGeowConfig.restBaseUrl+"community/groups/"+a,c,b)},createGroup:function(a,c,b){null!=this.util.getUser()&&this.util.postForm(a,esriGeowConfig.restBaseUrl+"community/createGroup",c,b)},updateGroup:function(a,c,b,e){null!=this.util.getUser()&&this.util.postForm(c,esriGeowConfig.restBaseUrl+"community/groups/"+a+"/update",b,e)},deleteGroup:function(a,c,b){null!=
this.util.getUser()&&this.util.postJson("",esriGeowConfig.restBaseUrl+"community/groups/"+a.id+"/delete",c,b)},reassignGroup:function(a,c,b,e){null!=this.util.getUser()&&this.util.postJson({targetUsername:c},esriGeowConfig.restBaseUrl+"community/groups/"+a.id+"/reassign",b,e)},leaveGroup:function(a,c,b){this.util.postJson("",esriGeowConfig.restBaseUrl+"community/groups/"+a.id+"/leave",c,b)},inviteToGroup:function(a,c,b){null!=this.util.getUser()&&this.util.globalMessage("TODO: not implemented in rest",
"error",0)},searchGroups:function(a,c,b){this.util.getJson(esriGeowConfig.restBaseUrl+"community/groups?q\x3d"+a,c)},searchToStore:function(a){var c=[];d.forEach(a.results,function(b,a){var d={id:a,title:this._getGroupTitleLink(b),owner:b.owner,description:b.description,imageUrl:b.imageUrl,tags:b.keywords,created:b.created};c[a]=d},this);return new d.data.ItemFileReadStore({data:{identifier:"id",label:"item",items:c}})},_getGroupTitleLink:function(a){return"\x3ca href\x3d'group.html?owner\x3d"+a.owner+
"\x26title\x3d"+encodeURIComponent(a.title)+'\' class\x3d"esriGroupTitle" alt\x3d'+this.i18n().viewGroupDetails+" title\x3d"+this.i18n().viewGroupDetails+"\x3e"+a.title+"\x3c/a\x3e"},getNotifications:function(){arcgisonline.sharing.dijit.dialog.NotificationsDlg.prototype.statics.getInstance().show()},getNotificationsCount:function(){var a=this.util.getUser();null!=a&&this.util.getJson(esriGeowConfig.restBaseUrl+"community/users/"+a.email+"/notifications",d.hitch(this,function(a,b){d.publish("onNotificationCount",
[a.notifications.length])}))},deleteNotifictation:function(a){var c=this.util.getUser();null!=c&&this.util.postJson("",esriGeowConfig.restBaseUrl+"community/users/"+c.email+"/notifications/"+a+"/delete",d.hitch(this,function(a,c){d.publish("onNotificationDelete",[""])}))},updateUserSecure:function(a,c,b,d){d=esriGeowConfig.restBaseUrl;esriGeowConfig.useDefaultIdentityStore&&(d=!1!==esriGeowConfig.useSSL?this.util.getSecureUrl(d):d);this.util.postForm(c,d+"community/users/"+a+"/update",b)}}});