// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
require({cache:{"url:webSceneViewer/widgets/OptionsMenu/templates/OptionsMenu.html":'\x3cdiv\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"optionsMenuContainer"\x3e\r\n    \x3cdiv class\x3d"OptionsMenu" data-dojo-attach-point\x3d"optionsMenu"\x3e\r\n      \x3cdiv class\x3d"dropdown-wrapper" data-dojo-attach-point\x3d"dropDownWrapper"\x3e\r\n        \x3ca data-dojo-attach-point\x3d"dropdownButton" href\x3d"#" class\x3d"dropdown"\x3e\x3c/a\x3e\r\n      \x3c/div\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("esri/core/declare dojo/dom-construct dojo/dom-class dojo/dom-style dojo/on dojo/_base/html dojo/query dijit/_WidgetBase dijit/_TemplatedMixin dojo/text!./templates/OptionsMenu.html".split(" "),function(h,b,e,g,d,k,l,m,n,p){return h([m,n],{name:"OptionsMenu",templateString:p,constructor:function(a){this._onHandles=[]},postMixInProperties:function(){},createMenu:function(a){this.menu=b.create("div",{className:"menuOverlay"},a);this.wrapper=b.create("div",{className:"dropdown-wrapper"},this.menu);
this.dropdownDomNode=b.create("div",{className:"dropdown-content"},this.wrapper);this.dropdownMenu=b.create("div",{className:"options-menu"},this.dropdownDomNode);this.menuListDomNode=b.create("ul",{className:"options-menu"},this.dropdownMenu);this.entries.forEach(this._createMenuEntry.bind(this))},postCreate:function(){var a=dojo.byId("webscene-page");a&&this.createMenu(a);a=d(this.optionsMenuContainer,"click",function(){this.visible?this.hide():this.show()}.bind(this));this._onHandles.push(a)},
destroy:function(){this._onHandles.forEach(function(a){a.remove()});var a=dojo.byId("webscene-page");a&&a.removeChild(this.menu)},show:function(){this.visible=!0;e.add(this.optionsMenu,"active");e.add(this.menu,"show");var a=k.coords(this.optionsMenuContainer),c=a.x;e.contains(dojo.doc.body.parentNode,"esriRtl")&&(c=a.x-this.dropdownMenu.clientWidth+30);g.set(this.menu,"left",c+"px");g.set(this.menu,"top",a.y+a.h+"px");this._addHideListener()},hide:function(){this.visible&&(this.visible=!1,e.remove(this.optionsMenu,
"active"),e.remove(this.menu,"show"),this._removeHideListener())},_createMenuEntry:function(a){a.className=a.className?a.className:"";var c=b.create("li",{className:"entry "+a.className,id:a.id},this.menuListDomNode);b.create("a",{},c).textContent=a.title;c=d(c,"click",function(c){c.preventDefault();a.func.apply()});this._onHandles.push(c)},_addHideListener:function(){this._hideListener=d(document,"click",function(a){a.target!==this.optionsMenu&&(a.target!==this.dropdownButton&&a.target!==this.dropDownWrapper&&
a.target!==this.optionsMenuContainer)&&this.hide()}.bind(this));this._hideListener=d(l(".NavigatorContainerContentInner")[0],"scroll",function(a){a.target!==this.dropdownButton&&this.hide()}.bind(this));this._hideListener=d(window,"resize",function(a){a.target!==this.dropdownButton&&this.hide()}.bind(this))},_removeHideListener:function(){this._hideListener.remove()},setMenuEntryTitle:function(a,c){for(var f=0;f<this.menuListDomNode.children.length;f++){var b=this.menuListDomNode.children[f];b.id==
a&&(b.children[0].textContent=c,this.entries[f].title=c)}},enableDisableMenuEntry:function(a,c){for(var b=0;b<this.menuListDomNode.children.length;b++){var d=this.menuListDomNode.children[b];d.id==a&&(c?e.remove(d,"disabled"):e.add(d,"disabled"))}}})});