// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/map/dynLayer",["dijit","dojo","dojox","dojo/require!arcgisonline/map/main"],function(m,g,n){g.provide("arcgisonline.map.dynLayer");g.require("arcgisonline.map.main");arcgisonline.map.dynLayer={checkDynamicLayers:function(a){if(a.layer&&a.layer.supportsDynamicLayers&&(!a.itemLayers||!a.itemLayers.length||!a.itemLayers[0].layerDefinition||!a.itemLayers[0].layerDefinition.source)){a.itemLayers=a.itemLayers||[];var d=[];g.forEach(a.layer.layerInfos,function(c){var e=g.filter(a.itemLayers,
function(a){return a.id==c.id}),b;e&&e.length&&(b=e[0]);b?(b.layerDefinition=b.layerDefinition||{},b.layerDefinition.source={type:"mapLayer",mapLayerId:c.id}):b={id:c.id,layerDefinition:{source:{type:"mapLayer",mapLayerId:c.id}}};b.name=b.name||c.name;esri.isDefined(c.minScale)&&(b.minScale=c.minScale);esri.isDefined(c.maxScale)&&(b.maxScale=c.maxScale);esri.isDefined(c.parentLayerId)&&(b.parentLayerId=c.parentLayerId);esri.isDefined(c.subLayerIds)&&(b.subLayerIds=c.subLayerIds);esri.isDefined(c.defaultVisibility)&&
(b.defaultVisibility=c.defaultVisibility);d.push(b)},this);a.itemLayers=d}},setupDynamicLayers:function(a){var d=[],c=[],e=[];g.forEach(a.itemLayers,function(a){a.layerDefinition&&a.layerDefinition.definitionExpression&&(d[a.id]=a.layerDefinition.definitionExpression);a.layerDefinition&&a.layerDefinition.source&&(dynamicLayerInfo=new esri.layers.DynamicLayerInfo(g.clone(a.layerDefinition)),dynamicLayerInfo.id=a.id,dynamicLayerInfo.name=a.name,dynamicLayerInfo.subLayerIds=a.subLayerIds,dynamicLayerInfo.parentLayerId=
a.parentLayerId,dynamicLayerInfo.minScale=esri.isDefined(a.minScale)?a.minScale:0,dynamicLayerInfo.maxScale=esri.isDefined(a.maxScale)?a.maxScale:0,dynamicLayerInfo.defaultVisibility=!1===a.defaultVisibility?!1:!0,c.push(dynamicLayerInfo));a.layerDefinition&&(a.layerDefinition.source&&a.layerDefinition.drawingInfo)&&(e[a.id]=new esri.layers.LayerDrawingOptions(g.clone(a.layerDefinition.drawingInfo)))},this);d.length&&a.layer.setLayerDefinitions(d);c.length&&(a.layer.setDynamicLayerInfos(c,!0),e.length&&
a.layer.setLayerDrawingOptions(e,!0))},updateDynamicLayers:function(a){var d=[],c=[],e=[];g.forEach(a.itemLayers,function(b){b.layerDefinition&&b.layerDefinition.source&&(dynamicLayerInfo=new esri.layers.DynamicLayerInfo(g.clone(b.layerDefinition)),dynamicLayerInfo.id=b.id,dynamicLayerInfo.name=b.name,dynamicLayerInfo.subLayerIds=b.subLayerIds,dynamicLayerInfo.parentLayerId=b.parentLayerId,dynamicLayerInfo.minScale=esri.isDefined(b.minScale)?b.minScale:0,dynamicLayerInfo.maxScale=esri.isDefined(b.maxScale)?
b.maxScale:0,esri.isDefined(a.startVisibleLayers)?-1<a.startVisibleLayers.indexOf(b.id)?dynamicLayerInfo.defaultVisibility=!0:dynamicLayerInfo.defaultVisibility=!1:dynamicLayerInfo.defaultVisibility=!1===b.defaultVisibility?!1:!0,c.push(dynamicLayerInfo));b.layerDefinition&&(b.layerDefinition.source&&b.layerDefinition.drawingInfo)&&(e[b.id]=new esri.layers.LayerDrawingOptions(g.clone(b.layerDefinition.drawingInfo)));(!esri.isDefined(b.defaultVisibility)||b.defaultVisibility)&&d.push(b.id)},this);
c.length&&(a.layer.setDynamicLayerInfos(c,!0),e.length&&a.layer.setLayerDrawingOptions(e,!0));if(esri.isDefined(a.visibleLayers)){var b=a.visibleLayers.split(","),f=[];g.forEach(b,function(a){g.forEach(c,function(b){b.source.mapLayerId===parseInt(a)&&f.push(b.id)})});a.visibleLayers=f.toString()}else a.visibleLayers=d.toString()},refreshDynamicLayers:function(a){var d=[],c,e=[],b;g.forEach(a.itemLayers,function(f){f.layerDefinition&&f.layerDefinition.source&&(c=new esri.layers.DynamicLayerInfo(g.clone(f.layerDefinition)),
c.id=f.id,c.name=f.name,c.subLayerIds=f.subLayerIds,c.parentLayerId=f.parentLayerId,c.minScale=esri.isDefined(f.minScale)?f.minScale:0,c.maxScale=esri.isDefined(f.maxScale)?f.maxScale:0,c.defaultVisibility=esri.isDefined(a.visibleLayers)?-1<(","+a.visibleLayers+",").indexOf(","+f.id+","):esri.isDefined(f.defaultVisibility)?f.defaultVisibility:!0,d.push(c));f.layerDefinition&&(f.layerDefinition.source&&f.layerDefinition.drawingInfo)&&(b=new esri.layers.LayerDrawingOptions(g.clone(f.layerDefinition.drawingInfo)),
e[f.id]=b)},this);d.length&&(a.layer.setDynamicLayerInfos(d,!0),e.length&&a.layer.setLayerDrawingOptions(e,!0),a.layer.refresh())},removeDynamicLayer:function(a,d){arcgisonline.map.dynLayer.checkDynamicLayers(a);var c=a.itemLayers.splice(d,1)[0];arcgisonline.map.dynLayer.removeFromParentLayer(a,c.id,c.parentLayerId);arcgisonline.map.dynLayer.removeSubLayers(a,c.subLayerIds);a.itemLayers.length&&arcgisonline.map.dynLayer.refreshDynamicLayers(a);if(esri.isDefined(a.visibleLayers)&&""!==a.visibleLayers){var e=
a.visibleLayers.split(","),b=g.indexOf(e,c.id);-1<b&&(e.splice(b,1),a.visibleLayersChanged=!0);c.subLayerIds&&c.subLayerIds.length&&g.forEach(c.subLayerIds,function(c){b=g.indexOf(e,c);-1<b&&(e.splice(b,1),a.visibleLayersChanged=!0)});a.visibleLayers=e.toString()}a.layersChanged=!0},removeFromParentLayer:function(a,d,c){for(var e=0;e<a.itemLayers.length;e++){var b=a.itemLayers[e];if(b.id===c){b.subLayerIds.splice(b.subLayerIds.indexOf(d),1);if(!b.subLayerIds||!b.subLayerIds.length)a.itemLayers.splice(e,
1),arcgisonline.map.dynLayer.removeFromParentLayer(a,b.id,b.parentLayerId);break}}},removeSubLayers:function(a,d){if(d)for(var c=a.itemLayers.length-1;0<=c;c--){var e=a.itemLayers[c];-1<g.indexOf(d,e.id)&&(a.itemLayers.splice(c,1),e.subLayerIds&&e.subLayerIds.length&&arcgisonline.map.dynLayer.removeSubLayers(a,e.subLayerIds))}},renameDynamicLayer:function(a,d,c){arcgisonline.map.dynLayer.checkDynamicLayers(a);a.itemLayers[d].name=c;arcgisonline.map.dynLayer.refreshDynamicLayers(a);a.layersChanged=
!0},moveUpLayer:function(a,d){if(0!==d){arcgisonline.map.dynLayer.checkDynamicLayers(a);var c=arcgisonline.map.dynLayer.buildGroupLevelInfo(a.itemLayers,0,a.itemLayers[a.itemLayers.length-1].id,0,null),e=a.itemLayers[d],b=a.itemLayers[d-1],f=d-1;if(c[e.id].level!==c[b.id].level)for(var h=2;;){b=a.itemLayers[d-h];if(!b)return;f=d-h;if(c[e.id].level===c[b.id].level)break;h++}if(e.subLayerIds&&e.subLayerIds.length){var k;g.forEach(a.itemLayers,function(b,c){if(b.id==e.subLayerIds[e.subLayerIds.length-
1]){k=c;for(var d=b.id+1;b.subLayerIds&&b.subLayerIds.length;){if(a.itemLayers[d].id===b.subLayerIds[b.subLayerIds.length-1]){k=d;break}d++}}});c=a.itemLayers.splice(d,k-d+1)}else c=a.itemLayers.splice(d,1);a.itemLayers=a.itemLayers.slice(0,f).concat(c).concat(a.itemLayers.slice(f));-1<e.parentLayerId&&g.forEach(a.itemLayers,function(a,c){if(a.id===e.parentLayerId){for(var d=g.indexOf(a.subLayerIds,e.id),f=g.indexOf(a.subLayerIds,b.id),h=0<f-d?1:-1;d!=f;d+=h)a.subLayerIds[d]=a.subLayerIds[d+h];a.subLayerIds[f]=
e.id}});arcgisonline.map.dynLayer.refreshDynamicLayers(a);a.layersChanged=!0}},moveDownLayer:function(a,d){if(arcgisonline.map.main.hasDynamicLayers(a)){if(d>=a.layer.dynamicLayerInfos.length-1)return}else if(d>=a.layer.layerInfos.length-1)return;arcgisonline.map.dynLayer.checkDynamicLayers(a);var c=arcgisonline.map.dynLayer.buildGroupLevelInfo(a.itemLayers,0,a.itemLayers[a.itemLayers.length-1].id,0,null),e=a.itemLayers[d],b=a.itemLayers[d+1],f=d+1;if(c[e.id].level!==c[b.id].level)for(var h=2;;){b=
a.itemLayers[d+h];if(!b)return;f=d+h;if(c[e.id].level===c[b.id].level)break;h++}for(;b.subLayerIds&&b.subLayerIds.length;){c=b.subLayerIds[b.subLayerIds.length-1];for(h=0;h<a.itemLayers.length;h++){var k=a.itemLayers[h];if(c==k.id){b=k;f=h;break}}}if(e.subLayerIds&&e.subLayerIds.length){var l;g.forEach(a.itemLayers,function(b,c){if(b.id==e.subLayerIds[e.subLayerIds.length-1]){l=c;for(var d=b.id+1;b.subLayerIds&&b.subLayerIds.length;){if(a.itemLayers[d].id===b.subLayerIds[b.subLayerIds.length-1]){l=
d;break}d++}}});h=a.itemLayers.splice(d,l-d+1)}else h=a.itemLayers.splice(d,1);f=f-h.length+1;a.itemLayers=a.itemLayers.slice(0,f).concat(h).concat(a.itemLayers.slice(f));-1<e.parentLayerId&&g.forEach(a.itemLayers,function(a,c){if(a.id===e.parentLayerId){for(var d=g.indexOf(a.subLayerIds,e.id),f=g.indexOf(a.subLayerIds,b.id),h=0<f-d?1:-1;d!=f;d+=h)a.subLayerIds[d]=a.subLayerIds[d+h];a.subLayerIds[f]=e.id}});arcgisonline.map.dynLayer.refreshDynamicLayers(a);a.layersChanged=!0},buildGroupLevelInfo:function(a,
d,c,e,b){for(var f=b||[],f=f.info?f.info:f,g=0;d<a.length;){var k=a[d];f[k.id]={layer:k,level:e};k.subLayerIds&&k.subLayerIds.length?(d=arcgisonline.map.dynLayer.buildGroupLevelInfo(a,d+1,k.subLayerIds[k.subLayerIds.length-1],e+1,f),f=d.info,d=d.idx):d++;if(k.id===c){g=d;break}}return!b?f:{info:f,idx:g}}}});