// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/map/edit",["dijit","dojo","dojox","dojo/require!arcgisonline/map/main"],function(g,d,q){d.provide("arcgisonline.map.edit");d.require("arcgisonline.map.main");arcgisonline.map.edit={editActivated:!1,hasEditableFS:!1,notEditableLayers:[],proxyCheckedServers:[],checkGoingOn:!1,startMsg:null,addPointMsg:null,checkOnEditButton:function(){arcgisonline.map.edit.checkGoingOn||arcgisonline.map.edit.checkInternalLayer()},checkInternalLayer:function(){arcgisonline.map.edit.checkGoingOn=
!0;for(var a=!1,c=0;c<arcgisonline.map.main.mapLayers.length;c++){var b=arcgisonline.map.main.mapLayers[c];if(b&&b.layer&&b.layer.visible&&b.url&&(!arcgisonline.map.featColl.isFeatureCollection(b)&&!arcgisonline.sharing.util.isHostedService(b.url)&&b.layer instanceof esri.layers.FeatureLayer&&b.layer.isEditable())&&!b.proxyCheck)if(esri.hasSameOrigin(b.url,window.location.href))b.proxyCheck="sameOrigin";else{var h=b.url.substring(0,b.url.indexOf("/",10)),h=h.substring(h.indexOf(":")+3),e=esriConfig.defaults.io.corsStatus;
if(esri.canUseXhr(b.url))b.proxyCheck="cors";else{if(-1===e[h]){setTimeout(d.hitch(this,function(){arcgisonline.map.edit.checkInternalLayer()}),1E3);return}a=!0;arcgisonline.map.edit.getProxyServiceInfo(c,1);break}}}a||(arcgisonline.map.edit.checkGoingOn=!1,arcgisonline.map.edit.hasEditableLayer())},hasEditableLayer:function(){if(arcgisonline.map.role.isAllowed("tool_edit")){var a=!1;arcgisonline.map.edit.hasEditableFS=!1;for(c=0;c<arcgisonline.map.main.mapLayers.length;c++)if(b=arcgisonline.map.main.mapLayers[c],
arcgisonline.map.featColl.isFeatureCollection(b)&&arcgisonline.map.role.isAllowed("tool_edit_featCol"))if(b.layer&&b.layer.visible&&b.layer.isEditable())a=!0;else{if(b.layers&&0<b.layers.length)for(d=0;d<b.layers.length;d++)if(e=b.layers[d],e.visible&&e.isEditable()){a=!0;break}}else b&&(b.layer&&b.layer.visible)&&(b.layer.url&&b.layer instanceof esri.layers.FeatureLayer&&b.layer.isEditable())&&("success"===b.proxyCheck||"cors"===b.proxyCheck||"sameOrigin"===b.proxyCheck||arcgisonline.sharing.util.isHostedService(b.url)&&
b.layer.isEditable()?a=arcgisonline.map.edit.hasEditableFS=!0:b.layer._editable=!1);a?arcgisonline.map.edit.enableEditButton():arcgisonline.map.edit.disableEditButton()}else if(arcgisonline.map.role.isAllowed("tool_edit_mapNotes")){for(var a=!1,c=0;c<arcgisonline.map.main.mapLayers.length;c++){var b=arcgisonline.map.main.mapLayers[c];if("mapNotes"===b.type){for(var d=0;d<b.layers.length;d++){var e=b.layers[d];if(e.visible&&e.isEditable()){a=!0;break}}break}}a?arcgisonline.map.edit.enableEditButton():
arcgisonline.map.edit.disableEditButton()}else arcgisonline.map.edit.disableEditButton()},getProxyServiceInfo:function(a,c){var b=arcgisonline.map.main.mapLayers[a],h=function(a,c){clearTimeout(g);g=null;if(a){var f=b.layer.url,e=-1<f.indexOf("/FeatureServer")?f.substring(0,f.indexOf("/FeatureServer")+14):null;arcgisonline.map.edit.proxyCheckedServers[m]=arcgisonline.map.edit.proxyCheckedServers[m]||[];d.filter(arcgisonline.map.edit.proxyCheckedServers[m],function(a){return a.service===e}).length||
arcgisonline.map.edit.proxyCheckedServers[m].push({service:e,result:{},proxyCheck:"success"})}b.proxyCheck="success";b.layer._editable=!0;arcgisonline.map.edit.checkInternalLayer()},e=function(f){clearTimeout(g);g=null;if(!f&&1===c)arcgisonline.map.edit.getProxyServiceInfo(a,2);else{b.proxyCheck="failure";arcgisonline.map.edit.checkInternalLayer();arcgisonline.map.edit.notEditableLayers.push(b.title);var e=b.layer.url,h=-1<e.indexOf("/FeatureServer")?e.substring(0,e.indexOf("/FeatureServer")+14):
null;arcgisonline.map.edit.proxyCheckedServers[m]=arcgisonline.map.edit.proxyCheckedServers[m]||[];d.filter(arcgisonline.map.edit.proxyCheckedServers[m],function(a){return a.service===h}).length||(arcgisonline.map.edit.proxyCheckedServers[m].push({service:h,result:f||{},proxyCheck:"failure"}),setTimeout(function(){var a="",a=f&&400===f.status?1<arcgisonline.map.edit.notEditableLayers.length?d.string.substitute(esri.i18nBundle.viewer.edit.notEditableLayers,{layers:"\x3cbr/\x3e-\x26nbsp;\x26nbsp;"+
arcgisonline.map.edit.notEditableLayers.toString().replace(/,/g,"\x3cbr/\x3e-\x26nbsp;\x26nbsp;")+"\x3cbr/\x3e\x3cbr/\x3e",appName:esriGeowConfig.portalName?esriGeowConfig.portalName:esri.i18nBundle.common.arcgisCom}):d.string.substitute(esri.i18nBundle.viewer.edit.notEditableLayer,{layer:arcgisonline.map.edit.notEditableLayers[0],appName:esriGeowConfig.portalName?esriGeowConfig.portalName:esri.i18nBundle.common.arcgisCom}):esriGeowConfig.self.isPortal&&f&&(-1===f.code||403===f.code&&2===f.subcode)?
1<arcgisonline.map.edit.notEditableLayers.length?d.string.substitute(esri.i18nBundle.viewer.edit.notEditableLayersTrusted,{layers:"\x3cbr/\x3e-\x26nbsp;\x26nbsp;"+arcgisonline.map.edit.notEditableLayers.toString().replace(/,/g,"\x3cbr/\x3e-\x26nbsp;\x26nbsp;")+"\x3cbr/\x3e\x3cbr/\x3e",appName:esriGeowConfig.portalName?esriGeowConfig.portalName:esri.i18nBundle.common.arcgisCom}):d.string.substitute(esri.i18nBundle.viewer.edit.notEditableLayerTrusted,{layer:arcgisonline.map.edit.notEditableLayers[0],
appName:esriGeowConfig.portalName?esriGeowConfig.portalName:esri.i18nBundle.common.arcgisCom}):1<arcgisonline.map.edit.notEditableLayers.length?d.string.substitute(esri.i18nBundle.viewer.edit.notEditableLayersGeneric,{layers:"\x3cbr/\x3e-\x26nbsp;\x26nbsp;"+arcgisonline.map.edit.notEditableLayers.toString().replace(/,/g,"\x3cbr/\x3e-\x26nbsp;\x26nbsp;")+"\x3cbr/\x3e\x3cbr/\x3e",appName:esriGeowConfig.portalName?esriGeowConfig.portalName:esri.i18nBundle.common.arcgisCom}):d.string.substitute(esri.i18nBundle.viewer.edit.notEditableLayerGeneric,
{layer:arcgisonline.map.edit.notEditableLayers[0],appName:esriGeowConfig.portalName?esriGeowConfig.portalName:esri.i18nBundle.common.arcgisCom}),b=arcgisonline.sharing.dijit.dialog.GeneralDlg.prototype.statics.getInstance();b.show({title:esri.i18nBundle.viewer.edit.editing,message:a});d.aspect.after(b,"onHide",function(){arcgisonline.map.edit.notEditableLayers=[]})},2E3))}};if(arcgisonline.map.edit.proxyCheckedServers){var f=b.layer.url,m=f.substring(0,f.indexOf("/",9)),l=arcgisonline.map.edit.proxyCheckedServers[m];
if(l){var n=-1<f.indexOf("/FeatureServer")?f.substring(0,f.indexOf("/FeatureServer")+14):null,k=l[0];n&&d.forEach(l,function(a){a.service===n&&(k=a)});if("success"===k.proxyCheck){if(!esriGeowConfig.self.isPortal||!(n&&k.service!==n)){h();return}}else if(!(403===k.result.code&&2===k.result.subcode&&k.service!==n)){e(k.result);return}}}var g=setTimeout(function(){e({})},2E4);b.layer._editable=!1;f=b.layer.url+"?f\x3djson";(l=b.layer._getToken())&&(f+="\x26token\x3d"+l);esri.request({url:f,content:null,
callbackParamName:"callback",load:function(a,b){g&&(a.error&&0<a.error.length?e(a):h(a,b))},error:function(a,b){g&&e(a)}},{usePost:!0,useProxy:!0})},enableEditButton:function(){g.byId("webmap-edit")&&"none"===d.style(g.byId("webmap-edit").domNode,"display")&&(g.byId("webmap-edit").set("disabled",!1),10>=d.isIE?d.style(g.byId("webmap-edit").domNode,"display","inline-block"):d.style(g.byId("webmap-edit").domNode,"display",""),arcgisonline.map.main.checkMinWidthOfPage())},disableEditButton:function(){g.byId("webmap-edit")&&
"none"!==d.style(g.byId("webmap-edit").domNode,"display")&&(d.style(g.byId("webmap-edit").domNode,"display","none"),arcgisonline.map.main.checkMinWidthOfPage())},clearSelection:function(){arcgisonline.map.edit.editActivated&&leftPanel.editPanel.editorWidget._clearSelection()},activateEdit:function(){arcgisonline.map.main.map.infoWindow.hide();arcgisonline.map.popup.disablePopupHandler();arcgisonline.map.edit.editActivated=!0;arcgisonline.map.main.map.setMapCursor("default");arcgisonline.map.labels.hideAllLabels();
arcgisonline.map.geocode.geocoder&&d.forEach(arcgisonline.map.geocode.geocoder.sources,function(a){if(a.layerId){var c=arcgisonline.map.main.getParameterListById(a.layerId);c&&(c.layer&&c.layer.isEditable())&&(a.showInfoWindowOnSelect=!1)}});arcgisonline.map.edit.createTypesAndTemplatesForAllFeatCollLayers();d.forEach(arcgisonline.map.main.mapLayers,function(a){a.layer&&a.layer instanceof esri.layers.FeatureLayer&&a.layer.isEditable()?arcgisonline.map.mapUtil.checkHostedFSAccess(a,d.hitch(this,function(a){"esri.renderer.HeatmapRenderer"===
a.layer.renderer.declaredClass&&(a.layer.__currentRenderer=a.layer.renderer.toJson(),a.layer.setRenderer(new esri.renderers.SimpleRenderer(new esri.symbols.SimpleMarkerSymbol)),a.layer.redraw())}),d.hitch(this,function(){if(a.serviceInfo&&a.serviceInfo.drawingInfo&&a.serviceInfo.drawingInfo.renderer){var c=a.layer.renderer.toJson();if(d.toJson(a.serviceInfo.drawingInfo.renderer)!==d.toJson(c)){a.layer.__currentRenderer=a.layer.renderer.toJson();c=esri.renderer.fromJson(a.serviceInfo.drawingInfo.renderer);
if("esri.renderer.HeatmapRenderer"===c.declaredClass)a.layer.setRenderer(new esri.renderers.SimpleRenderer(new esri.symbols.SimpleMarkerSymbol));else if(a.layer.setRenderer(c),9>d.has("ie")){var b=[];c.symbol&&b.push(c.symbol);c.defaultSymbol&&b.push(c.defaultSymbol);c.infos&&d.forEach(c.infos,function(a){a.symbol&&b.push(a.symbol)});var h=a.layer._url.path+"/images/",e=a.layer._getToken();d.forEach(b,function(a){var b=a.url;b&&(-1===b.search(/https?\:/)&&-1===b.indexOf("data:")&&(a.url=h+b),e&&-1!==
a.url.search(/https?\:/)&&(a.url+="?token\x3d"+e))})}a.layer.redraw()}}else"esri.renderer.HeatmapRenderer"===a.layer.renderer.declaredClass&&(a.layer.__currentRenderer=a.layer.renderer.toJson(),a.layer.setRenderer(new esri.renderers.SimpleRenderer(new esri.symbols.SimpleMarkerSymbol)),a.layer.redraw())})):a.layers&&d.forEach(a.layers,function(a){a&&a.isEditable()&&"esri.renderer.HeatmapRenderer"===a.renderer.declaredClass&&(a.__currentRenderer=a.renderer.toJson(),a.setRenderer(new esri.renderers.SimpleRenderer(new esri.symbols.SimpleMarkerSymbol)),
a.redraw())})});arcgisonline.map.edit.startMsg=esri.bundle.toolbars.draw.start;arcgisonline.map.edit.addPointMsg=esri.bundle.toolbars.draw.addPoint;-1===esri.bundle.toolbars.draw.start.indexOf(esri.i18nBundle.viewer.main.snappingTip)&&(esri.bundle.toolbars.draw.start=esri.bundle.toolbars.draw.start+"\x3cbr/\x3e"+esri.i18nBundle.viewer.main.snappingTip);-1===esri.bundle.toolbars.draw.addPoint.indexOf(esri.i18nBundle.viewer.main.snappingTip)&&(esri.bundle.toolbars.draw.addPoint=esri.bundle.toolbars.draw.addPoint+
"\x3cbr/\x3e"+esri.i18nBundle.viewer.main.snappingTip)},stopEdit:function(){leftPanel&&(leftPanel.editPanel&&leftPanel.editPanel.editorWidget)&&leftPanel.editPanel.destroyEditor();arcgisonline.map.edit.editActivated=!1;arcgisonline.map.main.map&&arcgisonline.map.main.map.infoWindow.resize(270,300);arcgisonline.map.main.setHandCursor();arcgisonline.map.popup.setupPopupHandler();arcgisonline.map.labels.showAllLabels();arcgisonline.map.edit.removeTypesAndTemplatesForAllFeatCollLayers();arcgisonline.map.geocode.geocoder&&
d.forEach(arcgisonline.map.geocode.geocoder.sources,function(a){delete a.showInfoWindowOnSelect});d.forEach(arcgisonline.map.main.mapLayers,function(a){a.layer&&a.layer.__currentRenderer?(a.layer.setRenderer(esri.renderer.fromJson(a.layer.__currentRenderer)),a.layer.redraw(),delete a.layer.__currentRenderer):a.layers&&d.forEach(a.layers,function(a){a&&a.__currentRenderer&&(a.setRenderer(esri.renderer.fromJson(a.__currentRenderer)),a.redraw(),delete a.__currentRenderer)})});esri.bundle.toolbars.draw.start=
arcgisonline.map.edit.startMsg||esri.bundle.toolbars.draw.start;esri.bundle.toolbars.draw.addPoint=arcgisonline.map.edit.addPointMsg||esri.bundle.toolbars.draw.addPoint},createTypesAndTemplatesForAllFeatCollLayers:function(){for(var a=arcgisonline.map.main.mapLayers.length-1;0<=a;a--){var c=arcgisonline.map.main.mapLayers[a];if(arcgisonline.map.featColl.isFeatureCollection(c)&&!arcgisonline.map.mapNotes.isMapNotesMapLayer(c))if(c.layer)arcgisonline.map.edit.createTypesAndTemplatesOnLayer(c.layer);
else if(c.layers)for(var b=c.layers.length-1;0<=b;b--)arcgisonline.map.edit.createTypesAndTemplatesOnLayer(c.layers[b])}},createTypesAndTemplatesOnMapLayer:function(a){if(a.layer&&arcgisonline.map.featColl.isFeatureCollection(a)&&!arcgisonline.map.mapNotes.isMapNotesMapLayer(a))if(a.layer){var c=a.layer;if(c.visible){var b=c.toJson();(!b.layerDefinition.types||0==b.layerDefinition.types.length)&&(!b.layerDefinition.templates||0==b.layerDefinition.templates.length)&&arcgisonline.map.edit.createTypesAndTemplatesOnLayer(c)}}else for(var d=
a.layers.length-1;0<=d;d--)c=a.layers[d],c.visible&&(b=c.toJson(),(!b.layerDefinition.types||0==b.layerDefinition.types.length)&&(!b.layerDefinition.templates||0==b.layerDefinition.templates.length)&&arcgisonline.map.edit.createTypesAndTemplatesOnLayer(c));else if(a.layer&&a.layer instanceof esri.layers.FeatureLayer&&(!a.serviceInfo||a.serviceInfo&&a.serviceInfo.types&&a.serviceInfo.templates))c=a.layer,!c.templates.length&&!c.types.length&&arcgisonline.map.edit.createTypesAndTemplatesOnLayer(c)},
createTypesAndTemplatesOnLayer:function(a){var c=a.renderer;if("esri.renderer.SimpleRenderer"==c.declaredClass||"esri.renderer.ClassBreaksRenderer"==c.declaredClass||"esri.renderer.HeatmapRenderer"==c.declaredClass){c=new esri.layers.FeatureTemplate;c.description="";c.name=esri.i18nBundle.viewer.edit.newFeature;var b={};d.forEach(a.fields,function(a){a.editable&&(b[a.name]=a.defaultValue||null,!b[a.name]&&!1===a.nullable&&(b[a.name]="esriFieldTypeString"===a.type?" ":0))});var h=new esri.Graphic({attributes:b});
c.prototype=h;arcgisonline.map.edit.updateTypeIdField(a,"");arcgisonline.map.edit.updateTemplates(a,[c]);a.__hasTemporaryTypes=!0}else if("esri.renderer.UniqueValueRenderer"==c.declaredClass){var e=c.attributeField;a.types=[];d.forEach(c.infos,function(b,c){var h=new esri.layers.FeatureType;h.id=b.value;h.name=b.label||b.value;var g=new esri.layers.FeatureTemplate;g.description="";g.name=b.label||b.value;var k={};k[e]="\x3cNull\x3e"===b.value||"Null"===b.value?null:b.value;d.forEach(a.fields,function(a){a.name!==
e&&a.editable&&(k[a.name]=a.defaultValue||null,!k[a.name]&&!1===a.nullable&&(k[a.name]="esriFieldTypeString"===a.type?" ":0))});var p=new esri.Graphic(null,null,k,null);g.prototype=p;h.templates=[g];a.addType(h)});arcgisonline.map.edit.updateTypeIdField(a,e);a.__hasTemporaryTypes=!0}},removeTypesAndTemplatesForAllFeatCollLayers:function(){for(var a=arcgisonline.map.main.mapLayers.length-1;0<=a;a--){var c=arcgisonline.map.main.mapLayers[a];if(arcgisonline.map.featColl.isFeatureCollection(c)&&!arcgisonline.map.mapNotes.isMapNotesMapLayer(c))if(c.layer)arcgisonline.map.edit.removeTypesAndTemplatesOnLayer(c.layer);
else if(c.layers)for(var b=c.layers.length-1;0<=b;b--)arcgisonline.map.edit.removeTypesAndTemplatesOnLayer(c.layers[b])}},removeTypesAndTemplatesOnMapLayer:function(a,c){if(a.layer&&arcgisonline.map.featColl.isFeatureCollection(a)&&!arcgisonline.map.mapNotes.isMapNotesMapLayer(a))if(a.layer)c&&a.layer.__hasTemporaryTypes?(arcgisonline.map.edit.removeTypesAndTemplatesOnLayer(a.layer),delete a.layer.__hasTemporaryTypes):c||arcgisonline.map.edit.removeTypesAndTemplatesOnLayer(a.layer);else for(var b=
a.layers.length-1;0<=b;b--){var d=a.layers[b];c&&d.__hasTemporaryTypes?(arcgisonline.map.edit.removeTypesAndTemplatesOnLayer(d),delete d.__hasTemporaryTypes):c||arcgisonline.map.edit.removeTypesAndTemplatesOnLayer(d)}},removeTypesAndTemplatesOnLayer:function(a){a.types&&(a.types=[],a._typesDirty=!0,arcgisonline.map.edit.updateTypeIdField(a,""));a.templates&&arcgisonline.map.edit.updateTemplates(a,[])},checkTypesAndTemplatesOnLayer:function(a){if(a.templates&&a.templates.length&&a.types&&a.types.length){if("esri.renderer.SimpleRenderer"==
a.renderer.declaredClass||"esri.renderer.ClassBreaksRenderer"==a.renderer.declaredClass||"esri.renderer.HeatmapRenderer"==a.renderer.declaredClass)a.types=[],a._typesDirty=!0,arcgisonline.map.edit.updateTypeIdField(a,"");"esri.renderer.UniqueValueRenderer"==a.renderer.declaredClass&&arcgisonline.map.edit.updateTemplates(a,[])}if((!a.templates||!a.templates.length)&&("esri.renderer.SimpleRenderer"==a.renderer.declaredClass||"esri.renderer.ClassBreaksRenderer"==a.renderer.declaredClass||"esri.renderer.HeatmapRenderer"==
a.renderer.declaredClass)||(!a.types||!a.types.length)&&"esri.renderer.UniqueValueRenderer"==a.renderer.declaredClass)arcgisonline.map.edit.removeTypesAndTemplatesOnLayer(a),arcgisonline.map.edit.createTypesAndTemplatesOnLayer(a);else if(a.types&&"esri.renderer.UniqueValueRenderer"==a.renderer.declaredClass){var c=a.renderer;c.attributeField!==a.typeIdField?(arcgisonline.map.edit.removeTypesAndTemplatesOnLayer(a),arcgisonline.map.edit.createTypesAndTemplatesOnLayer(a)):d.forEach(c.infos,function(b){var c=
!1;d.forEach(a.types,function(a){a.id==b.value&&(c=!0)});c||(arcgisonline.map.edit.removeTypesAndTemplatesOnLayer(a),arcgisonline.map.edit.createTypesAndTemplatesOnLayer(a))})}},updateTypeIdField:function(a,c){a.typeIdField=c;if(a._collection){var b;b=9>d.isIE?d.json.parse(a._json):JSON.parse(a._json);b.layerDefinition?b.layerDefinition.typeIdField=c:b.typeIdField=c;a._json=9>d.isIE?d.json.stringify(b):JSON.stringify(b)}},updateTemplates:function(a,c){a.templates=c;if(a._collection){var b;b=9>d.isIE?
d.json.parse(a._json):JSON.parse(a._json);b.layerDefinition?b.layerDefinition.templates=c:b.templates=c;a._json=9>d.isIE?d.json.stringify(b):JSON.stringify(b)}},hasDefaultTypesAndTemplates:function(a){var c=a.renderer;if("esri.renderer.SimpleRenderer"==c.declaredClass||"esri.renderer.ClassBreaksRenderer"==c.declaredClass||"esri.renderer.HeatmapRenderer"==c.declaredClass){if(!a.templates||1!==a.templates.length)return!1;var b=a.templates[0];if(!(""!==b.description||b.name!==esri.i18nBundle.viewer.edit.newFeature)&&
!a.typeIdField&&b.prototype&&b.prototype.attributes)for(var b=b.prototype.attributes,d=0,d=0;d<a.fields.length;d++){var e=a.fields[d];if(e.editable&&b[e.name]!==e.defaultValue&&" "!==b[e.name]&&0!==b[e.name]&&b[e.name])return!1}else return!1}else if("esri.renderer.UniqueValueRenderer"==c.declaredClass&&c.infos){if(a.typeIdField!==c.attributeField||!a.types||a.types.length!==c.infos.length)return!1;for(var f,g,d=0;d<c.infos.length;d++){var l=c.infos[d],n=!1;for(f=0;f<a.types.length;f++)if(b=a.types[f],
b.id==l.value&&(b.name==l.label||b.name==l.value)){n=!0;if(!b.templates||1!==b.templates.length)return!1;b=b.templates[0];if(""!=b.description||b.name!=l.label&&b.name!=l.value)return!1;b=b.prototype.attributes;for(g=0;g<a.fields.length;g++)if(e=a.fields[g],e.editable&&(e.name===c.attributeField&&b[c.attributeField]!=l.value||e.name!==c.attributeField&&b[e.name]!==e.defaultValue&&" "!==b[e.name]&&0!==b[e.name]&&b[e.name]))return!1}if(!n)return!1}}else return!1;return!0},toc_enableEditing:function(a){if(a.layer){if(a.layer.url)a.serviceInfo&&
a.serviceInfo.capabilities&&a.serviceInfo._origCapabilities&&(a.serviceInfo.capabilities=a.serviceInfo._origCapabilities,delete a.serviceInfo._origCapabilities,arcgisonline.map.main.reloadFeatureLayer(a));else{a.layer.setEditable(!0);var c=arcgisonline.sharing.util.getUser();c&&(a.itemCard&&a.itemCard.owner===c.email)&&(a.editableChanged=!0)}a.itemCard&&(-1<d.indexOf(a.itemCard.typeKeywords,"Location Tracking")&&-1<d.indexOf(a.itemCard.typeKeywords,"Collector"))&&(a.isTrackingInfoLayer=!0)}else d.forEach(a.layers,
function(a){a.setEditable(!0)}),a.editableChanged=!0;arcgisonline.map.edit.createTypesAndTemplatesOnMapLayer(a);arcgisonline.map.edit.checkOnEditButton();arcgisonline.map.main.markMapAsChanged("enableEditing")},toc_disableEditing:function(a){if(a.layer)if(a.layer.url)a.serviceInfo&&a.serviceInfo.capabilities&&(a.serviceInfo._origCapabilities=a.serviceInfo.capabilities,a.serviceInfo.capabilities=arcgisonline.map.edit.removeEditCapabilities(a.serviceInfo.capabilities),arcgisonline.map.main.reloadFeatureLayer(a));
else{a.layer.setEditable(!1);var c=arcgisonline.sharing.util.getUser();c&&(a.itemCard&&a.itemCard.owner===c.email)&&(a.editableChanged=!0)}else d.forEach(a.layers,function(a){a.setEditable(!1)}),a.editableChanged=!0;arcgisonline.map.edit.removeTypesAndTemplatesOnMapLayer(a);arcgisonline.map.edit.checkOnEditButton();arcgisonline.map.main.markMapAsChanged("disableEditing")},removeEditCapabilities:function(a){a=a.split(",");a=d.filter(a,function(a){var b=a.toLowerCase();if("create"!==b&&"update"!==b&&
"delete"!==b&&"editing"!==b&&"uploads"!==b)return a});return a.toString()}}});