// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/map/geocodeReview",["dijit","dojo","dojox","dojo/require!arcgisonline/map/main"],function(d,a,h){a.provide("arcgisonline.map.geocodeReview");a.require("arcgisonline.map.main");arcgisonline.map.geocodeReview={geocodeReviewWidget:null,geocodeMatchWidget:null,reviewTableCloseButtonHandler:null,currentlyReviewedMapLayer:null,showGeocodeReview:function(b,e){if(b.itemId&&b.itemCard&&-1!=a.indexOf(b.itemCard.typeKeywords,"Involved Lookup")){arcgisonline.map.table.hideAttributeTable();
a.style(d.byId("rightDiv").getSplitter("bottom").domNode,"height","5px");a.style(a.byId("bottomDiv"),"height","200px");a.style(a.byId("geocodeDiv"),"height","200px");a.style(a.byId("geocodeDiv"),"display","block");d.byId("main-content").resize();a.byId("geocodeReviewDiv")||a.create("div",{id:"geocodeReviewDiv"},"geocodeReviewContPane");arcgisonline.map.geocodeReview.geocodeMatchWidget=e;arcgisonline.map.geocodeReview.currentlyReviewedMapLayer=b;var c=null;a.forEach(esriGeowConfig.self.helperServices.geocode,
function(a){if(!c&&arcgisonline.sharing.util.isEsriWorldGeocoder(a.url)&&(c=a.url,esriGeowConfig.allSSL||"https:"==location.protocol))c=c.replace("http:","https:")});arcgisonline.map.geocodeReview.geocodeReviewWidget=new esri.dijit.GeocodeReview({map:arcgisonline.map.main.map,itemId:b.itemId,userIsAdmin:-1<a.indexOf(b.itemCard.typeKeywords,"Hosted Service")?!0:!1,geocodeMatch:e,geocoder:c},"geocodeReviewDiv");arcgisonline.map.geocodeReview.geocodeReviewWidget.startup();var g=a.query(".ReviewWidgetBase .dijitToggleButton");
a.forEach(g,function(b){a.addClass(b,"calcite small")});if(esriGeowConfig.helpMap&&esriGeowConfig.helpMap["120000900"]){var g=a.create("a",{className:"esriHelpIcon esriFloatTrailing",title:esri.i18nBundle.viewer.geocodeReview.learnMore,href:esriGeowConfig.helpBase+esriGeowConfig.helpMap["120000900"],target:"_blank"}),f=a.query(".learnMoreDiv")[0];f&&a.place(g,f,"only")}else f=a.query(".learnMoreDiv")[0],a.style(f,"display","none");a.create("img",{src:"images/transparent.gif",border:"0"},a.create("a",
{href:"JavaScript:void(0);",id:"reviewTableCloseButton",title:esri.i18nBundle.common.close},a.create("div",{"class":"esriFloatTrailing",style:"padding:0;width:27px;"},a.query(".learnMoreDiv")[0].parentNode,"last")));arcgisonline.map.geocodeReview.reviewTableCloseButtonHandler=a.connect(a.byId("reviewTableCloseButton"),"onclick",function(a){a.preventDefault();arcgisonline.map.leftPanel.openLeftTOCPanel()})}},hideGeocodeReview:function(){a.style(a.byId("geocodeDiv"),"display","none");a.style(d.byId("rightDiv").getSplitter("bottom").domNode,
"height","0");a.style(a.byId("geocodeDiv"),"height","0");a.style(a.byId("bottomDiv"),"height","0");d.byId("main-content").resize();if(arcgisonline.map.geocodeReview.geocodeReviewWidget){var b=arcgisonline.map.geocodeReview.currentlyReviewedMapLayer.layer,e=b._ts;b._ts=!0;b.refresh();b._ts=e;arcgisonline.map.geocodeReview.geocodeReviewWidget.destroy();arcgisonline.map.geocodeReview.geocodeReviewWidget=null;arcgisonline.map.geocodeReview.geocodeMatchWidget=null;a.disconnect(arcgisonline.map.geocodeReview.reviewTableCloseButtonHandler);
arcgisonline.map.geocodeReview.reviewTableCloseButtonHandler=null;arcgisonline.map.geocodeReview.currentlyReviewedMapLayer=null}}}});