// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/map/geoRSS",["dijit","dojo","dojox","dojo/require!arcgisonline/map/main"],function(l,d,m){d.provide("arcgisonline.map.geoRSS");d.require("arcgisonline.map.main");arcgisonline.map.geoRSS={addGeoRSSLayer:function(c,b,d,f){-1==c.indexOf("http")&&(c="http://"+c);b||(b={id:"GeoRSS_"+Math.floor(10001*Math.random()),visibility:!0,opacity:1,title:"GeoRSS",_addedVia:"url"});c={layer:null,id:b.id,itemId:b.itemId,url:c,type:"user",subType:"GeoRSS",title:b.title,defaultVisibility:b.visibility,
defaultOpacity:b.opacity,showLegend:!1===b.showLegend?!1:!0,visibility:b.visibility,visibleLayers:b.visibleLayers,minScale:b.minScale,maxScale:b.maxScale,snippet:"",identify:!1,_addedVia:b._addedVia,refreshInterval:b.refreshInterval,layers:b.layers,pointSymbol:b.pointSymbol,lineSymbol:b.lineSymbol,polygonSymbol:b.polygonSymbol};null!==b.showLegend&&void 0!==b.showLegend&&(c.showLegend=b.showLegend);b=arcgisonline.map.layer.getLayerPosition(c);arcgisonline.map.main.mapLayers.splice(b.list,0,c);arcgisonline.map.geoRSS.createGeoRSSLayer(c,
b.map,d,f)},createGeoRSSLayer:function(c,b,e,f){b=function(a){if(a.layer.getFeatureLayers().length){a.successfulDraw=!0;!1===a.defaultVisibility&&a.layer.hide();d.publish("layerAddedNoRemove",[a.id]);d.publish("onLayerUpdate",[""]);arcgisonline.map.main.mapInitialized||arcgisonline.map.main.initMap();"GeoRSS"===a.title&&(a.layer.name?a.title=a.layer.name:(a.title=a.url.substring(a.url.lastIndexOf("/")+1,a.url.length),-1<a.title.indexOf(".")&&(a.title=a.title.substring(0,a.title.indexOf(".")))));var b=
a.layer.getFeatureLayers();d.forEach(b,function(c){a.pointSymbol&&"esriGeometryPoint"===c.geometryType?(c.renderer.symbol=esri.symbol.fromJson(a.pointSymbol),1===b.length&&(a.layer.pointSymbol=esri.symbol.fromJson(a.pointSymbol))):a.lineSymbol&&"esriGeometryPolyline"===c.geometryType?(c.renderer.symbol=esri.symbol.fromJson(a.lineSymbol),1===b.length&&(a.layer.polylineSymbol=esri.symbol.fromJson(a.lineSymbol))):a.polygonSymbol&&"esriGeometryPolygon"===c.geometryType&&(c.renderer.symbol=esri.symbol.fromJson(a.polygonSymbol),
1===b.length&&(a.layer.polygonSymbol=esri.symbol.fromJson(a.polygonSymbol)))});a.layer.fullExtent=function(a){a=a.getFeatureLayers();var b=null;d.forEach(a,function(a){(a=arcgisonline.map.featColl.getLayerFullExtent(a))&&(b=!b?a:b.union(a))});return b}(a.layer);null!==a.defaultOpacity&&a.layer.setOpacity(a.defaultOpacity);if(esri.isDefined(a.minScale)||esri.isDefined(a.maxScale))a.scaleChanged=!0,a.layer.setScaleRange(a.minScale,a.maxScale);!arcgisonline.map.main.isMapFullyLoaded&&-1==document.location.href.indexOf("layers\x3d")&&
-1==document.location.href.indexOf("services\x3d")?(arcgisonline.map.main.map.addLayer(a.layer),arcgisonline.map.popup.setupPopupHandler()):a.layer.fullExtent?arcgisonline.map.main.projectToMapAndZoom(a.layer.fullExtent,0,0,d.hitch(this,function(){arcgisonline.map.main.map.addLayer(a.layer);arcgisonline.map.popup.setupPopupHandler()},this)):(arcgisonline.map.main.map.addLayer(a.layer),arcgisonline.map.popup.setupPopupHandler());d.publish("layerAdded",[a.id]);e&&e(a.layer)}else h(a,{message:"no data"})};
var g=c.url;if(arcgisonline.sharing.util.isHostedService(g)){var k=arcgisonline.sharing.util.getToken();k&&(g+="?token\x3d"+k)}c.layer=new esri.layers.GeoRSSLayer(g,{id:c.id,refreshInterval:c.refreshInterval?c.refreshInterval:null,outSpatialReference:arcgisonline.map.main.map.spatialReference});c.layer.loaded?b(c):d.connect(c.layer,"onLoad",d.hitch(this,b,c));var h=function(a,b){console.log(b);f&&f();if(!a.successfulDraw){var c=arcgisonline.sharing.dijit.dialog.GeneralDlg.prototype.statics.getInstance(),
e;"url"===a._addedVia?(e=d.string.substitute(esri.i18nBundle.viewer.geoRSS.error,{url:a.url}),b.message&&-1<b.message.indexOf("File not found")?e=d.string.substitute(esri.i18nBundle.viewer.geoRSS.badUrl,{url:a.url}):b.message&&-1<b.message.indexOf("no data")&&(e=d.string.substitute(esri.i18nBundle.viewer.geoRSS.noData,{url:a.url})),c.showWide({title:esri.i18nBundle.generalDlg.errorDlgTitle,message:e})):c.show({title:esri.i18nBundle.generalDlg.errorDlgTitle,message:d.string.substitute(esri.i18nBundle.viewer.geoRSS.notAvailable,
{title:a.title})});arcgisonline.map.layer.removeLayer(a);d.publish("layerAddFailed",[a.id]);arcgisonline.map.main.mapInitialized||arcgisonline.map.main.initMap()}};c.onError=d.connect(c.layer,"onError",d.hitch(this,h,c))},buildConfig:function(c){var b=c.layer.getFeatureLayers(),e={url:c.url,id:c.id,type:"GeoRSS",layerType:"GeoRSS",title:c.title};e.visibility=c.layer.visible;!1===c.showLegend&&(e.showLegend=!1);e.opacity=esri.isDefined(b[0].opacity)?b[0].opacity:1;if(c.scaleChanged&&(b[0].minScale||
b[0].maxScale))e.minScale=b[0].minScale?b[0].minScale:0,e.maxScale=b[0].maxScale&&1!==b[0].maxScale?b[0].maxScale:0;d.forEach(b,function(b){"esri.renderer.SimpleRenderer"==b.renderer.declaredClass&&("esriGeometryPoint"===b.geometryType?e.pointSymbol=b.renderer.symbol.toJson():"esriGeometryPolyline"===b.geometryType?e.lineSymbol=b.renderer.symbol.toJson():"esriGeometryPolygon"===b.geometryType&&(e.polygonSymbol=b.renderer.symbol.toJson()))});c.layer.refreshInterval&&(e.refreshInterval=c.layer.refreshInterval);
return e}}});