// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/map/kml",["dijit","dojo","dojox","dojo/require!arcgisonline/map/main"],function(n,c,p){c.provide("arcgisonline.map.kml");c.require("arcgisonline.map.main");arcgisonline.map.kml={addKMLLayer:function(a,b,c,e){-1==a.indexOf("http")&&(a="http://"+a);b||(b=a.substring(a.lastIndexOf("/")+1,a.length),b=b.substring(0,b.indexOf(".")),0==b.length&&(b="KML"),b={id:"kml_"+Math.floor(10001*Math.random()),visibility:!0,opacity:1,title:b,_addedVia:"url"});a={layer:null,id:b.id,itemId:b.itemId,
url:a,type:"user",subType:"kml",title:b.title,defaultVisibility:b.visibility,defaultOpacity:b.opacity,minScale:b.minScale,maxScale:b.maxScale,snippet:"",identify:!1,refreshInterval:b.refreshInterval,_addedVia:b._addedVia};b.itemId&&(a.itemId=b.itemId);b.itemCard&&(a.itemCard=b.itemCard);null!==b.showLegend&&void 0!==b.showLegend&&(a.showLegend=b.showLegend);var h=arcgisonline.map.layer.getLayerPosition(a);arcgisonline.map.main.mapLayers.splice(h.list,0,a);arcgisonline.map.kml.createKMLLayer(a,h.map,
b.visibleFolders,c,e)},createKMLLayer:function(a,b,g,e,h){var d=function(a){arcgisonline.map.main.mapInitialized||arcgisonline.map.main.initMap();var h=function(a,b){var e=a.getLayers(),d=null;c.forEach(e,function(a){if("esri.layers.FeatureLayer"==a.declaredClass){var e=arcgisonline.map.featColl.getLayerFullExtent(a);e&&(d=!d?e:d.union(e))}else"esri.layers.MapImageLayer"==a.declaredClass?(e=null,c.forEach(a.getImages(),function(a){e=!e?a.extent:e.union(a.extent)},this),e&&(d=!d?e:d.union(e))):"esri.layers.KMLLayer"==
a.declaredClass&&(a.loaded?(e=h(a,b))&&(d=!d?e:d.union(e)):c.connect(a,"onLoad",c.hitch(this,function(a){if(a=h(a,b))b.layer.fullExtent=!b.layer.fullExtent?a:b.layer.fullExtent.union(a),c.publish("KMLNetworkLinkLoaded",[b])})))});return d};a.layer.fullExtent=h(a.layer,a);null!==a.defaultOpacity&&a.layer.setOpacity(a.defaultOpacity);g&&c.forEach(a.layer.folders,function(b){-1<c.indexOf(g,b.id)?a.layer.setFolderVisibility(b,!0):a.layer.setFolderVisibility(b,!1)},this);if(esri.isDefined(a.minScale)&&
esri.isDefined(a.maxScale)){a.layer.setScaleRange(a.minScale,a.maxScale);var d=a.layer.getLayers();c.forEach(d,function(b){b.setScaleRange(a.minScale,a.maxScale)});a.scaleChanged=!0;delete a.minScale;delete a.maxScale}if(!arcgisonline.map.main.isMapFullyLoaded&&-1==document.location.href.indexOf("layers\x3d")&&-1==document.location.href.indexOf("services\x3d"))arcgisonline.map.main.map.addLayer(a.layer,b),arcgisonline.map.popup.setupPopupHandler();else if(a.layer.fullExtent)arcgisonline.map.main.projectToMapAndZoom(a.layer.fullExtent,
0,0,c.hitch(this,function(){arcgisonline.map.main.map.addLayer(a.layer,b);arcgisonline.map.popup.setupPopupHandler()},this));else{arcgisonline.map.main.map.addLayer(a.layer,b);arcgisonline.map.popup.setupPopupHandler();var f=c.subscribe("KMLNetworkLinkLoaded",c.hitch(this,function(a){c.unsubscribe(f);setTimeout(c.hitch(this,function(){arcgisonline.map.main.projectToMapAndZoom(a.layer.fullExtent,0,0,function(){})}),1E3)}))}c.publish("layerAdded",[a.id]);e&&e(a.layer)},l=null,f=arcgisonline.map.main.checkMapSpatialReference();
!f.mapIsWebMercator&&!f.mapIsGCS&&(l=arcgisonline.map.main.map.spatialReference);var f=a.url,k=arcgisonline.sharing.util.getUser(),m=esriGeowConfig.self.urlKey?esriGeowConfig.self.customBaseUrl:esriGeowConfig.self.portalHostname;b=f.indexOf(m);k&&(a.itemId&&-1<b)&&(f="https://"+esriGeowConfig.self.portalHostname+f.substring(b+m.length),(k=arcgisonline.sharing.util.getToken())&&(f+="?token\x3d"+k));a.layer=new esri.layers.KMLLayer(f,{id:a.id,visible:a.defaultVisibility,refreshInterval:a.refreshInterval?
a.refreshInterval:null,outSR:l});a.layer.loaded?d(a):c.connect(a.layer,"onLoad",c.hitch(this,d,a));a.onError=c.connect(a.layer,"onError",c.hitch(this,function(a,b){console.log(c.json.stringify(b));h&&h();var e=arcgisonline.sharing.dijit.dialog.GeneralDlg.prototype.statics.getInstance(),d;if("url"===a._addedVia){d=c.string.substitute(esri.i18nBundle.viewer.kml.error,{url:a.url});if(b.message&&-1<b.message.indexOf("File not found"))d=c.string.substitute(esri.i18nBundle.viewer.kml.badUrl,{url:a.url});
else if(b.message&&(-1<b.message.indexOf(" file size ")||-1<b.message.indexOf("too large")))d=c.string.substitute(esri.i18nBundle.viewer.kml.tooBig,{url:a.url});e.showWide({title:esri.i18nBundle.generalDlg.errorDlgTitle,message:d})}else e.show({title:esri.i18nBundle.generalDlg.errorDlgTitle,message:c.string.substitute(esri.i18nBundle.viewer.kml.notAvailable,{title:a.title})});arcgisonline.map.layer.removeLayer(a);c.publish("layerAddFailed",[a.id]);arcgisonline.map.main.mapInitialized||arcgisonline.map.main.initMap()},
a))},addKMLItem:function(a){var b={id:"kml_"+Math.floor(10001*Math.random()),visibility:!0,opacity:1,title:a.title,itemId:a.id,itemCard:a},g=a.url;g||(g=esriGeowConfig.restBaseUrl+"content/items/"+a.id+"/data");var e=function(){c.publish("ServiceAnswerReceived",[])};arcgisonline.map.kml.addKMLLayer(g,b,c.hitch(this,e),c.hitch(this,e));null!=arcgisonline.map.save_open.itemCard&&null!=a&&arcgisonline.map.save_open.itemCard.id==a.id?(null==arcgisonline.map.save_open.webMapInfo&&arcgisonline.map.main.setTitle(a.title),
arcgisonline.map.leftPanel.recreateAboutStack(),arcgisonline.map.leftPanel.openLeftTOCPanel()):null==arcgisonline.map.save_open.webMapInfo&&null==arcgisonline.map.save_open.itemCard&&arcgisonline.map.main.setTitle(esri.i18nBundle.viewer.defaultMapTitle)},buildConfig:function(a){var b={};a instanceof esri.layers.KMLLayer&&(b.type="KML",b.layerType="KML");b.visibleFolders=[];c.forEach(a.folders,function(a){a.visible&&b.visibleFolders.push(a.id)},this);var g=function(a){for(var c=0;c<a.length;c++){var d=
a[c];if("esri.layers.FeatureLayer"==d.declaredClass||"esri.layers.MapImageLayer"==d.declaredClass){b.opacity=d.opacity||0===d.opacity?d.opacity:1;return}}for(c=0;c<a.length;c++)if(d=a[c],"esri.layers.KMLLayer"==d.declaredClass){g(d.getLayers());break}};g(a.getLayers());a.refreshInterval&&(b.refreshInterval=a.refreshInterval);return b}}});