// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/map/mapNotes",["dijit","dojo","dojox"],function(m,e,p){e.provide("arcgisonline.map.mapNotes");arcgisonline.map.mapNotes={addMapNotesLayer:function(a){arcgisonline.sharing.dijit.dialog.MapNotesDlg.prototype.statics.getInstance().show()},addFeatureLayers:function(a,b,k){e.forEach(a.featureCollection.layers,function(a){a.layerDefinition.capabilities||(a.layerDefinition.capabilities="Query")});var g=a.featureCollection.layers.length,f=Math.floor(10001*Math.random()),d={layer:null,
id:a.id?a.id:"mapNotes_"+f,type:"mapNotes",title:b?b:a.title,defaultVisibility:null!=a.visibility?a.visibility:!0,visibility:null!=a.visibility?a.visibility:!0,defaultOpacity:null!=a.opacity?a.opacity:1,snippet:"",showLegend:a.featureCollection.showLegend,identify:!1,layers:1<g?[]:null,fieldInfos:arcgisonline.map.mapNotes.getFieldInfos()};if(void 0===a.featureCollection.showLegend||null===a.featureCollection.showLegend)d.showLegend=!1;f=arcgisonline.map.main.numLabelsLayers();arcgisonline.map.main.mapLayers.splice(arcgisonline.map.main.mapLayers.length-
f,0,d);delete a.featureCollection.id;for(f=0;f<a.featureCollection.layers.length;f++){var c=a.featureCollection.layers[f],l=!1;if(c.layerDefinition.drawingInfo.renderer){var h=c.layerDefinition.drawingInfo.renderer;"uniqueValue"===h.type&&(h.uniqueValueInfos&&h.uniqueValueInfos.length&&h.uniqueValueInfos[0].symbol&&"esriTS"===h.uniqueValueInfos[0].symbol.type)&&(l=!0)}b&&0<b.length&&(c.layerDefinition.name=c.layerDefinition.name);c.popupInfo||(c.popupInfo={title:"{TITLE}",description:"{DESCRIPTION}",
mediaInfos:[{type:"image",value:{sourceURL:"{IMAGE_URL}",linkURL:"{IMAGE_LINK_URL}"}}]});l&&delete c.popupInfo;h=d.id+(1<g?"_"+f:"");l=null;!1===c.showLegend&&(l=!1);delete c.showLegend;c=arcgisonline.map.featColl.addFeatureLayer(c,d.defaultVisibility,d.defaultOpacity,h);!1===l&&(c.__showLegend=!1);d.layers?d.layers.push(c):d.layer=c}var n=e.connect(arcgisonline.map.main.map,"onLayersAddResult",e.hitch(this,function(){e.disconnect(n);if(d.layers)for(var a=0;a<d.layers.length;a++){var c=d.layers[a].toJson();
-1<d.layers[a].name.indexOf("Text")&&e.forEach(c.featureSet.features,function(c,f){if(c.attributes.TEXT){var b=d.layers[a].graphics[f];b.symbol.setText(c.attributes.TEXT);c.symbol.horizontalAlignment&&(b.symbol.align=c.symbol.horizontalAlignment);b.setSymbol(b.symbol);b.setAttributes(c.attributes)}},this)}else c=d.layer.toJson(),-1<d.layer.name.indexOf("Text")&&e.forEach(c.featureSet.features,function(a,c){if(a.attributes.TEXT){var b=d.layer.graphics[c];b.symbol.setText(a.attributes.TEXT);a.symbol.horizontalAlignment&&
(b.symbol.align=a.symbol.horizontalAlignment);b.setSymbol(b.symbol);b.setAttributes(a.attributes)}},this);b&&(0<b.length&&!k)&&("editStack"===arcgisonline.map.leftPanel.getLeftContentPanelStack()?setTimeout(function(){m.byId("editPanel").recreateEditor()},0):(arcgisonline.map.leftPanel.openLeftEditPanel(),arcgisonline.map.edit.enableEditButton()))}));d.layers?arcgisonline.map.main.map.addLayers(d.layers):arcgisonline.map.main.map.addLayer(d.layer)},getMapNotesConfig:function(a,b,k){var g=function(a,
b){arcgisonline.sharing.dijit.dialog.GeneralDlg.prototype.statics.getInstance().show({title:esri.i18nBundle.generalDlg.errorDlgTitle,message:esri.i18nBundle.viewer.mapNotes.notAdded})};arcgisonline.sharing.util.getJson(esriGeowConfig.restBaseUrl+"/content/items/"+a+"/data",e.hitch(this,function(a,d){a||(a={});a.layers?((esriGeowConfig.allSSL||"https:"==location.protocol)&&e.forEach(a.layers,function(a){a=a.layerDefinition.drawingInfo.renderer;a.symbol&&a.symbol.url&&arcgisonline.sharing.util.supportsHttps(a.symbol.url)?
a.symbol.url=a.symbol.url.replace("http:","https:"):a.uniqueValueInfos&&e.forEach(a.uniqueValueInfos,function(a){a.symbol.url&&arcgisonline.sharing.util.supportsHttps(a.symbol.url)&&(a.symbol.url=a.symbol.url.replace("http:","https:"))})}),arcgisonline.map.mapNotes.addFeatureLayers({featureCollection:a},b,k),arcgisonline.map.main.markMapAsChanged("getMapNotesConfig")):g(a,d)}),e.hitch(this,g))},isMapNotesMapLayer:function(a){return a.layer?(a=a.layer.toJson(),arcgisonline.map.mapNotes.isMapNotesFeatColl(a)):
a.layers?(a=a.layers[0].toJson(),arcgisonline.map.mapNotes.isMapNotesFeatColl(a)):!1},isMapNotesLayer:function(a){return arcgisonline.map.mapNotes.isMapNotesFeatColl(a.featureCollection.layers[0])},isMapNotesFeatColl:function(a){var b=",",k="";e.forEach(a.layerDefinition.fields,function(a){b+=k+a.name;k=","});b=b.toLowerCase();a=arcgisonline.map.mapNotes.getFieldInfos();for(var g=0;g<a.length;g++){var f=a[g].fieldName.toLowerCase();if(-1===b.indexOf(","+f+","))return a=null,!1}return!0},getFieldInfos:function(){return[{fieldName:"TITLE",
stringFieldOption:esri.dijit.AttributeInspector.STRING_FIELD_OPTION_TEXTBOX},{fieldName:"DESCRIPTION",stringFieldOption:esri.dijit.AttributeInspector.STRING_FIELD_OPTION_RICHTEXT,richTextPlugins:"bold italic underline foreColor hiliteColor | justifyLeft justifyCenter justifyRight justifyFull | insertOrderedList insertUnorderedList | createLink unlink | undo redo".split(" ")},{fieldName:"IMAGE_URL",stringFieldOption:esri.dijit.AttributeInspector.STRING_FIELD_OPTION_TEXTBOX},{fieldName:"IMAGE_LINK_URL",
stringFieldOption:esri.dijit.AttributeInspector.STRING_FIELD_OPTION_TEXTBOX}]}}});