// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/map/print",["dijit","dojo","dojox","dojo/require!arcgisonline/map/main,dojo/io/iframe"],function(g,a,h){a.provide("arcgisonline.map.print");a.require("arcgisonline.map.main");a.require("dojo.io.iframe");arcgisonline.map.print={printMap:function(a){arcgisonline.map.print.template=a;window.open("print.html","WebMapViewerPrint")},initPrint:function(){arcgisonline.map.main.mapLayers=top.opener.arcgisonline.map.main.mapLayers;arcgisonline.map.save_open.webMapInfo=top.opener.arcgisonline.map.save_open.webMapInfo;
arcgisonline.map.save_open.itemCard=top.opener.arcgisonline.map.save_open.itemCard;arcgisonline.map.main.map=top.opener.arcgisonline.map.main.map;arcgisonline.map.print.template=top.opener.arcgisonline.map.print.template;arcgisonline.map.print.initPrint2()},initPrint2:function(){if(!arcgisonline.map.print.template||"MAP_ONLY"===arcgisonline.map.print.template.layout&&"PDF"!==arcgisonline.map.print.template.format){var b="";if(arcgisonline.map.save_open.webMapInfo){if("_r_"==arcgisonline.map.save_open.webMapInfo.description){var b=
esriGeowConfig.restBaseUrl+"content/items/"+arcgisonline.map.save_open.webMapInfo.id,d=function(a,c){arcgisonline.map.save_open.webMapItemCard=a;arcgisonline.map.save_open.webMapInfo.snippet=a.snippet;arcgisonline.map.save_open.webMapInfo.description=a.description;arcgisonline.map.print.initPrint2()},c=function(a,c){arcgisonline.map.save_open.webMapInfo.snippet="";arcgisonline.map.save_open.webMapInfo.description="";arcgisonline.map.print.initPrint2()};arcgisonline.sharing.util.getJson(b,a.hitch(this,
d),a.hitch(this,c));return}b='\x3cdiv class\x3d"print_title"\x3e'+arcgisonline.map.save_open.webMapInfo.title+"\x3c/div\x3e";d=arcgisonline.sharing.util.getSnippet(arcgisonline.map.save_open.webMapInfo.snippet,arcgisonline.map.save_open.webMapInfo.description);250<d.length&&(d=d.substring(0,250)+esri.i18nBundle.viewer.shortenedTextEnding);b+='\x3cdiv class\x3d"print-snippet"\x3e'+d+"\x3c/div\x3e";a.doc.title=(esriGeowConfig.portalName?esriGeowConfig.portalName:esri.i18nBundle.common.arcgis)+" - "+
arcgisonline.map.save_open.webMapInfo.title}else{for(c=d=b=0;c<arcgisonline.map.main.mapLayers.length;c++)"user"==arcgisonline.map.main.mapLayers[c].type&&(b++,d=c);if(1==b){var e=arcgisonline.map.main.mapLayers[d];if(e.itemId){b='\x3cdiv class\x3d"print_title"\x3e'+e.title+"\x3c/div\x3e";a.doc.title=(esriGeowConfig.portalName?esriGeowConfig.portalName:esri.i18nBundle.common.arcgis)+" - "+e.title;if(!e.serviceInfo){b=esriGeowConfig.restBaseUrl+"content/items/"+e.itemId;d=function(a,c){e.serviceInfo=
a;e.snippet=arcgisonline.sharing.util.getSnippet(a.snippet,a.description);arcgisonline.map.print.initPrint2()};c=function(a,c){e.snippet="";arcgisonline.map.print.initPrint2()};arcgisonline.sharing.util.getJson(b,a.hitch(this,d),a.hitch(this,c));return}d=e.snippet;null==d&&(d="");b+='\x3cdiv class\x3d"print-snippet"\x3e'+d+"\x3c/div\x3e"}else b='\x3cdiv class\x3d"print_title"\x3e'+esri.i18nBundle.viewer.defaultMapTitle+"\x3c/div\x3e",b+='\x3cdiv class\x3d"print-snippet"\x3e\x3c/div\x3e',a.doc.title=
(esriGeowConfig.portalName?esriGeowConfig.portalName:esri.i18nBundle.common.arcgis)+" - "+esri.i18nBundle.viewer.defaultMapTitle}else b='\x3cdiv class\x3d"print_title"\x3e'+esri.i18nBundle.viewer.defaultMapTitle+"\x3c/div\x3e",b+='\x3cdiv class\x3d"print-snippet"\x3e\x3c/div\x3e',a.doc.title=(esriGeowConfig.portalName?esriGeowConfig.portalName:esri.i18nBundle.common.arcgis)+" - "+esri.i18nBundle.viewer.defaultMapTitle}arcgisonline.sharing.geow.Account.getSelf(function(c){if(c&&c.id){c=(esriGeowConfig.portalName?
esriGeowConfig.portalName:esri.i18nBundle.common.arcgis)+" - ";var b=a.doc.title.indexOf(c);a.doc.title=a.doc.title.substring(b+(c?c.length:0))}});a.byId("print-title").innerHTML=b;a.byId("print-copyright").innerHTML='\x3cspan style\x3d"float:right;padding-top:6px;"\x3e'+top.opener.arcgisonline.map.print.getMapAttribution()+"\x3c/span\x3e"}else a.body().innerHTML='\x3cdiv style\x3d"background: url(images/loading-throb.gif) no-repeat center; width: 100%; height: 100%"\x3e\x3cdiv style\x3d"position: absolute; left: 50%; top: 50%; margin: 30px 0 0 -30px;"\x3e'+
esri.i18nBundle.arcGISServerServices.loadingShort+"\x3c/div\x3e\x3c/div\x3e";!arcgisonline.map.print.template||"MAP_ONLY"===arcgisonline.map.print.template.layout?top.opener.arcgisonline.map.print.buildPrintMap().then(a.hitch(arcgisonline.map.print,arcgisonline.map.print.printComplete),a.hitch(arcgisonline.map.print,arcgisonline.map.print.printError)):arcgisonline.map.save_open.webMapInfo?arcgisonline.map.save_open.webMapInfo.ownerFullName?top.opener.arcgisonline.map.print.buildPrintMap(arcgisonline.map.save_open.webMapInfo.ownerFullName).then(a.hitch(arcgisonline.map.print,
arcgisonline.map.print.printComplete),a.hitch(arcgisonline.map.print,arcgisonline.map.print.printError)):arcgisonline.sharing.geow.Community.getProfile(arcgisonline.map.save_open.webMapInfo.owner,a.hitch(this,a.hitch(this,function(c,b){arcgisonline.map.save_open.webMapInfo.ownerFullName=c.fullName;top.opener.arcgisonline.map.print.buildPrintMap(c.fullName).then(a.hitch(arcgisonline.map.print,arcgisonline.map.print.printComplete),a.hitch(arcgisonline.map.print,arcgisonline.map.print.printError))})),
a.hitch(this,function(){top.opener.arcgisonline.map.print.buildPrintMap(arcgisonline.map.save_open.webMapInfo.owner).then(a.hitch(arcgisonline.map.print,arcgisonline.map.print.printComplete),a.hitch(arcgisonline.map.print,arcgisonline.map.print.printError))})):arcgisonline.map.save_open.itemCard?arcgisonline.map.save_open.itemCard.ownerFullName?top.opener.arcgisonline.map.print.buildPrintMap(arcgisonline.map.save_open.itemCard.ownerFullName).then(a.hitch(arcgisonline.map.print,arcgisonline.map.print.printComplete),
a.hitch(arcgisonline.map.print,arcgisonline.map.print.printError)):arcgisonline.sharing.geow.Community.getProfile(arcgisonline.map.save_open.itemCard.owner,a.hitch(this,a.hitch(this,function(c,b){arcgisonline.map.save_open.itemCard.ownerFullName=c.fullName;top.opener.arcgisonline.map.print.buildPrintMap(c.fullName).then(a.hitch(arcgisonline.map.print,arcgisonline.map.print.printComplete),a.hitch(arcgisonline.map.print,arcgisonline.map.print.printError))})),a.hitch(this,function(){top.opener.arcgisonline.map.print.buildPrintMap(arcgisonline.map.save_open.itemCard.owner).then(a.hitch(arcgisonline.map.print,
arcgisonline.map.print.printComplete),a.hitch(arcgisonline.map.print,arcgisonline.map.print.printError))})):(b=top.opener.arcgisonline.sharing.util.getUser(),top.opener.arcgisonline.map.print.buildPrintMap(b&&b.fullName).then(a.hitch(arcgisonline.map.print,arcgisonline.map.print.printComplete),a.hitch(arcgisonline.map.print,arcgisonline.map.print.printError)))},buildPrintMap:function(b){var d=new esri.tasks.PrintTemplate;!arcgisonline.map.print.template||"MAP_ONLY"===arcgisonline.map.print.template.layout?
(arcgisonline.map.print.template=arcgisonline.map.print.template||{},d.layout="MAP_ONLY",d.format=arcgisonline.map.print.template.format||"png32",d.showAttribution=!1,d.exportOptions=arcgisonline.map.print.template.exportOptions||{width:670,height:500,dpi:96}):(d.layout=arcgisonline.map.print.template.layout,d.format=arcgisonline.map.print.template.format,d.exportOptions=arcgisonline.map.print.template.exportOptions,d.layoutOptions=arcgisonline.map.print.template.layoutOptions||{},d.layoutOptions.titleText=
document.getElementById("webmap-title-text").innerHTML,d.layoutOptions.scalebarUnit="english"===arcgisonline.map.main.scaleBarUnits?"Miles":"Kilometers",d.layoutOptions.copyrightText=arcgisonline.map.print.getMapAttribution(),!1===arcgisonline.map.print.template.layoutOptions.legend?d.layoutOptions.legendLayers=[]:(d.layoutOptions.legendLayers=[],a.forEach(arcgisonline.map.main.mapLayers,function(c){if(c&&("base"!=c.type&&"labels"!=c.type&&!1!==c.showLegend||("base"==c.type||"labels"==c.type)&&!0===
c.showLegend))if(c.layers)a.forEach(c.layers,function(a){if(!1!==c.showLegend&&a.visible){a.arcgisProps={title:c.title!==a.name?c.title+" - "+a.name:c.title};var b=new esri.tasks.LegendLayer;b.layerId=a.id;d.layoutOptions.legendLayers.push(b)}},this);else if(c.layer&&c.layer.visible)if(c.layer instanceof esri.layers.GeoRSSLayer&&!1!==c.showLegend){var b=c.layer.getFeatureLayers();a.forEach(b,function(a){var b=c.title+" - ";"esriGeometryPoint"==a.geometryType?b+=esri.i18nBundle.common.points:"esriGeometryPolyline"==
a.geometryType?b+=esri.i18nBundle.common.lines:"esriGeometryPolygon"==a.geometryType&&(b+=esri.i18nBundle.common.areas);a.arcgisProps={title:b};b=new esri.tasks.LegendLayer;b.layerId=a.id;d.layoutOptions.legendLayers.push(b)})}else if(c.layer instanceof esri.layers.WMSLayer)b=new esri.tasks.LegendLayer,b.layerId=c.layer.id,b.subLayerIds=c.visibleLayers.split(","),d.layoutOptions.legendLayers.push(b);else if(c.itemLayers){var f=null,f=a.map(c.layer.dynamicLayerInfos||c.layer.layerInfos,function(a){return a.id});
a.forEach(c.itemLayers,function(b){!1===b.showLegend&&(b=a.indexOf(f,b.id),-1<b&&f.splice(b,1))});if(!esri.isDefined(f)||f.length)b=new esri.tasks.LegendLayer,b.layerId=c.layer.id,esri.isDefined(f)&&f.length&&(b.subLayerIds=f),d.layoutOptions.legendLayers.push(b)}else c.layer.arcgisProps={title:c.title},b=new esri.tasks.LegendLayer,b.layerId=c.layer.id,d.layoutOptions.legendLayers.push(b)})),b&&(d.layoutOptions.authorText=b));arcgisonline.map.print.printTask||(arcgisonline.map.print.printTask=new esri.tasks.PrintTask(esriGeowConfig.self.helperServices.printTask.url,
{}));b=new esri.tasks.PrintParameters;b.map=arcgisonline.map.main.map;b.template=d;esri.config.defaults.io.timeout=12E4;return arcgisonline.map.print.printTask.execute(b)},printComplete:function(b){esri.config.defaults.io.timeout=6E4;!arcgisonline.map.print.template||"MAP_ONLY"===arcgisonline.map.print.template.layout&&"PDF"!==arcgisonline.map.print.template.format?(a.byId("print-map-img").onload=function(){a.style(a.byId("loadingMsg"),"display","none")},a.byId("print-map-img").src=b.url):window.location=
b.url},printError:function(b){esri.config.defaults.io.timeout=6E4;!arcgisonline.map.print.template||"MAP_ONLY"===arcgisonline.map.print.template.layout?a.byId("print-map").innerHTML="\x3cdiv style\x3d'padding:10px'\x3e"+esri.i18nBundle.print.errorMsg+"\x3c/div\x3e":a.body().innerHTML="\x3cdiv style\x3d'padding:10px'\x3e"+esri.i18nBundle.print.errorMsg+"\x3c/div\x3e";console.log(b.message?b.message:b)},getMapAttribution:function(){var b="",d="";a.query(".esriAttributionItem","map_root").forEach(function(a){if(a=
a.innerHTML)b+=d+a.substring(0,a.indexOf("\x3cspan")),d=" | "});a.query(".esriAttributionLastItem","map_root").forEach(function(a){if(a=a.innerHTML)b+=d+a.substring(0,a.indexOf("\x3cspan")),d=" | "});return b}}});