// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/map/vectorTile",["dijit","dojo","dojox","dojo/require!arcgisonline/map/main"],function(q,c,r){c.provide("arcgisonline.map.vectorTile");c.require("arcgisonline.map.main");arcgisonline.map.vectorTile={onVectorTileServiceCreateHandler:null,addVectorTileLayer:function(a,b,e,d,f){arcgisonline.map.vectorTile.checkSupport().then(c.hitch(this,function(a,b,e,d,f,g){if(g)if(!a&&b&&b.itemId)arcgisonline.map.vectorTile.getStyleUrlFromItemId(b.itemId,b.itemCard).then(c.hitch(this,function(a,
b,c,k,e){arcgisonline.map.vectorTile.addVectorTileLayer(e,a,b,c,k)},b,e,d,f),c.hitch(this,function(a){a&&a()},d));else{if(!b){b=a.indexOf("/VectorTileServer");g="";-1<b?(g=a.substring(0,b).lastIndexOf("/"),g=a.substring(g+1,b)):(b=a.indexOf("//")+2,g=a.substring(b,a.indexOf("/",b)));0==g.length&&(g="VectorTileLayer");var h=Math.floor(10001*Math.random());b={id:"VectorTile_"+h,visibility:!0,opacity:1,title:g,_addedVia:"url"}}b.id||(h=Math.floor(10001*Math.random()),b=c.mixin(b,{id:"VectorTile_"+h,
visibility:!0,opacity:1,_addedVia:"url"}));a={layer:null,id:b.id,itemId:b.itemId,url:a,type:b.type?b.type:"user",subType:"VectorTileLayer",title:b.title,itemCard:b.itemCard,visibility:!0,defaultVisibility:b.visibility,defaultOpacity:b.opacity,minScale:b.minScale,maxScale:b.maxScale,_addedVia:b._addedVia};f||(f=arcgisonline.map.layer.getLayerPosition(a));arcgisonline.map.main.mapLayers.splice(f.list,0,a);arcgisonline.map.vectorTile.createVectorTileLayer(a,f.map,e,d)}else c.publish("layerAddFailed",
[]),arcgisonline.map.vectorTile.displayErrorMessage(b||{url:a})},a,b,e,d,f))},createVectorTileLayer:function(a,b,e,d){var f=function(a){if("user"===a.type){var d=new esri.SpatialReference(a.layer.spatialReference),d=arcgisonline.map.main.sameSpatialReference(d,arcgisonline.map.main.map.spatialReference),f=arcgisonline.map.main.mapLayers[0].layer.tileInfo&&arcgisonline.map.main.sameTilingScheme(arcgisonline.map.main.mapLayers[0].layer.tileInfo,a.layer.tileInfo);if(!d||!f){arcgisonline.sharing.dijit.dialog.GeneralDlg.prototype.statics.getInstance().show({title:esri.i18nBundle.generalDlg.errorDlgTitle,
message:c.string.substitute(esri.i18nBundle.viewer.error.layerDoesntFit,{layer:a.title})});arcgisonline.map.layer.removeLayer(a);c.publish("layerAddFailed",[a.id]);return}}"labels"===a.type&&a.layer.attr("data-reference",!0);c.publish("onLayerUpdate",[""]);esri.isDefined(a.minScale)&&esri.isDefined(a.maxScale)&&(a.layer.setScaleRange(a.minScale,a.maxScale),a.scaleChanged=!0,delete a.minScale,delete a.maxScale);esri.isDefined(a.defaultOpacity)&&a.layer.setOpacity&&a.layer.setOpacity(a.defaultOpacity);
d=arcgisonline.sharing.util.urlToObject(document.URL);d.query=d.query||{};!arcgisonline.map.main.mapInitialized&&d.query.vectorTile&&arcgisonline.map.main.initMap();!arcgisonline.map.main.isMapFullyLoaded&&!d.query.layers&&!d.query.services?(arcgisonline.map.main.map.addLayer(a.layer,b),c.publish("layerAdded",[a.id]),e&&e(a.layer)):a.layer.fullExtent?arcgisonline.map.main.getIntersectionPercent(a.layer.fullExtent,arcgisonline.map.main.map.extent).then(c.hitch(this,function(d){5>d?(arcgisonline.map.main.map.addLayer(a.layer,
b),arcgisonline.map.main.map.setExtent(a.layer.fullExtent,!1)):arcgisonline.map.main.map.addLayer(a.layer,b);c.publish("layerAdded",[a.id]);e&&e(a.layer)})):(arcgisonline.map.main.map.addLayer(a.layer,b),c.publish("layerAdded",[a.id]),e&&e(a.layer));!arcgisonline.map.save_open.webMapInfo&&!arcgisonline.map.save_open.itemCard&&arcgisonline.map.main.setTitle(esri.i18nBundle.viewer.defaultMapTitle)};a.layer?f(a):(a.layer=new esri.layers.VectorTileLayer(a.url,{id:a.id,visible:a.defaultVisibility}),a.layer.loaded?
f(a):c.connect(a.layer,"onLoad",c.hitch(this,f,a)),a.onError=c.connect(a.layer,"onError",c.hitch(this,function(a,b){console.log(b&&b.message||b);if(!a.layer||!a.layer.loaded)d&&d(),arcgisonline.map.vectorTile.displayErrorMessage(a),arcgisonline.map.layer.removeLayer(a),c.publish("layerAddFailed",[a.id]),arcgisonline.map.main.mapInitialized||arcgisonline.map.main.initMap()},a)))},addVectorTileAsBaseLayer:function(a,b,e,d,f){arcgisonline.map.main.isUserBaseService=!0;var k=function(){c.unsubscribe(p);
c.unsubscribe(l);c.unsubscribe(g);arcgisonline.map.main.currentBaseService=b.id;arcgisonline.map.main.defaultService=b;arcgisonline.map.main.defaultBaseLayerMapLods=b.layer.tileInfo.lods;arcgisonline.map.main.mapLods=arcgisonline.map.main.defaultBaseLayerMapLods;if(null==arcgisonline.map.main.mapLods){arcgisonline.map.main.mapLods=b.layer.tileInfo.lods;arcgisonline.map.main.baseTilingSchemeScales="|";for(i=0;i<b.layer.tileInfo.lods.length;i++)arcgisonline.map.main.baseTilingSchemeScales+=b.layer.tileInfo.lods[i].scale+
"|"}arcgisonline.map.main.recreateOverviewMap();e&&e(b)},m=function(a,e){c.unsubscribe(p);c.unsubscribe(l);c.unsubscribe(g);arcgisonline.sharing.dijit.dialog.GeneralDlg.prototype.statics.getInstance().show({title:esri.i18nBundle.generalDlg.errorDlgTitle,message:c.string.substitute(esri.i18nBundle.viewer.error.layerNotAdded,{layer:b.title})});arcgisonline.map.layer.loadDefaultMap();d&&d()};if(b)b.type="base";else{var n=a.styleUrl;if(!n&&a.itemId){arcgisonline.map.vectorTile.getStyleUrlFromItemId(a.itemId,
a.itemCard).then(c.hitch(this,function(a,b,c,d,e,f){a.styleUrl=f;arcgisonline.map.vectorTile.addVectorTileAsBaseLayer(a,b,c,d,e)},a,b,e,d,f),c.hitch(this,function(){m()}));return}b={layer:null,id:a.id,url:n,type:"base",subType:"VectorTileLayer",title:a.title,defaultVisibility:a.visibility,defaultOpacity:a.opacity};a.itemId&&(b.itemId=a.itemId);esri.isDefined(a.minScale)&&esri.isDefined(a.maxScale)&&(b.minScale=a.minScale,b.maxScale=a.maxScale);arcgisonline.map.main.mapLayers.push(b)}var p=c.subscribe("layerAdded",
c.hitch(this,k)),l=c.subscribe("layerAddedNoRemove",c.hitch(this,k)),g=c.subscribe("layerAddFailed",c.hitch(this,m));if(f){var h=function(a){arcgisonline.map.main.defaultExtent=new esri.geometry.Extent(a.layer.fullExtent.toJson());arcgisonline.map.main.currentBaseService=a.id;arcgisonline.map.main.defaultService=a;var b=arcgisonline.map.main.defaultExtent.spatialReference,c=arcgisonline.map.main.map.extent,d=a.layer.tileInfo;if(arcgisonline.map.save_open.checkIfOpLayersFitToNewBasemap(b,{tileInfo:d})){var e=
arcgisonline.map.main.sameSpatialReference(c.spatialReference,b);if(arcgisonline.map.layer.sameTilingSchemeAsBasemap({tileInfo:d})&&e){arcgisonline.map.main.updateTilingScheme(d,arcgisonline.map.main.mapLayers[0].layer.tileInfo.dpi);arcgisonline.map.layer.removeLabelsLayers();b=[];for(c=0;c<arcgisonline.map.main.mapLayers.length;c++)d=arcgisonline.map.main.mapLayers[c],"base"==d.type?(arcgisonline.map.main.mapLayers[c]=null,d.layer&&arcgisonline.map.main.map.removeLayer(d.layer)):b[b.length]=d;arcgisonline.map.main.mapLayers=
b;for(c=arcgisonline.map.main.mapLayers.length;0<c;c--)arcgisonline.map.main.mapLayers[c]=arcgisonline.map.main.mapLayers[c-1];arcgisonline.map.main.mapLayers[0]=a;arcgisonline.map.main.currentBaseService=a.id;arcgisonline.map.main.defaultService=a;arcgisonline.map.vectorTile.createVectorTileLayer(a,0)}else arcgisonline.map.main.defaultExtent=new esri.geometry.Extent(a.layer.fullExtent.toJson()),arcgisonline.map.main.mapLods=null,arcgisonline.map.main.baseTilingSchemeScales="",arcgisonline.map.save_open.basemapWebMap=
null,arcgisonline.map.save_open.prepRecreateMap(a,b,c);arcgisonline.map.main.markMapAsChanged("addVectorTileAsBaseLayer")}};b.layer?h(b):(b.layer=new esri.layers.VectorTileLayer(b.url,{id:b.id}),a=function(a){h(a)},b.layer.loaded?a(b):c.connect(b.layer,"onLoad",c.hitch(this,a,b)))}else h=function(a){arcgisonline.map.main.currentBaseService=a.id;arcgisonline.map.main.defaultService=a;arcgisonline.map.main.defaultExtent=new esri.geometry.Extent(a.layer.fullExtent.toJson());arcgisonline.map.main.createMapObject(null,
arcgisonline.map.main.defaultExtent);arcgisonline.map.main.map.addLayer(a.layer,0);c.publish("layerAddedNoRemove",[a.id]);c.publish("onLayerUpdate",[""]);arcgisonline.map.main.markMapAsChanged("addVectorTileAsBaseLayer")},arcgisonline.map.main.mapLods=null,arcgisonline.map.main.baseTilingSchemeScales="",b.layer?h(b):(b.layer=new esri.layers.VectorTileLayer(b.url,{id:b.id}),a=function(a){h(a)},b.layer.loaded?a(b):c.connect(b.layer,"onLoad",c.hitch(this,a,b)))},addVectorTileLayerItem:function(a){arcgisonline.map.vectorTile.getStyleUrlFromItemId(a.id,
a).then(c.hitch(this,function(a,c,d){arcgisonline.map.vectorTile.addVectorTileLayer(d,{itemCard:a,itemId:a.id,title:a.title},c)},a,function(){arcgisonline.map.save_open.itemCard&&a&&arcgisonline.map.save_open.itemCard.id===a.id?(arcgisonline.map.save_open.webMapInfo||arcgisonline.map.main.setTitle(a.title),arcgisonline.map.leftPanel.recreateAboutStack(),arcgisonline.map.leftPanel.openLeftTOCPanel()):!arcgisonline.map.save_open.webMapInfo&&!arcgisonline.map.save_open.itemCard&&arcgisonline.map.main.setTitle(esri.i18nBundle.viewer.defaultMapTitle)}))},
addVectorTileLayerItemAsBasemap:function(a){a={id:"VectorTile_"+Math.floor(10001*Math.random()),type:"VectorTileLayer",layerType:"VectorTileLayer",title:a.title,itemCard:a,itemId:a.id,visibility:!0,opacity:1};arcgisonline.map.vectorTile.addVectorTileAsBaseLayer(a,null,function(){},function(){},!0)},copyLayer:function(a){var b=Math.floor(10001*Math.random()),b={id:a.id+"_"+b,title:a.title+" - "+esri.i18nBundle.viewer.copy.copy,url:a.url,type:a.type,subType:a.subType,defaultOpacity:a.layer.opacity,
defaultVisibility:a.layer?a.layer.visible:a.visibility,visibility:a.visibility,minScale:a.minScale,maxScale:a.maxScale};a.itemId&&(b.oldItemCard=c.clone(a.itemCard));if(a.scaleChanged&&(b.minScale=a.layer.minScale?a.layer.minScale:0,b.maxScale=a.layer.maxScale&&1!==a.layer.maxScale?a.layer.maxScale:0,(!a.itemId||!a.origItemLayers)&&0===b.minScale&&0===b.maxScale))delete b.minScale,delete b.maxScale;a=arcgisonline.map.layer.getLayerPosition(b);arcgisonline.map.main.mapLayers.splice(a.list,0,b);arcgisonline.map.vectorTile.createVectorTileLayer(b,
a.map,function(a){arcgisonline.map.main.markMapAsChanged("copyLayer")})},addVectorTileLayerConfig:function(a,b){a.styleUrl?arcgisonline.map.vectorTile.addVectorTileLayer(a.styleUrl,a,b):arcgisonline.map.vectorTile.getStyleUrlFromItemId(a.itemId,a.itemCard).then(c.hitch(this,function(a,b,c){a.styleUrl=c;arcgisonline.map.vectorTile.addVectorTileLayer(c,a,b)},a,b),c.hitch(this,function(){c.publish("layerAddFailed",[]);arcgisonline.map.vectorTile.displayErrorMessage(a)}))},getStyleUrlFromItemId:function(a,
b){var e=new c.Deferred,d=esriGeowConfig.restBaseUrl+"content/items/"+a+"/resources/styles/root.json";if(!esriGeowConfig.self.isPortal)var f=d.indexOf("://"),k=d.indexOf("/",f+3),d=d.substring(0,f+3)+esriGeowConfig.self.portalHostname+d.substring(k);esri.request({url:d+"?f\x3djson",callbackParamName:"callback",load:c.hitch(this,function(a,b,c){e.resolve(a)},d),error:c.hitch(this,function(a,b,d,f){b?e.resolve(b.url+"/resources/styles/root.json"):esri.request({url:esriGeowConfig.restBaseUrl+"content/items/"+
a+"?f\x3djson",callbackParamName:"callback",load:c.hitch(this,function(a,b){e.resolve(a.url+"/resources/styles/root.json")}),error:c.hitch(this,function(a,b){e.reject()})})},a,b)});return e},getStyleInfo:function(a){a+=-1<a.indexOf("?")?"\x26f\x3djson":"?f\x3djson";return esri.request({url:a,callbackParamName:"callback"})},checkSupport:function(){var a=new c.Deferred;esri.isDefined(arcgisonline.map.vectorTile.supported)?a.resolve(arcgisonline.map.vectorTile.supported):c.isIE?a.resolve(!1):window.require(["esri/layers/vector-tile"],
function(b){arcgisonline.map.vectorTile.supported=b.supported();a.resolve(arcgisonline.map.vectorTile.supported)});return a},checkFallBackVectorTileLayers:function(a){for(var b=new c.Deferred,e=a.baseMap.baseMapLayers,d=0;d<e.length;d++){var f=e[d];if(!f.isReference){"VectorTileLayer"===f.layerType&&f.itemId?arcgisonline.map.vectorTile.checkSupport().then(c.hitch(this,function(a,d,e,f,l){if(l)b.resolve(a);else{var g=RegExp(/^https?:\/\/basemaps(dev)?\.arcgis\.com\/arcgis\/rest\/services\/World_Basemap\/VectorTileServer/i);
esri.request({url:esriGeowConfig.restBaseUrl+"content/items/"+d.itemId+"?f\x3djson",callbackParamName:"callback",load:c.hitch(this,function(a,c,d,k){if(d.url.match(g)&&(console.log("Basemap, "+(c.baseMap.title||c.baseMap.baseMapLayers[0].title)+", contains a Vector Tile layer which is not supported. Switching to Esri Streets basemap instead."),c.baseMap.title="Streets",e[f]={id:"FB_"+a.id,layerType:"ArcGISTiledMapServiceLayer",opacity:"opacity"in a?a.opacity:1,visibility:"visibility"in a?a.visibility:
!0,url:"http://services.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer"},esriGeowConfig.allSSL||"https:"==location.protocol))e[f].url=e[f].url.replace("http:","https:");b.resolve(c)},d,a),error:c.hitch(this,function(a,c,d){b.resolve(a)},a)})}},a,f,e,d)):b.resolve(a);break}}return b},checkIfFitsToNewService:function(a,b,c){if(b.wkid&&c){var d=a.layer.tileInfo;a=arcgisonline.map.main.sameSpatialReference(a.layer.spatialReference,b);c=arcgisonline.map.main.sameTilingScheme(d,c);return!a||
!c?!1:!0}return!1},displayErrorMessage:function(a){arcgisonline.sharing.dijit.dialog.GeneralDlg.prototype.statics.getInstance().show({title:esri.i18nBundle.generalDlg.errorDlgTitle,message:c.string.substitute(esri.i18nBundle.viewer.error.layerNotAdded,{layer:"url"===a._addedVia&&!a.itemId&&a.url||a.title||a.itemCard&&a.itemCard.title||a.url||a.styleUrl})})},buildConfig:function(a){var b={id:a.id,type:"VectorTileLayer",layerType:"VectorTileLayer",title:a.title};b.styleUrl=a.layer.styleUrl;a.itemId?
b.itemId=a.itemId:b.styleUrl=a.url;"labels"===a.type&&(b.isReference=!0);b.visibility=a.layer.visible;b.opacity=esri.isDefined(a.layer.opacity)?a.layer.opacity:1;if(a.scaleChanged&&(a.layer.minScale||a.layer.maxScale))b.minScale=a.layer.minScale?a.layer.minScale:0,b.maxScale=a.layer.maxScale&&1!==a.layer.maxScale?a.layer.maxScale:0;return b}}});