// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/persist",["dijit","dojo","dojox"],function(q,p,s){p.provide("arcgisonline.persist");arcgisonline.persist=function(){var f,h,g,l,n,k;k=function(){var a=["expires","path","domain"],b=escape,c=unescape,d=document,e,g=function(c,d){var m,e,g,f=[],h=2<arguments.length?arguments[2]:{};f.push(b(c)+"\x3d"+b(d));for(m=0;m<a.length;m++)e=a[m],(g=h[e])&&f.push(e+"\x3d"+g);h.secure&&f.push("secure");return f.join("; ")};e={set:function(a,b){var c=2<arguments.length?arguments[2]:{},e=new Date;
e.setTime(e.getTime());var f={};c.expires&&(c.expires*=864E5,f.expires=new Date(e.getTime()+c.expires),f.expires=f.expires.toGMTString());e=["path","domain","secure"];for(i=0;i<e.length;i++)c[e[i]]&&(f[e[i]]=c[e[i]]);c=g(a,b,f);d.cookie=c;return b},has:function(a){a=b(a);var c=d.cookie,e=c.indexOf(a+"\x3d"),c=c.substring(0,a.length);return!e&&a!=c||0>e?!1:!0},get:function(a){a=b(a);var e=d.cookie,f=e.indexOf(a+"\x3d"),g=f+a.length+1,h=e.substring(0,a.length);if(!f&&a!=h||0>f)return null;a=e.indexOf(";",
g);0>a&&(a=e.length);return c(e.substring(g,a))},remove:function(a){var b=e.get(a);d.cookie=g(a,"",{expires:"Thu, 01-Jan-1970 00:00:01 GMT"});return b},keys:function(){var a=d.cookie.split("; "),b,e,f=[];for(b=0;b<a.length;b++)e=a[b].split("\x3d"),f.push(c(e[0]));return f},all:function(){var a=d.cookie.split("; "),b,e,f=[];for(b=0;b<a.length;b++)e=a[b].split("\x3d"),f.push([c(e[0]),c(e[1])]);return f},version:"0.2.1",enabled:!1};e.enabled=function(){var a=new Date,a=a.toGMTString();this.set("__EC_TEST__",
a);return this.enabled=this.remove("__EC_TEST__")==a}.call(e);return e}();n=function(){};g=function(a){return"PS"+a.replace(/_/g,"__").replace(/ /g,"_s")};C={search_order:"localstorage whatwg_db globalstorage flash ie cookie".split(" "),name_re:/^[a-z][a-z0-9_ -]+$/i,methods:"init get set remove load save".split(" "),sql:{version:"1",create:"CREATE TABLE IF NOT EXISTS persist_data (k TEXT UNIQUE NOT NULL PRIMARY KEY, v TEXT NOT NULL)",get:"SELECT v FROM persist_data WHERE k \x3d ?",set:"INSERT INTO persist_data(k, v) VALUES (?, ?)",
remove:"DELETE FROM persist_data WHERE k \x3d ?"},flash:{div_id:"_persist_flash_wrap",id:"_persist_flash",path:"persist.swf",size:{w:1,h:1},args:{autostart:!0}}};h={gears:{size:-1,test:function(){return window.google&&window.google.gears?!0:!1},methods:{transaction:function(a){var b=this.db;b.execute("BEGIN").close();a.call(this,b);b.execute("COMMIT").close()},init:function(){var a;a=this.db=google.gears.factory.create("beta.database");a.open(g(this.name));a.execute(C.sql.create).close()},get:function(a,
b,c){var d,e=C.sql.get;b&&this.transaction(function(f){d=f.execute(e,[a]);d.isValidRow()?b.call(c||this,!0,d.field(0)):b.call(c||this,!1,null);d.close()})},set:function(a,b,c,d){var e=C.sql.remove,f=C.sql.set;this.transaction(function(g){g.execute(e,[a]).close();g.execute(f,[a,b]).close();c&&c.call(d||this,!0,b)})},remove:function(a,b,c){var d=C.sql.get;sql=C.sql.remove;r;val;this.transaction(function(e){b?(r=e.execute(d,[a]),r.isValidRow()?(val=r.field(0),e.execute(sql,[a]).close(),b.call(c||this,
!0,val)):b.call(c||this,!1,null),r.close()):e.execute(sql,[a]).close()})}}},whatwg_db:{size:204800,test:function(){return!window.openDatabase||!window.openDatabase("PersistJS Test",C.sql.version,"Persistent database test.",h.whatwg_db.size)?!1:!0},methods:{transaction:function(a){if(!this.db_created){var b=C.sql.create;this.db.transaction(function(a){a.executeSql(b,[],function(){this.db_created=!0})},n)}this.db.transaction(a)},init:function(){this.db=openDatabase(this.name,C.sql.version,this.o.about||
"Persistent storage for "+this.name,this.o.size||h.whatwg_db.size)},get:function(a,b,c){var d=C.sql.get;b&&(c=c||this,this.transaction(function(e){e.executeSql(d,[a],function(a,d){0<d.rows.length?b.call(c,!0,d.rows.item(0).v):b.call(c,!1,null)})}))},set:function(a,b,c,d){var e=C.sql.remove,f=C.sql.set;this.transaction(function(g){g.executeSql(e,[a],function(){g.executeSql(f,[a,b],function(a,e){c&&c.call(d||this,!0,b)})})});return b},remove:function(a,b,c){var d=C.sql.get;sql=C.sql.remove;this.transaction(function(e){b?
e.executeSql(d,[a],function(d,e){if(0<e.rows.length){var f=e.rows.item(0).v;d.executeSql(sql,[a],function(a,d){b.call(c||this,!0,f)})}else b.call(c||this,!1,null)}):e.executeSql(sql,[a])})}}},globalstorage:{size:5242880,test:function(){return window.globalStorage?!0:!1},methods:{key:function(a){return g(this.name)+g(a)},init:function(){this.store=globalStorage[this.o.domain]},get:function(a,b,c){a=this.key(a);b&&b.call(c||this,!0,this.store.getItem(a))},set:function(a,b,c,d){a=this.key(a);this.store.setItem(a,
b);c&&c.call(d||this,!0,b)},remove:function(a,b,c){var d;a=this.key(a);d=this.store[a];this.store.removeItem(a);b&&b.call(c||this,null!==d,d)}}},localstorage:{size:-1,test:function(){return window.localStorage?!0:!1},methods:{key:function(a){return g(this.name)+g(a)},init:function(){this.store=localStorage},get:function(a,b,c){a=this.key(a);b&&b.call(c||this,!0,this.store.getItem(a))},set:function(a,b,c,d){a=this.key(a);this.store.setItem(a,b);c&&c.call(d||this,!0,b)},remove:function(a,b,c){var d;
a=this.key(a);d=this.getItem(a);this.store.removeItem(a);b&&b.call(c||this,null!==d,d)}}},ie:{prefix:"_persist_data-",size:65536,test:function(){return window.ActiveXObject?!0:!1},make_userdata:function(a){var b=document.createElement("div");b.id=a;b.style.display="none";b.addBehavior("#default#userData");document.body.appendChild(b);return b},methods:{init:function(){var a=h.ie.prefix+g(this.name);this.el=h.ie.make_userdata(a);this.o.defer&&this.load()},get:function(a,b,c){a=g(a);this.o.defer||this.load();
a=this.el.getAttribute(a);b&&b.call(c||this,a?!0:!1,a)},set:function(a,b,c,d){a=g(a);this.el.setAttribute(a,b);this.o.defer||this.save();c&&c.call(d||this,!0,b)},load:function(){this.el.load(g(this.name))},save:function(){this.el.save(g(this.name))}}},cookie:{delim:":",size:4E3,test:function(){return f.Cookie.enabled?!0:!1},methods:{key:function(a){return this.name+h.cookie.delim+a},get:function(a,b,c,d){a=this.key(a);b=k.get(a);c&&c.call(d||this,null!=b,b)},set:function(a,b,c,d){a=this.key(a);k.set(a,
b,this.o);c&&c.call(d||this,!0,b)},remove:function(a,b,c,d){a=this.key(a);b=k.remove(a);c&&c.call(d||this,null!=b,b)}}},flash:{test:function(){return!window.SWFObject||!deconcept||!deconcept.SWFObjectUtil?!1:8<=deconcept.SWFObjectUtil.getPlayerVersion().major?!0:!1},methods:{init:function(){if(!h.flash.el){var a,b,c,d=C.flash;c=document.createElement("div");c.id=d.div_id;document.body.appendChild(c);a=new SWFObject(this.o.swf_path||d.path,d.id,d.size.w,d.size.h,"8");for(b in d.args)a.addVariable(b,
d.args[b]);a.write(c);h.flash.el=document.getElementById(d.id)}this.el=h.flash.el},get:function(a,b,c){a=g(a);a=this.el.get(this.name,a);b&&b.call(c||this,null!==a,a)},set:function(a,b,c,d){a=g(a);this.el.set(this.name,a,b);c&&c.call(d||this,!0,b)},remove:function(a,b,c){a=g(a);a=this.el.remove(this.name,a);b&&b.call(c||this,!0,a)}}}};l=function(){var a,b,c,d;c=C.methods;var e=C.search_order;a=0;for(b=c.length;a<b;a++)f.Store.prototype[c[a]]=n;f.type=null;f.size=-1;a=0;for(b=e.length;!f.type&&a<b;a++)if(c=
h[e[a]],c.test())for(d in f.type=e[a],f.size=c.size,c.methods)f.Store.prototype[d]=c.methods[d];f._init=!0};f={VERSION:"0.1.0",type:null,size:0,add:function(a){h[a.id]=a;C.search_order=[a.id].concat(C.search_order);l()},remove:function(a){Array.indexOf||(Array.prototype.indexOf=function(a){for(var b=0;b<this.length;b++)if(this[b]==a)return b;return-1});var b=C.search_order.indexOf(a);0>b||(C.search_order.splice(b,1),delete h[a],l())},Cookie:k,Store:function(a,b){if(!C.name_re.exec(a))throw Error("Invalid name");
if(!f.type)throw Error("No suitable storage found");b=b||{};this.name=a;b.domain=b.domain||location.hostname||"localhost.localdomain";this.o=b;b.expires=b.expires||730;b.path=b.path||"/";this.init()}};l();return f}()});