// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("../core/declare dojo/_base/lang dojo/promise/all ../core/Collection ../core/Scheduler ../geometry/Point ../geometry/Extent ../geometry/ScreenPoint ./View ./ViewAnimation ./inputs/GestureManager ./2d/AnimationManager ./2d/PaddedViewState ./2d/viewpointUtils ./2d/MapViewConstraints ./2d/handlers/Navigation ./2d/engine/Stage".split(" "),function(m,g,n,p,k,h,l,q,r,s,t,u,v,f,w,x,y){return m([r],{declaredClass:"esri.views.MapView",classMetadata:{properties:{constraints:{dependsOn:["ready","tileInfo"]},
center:{type:h,copy:function(a,b){a.x=b.x;a.y=b.y;a.spatialReference=b.spatialReference}},extent:{type:l,copy:function(a,b){a.xmin=b.xmin;a.ymin=b.ymin;a.xmax=b.xmax;a.ymax=b.ymax;a.spatialReference=b.spatialReference}},viewpoint:{copy:f.copy}},computed:{center:["content.center"],extent:["content.extent"],rotation:["content.rotation"],scale:["content.scale"],zoom:["content.scale"],viewpoint:["content.viewpoint"]}},constructor:function(){this._proxyProps={};this._pendingUpdates=new p;this._updateTask=
k.addFrameTask({update:function(){this._pendingUpdates.drain(function(a){a._commitUpdate()});this._pendingUpdates.length||this._updateTask.pause()}.bind(this)});this._updateTask.pause();this._handles.add([this.on("resize",this._resizeHandler.bind(this)),this.layerViewsFlat.on("change",this._viewsChangeHander.bind(this)),this.watch("ready",this._readyWatcher.bind(this)),this.watch("constraints",this._constraintsWatcher.bind(this))]);this._viewInitializePromise.resolve()},getDefaults:function(){return g.mixin(this.inherited(arguments),
{constraints:{minScale:0,maxScale:0,minZoom:-1,maxZoom:-1},padding:{top:0,right:0,bottom:0,left:0},ui:{components:["logo","attribution","zoom"]}})},destroy:function(){},_pendingUpdates:null,className:"esriMapView",resizeAlign:"center",animation:null,_animationSetter:function(a,b){b&&b.stop();return a&&!a.isFulfilled()?(a.then(function(){this.animation=null}.bind(this),function(){this.animation=null}.bind(this),function(a){this.state.viewpoint=a}.bind(this)),a):null},center:null,_centerGetter:function(a){if(this._proxyProps)return this._proxyProps.center;
a||(a=new h);var b=this.content.center,c=this.content.spatialReference;a.x=b[0];a.y=b[1];a.spatialReference=c;return a},_centerSetter:function(a){if(null!=a)if(this._proxyProps)this._proxyProps.center=a;else{var b=this.viewpoint;f.centerAt(b,b,a);this.viewpoint=b}},_constraintsSetter:function(a){a=g.mixin({minScale:0,maxScale:0,minZoom:-1,maxZoom:-1,snapToZoom:!0},a);return!this.ready||!this.tileInfo?a:new w(g.mixin(a,{tileInfo:this.tileInfo}))},extent:null,_extentGetter:function(a){if(this._proxyProps)return this._proxyProps.extent;
a||(a=new l);var b=this.content.extent;a.xmin=b.xmin;a.ymin=b.ymin;a.xmax=b.xmax;a.ymax=b.ymax;a.spatialReference=b.spatialReference;return a},_extentSetter:function(a){if(null!=a)if(this._proxyProps)this._proxyProps.extent=a;else{var b=this.viewpoint;f.setExtent(b,b,a,this.size,{tileInfo:this.tileInfo,snapToZoom:this.constraints.snapToZoom});this.viewpoint=b}},_paddingGetter:function(){return this._proxyProps?this._proxyProps.padding:this.state.padding},_paddingSetter:function(a){a=g.mixin({top:0,
right:0,bottom:0,left:0},a);if(this._proxyProps)return this._proxyProps.padding=a;this.state.padding=a;return this.state.padding},rotation:0,_rotationGetter:function(){return this._proxyProps?this._proxyProps.rotation:this.content.rotation},_rotationSetter:function(a){if(null!=a)if(this._proxyProps)this._proxyProps.rotation=a;else{var b=this.viewpoint;f.rotateTo(b,b,a);this.viewpoint=b}},scale:0,_scaleGetter:function(){return this._proxyProps?this._proxyProps.scale:this.content.scale},_scaleSetter:function(a){if(null!=
a)if(this._proxyProps)this._proxyProps.scale=a;else{var b=this.viewpoint;f.scaleTo(b,b,a);this.viewpoint=b}},_surfaceSetter:function(a,b){if(b===a)return b;if(a){this.stage=new y({container:a,scheduler:k.instance});this.gestureManager=new t({view:this,surface:a,inputOptions:{mouseModifiers:!0}});var c=new x({view:this});this.addHandler(c)}else this.stage.destroy(),this.gestureManager.destroy(),this.gestureManager=null;return a},type:"2d",viewpoint:null,_viewpointGetter:function(a){var b=this._proxyProps?
this._proxyProps.viewpoint:this.content.viewpoint;return!b?b:!a?b.clone():f.copy(a,b)},_viewpointSetter:function(a){null!=a&&(this._proxyProps?this._proxyProps.viewpoint=a:(this.constraints.constrain(a,this.content.viewpoint,this),this.state.viewpoint=a))},zoom:-1,_zoomGetter:function(){return this._proxyProps?this._proxyProps.zoom:this.tileInfo?this.tileInfo.scaleToZoom(this.scale):-1},_zoomSetter:function(a){if(null!=a){if(this._proxyProps)return this._proxyProps.zoom=a;var b=this.viewpoint;f.scaleTo(b,
b,this.tileInfo.zoomToScale(a));this.viewpoint=b}},animateTo:function(a,b){var c=this.createViewpoint(a),d=null;if(!this.ready||!this.animationManager)return this.viewpoint=c,d=new s({target:c}),d.finish(),d;this.constraints.constrain(c,this.viewpoint,this);return d=this.animation=this.animationManager.animateTo(c,this.viewpoint,b)},createViewpoint:function(a,b){var c=this.content;return f.create(a,g.mixin({},b,{spatialReference:this.map?this.map.spatialReference:null,size:c?c.size:this.size,currentViewpoint:c?
c.viewpoint:this.viewpoint,tileInfo:this.tileInfo,snapToZoom:this.constraints.snapToZoom}))},hitTest:function(a,b){if(!this.ready)return null;var c=this.toMap(a,b);return n(this.layerViewsFlat.map(function(c){return c.hitTest(a,b)}).getAll()).then(function(a){var b=null;a.some(function(a){a&&(b=a);return b});return{mapPoint:c,graphic:b}})},toMap:function(a,b,c){if(!this.ready)return null;a&&null!=a.x&&(c=b,b=a.y,a=a.x);var d=[0,0];this.state.toMap(d,[a,b]);c=c||new h;c.x=d[0];c.y=d[1];c.spatialReference=
this.map.spatialReference;return c},toScreen:function(a,b,c){if(!this.ready)return null;a&&null!=a.x&&(c=b,b=a.y,a=a.x);c=c||new q;a=[a,b];this.state.toScreen(a,a);c.x=a[0];c.y=a[1];return c},pixelSizeAt:function(a,b){if(!this.ready)return NaN;a&&null!=a.x&&(b=a.y,a=a.x);return this.state.pixelSizeAt([a,b])},scheduleLayerViewUpdate:function(a){this._pendingUpdates.addItem(a);this.ready&&this._updateTask.resume()},_readyWatcher:function(a,b){if(a){var c=this._proxyProps,d=this.map,e=d.basemap?d.basemap.tileInfo:
d.layers.getItemAt(0).tileInfo,d=f.create(c,{spatialReference:d.spatialReference,size:this.size,tileInfo:e,extent:d.extent}),c=new v({padding:c.padding,size:this.size,viewpoint:d});this._proxyProps=null;e&&(this.tileInfo=e);this.constraints=this.constraints;this.animationManager=new u;this.state=c;this.content=c.content;this.stage.state=c;this.stage.run();this._pendingUpdates.length&&this._updateTask.resume()}else this._proxyProps={viewpoint:this.viewpoint,padding:this.padding}},_constraintsWatcher:function(a){this.ready&&
(this.viewpoint=a.constrain(this.viewpoint,null,this))},_viewsChangeHander:function(a){var b=this.layerViewsFlat,c=a.added,d=a.removed;a=a.moved;var e,f;e=0;for(f=d.length;e<f;e++)this.stage.removeChild(d[e].container);e=0;for(f=c.length;e<f;e++)this.stage.addChildAt(c[e].container,b.indexOf(c[e]));e=0;for(f=a.length;e<f;e++)this.stage.setChildIndex(a[e].container,b.indexOf(a[e]))},_resizeHandler:function(a){var b=this.state;if(b){var c=this.content.viewpoint,d=this.content.size.concat();b.size=[a.width,
a.height];f.resize(c,c,d,this.content.size,this.resizeAlign);c=this.constraints.constrain(c,null,this);this.state.viewpoint=c}}})});