// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("require ../core/declare dojo/_base/array dojo/on dojo/Deferred dojo/promise/all ../layers/support/layerUtils ../geometry/Extent ../tasks/support/Query ../layers/GroupLayer ../core/Accessor".split(" "),function(F,x,h,C,t,G,D,y,H,I,J){var q;return x(J,{declaredClass:"esri.views.PopupManager",classMetadata:{properties:{map:{dependsOn:["view.map"],readOnly:!0}}},constructor:function(){this._featureLayersCache={}},destroy:function(){this._featureLayersCache={};this.view=null},_clickHandle:null,
_featureLayersCache:null,enabled:!1,_enabledSetter:function(a){this._clickHandle&&(a?this._clickHandle.resume():this._clickHandle.pause());return a},_mapGetter:function(){return this.get("view.map")||null},view:null,_viewSetter:function(a){this._clickHandle&&(this._clickHandle.remove(),this._clickHandle=null);a&&(this._clickHandle=C.pausable(a,"click",this._clickHandler.bind(this)),this.enabled||this._clickHandle.pause());return a},getMapLayer:function(a){var c;if(a&&(c=a.getLayer()))if(a=c.id,this._featureLayersCache[a]){var f=
a.lastIndexOf("_");-1<f&&(a=a.substring(0,f),c=this.map.getLayer(a))}return c},_showPopup:function(a){function c(a){if(null==a)return!1;var f=e.getLayerView(a);return null==f?!1:a.loaded&&!a.disablePopup&&a.popupTemplate&&!f.suspended}var f=this.map,e=this.view,q=e.popup,v=this,n=[];h.forEach(f.layers.getAll(),function(a){a.isInstanceOf(I)?h.forEach(a.layers.getAll(),function(a){c(a)&&(!a.elevationInfo||"onTheGround"===a.elevationInfo.mode)&&n.push(a)}):c(a)&&(!a.elevationInfo||"onTheGround"===a.elevationInfo.mode)&&
n.push(a)});var p=null;if(a.graphic&&(a.graphic.popupTemplate||c(a.graphic.layer)))p=a.graphic;if(n.length||p){var d=[],l=!!p;if(!p){var b=v._calculateClickTolerance(n),d=a.mapPoint;if(!d)return;var m=b*(e.basemapTerrain&&e.basemapTerrain.overlayManager.overlayPixelSizeInMapUnits(d)),b=d.offset(-m,-m),d=d.offset(m,m);if(null==b||null==d)return;var r=new y(Math.min(b.x,d.x),Math.min(b.y,d.y),Math.max(b.x,d.x),Math.max(b.y,d.y),f.spatialReference),s=new H,d=h.map(n,function(c){var b;s.timeExtent=c.useMapTime?
f.timeExtent:null;if("esri.layers.ArcGISImageLayer"===c.declaredClass){s.geometry=a.mapPoint;var d=e.getLayerView(c);b={rasterAttributeTableFieldPrefix:"Raster.",returnDomainValues:!0};b.layerView=d;b=c.queryVisibleRasters(s,b);b.then(function(a){l=l||0<a.length;return a})}else if("esri.layers.SceneLayer"===c.declaredClass)b=new t,b.resolve();else if(v._featureLayersCache[c.id]||"function"===typeof c.queryFeatures&&(0===c.currentMode||1===c.currentMode))s.geometry=r,b=c.queryFeatures(s),b.then(function(a){a=
a.features;l=l||0<a.length;return a});else{b=new t;var k=[];(d=e.getLayerView(c))&&d._graphicsCollection&&(k=h.filter(d._graphicsCollection.getAll(),function(a){return a&&r.intersects(a.geometry)}));l=l||0<k.length;b.resolve(k)}return b.promise})}p&&(b=new t,d.unshift(b.resolve([p])));!h.some(d,function(a){return!a.isFulfilled()})&&!l?q.set({features:[],visible:!1}):q.set({promises:d,visible:!0,location:a.mapPoint})}},_getSubLayerFeatureLayers:function(a,c){var f=c||new t,e=[],x=a.length,v=Math.floor(this.map.extent.getWidth()/
this.map.width),n=this.map.getScale(),p=!1,d=this,l=0;a:for(;l<x;l++){var b=a[l],m=b.dynamicLayerInfos||b.layerInfos;if(m){var r=null;if(b._params&&(b._params.layers||b._params.dynamicLayers))r=b.visibleLayers;for(var r=D._getVisibleLayers(m,r),s=D._getLayersForScale(n,m),y=m.length,z=0;z<y;z++){var w=m[z],k=w.id,u=b.popupTemplates[k];if(!w.subLayerIds&&u&&u.popupTemplate&&-1<h.indexOf(r,k)&&-1<h.indexOf(s,k)){if(!q){p=!0;break a}var A=b.id+"_"+k,g=this._featureLayersCache[A];if(!g||!g.loadError)g||
((g=u.layerUrl)||(g=w.source?this._getLayerUrl(b.url,"/dynamicLayer"):this._getLayerUrl(b.url,k)),g=new q(g,{id:A,drawMode:!1,mode:q.MODE_SELECTION,outFields:this._getOutFields(u.popupTemplate),resourceInfo:u.resourceInfo,source:w.source}),this._featureLayersCache[A]=g),g.setDefinitionExpression(b.layerDefinitions&&b.layerDefinitions[k]),g.setGDBVersion(b.gdbVersion),g.popupTemplate=u.popupTemplate,g.setMaxAllowableOffset(v),g.setUseMapTime(!!b.useMapTime),b.layerDrawingOptions&&(b.layerDrawingOptions[k]&&
b.layerDrawingOptions[k].renderer)&&g.setRenderer(b.layerDrawingOptions[k].renderer),e.push(g)}}}}if(p){var E=new t;F(["../layers/FeatureLayer"],function(a){q=a;E.resolve()});E.then(function(){d._getSubLayerFeatureLayers(a,f)})}else{var B=[];h.forEach(e,function(a){if(!a.loaded){var b=new t;C.once(a,"load, error",function(){b.resolve()});B.push(b.promise)}});B.length?G(B).then(function(){e=h.filter(e,function(a){return!a.loadError&&a.isVisibleAtScale(n)});f.resolve(e)}):(e=h.filter(e,function(a){return a.isVisibleAtScale(n)}),
f.resolve(e))}return f.promise},_getLayerUrl:function(a,c){var f=a.indexOf("?");return-1===f?a+"/"+c:a.substring(0,f)+"/"+c+a.substring(f)},_getOutFields:function(a){var c;a.info&&"esri.widgets.PopupTemplate"===a.declaredClass?(c=[],h.forEach(a.info.fieldInfos,function(a){var e=a.fieldName&&a.fieldName.toLowerCase();e&&("shape"!==e&&0!==e.indexOf("relationships/"))&&c.push(a.fieldName)})):c=["*"];return c},_calculateClickTolerance:function(a){var c=6;h.forEach(a,function(a){if(a=a.renderer)"esri.renderer.SimpleRenderer"===
a.declaredClass?((a=a.symbol)&&a.xoffset&&(c=Math.max(c,Math.abs(a.xoffset))),a&&a.yoffset&&(c=Math.max(c,Math.abs(a.yoffset)))):("esri.renderer.UniqueValueRenderer"===a.declaredClass||"esri.renderer.ClassBreaksRenderer"===a.declaredClass)&&h.forEach(a.infos,function(a){(a=a.symbol)&&a.xoffset&&(c=Math.max(c,Math.abs(a.xoffset)));a&&a.yoffset&&(c=Math.max(c,Math.abs(a.yoffset)))})});return c},_clickHandler:function(a){this.view.popup&&(this.map.loaded&&this.view.ready)&&this._showPopup(a)}})});