// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("../core/declare dojo/_base/lang dojo/dom dojo/Deferred ./View ./ViewAnimation ../geometry/SpatialReference ../geometry/support/webMercatorUtils ../Camera ../geometry/Point ../geometry/Extent ../geometry/ScreenPoint ../Viewpoint ../core/Scheduler ../core/sniff ../core/watchUtils ./3d/SceneViewEnvironment ./3d/SceneViewEnvironmentManager ./3d/SceneViewConstraints ./3d/lib/glMatrix ./3d/support/cameraUtils ./3d/support/viewpointUtils ./3d/support/eventUtils ./3d/support/projectionUtils ./3d/webgl-engine/Stage ./3d/webgl-engine/lib/Selector ./3d/support/RenderCoordsHelper ./3d/support/MapCoordsHelper ./3d/support/ResourceController ./3d/terrain/TerrainSurface ./3d/layers/graphics/LabelManager ./3d/navigation/spherical/NavigationSpherical ./3d/navigation/planar/NavigationPlanar ./3d/navigation/EventController ./3d/support/Frustum ./3d/webgl-engine/lib/es6-shim".split(" "),
function(G,v,H,p,I,n,l,q,A,r,s,B,J,K,L,M,w,N,C,O,e,m,P,k,Q,D,E,R,S,T,U,V,W,F,X,Y){function g(a,b){return function(){return!this.ready||this._destroying?this._initialProps&&this._initialProps[a]:b.apply(this,arguments)}}function h(a,b){return function(c){if(!this.ready||this._destroying)this._initialProps[a]=c;else return b.apply(this,arguments)}}var x=O.vec3d,f=x.create(),t=new r(0,0,0),y=new A(new r(0,0,0)),u=G(I,{declaredClass:"esri.views.SceneView",classMetadata:{properties:{spatialReference:{readOnly:!0,
dependsOn:["map.spatialReference"],getter:function(){return this.map&&this.map.spatialReference}},camera:{copy:function(a,b){a.position.x=b.position.x;a.position.y=b.position.y;a.position.z=b.position.z;a.position.spatialReference=b.position.spatialReference;a.heading=b.heading;a.tilt=b.tilt},type:A},center:{copy:function(a,b){if(!a)return b.clone();a.x=b.x;a.y=b.y;a.z=b.z;a.spatialReference=b.spatialReference;return a},type:r},extent:{copy:function(a,b){a.xmin=b.xmin;a.ymin=b.ymin;a.zmin=b.zmin;
a.xmax=b.xmax;a.ymax=b.ymax;a.zmax=b.zmax;a.spatialReference=b.spatialReference},type:s},viewpoint:{copy:function(a,b){a.rotation=b.rotation;a.scale=b.scale;a.targetGeometry=b.targetGeometry;a.camera=b.camera}},fullExtent:{readOnly:!0},clippingArea:{type:s},basemapTerrain:{readOnly:!0},canvas:{readOnly:!0},environment:{type:w},constraints:{type:C},animation:{type:n},navigation:{readOnly:!0}},computed:{scale:["camera"],zoom:["camera"],center:["camera"],viewpoint:["camera"],extent:["camera"],rotation:["camera"]}},
getDefaults:function(a){var b=v.mixin(this.inherited(arguments),{padding:{top:0,right:0,bottom:0,left:0}});b.environment||(b.environment=new w);b.constraints||(this._defaultConstraints=new C,b.constraints=this._defaultConstraints);return b},normalizeCtorArgs:function(a){a=v.mixin({},a);a.environment&&"esri.views.3d.SceneViewEnvironment"!==a.environment.declaredClass&&(a.environment=new w(a.environment));"planar"!==a.globeMode&&"spherical"!==a.globeMode&&delete a.globeMode;return a},constructor:function(){this.watch("ready",
this._viewReadyHandler.bind(this));this._initialProps={};this._basemapTerrainExtentHandler=this._basemapTerrain=this._canvas=null;this._globeMode="spherical";this._initCoordinateSystem();this._externalCameraSet=!1;this._frustum=new X;this.navigationController=this._navigation=this._constraints=this._environment=this._animationDelayId=this._animationStateWatcher=this.animation=null;this.navigationControls=F.PAN;this.resourceController=new S(this);this.labelManager=new U(this);this.environmentManager=
new N({view:this});this._updateDrawingOrderHandle=this.layerViewsFlat.on("change",this._updateDrawingOrder.bind(this));this._updateDrawingOrder();this._initialExtent=null;this._initialExtentOrigin=u.ExtentOrigins.VIEWPORT;this._layerViewsUpdatingHandles={};this._evaluateUpdating=this._evaluateUpdating.bind(this);this._updateUpdatingMonitorsHandle=this.layerViewsFlat.on("change",this._updateUpdatingMonitors.bind(this));this._navigationHandles=P.on(this,{navigation:{currentViewChanged:this._navigationCurrentViewChanged,
targetViewChanged:{handler:this._navigationTargetViewChanged,pausable:!0},currentViewReachedTarget:this._navigationCurrentViewReachedTarget,animationStarted:{handler:this._navigationAnimationStarted,pausable:!0}}},this);this._navigationHandles.push(this.watch("navigation.interacting",this._navigationInteractingChanged.bind(this)));this._mapSpatialReferenceHandle=this.watch("map.spatialReference",this._mapSpatialReferenceChanged.bind(this))},initialize:function(){L("esri-webgl")?this._viewInitializePromise.resolve():
this._viewInitializePromise.reject(Error("WebGL is required but not supported"))},type:"3d",globeMode:"spherical",updatingPercentage:0,environment:null,constraints:null,animation:null,camera:null,viewpoint:null,extent:null,clippingArea:null,scale:0,zoom:0,center:null,toMap:function(a,b,c){if(!this.ready)return null;a=this._normalizePoint(a,b,void 0,t);a=this._stage._pick([a.x,this.height-a.y]).getMinResult();return this._computeMapPointFromIntersectionResult(a,c)},toScreen:function(a,b,c,d){if(!this.ready)return null;
a=this._normalizePoint(a,b,c,t);k.pointToVector(a,f,this.renderSpatialReference);return this.engineToScreen(f,d)},pixelSizeAt:function(a,b,c){if(!this.ready)return null;if("esri.geometry.ScreenPoint"===a.declaredClass){if(!this._stage._pick([a.x,this.height-a.y]).getMinResult().getIntersectionPoint(f))return 0}else a=this._normalizePoint(a,b,c,t),k.pointToVector(a,f,this.renderSpatialReference);return this.navigation.currentCamera.computePixelSizeAt(f)},hitTest:function(a,b){if(!this.ready)return null;
var c=this._normalizePoint(a,b,void 0,t),d=new p,c=[c.x,this.height-c.y],c=this._stage._pick(c,null,null,!0).getMinResult(),z=this._computeMapPointFromIntersectionResult(c),e;null!=c.object&&(e=this._getGraphicFromStageObject(c.object,c.triangleNr));e?e.then(function(a){d.resolve({mapPoint:z,graphic:a})},function(){d.resolve({mapPoint:z,graphic:null})}):d.resolve({mapPoint:z,graphic:null});return d.promise},animateTo:function(a,b){if(this.ready){b=b||{};var c=this.createViewpoint(a,b);if(!c)return(new p).reject(Error("Failed to convert target to viewpoint")).promise;
var d=m.toCamera(this,c);if(!d)return(new p).reject(Error("Failed to convert viewpoint to camera")).promise;this._animationDelayId&&(clearTimeout(this._animationDelayId),this._animationDelayId=0);!this.animation||"running"!==this.animation.state?this.animation=new n({target:c}):this.animation.target=c;var e=this.animation,f=function(){this._navigationHandles.byId("navigation.targetViewChanged").pause();this._navigationHandles.byId("navigation.animationStarted").pause();this._setCamera(d,{animate:!0});
e.state===n.State.STOPPED&&(e.state=n.State.FINISHED);this._navigationHandles.byId("navigation.targetViewChanged").resume();this._navigationHandles.byId("navigation.animationStarted").resume();this.animation&&this._hidePopupWindow()}.bind(this);b.delay?this._animationDelayId=setTimeout(function(){this._animationDelayId=0;f()}.bind(this),b.delay):f();return e}},createViewpoint:function(a,b){return m.create(this,a,b)},takeScreenshot:function(a){a=v.mixin({format:"png",quality:100},a||{});var b=new p,
c,d;a.includePadding||(c=this.width-this.padding.left-this.padding.right,d=this.height-this.padding.top-this.padding.bottom);var e=c/d;void 0!==a.width&&void 0===a.height?a.height=Math.floor(a.width/e):void 0!==a.height&&void 0===a.width&&(a.width=Math.floor(e*a.height));!a.area&&!a.includePadding&&(a.area={x:this.padding.left,y:this.padding.top,width:c,height:d});this._stage.requestScreenCapture(a,function(a){b.resolve(a)});return b.promise},setInitialExtent:function(a,b){var c=this.get("map.spatialReference");
return c&&a&&!q.canProject(a.spatialReference,c)?!this._externalCameraSet:b>=this._initialExtentOrigin?(this._initialExtentOrigin=b,a&&!this._externalCameraSet?(this.ready?(this._setInitialViewpointFromExtent(a),this._initialExtent=null):this._initialExtent=a,!0):!this._externalCameraSet):!1},engineToScreen:function(a,b){var c=x.create();this._stage.getCamera().projectPoint(a,c);var d=c[0],e=this.height-c[1],c=c[2];return b?(b.x=d,b.y=e,b.z=c,b):new B({x:d,y:e,z:c})},destroy:function(){this._destroying=
!0;this._animationDelayId&&clearTimeout(this._animationDelayId);this.environmentManager.view=null;this.destroyLayerViews();this.factory.destroy();this._disposeSurface();this.labelManager.destroy();this.labelManager=null;this.resourceController.destroy();this.resourceController=null;this._updateUpdatingMonitorsHandle.remove();this._updateUpdatingMonitorsHandle=null;this._navigationHandles.remove();this._navigationHandles=null;this._mapSpatialReferenceHandle.remove();this._mapSpatialReferenceHandle=
null},setLightingParameters:function(a){this._stage&&(this._stage.setDirectionalLight(a.diffuse),this._stage.setAmbientLight(a.ambient))},getRenderingParameters:function(a){return this._stage?this._stage.getRenderParams(a):null},setRenderingParameters:function(a){this._stage&&this._stage.setRenderParams(a)},has:function(a){return this._stage.has(a)},flushDisplayModifications:function(){this._stage.processDirty()},getFrustum:function(){this._frustum.dirty&&this._frustum.update(this.navigation.currentCamera);
return this._frustum},getDrawingOrder:function(a){return this.layerViewsFlat.findIndex(function(b){return b.layer&&b.layer.id===a})},renderSpatialReference:null,_trackCanvasSize:function(){this.on("resize",function(a){if(this.canvas){this.canvas.width=a.width;this.canvas.height=a.height;var b=this._stage.getCamera();b.width=a.width;b.height=a.height;this._stage.setCamera(b);this.navigation&&(this.navigation.windowSize=[a.width,a.height])}}.bind(this));this.canvas.width=this.width;this.canvas.height=
this.height},_computeMapPointFromIntersectionResult:function(a,b){if(a.getIntersectionPoint(f)){var c=this.map.spatialReference||l.WGS84;k.vectorToVector(f,this.renderSpatialReference,f,c)||(c=l.WGS84,k.vectorToVector(f,this.renderSpatialReference,f,c));b?(b.x=f[0],b.y=f[1],b.z=f[2],b.spatialReference=c):b=new r(f,c);"terrain"===a.intersector&&this.basemapTerrain&&(c=this.basemapTerrain.getElevation(b),null!==c&&(b.z=c));return b}return null},_onGeometryPicked:function(a,b,c){var d={};d.screenPoint=
{x:b[0],y:b[1]};if(b=this._computeMapPointFromIntersectionResult(c))d.mapPoint=b;null!=a?(a=this._getGraphicFromStageObject(a,c.triangleNr))&&a.then(function(a){d.graphic=a;this.emit("tap",d);this.emit("click",d)}.bind(this),function(a){this.emit("tap",d);this.emit("click",d)}.bind(this)):(this.emit("tap",d),this.emit("click",d))},_getGraphicFromStageObject:function(a,b){var c=a.getMetadata();if(null!=c&&null!=c.layerId&&(c=this.map.getLayer(c.layerId)))if((c=this.getLayerView(c))&&null!=c.getGraphicsFromStageObject&&
!c.suspended)return c.getGraphicsFromStageObject(a,b);return null},_initBasemapTerrain:function(a){this._disposeBasemapTerrain();this._basemapTerrain=new T(this,a);this.notifyChange("basemapTerrain");this.notifyChange("fullExtent");this._basemapTerrainExtentHandler=this._basemapTerrain.watch("extent",function(){this.notifyChange("fullExtent")}.bind(this));this.navigation.elevationProvider=this._basemapTerrain},_initGlobe:function(a){this._initCoordinateSystem();this._initNavigation(a);this.onViewExtentUpdatedHandle&&
(this.onViewExtentUpdatedHandle.remove(),this.onViewExtentUpdatedHandle=null);this._stage.setViewParams({backgroundColor:[0,0,0,0],maxFarNearRatio:0,frustumCullingEnabled:!1});this._initBasemapTerrain(a);this._navigationCurrentViewChanged({camera:this.navigation.currentCamera})},_initCoordinateSystem:function(){if(this.map&&this.map.spatialReference){var a=this.map.spatialReference,b=this.mapCoordsHelper?this.mapCoordsHelper.mapUnitInMeters:1;if(!this.mapCoordsHelper||!this.mapCoordsHelper.spatialReference.equals(a))this.mapCoordsHelper=
new R(a),this._stage&&this._stage.setIntersectTolerance(D.DEFAULT_TOLERANCE/this.mapCoordsHelper.mapUnitInMeters),this._constraints&&this._constraints.scale(b/this.mapCoordsHelper.mapUnitInMeters);a=(b="spherical"===this._globeMode)?k.SphericalRenderSpatialReference:a;a!==this.renderSpatialReference&&(this.renderSpatialReference=a,this.renderCoordsHelper=new (b?E.Spherical:E.Planar)(a))}else this.renderSpatialReference=this.renderCoordsHelper=this.mapCoordsHelper=null},_hidePopupWindow:function(){this.popup&&
this.popup.isShowing&&this.popup.hide()},_navigationInteractingChanged:function(a){a=!!a;a!==this.interacting&&(a&&this._hidePopupWindow(),this.interacting=a)},_paddingEqualsArray:function(a){var b=this.padding;return!b?!0:b.top===a[0]&&b.right===a[1]&&b.bottom===a[2]&&b.left===a[3]},_navigationCurrentViewChanged:function(a){this._frustum.dirty=!0;a=a.camera;var b=a.padding;if(!this._paddingEqualsArray(b)){var c=this._padding,b={top:b[0],right:b[1],bottom:b[2],left:b[3]};this.ready?(this._padding=
b,this.notifyChange("padding",c,b)):this.padding=b}this._stage.setCamera(a);this.notifyChange("camera")},_navigationAnimationStarted:function(a){a=m.create(this,this.navigation.targetCamera);this.animation?this.animation.target=a:this.animation=new n({target:a})},_navigationTargetViewChanged:function(a){if(this.animation){a=a.camera;var b=this.map.spatialReference||l.WGS84,c=e.internalToExternal(this,a);a=new J({camera:c,targetGeometry:k.vectorToPoint(a.center,b,this.renderSpatialReference),scale:e.computeScale(this,
a),rotation:m.headingToRotation(c.heading)});this.animation.target=a}},_navigationCurrentViewReachedTarget:function(a){if(this.animation&&(!a.finishedAnimation||!this._animationDelayId)){this._animationDelayId&&(clearTimeout(this._animationDelayId),this._animationDelayId=0);this._animationStateWatcher&&(this._animationStateWatcher.remove(),this._animationStateWatcher=null);var b=this.animation;this.animation=null;a.finishedAnimation?b.finish():b.stop();this.notifyChange("animation")}},_setCamera:function(a,
b){var c=e.externalToInternal(this,a);c&&(this.navigation.setCamera(c,b),this._externalCameraSet=!0);this._hidePopupWindow()},_evaluateUpdating:function(){var a=0,b=0,c=!1;this.layerViewsFlat.forEach(function(d){d.updating&&(c=!0,d=d.updatingPercentage,null!=d&&(++b,a+=d))});c!==this.updating&&(this.updating=c);a=0!==b?a/b:c?100:0;this.updatingPercentage!==a&&(this.updatingPercentage=a)},_updateUpdatingMonitors:function(a){for(var b=0;b<a.removed.length;b++){var c=a.removed[b],d=this._layerViewsUpdatingHandles[c.id];
d&&(delete this._layerViewsUpdatingHandles[c.id],d.remove())}for(b=0;b<a.added.length;b++)c=a.added[b],c.layer&&(d=c.watch(["updating","updatingPercentage"],this._evaluateUpdating),this._layerViewsUpdatingHandles[c.id]=d);this._evaluateUpdating()},_mapSpatialReferenceChanged:function(a){this.basemapTerrain&&(this.basemapTerrain.spatialReference&&a&&!this.basemapTerrain.spatialReference.equals(a))&&(this.basemapTerrain.tilingScheme=null,this._externalCameraSet=!1,M.once(this,"fullExtent",function(){this._externalCameraSet||
this._setInitialViewpointFromExtent(this.fullExtent)}.bind(this)));this._initCoordinateSystem()},_pickRay:function(){return this._stage?this._stage.pickRay.apply(this._stage,arguments):null},_pickRayWithBeginPoint:function(){return this._stage?this._stage.pickRayWithBeginPoint.apply(this._stage,arguments):null},_removeHandles:function(a){for(var b=0;b<a.length;b++){var c=a[b];this[c]&&(this[c].remove(),this[c]=null)}},_setCanvas:function(a){if(a!==this._canvas){var b=this._canvas;this._canvas=a;this.notifyChange("canvas",
b,a)}},_disposeSurface:function(){this._removeHandles(["_stageFrameTask","_updateDrawingOrderHandle","onViewExtentUpdateHandle"]);this._disposeBasemapTerrain();this._setNavigation(null);this.environmentManager.dispose();this._stage&&(this._stage.dispose(),this._stage=null);this._setCanvas(null)},_disposeBasemapTerrain:function(){this._basemapTerrain&&(this._basemapTerrain.destroy(),this._basemapTerrain=null,this._basemapTerrainExtentHandler.remove(),this._basemapTerrainExtentHandler=null)},_disposeNavigation:function(){this._navigation&&
(this._navigation.destroy(),this._navigation=this._navigation.elevationProvider=null);this.navigationController&&(this.navigationControls=this.navigationController.getControls(),this.navigationController.destroy(),this.navigationController=null)},_setNavigation:function(a){if(this._navigation!==a){this._disposeNavigation();if(this._navigation=a)a.windowSize=[this.width,this.height],a.userConstraints=this.constraints;this.notifyChange("navigation");this._accessorProps.dispatch()}},_initNavigation:function(a){a=
a||this.globeMode;var b={view:this};"spherical"===a?this._setNavigation(new V(b)):this._setNavigation(new W(b));this.navigationController=new F(this,this.navigationControls)},_initSurface:function(){var a={};null!=this.antialias&&(a.antialias=this.antialias);this._stage=new Q(H.byId(this.surface),a);this._stage.selectionState=!1;this._stage.onGeometryPicked=this._onGeometryPicked.bind(this);this.mapCoordsHelper&&this._stage.setIntersectTolerance(D.DEFAULT_TOLERANCE/this.mapCoordsHelper.mapUnitInMeters);
this._setCanvas(this._stage.getCanvas());this._stageFrameTask=K.addFrameTask(this._stage.getFrameTask());this._trackCanvasSize();this._initGlobe(this.globeMode)},_normalizePoint:function(a,b,c,d){d.spatialReference=void 0;"object"===typeof a?Array.isArray(a)?(d.x=a[0],d.y=a[1],d.z=a[2]):(d.x=a.x,d.y=a.y,d.z=a.z,a.spatialReference&&(d.spatialReference=a.spatialReference)):(d.x=a,d.y=b,d.z=c);d.spatialReference||(d.spatialReference=this.map.spatialReference||l.WGS84);return d},_viewReadyHandler:function(a){if(a){this._initSurface();
for(var b in this._initialProps)this._initialProps.hasOwnProperty(b)&&this.set(b,this._initialProps[b]);this._initialProps={};!this.setInitialExtent(this.map.extent,u.ExtentOrigins.MAP)&&(this._initialExtent&&!this._externalCameraSet)&&(this._setInitialViewpointFromExtent(this._initialExtent),this._initialExtent=null);this._externalCameraSet||(a=this.camera.clone(),a.heading=0,a.tilt=0,this.camera=a)}else this._disposeSurface()},_cameraSetter:h("camera",function(a){this._setCamera(a,{animate:!1})}),
_cameraGetter:g("camera",function(a){return e.internalToExternal(this,this.navigation.currentCamera,a)}),_externalExtent:function(){this._cachedExtentDirty&&(e.toExtent(this,null,null,this._cachedExtent,y),this._cachedExtentDirty=!1);return this._cachedExtent},_extentGetter:g("extent",function(a){return e.toExtent(this,null,null,a,y)}),_extentSetter:h("extent",function(a){if(a=e.fromExtent(this,a,this.camera,y))this.camera=a}),_scaleGetter:g("scale",function(){return e.computeScale(this)}),_scaleSetter:h("scale",
function(a){var b=this.camera,c=this.navigation.currentCamera.center,d=x.create();k.vectorToVector(c,this.renderSpatialReference,d,l.WGS84);a=e.scaleToDistance(this,a,d[1]);b=e.eyeHeadingTiltForCenterPointAtDistance(this,b.heading,b.tilt,c,a);this.navigation.setCameraFromEyeCenterAndUp(b.eye,b.center,b.up,{animate:!1});this._hidePopupWindow();this._externalCameraSet=!0}),_zoomGetter:g("zoom",function(){return e.scaleToZoom(this,this.scale)}),_zoomSetter:h("zoom",function(a){this.scale=e.zoomToScale(this,
a)}),_centerGetter:g("center",function(a){var b=this.map.spatialReference||l.WGS84;return k.vectorToPoint(this.navigation.currentCamera.center,this.renderSpatialReference,a||b,b)}),_centerSetter:h("center",function(a){var b=this.camera;a=e.eyeHeadingTiltForCenterPointAtDistance(this,b.heading,b.tilt,a,this.navigation.currentCamera.distance);this.navigation.setCameraFromEyeCenterAndUp(a.eye,a.center,a.up,{animate:!1});this._hidePopupWindow();this._externalCameraSet=!0}),_viewpointGetter:g("viewpoint",
function(){return this.createViewpoint(this.camera)}),_viewpointSetter:h("viewpoint",function(a){a=this.createViewpoint(a);(a=m.toCamera(this,a))&&this._setCamera(a,{animate:!1})}),_rotationGetter:g("rotation",function(){return m.headingToRotation(this.camera.heading)}),_rotationSetter:h("rotation",function(a){var b=this.navigation.currentCamera,c=b.distance,d=this.camera;a=m.rotationToHeading(a);b=e.eyeHeadingTiltForCenterPointAtDistance(this,a,d.tilt,b.center,c,{noReset:!0});this.navigation.setCameraFromEyeCenterAndUp(b.eye,
b.center,b.up,{animate:!1});this._hidePopupWindow();this._externalCameraSet=!0}),_fullExtentGetter:function(){if(this._basemapTerrain&&this._basemapTerrain.spatialReference){var a=this._basemapTerrain.extent,b=Math.max(a[2]-a[0],a[3]-a[1]);return new s({xmin:a[0],ymin:a[1],zmin:4*-b,xmax:a[2],ymax:a[3],zmax:4*b,spatialReference:this._basemapTerrain.spatialReference})}return new s({spatialReference:this.map&&this.map.spatialReference?this.map.spatialReference:l.WebMercator})},_globeModeSetter:function(a){a!==
this._globeMode&&(this._globeMode=a,this.ready&&this._initGlobe(a));return a},_globeModeGetter:function(){return this._globeMode},_screenCenterGetter:function(){var a=this.padding;return new B((this.size[0]-(a.left+a.right))/2+a.left,(this.size[1]-(a.top+a.bottom))/2+a.top)},_updateDrawingOrder:function(){var a=this.layerViewsFlat.length-1;this.layerViewsFlat.forEach(function(b,c){b.drawingOrder=a-c},this)},_paddingGetter:g("padding",function(){return this._padding}),_paddingSetter:h("padding",function(a){this._padding=
{top:a&&a.top||0,right:a&&a.right||0,bottom:a&&a.bottom||0,left:a&&a.left||0};this.navigation&&(this.navigation.padding=this._padding)}),_constraintsGetter:g("constraints",function(){return this._constraints}),_constraintsSetter:h("constraints",function(a){this._constraints=a;this._constraints===this._defaultConstraints&&(this._defaultConstraints=null,this._constraints.scale(1/this.mapCoordsHelper.mapUnitInMeters));this.navigation.userConstraints=a}),_animationSetter:function(a){this.ready&&(this._animationStateWatcher&&
(this._animationStateWatcher.remove(),this._animationStateWatcher=null),(this._animation=a)&&a.then(function(){if(this._animation===a){var b=!!this._animationDelayId;b&&(clearTimeout(this._animationDelayId),this._animationDelayId=0);var c=a.target;this.animation=null;a.state===n.State.FINISHED?b?this.viewpoint=c:this.navigation.setCurrentToTarget():this.navigation.setCamera(this.navigation.currentCamera,{animate:!1})}}.bind(this)))},_animationGetter:function(){return this._animation},_canvasGetter:function(){return this._canvas},
_basemapTerrainGetter:function(){return this._basemapTerrain},_navigationGetter:function(){return this._navigation},_clippingAreaSetter:function(a){if(null!=a&&!a.spatialReference.equals(this.map.spatialReference))if(q.canProject(a.spatialReference,this.map.spatialReference))a=q.project(a,this.map.spatialReference);else{console.error("Setting clippingArea with incompatible SpatialReference.");return}if(null!=a){if(!a.equals(this._clippingArea))return this._clippingArea=a}else if(null!=this._clippingArea)return this._clippingArea=
null},_clippingAreaGetter:function(){return this._clippingArea},_setInitialViewpointFromExtent:function(a){q.canProject(a.spatialReference,this.map.spatialReference)&&(this.viewpoint=this.createViewpoint({target:a,heading:0,tilt:0.5}))}});u.ExtentOrigins={VIEWPORT:0,MAP:1,PORTAL:2,WEBSCENE:3};return u});