// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define({moveUp:"Flytt opp",moveDown:"Flytt ned",rename:"Gi nytt navn",hideInMapLayers:"Skjul i lag",showInMapLayers:"Vis i lag",invalidTitle:"Tittelen kan ikke inneholde f\u00f8lgende tegn: \x3c or \x3e.",header:{home_link:"Hjem",simpleHome:"Hjem",support:"Hjelp",features:"Funksjoner",myAccount:"Min organisasjon",myProfile:"Min profil",help:"Hjelp",plans:"Planer",adminGuide:"Administratorveiledning",signOut:"Logg ut",signIn:"Logg p\u00e5",newScene:"Ny scene",gallery:"Galleri",groups:"Grupper",myContent:"Mitt innhold",
esriCommunity:"Fellesskap og fora",myEsri:"Mitt Esri",map:"Kart",training:"Oppl\u00e6ring",trialDownloads:"Nedlastinger av pr\u00f8veversjon",fullScreen:"Utforsk i fullvisning",newGlobal:"Ny global scene",newLocal:"Ny lokal scene",globalScene:"Global scene",localScene:"Lokal scene",spatialRef:"Romlig referanse"},environmentSettings:{dragSunSliderText:"Dra glidebryteren for \u00e5 endre tid p\u00e5 dagen.",dragSunSliderHint:"Dra glidebryteren",sunLight:"Solskinn",sunrise:"soloppgang",sunset:"solnedgang",
shadowing:"Skyggelegging",directShadow:"Direkte skygge (fra solskinn)",diffuseShadow:"Diffuse skygger (okklusjon i luften)"},layerItemEditable:{groupTypeCheckbox:"Avmerkingsboks",groupTypeRadio:"Radio",groupTypeCompact:"Sl\u00e5 sammen",groupTypeHide:"Skjul",configureLayer:"Konfigurer lag",zoomToLayer:"Zoom til",deleteLayer:"Fjern",dragHere:"Dra laget hit",changeGroupType:"Endre gruppetype"},slideDeckEditable:{addSlide:"Lag lysbilde",slide:"Lysbilde",updateSlide:"Oppdater slide",deleteSlide:"Fjern slide"},
symbologyEditor:{symbologyShieldWarning:"Kan ikke endre symbolene i dette laget. Klikk p\u00e5 OK for \u00e5 fjerne eksisterende symboler og definere nye.",colorOverride:"Fargeoverstyring",fill:"Fyll",outline:"Omriss",shape:"Form",color:"Farge",size:"St\u00f8rrelse",symbols:"Symboler",transparency:"Gjennomsiktighet (%)",ok:"OK",px:"px",points:"punkter",meters:"meter",feet:"fot",reset:"Tilbakestill",originalSymbology:"Opprinnelige symboler",modifySymbology:"Endre symboler",customize:"Tilpass",type:"Type",
icon2d:"2D-ikon",object3D:"3D-objekt",line2d:"2D-linje",line3d:"3D-linje",path3d:"3D-bane",polygon2d:"2D-polygon",polygon3d:"3D-dybde",fillColor:"Fyllfarge",outlineColor:"Omrissfarge",outlineSize:"Omrisst\u00f8rrelse",shapes:{circle:"Sirkel",cone:"Kjegle",cross:"Kryss",cube:"Kube",cylinder:"Sylinder",diamond:"Rombe",kite:"Drage",sphere:"Kule",square:"Kvadrat",tetrahedron:"Tetraeder",x:"X"},extrusion:"Dybde (meter)",rangeMsg:"Verdien er utenfor omr\u00e5det. Angi en verdi mellom ${minSize} og ${maxSize}"},
mapControls:{zoomIn:"Zoom inn",zoomOut:"Zoom ut",rotate:"Roter",home:"F\u00f8rste visning",pan:"Panorer",panRotateToggle:"Veksle for \u00e5 panorere eller rotere i 3D"},switchControl:{on:"p\u00e5",off:"av"},settings:{navigation:"3D-navigasjon",proNav:"ArcGIS Pro",sceneNav:"Standard",mouseImage:"Tilordning av museknapper for 3D-navigasjon"},share:{text:"Velg ett av alternativene nedenfor for \u00e5 dele denne scenen.",link:"Del en kobling til denne scenen",embed:"Bygg inn denne scenen p\u00e5 et webomr\u00e5de",
more:"Alternativer for innbygging",smallSize:"Liten",mediumSize:"Middels",largeSize:"Stor",customSize:"Tilpasset",shareTwitterTxt:"Utforsk ${sceneName} i 3D med nettleseren:",shareEmailSubject:"${sceneName} i 3D (sceneviseren)",shareEmailTxt1:"Ta en titt p\u00e5 denne webscenen:",shareEmailTxt2:"Du kan opprette og dele dine egne webscener i 3D med Esris sceneviser. G\u00e5 til http://www.arcgis.com, og klikk p\u00e5 Scene for \u00e5 pr\u00f8ve den gratis.",shortenLink:"Kort kobling",shareUnsaved:"Denne scenen inneholder endringer som ikke er lagret. Hvis du skal dele den, m\u00e5 du lagre disse endringene.",
shareNotPublic:"Denne scenen er ikke delt offentlig. Det kan hende at andre ikke kan vise den.",shareNotPublicLayer:"Minst ett lag i denne scenen er ikke offentlig. Det kan hende at andre ikke kan vise alle lagene.",changeShareSettings:"Endre delingsinnstillinger"},underground:{seeThroughGround:"Se gjennom bakken"},basemapGallery:{SRMismatch:"Romlig referanse er ikke kompatibel med scenen",SRMismatchGlobal:"Romlig referanse st\u00f8ttes ikke i globale scener",TSMismatch:"Fliseoppsettet er ikke kompatibelt med scenen",
TilingScheme:"Fliseoppsettet samsvarer ikke med fliseoppsettet for ArcGIS Online.",tilingSchemePowerOfTwo:"Ukompatibelt fliseoppsett: hver m\u00e5lestokk m\u00e5 v\u00e6re n\u00f8yaktig halvparten av m\u00e5lestokken for foreg\u00e5ende niv\u00e5.",tilingSchemeTileSize:"Ukompatibelt fliseoppsett: kun fliser med bredde og h\u00f8yde p\u00e5 256 st\u00f8ttes.",tiledMapServiceSRGCS:"Fliseinndelte kartlag i geografiske koordinatsystemer st\u00f8ttes ikke.",tiledMapServicesMinVersion:"Fliseinndelte kartlag p\u00e5 servere eldre enn 10.2.2 st\u00f8ttes ikke.",
basemapLayerTypeWMS:"OGC Web Map Service (WMS) st\u00f8ttes ikke som bakgrunnskart.",basemapLayerTypeWMTS:"OGC Web Tile Map Service (WMTS) st\u00f8ttes ikke som bakgrunnskart.",basemapLayerTypeWTL:"Webfliselag st\u00f8ttes ikke som bakgrunnskart.",basemapLayerTypeDMS:"Dynamisk karttjenestelag st\u00f8ttes ikke som bakgrunnskart.",basemapLayerTypeIS:"Bildetjenestelag st\u00f8ttes ikke som bakgrunnskart.",noBasemap:"Ingen bakgrunnskart"},compass:{compass:"Kompass"}});