// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define({panes:{slides:"Slaidid",properties:"Omadused",advancedSettings:"T\u00e4iustatud seaded",modifyScene:"Muuda",contents:"Sisu",addLayers:"Lisa kihid",enterLayerUrl:"Sisesta kihi URL",configureLayer:"Seadista kiht"},buttons:{saveScene:"Salvesta vaade",addGroup:"Loo kihtide grupp...",save:"Salvesta",cancel:"T\u00fchista",add:"Lisa",remove:"Eemalda",done:"Valmis",importLayer:"Impordi",saveTooltip:"Salvesta vaade (Ctrl+S)"},dialogs:{webSceneSaveOk:"Veebivaade on salvestatud.",webSceneSaveFailed:"Veebivaate salvestamine nurjus.",
addLayer:"Lisa kiht"},messages:{webSceneSaved:"Veebivaade salvestati edukalt 'Minu sisu' alla.",webSceneSavedShared:"Veebivaade salvestati edukalt omaniku ${sceneowner} sisu alla.",viewItemDetails:"Kuva objekti \u00fcksikasjad",addLayerFailed:"Kihti ei saa lisada",pendingChangesConfirm:"Teie salvestamata vaate muudatused l\u00e4hevad kaotsi."},contentsPane:{newGroup:"Uus grupp"},addLayerPane:{by:"autor:",searchForLayer:"Otsi kihti...",search:"Otsi",myContent:"Minu sisu",content:"Sisu",noResult:"Otsingule vastavaid tulemusi ei leitud.",
featuredContent:"Esri esiletoodud sisu",more:"Rohkem..."},addLayerByUrlPane:{addingLayer:"Kihi lisamine kaardile...",layerUrl:"Kihi URL",layerName:"Kihi nimi",placeholderLayerUrl:"nt http://server.esri.com/water/MapServer",placeholderLayerName:"nt veeteed"},editBasemapPane:{basemap:"Aluskaart",elevation:"K\u00f5rgus",elevationInBasemap:"K\u00f5rgus aluskaardil",elevationOn:"K\u00f5rgus sees",elevationOff:"K\u00f5rgus v\u00e4ljas"},editLayerPane:{elevation:"K\u00f5rgus",elevationMode:"K\u00f5rgusre\u017eiim",
mode:"Re\u017eiim",advancedSymbology:"T\u00e4iustatud s\u00fcmboloogia",popups:"H\u00fcpikaknad",onTheGround:"Maapinnal",relativeToGround:"Maapinna suhtes",absoluteHeight:"Absoluutk\u00f5rgus",elevationOffsetMeters:"K\u00f5rguse nihe (meetrid)",offsetMeters:"Nihe (meetrites)",popupsOn:"H\u00fcpikaknad sees",popupsOff:"H\u00fcpikaknad v\u00e4ljas",labels:"M\u00e4rgised",labelsOn:"M\u00e4rgised sisse",labelsOff:"M\u00e4rgised v\u00e4lja",layerType:"Kihi t\u00fc\u00fcp:",geometryType:"Geomeetria t\u00fc\u00fcp:",
point:"Punkt",lines:"Joon",polygon:"Pind",mesh:"V\u00f5rgustik",enabled:"Lubatud",disabled:"Keelatud",zoomTo:"Suumi",legend:"Legend",transparency:"L\u00e4bipaistvus"},sceneProperties:{title:"Pealkiri",summary:"Kokkuv\u00f5te",tags:"M\u00e4rks\u00f5nad",thumbnail:"Pisipilt",placeholderEnterTitle:"Sisesta pealkiri...",placeholderEnterSummary:"Vaate kokkuv\u00f5te (valikuline)",placeholderEnterTags:"Lisa m\u00e4rks\u00f5na(d)",copyTitle:"Vaate ${scenetitle} (autor: ${sceneauthor}) koopia",elevation:"K\u00f5rgus",
updateThumbnail:"Uuenda pisipilti",clipping:"L\u00f5ika ulatuseni",currentView:"Uuenda praeguse vaateulatuseni",elevationUnsupported:"K\u00f5rguste vaikekiht ei \u00fchildu aluskaardi koordinaats\u00fcsteemiga ja pildi\u00fcksuse skeemiga."},saveDialog:{saveInitialViewpoint:"Salvesta praegune algse vaatepunktina",saveInitialState:"Salvesta praegune algse vaate olekuna",saveAs:"Salvesta uue vaatena",websceneTitleExists:"Selle pealkirjaga vaade on juba olemas.",saveAsNewScene:"Vaade tuleb salvestada uue sisu\u00fcksusena.",
invalidTitle:"Pealkiri ei tohi sisaldada j\u00e4rgmisi t\u00e4hem\u00e4rke: \x3c or \x3e.",invalidSummary:"Kokkuv\u00f5te ei tohi sisaldada j\u00e4rgmisi t\u00e4hem\u00e4rke: \x3c or \x3e.",owner:"kuulub omanikule ${ownerName}",ownerMe:"minu omanduses",myContent:"Minu sisu",otherContent:"${sceneowner}",location:"Salvesta kohta",choseLocation:"Valige asukoht",overwriteScene:"Sellega kirjutatakse olemasolev sisu \u00fcle",copyScene:"Sellega luuakse uus \u00fcksus",confirmOverwrite:"Sama nimega vaade on juba olemas.",
confirmOverwrite2:"Sama nimega vaade on juba olemas ning kirjutatakse \u00fcle.",confirmOverwriteQuestion:"Kas soovite selle \u00fcle kirjutada?",confirmOverwriteYes:"Jah, kirjuta \u00fcle",confirmOverwriteCancel:"T\u00fchista",confirmOverwriteNo:"Ei"},confirmDialog:{confirm:"Kinnita",cancelButton:"T\u00fchista"},navigationContainer:{closeOpen:"Sulge redaktor",open:"Ava",back:"Tagasi"}});