// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define(["./GLSLShader","./gl-matrix"],function(m,h){function n(f,d){var h=z++,e,l,k,g=function(){if(void 0===e){e=d.createProgram();for(var b=0;b<f.length;++b)d.attachShader(e,f[b].getGLName());m()}},m=function(){void 0!==e&&(d.linkProgram(e),d.getProgramParameter(e,d.LINK_STATUS)||console.error("Could not initialize shader\nVALIDATE_STATUS: "+d.getProgramParameter(e,d.VALIDATE_STATUS)+", gl error ["+d.getError()+"]infoLog: "+d.getProgramInfoLog(e)),l={},k={})};this.clearLookupTables=function(){l=
{};k={};p={};q={};r={};s={};x={}};this.dispose=function(){for(var b=0;b<f.length;++b){var a=f[b].getGLName();d.isShader(a)&&d.deleteShader(a)}d.isProgram(e)&&d.deleteProgram(e);t===this&&n.unuse(d)};this.getId=function(){return h};this.getShader=function(b){return f["vertex"===b?0:1]};this.changeShaderDefines=function(b,a){f[b].changeDefines(a)&&m()};this.use=function(){t!==this&&(g(),d.useProgram(e),t=this)};this.getLocation=function(b){g();void 0===l[b]&&(l[b]=d.getUniformLocation(e,b));return l[b]};
this.hasUniform=function(b){return null!==this.getLocation(b)};this.getAttribLocation=function(b){g();void 0===k[b]&&(k[b]=d.getAttribLocation(e,b));return k[b]};var p={};this.uniform1i=function(b,a){var c=p[b];if(void 0===c||a!==c)this.use(),d.uniform1i(this.getLocation(b,d),a),p[b]=a};this.uniform1f=function(b,a){var c=p[b];if(void 0===c||a!==c)this.use(),d.uniform1f(this.getLocation(b,d),a),p[b]=a};var q={};this.uniform2f=function(b,a,c){var e=q[b];if(void 0===e||a!==e[0]||c!==e[1])this.use(),
d.uniform2f(this.getLocation(b,d),a,c),void 0===e?q[b]=u.createFrom(a,c):u.set2(a,c,e)};this.uniform2fv=function(b,a){var c=q[b];if(2<a.length||void 0===c||a[0]!==c[0]||a[1]!==c[1])this.use(),d.uniform2fv(this.getLocation(b,d),a),void 0===c?q[b]=u.create(a):u.set(a,c)};var r={};this.uniform3f=function(b,a,c,e){var f=r[b];if(void 0===f||a!==f[0]||c!==f[1]||e!==f[2])this.use(),d.uniform3f(this.getLocation(b,d),a,c,e),void 0===f?r[b]=v.createFrom(a,c,e):v.set3(a,c,e,f)};this.uniform3fv=function(b,a){var c=
r[b];if(3<a.length||void 0===c||a[0]!==c[0]||a[1]!==c[1]||a[2]!==c[2])this.use(),d.uniform3fv(this.getLocation(b,d),a),void 0===c?r[b]=v.create(a):v.set(a,c)};var s={};this.uniform4f=function(b,a,c,e,f){var g=s[b];if(void 0===g||a!==g[0]||c!==g[1]||e!==g[2]||f!==g[3])this.use(),d.uniform4f(this.getLocation(b,d),a,c,e,f),void 0===g?s[b]=w.createFrom(a,c,e,f):w.set4(a,c,e,f,g)};this.uniform4fv=function(b,a){var c=s[b];if(4<a.length||void 0===c||a[0]!==c[0]||a[1]!==c[1]||a[2]!==c[2]||a[3]!==c[3])this.use(),
d.uniform4fv(this.getLocation(b,d),a),void 0===c?s[b]=w.create(a):w.set(a,c)};var x={};this.uniformMatrix4fv=function(b,a){var c=x[b];if(16<a.length||void 0===c||!(c[0]===a[0]&&c[1]===a[1]&&c[2]===a[2]&&c[3]===a[3]&&c[4]===a[4]&&c[5]===a[5]&&c[6]===a[6]&&c[7]===a[7]&&c[8]===a[8]&&c[9]===a[9]&&c[10]===a[10]&&c[11]===a[11]&&c[12]===a[12]&&c[13]===a[13]&&c[14]===a[14]&&c[15]===a[15]))this.use(),d.uniformMatrix4fv(this.getLocation(b,d),!1,a),void 0===c?x[b]=y.create(a):y.set(a,c)};this.dispose=function(){if(void 0!==
e){for(var b=0;b<f.length;++b){var a=f[b].getGLName();d.detachShader(e,a);d.deleteShader(a)}d.deleteProgram(e)}}}var u=h.vec2d,v=h.vec3d,w=h.vec4d,y=h.mat4d,z=0,t;n.fromSnippets=function(f,d,h,e,l){var k=[];f=Array.isArray(f)?f:[f];d=Array.isArray(d)?d:[d];var g;for(g=0;g<f.length;g++)k.push(new m(e.VERTEX_SHADER,h[f[g]],e,l));for(g=0;g<d.length;g++)k.push(new m(e.FRAGMENT_SHADER,h[d[g]],e,l));return new n(k,e)};n.unuse=function(f){t=null;f.useProgram(null)};return n});