// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define(["./ModelContentType","./ModelDirtyTypes","./Util"],function(C,d,w){return function(A){function e(a,b,c,d,f,p,m,k,e){c=c||a.getParentLayer().getId();var l=a.getId();a=b.getId();c=y(h,c,l);(l=c[a])?(b=l[1],b&f?delete c[a]:b&p?(l[1]=d,l[2]=e):b&m?l[2]|=e:b&k||z("ModelDirtySet.objGeometryAdded: inconsistent state")):c[a]=[b,d,e]}function y(a,b,c){a[b]||(a[b]={});a[b][c]||(a[b][c]={});return a[b][c]}var D=w.objectEmpty,z=w.assert,s={},h={},q={};this._getResidentGeometryRecords=function(){return s};
this._getDirtyGeometryRecords=function(){return h};this.getDirtyMaterials=function(){return D(q)?null:q};this.clearDirtyMaterials=function(){q={}};this.hasDirtyGeometryRecords=function(){for(var a in h)for(var b in h[a]){var c=h[a][b];if(c&&!D(c))return!0}return!1};this.handleUpdate=function(a,b,c){z(this[b],"ModelDirtySet doesn't know how to process "+b);return this[b](a,c)};this.getAddRemoveUpdateList=function(a){return this.getAddRemoveUpdateListFilteredByLayers(Object.keys(h),a)};this.getAddRemoveUpdateListFilteredByLayers=
function(a,b){for(var c=[],B=[],f=[],p=0;p<a.length;p++){var m=a[p];if(m in h)for(var k in h[m]){var e=h[m][k];if(e){var l=y(s,m,k),v;for(v in e){var t=e[v],q=t[0],n=t[1],t=t[2],u=n&d.GeomDirtyType.UPDATE&&t&d.UpdateTypes.REINSERT,g,x;if(n&d.GeomDirtyType.REMOVE||u)(g=l[v])?B.push.apply(B,g[1]):n===d.GeomDirtyType.REMOVE&&z(!1,"ModelDirtySet.getAddRemoveListFilteredByLayers: invalid remove"),b&&g&&delete l[v];if(n&d.GeomDirtyType.ADD||u)g=[q,[]],x=A.get(C.OBJECT,k),A.getGeometryRenderGeometries(x,
q,g[1]),c.push.apply(c,g[1]),b&&(l[v]=g);if(n&d.GeomDirtyType.UPDATE&&!u)if(g=l[v],x=A.get(C.OBJECT,k),g){var n=g[1],u=n.length,r;if(t&d.UpdateTypes.FACERANGE){var w=x.getVisibleIndexRanges(q);for(g=0;g<u;g++)r=n[g],r.displayedIndexRange=w?w[r.componentIdx]:void 0}if(t&d.UpdateTypes.TRANSFORMATION)for(g=0;g<u;g++)r=n[g],x.getCombinedTransformation(q,r.transformation),r.updateTransformation(r.transformation);for(g=0;g<u;g++)r=n[g],f.push({renderGeometry:r,updateType:t})}else z(!1,"ModelDirtySet.getAddRemoveListFilteredByLayers: invalid update")}}}b&&
delete h[m]}return[c,B,f]};this.getResidentRenderGeometries=function(){return this.getResidentRenderGeometriesFilteredByLayers(Object.keys(s))};this.getResidentRenderGeometriesFilteredByLayers=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c];if(d in s)for(var f in s[d]){var p=s[d][f];if(p)for(var e in p)b.push.apply(b,p[e][1])}}return b};this.hideFaceRange=function(a,b,c){c=c||a.getParentLayer().getId();e(a,b,c,d.GeomDirtyType.UPDATE,0,0,d.GeomDirtyType.UPDATE,d.GeomDirtyType.ADD|d.GeomDirtyType.REMOVE,
d.UpdateTypes.FACERANGE)};this.unhideAllFaceRange=function(a,b){for(var c=0;c<a.getGeometryRecords().length;c++)e(a,a.getGeometryRecords()[c],b,d.GeomDirtyType.UPDATE,0,0,d.GeomDirtyType.UPDATE,d.GeomDirtyType.ADD|d.GeomDirtyType.REMOVE,d.UpdateTypes.FACERANGE)};this.vertexAttrsUpdated=function(a,b,c){e(a,b,c,d.GeomDirtyType.UPDATE,0,0,d.GeomDirtyType.UPDATE,d.GeomDirtyType.ADD|d.GeomDirtyType.REMOVE,d.UpdateTypes.VERTEXATTRS)};this.colorAttrsUpdated=function(a,b,c){e(a,b,c,d.GeomDirtyType.UPDATE,
0,0,d.GeomDirtyType.UPDATE,d.GeomDirtyType.ADD|d.GeomDirtyType.REMOVE,d.UpdateTypes.COLORATTRS)};this.matChanged=function(a){q[a.getId()]=!0};this.layerAdded=function(a){for(var b=a.getObjects(),c=0;c<b.length;c++)this.layObjectAdded(a,b[c])};this.layerRemoved=function(a){for(var b=a.getObjects(),c=0;c<b.length;c++)this.layObjectRemoved(a,b[c])};this.layObjectAdded=function(a,b){for(var c=a.getId(),d=b.getGeometryRecords(),f=0;f<d.length;f++)this.objGeometryAdded(b,d[f],c)};this.layObjectRemoved=
function(a,b){for(var c=a.getId(),d=b.getGeometryRecords(),f=0;f<d.length;f++)this.objGeometryRemoved(b,d[f],c)};this.layObjectReplaced=function(a,b){this.layObjectRemoved(a,b[0]);this.layObjectAdded(a,b[1])};this.objDirty=function(a,b){b=b||a.getParentLayer().getId();var c=a.getId(),c=y(s,b,c),h;for(h in c)e(a,c[h][0],b,d.GeomDirtyType.UPDATE,0,d.GeomDirtyType.UPDATE,0,d.GeomDirtyType.ADD|d.GeomDirtyType.REMOVE,d.UpdateTypes.REINSERT)};this.objTransformation=function(a,b){b=b||a.getParentLayer().getId();
var c=a.getId(),c=y(s,b,c),h;for(h in c)e(a,c[h][0],b,d.GeomDirtyType.UPDATE,0,0,d.GeomDirtyType.UPDATE,d.GeomDirtyType.ADD|d.GeomDirtyType.REMOVE,d.UpdateTypes.TRANSFORMATION)};this.objGeometryAdded=function(a,b,c){e(a,b,c,d.GeomDirtyType.ADD,d.GeomDirtyType.REMOVE,0,0,0)};this.objGeometryRemoved=function(a,b,c){e(a,b,c,d.GeomDirtyType.REMOVE,d.GeomDirtyType.ADD,d.GeomDirtyType.UPDATE,0,0)};this.objGeometryReplaced=function(a,b){this.objGeometryRemoved(a,b[0]);this.objGeometryAdded(a,b[1])};this.objGeometryTransformation=
function(a,b){this.objGeometryReplaced(a,b)};this.formatDebugInfo=function(a){var b=["ADD","UPD",void 0,"REM"];if(a)return"";a="";for(var c in h)for(var d in h[c]){var f=h[c][d];if(f){0<a.length&&(a+="\n");a+=c+"."+d;var e=[],m;for(m in f){var k=f[m][1];e[k]||(e[k]=[]);e[k].push(f[m][0].geometry.getId())}for(f=0;f<e.length;f++)if(e[f]){a+=" "+b[f-1]+": ";for(k=0;k<e[f].length;k++)a+=e[f][k]+", "}}}return a}}});