// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("../../core/declare ./viewpointUtils ./math/vec2 ./math/mat2d ../../geometry/Extent ../../core/Accessor".split(" "),function(g,d,c,e,h,k){var f=g(k,{declaredClass:"esri.views.2d.ViewState",classMetadata:{properties:{center:{copy:c.copy},extent:{copy:function(a,b){a.xmin=b.xmin;a.ymin=b.ymin;a.xmax=b.xmax;a.ymax=b.ymax;a.spatialReference=b.spatialReference}},inverseTransform:{readOnly:!0,copy:e.copy},screenCenter:{readOnly:!0,copy:c.copy},transform:{readOnly:!0,copy:e.copy},transformNoRotation:{readOnly:!0,
copy:e.copy},version:{readOnly:!0},viewpoint:{copy:d.copy},worldScreenWidth:{readOnly:!0},worldWidth:{readOnly:!0},wrappable:{readOnly:!0}},computed:{center:["viewpoint"],spatialReference:["viewpoint"],rotation:["viewpoint"],scale:["viewpoint"],resolution:["viewpoint"],x:["center"],y:["center"],inverseTransform:["transform"],latitude:["viewpoint"],longitude:["viewpoint"],screenCenter:["size"],width:["size"],height:["size"],extent:["viewpoint","size"],transform:["viewpoint","size"],transformNoRotation:["viewpoint",
"size"],version:["transform"],worldScreenWidth:["worldWidth","resolution"],worldWidth:["spatialReference"],wrappable:["spatialReference"]}},_centerGetter:function(a){var b=this.viewpoint.targetGeometry;return!a?c.fromValues(b.x,b.y):c.set(a,b.x,b.y)},_extentGetter:function(a){a||(a=new h);return d.getExtent(a,this.viewpoint,this.size)},_heightGetter:function(){return this.size?this.size[1]:0},_inverseTransformGetter:function(a){a||(a=e.create());return e.invert(a,this.transform)},_latitudeGetter:function(){return this.viewpoint.targetGeometry.latitude},
_longitudeGetter:function(){return this.viewpoint.targetGeometry.longitude},_resolutionGetter:function(){return d.getResolution(this.viewpoint)},_rotationGetter:function(){return this.viewpoint.rotation},_scaleGetter:function(){return this.viewpoint.scale},_screenCenterGetter:function(a){var b=this.size;a||(a=c.create());return c.scale(a,b,0.5)},_spatialReferenceGetter:function(){return this.viewpoint.targetGeometry.spatialReference},_transformGetter:function(a){a||(a=e.create());return d.getTransform(a,
this.viewpoint,this.size)},_transformNoRotationGetter:function(a){a||(a=e.create());return d.getTransformNoRotation(a,this.viewpoint,this.size)},size:null,version:0,_versionGetter:function(a){return a+1},viewpoint:null,_viewpointSetter:function(a,b){return!b?a.clone():d.copy(b,a)},_widthGetter:function(){return this.size?this.size[0]:0},_worldScreenWidthGetter:function(){return this.worldWidth/this.resolution},_worldWidthGetter:function(){if(this.wrappable){var a=this.spatialReference._getInfo();
return a.valid[1]-a.valid[0]}return 0},_wrappableGetter:function(){return!!this.spatialReference&&this.spatialReference.isWrappable()},_xGetter:function(){return this.center[0]},_yGetter:function(){return this.center[1]},copy:function(a){return this.set({viewpoint:a.viewpoint,size:a.size})},clone:function(){return new f({viewpoint:this.viewpoint.clone(),size:c.clone(this.size)})},toMap:function(a,b){return c.transformMat2d(a,b,this.inverseTransform)},toScreen:function(a,b){return c.transformMat2d(a,
b,this.transform)},pixelSizeAt:function(a){return d.pixelSizeAt(a,this.viewpoint,this.size)}});return f});