// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("./math/common ./math/mat2d ./math/vec2 ../../Viewpoint ../../geometry/SpatialReference ../../geometry/Geometry ../../geometry/Point ../../geometry/Extent ../../geometry/support/webMercatorUtils ../../geometry/support/scaleUtils".split(" "),function(l,k,e,y,O,z,t,P,A,B){var C=6370997*Math.PI/180,Q=180/Math.PI,D=function(a,b,c,d){return d&&(c&&!d.equals(c)&&d._canProject(c))&&d.isWebMercator()?(d.isWebMercator()?(c=b[1],89.99999<c?c=89.99999:-89.99999>c&&(c=-89.99999),c=Math.sin(l.toRadian(c)),
a=e.set(a,6378137*l.toRadian(b[0]),3189068.5*Math.log((1+c)/(1-c)))):(c=l.toDegree(b[0]/6378137),a=e.set(a,c-360*Math.floor((c+180)/360),l.toDegree(0.5*PI-2*Math.atan(Math.exp(-1*b[1]/6378137))))),a):e.copy(a,b)},r=function(a){return a.wkid?a:a.spatialReference||O.WGS84},p=function(a,b){return b.type?e.set(a,b.x,b.y):e.copy(a,b)},u=function(a,b){return Math.max(a.width/b[0],a.height/b[1])*E(a.spatialReference)},q=function(a,b,c){var d;if(!a)return null;if(Array.isArray(a)&&2===a.length&&"number"===
typeof a[0]&&"number"===typeof a[1])return new t(a);if(a.forEach)return a.reduce(function(a,c){return q(c,b,a)}),c;if(Array.isArray(a)){for(d=0;d<a.length;d++)if(c=q(a[d],b,c),!c)return null;return c}a instanceof z?d=a:a.geometry&&(d=a.geometry);if(!d)return null;a="point"===d.type?new P({xmin:d.x,ymin:d.y,xmax:d.x,ymax:d.y,spatialReference:d.spatialReference}):d.extent;if(!a||!A.canProject(a.spatialReference,b))return null;a=A.project(a,b);return c=c?c.union(a):a.clone()},h=function(a,b){var c=a.targetGeometry,
d=b.targetGeometry;c.x=d.x;c.y=d.y;c.spatialReference=d.spatialReference;a.scale=b.scale;a.rotation=b.rotation;return a},F=function(){var a=e.create();return function(b,c,d){if(!d)return e.scale(b,c,0.5);e.set(a,d.left+d.right,d.top+d.bottom);e.sub(b,c,a);e.set(a,d.left,d.top);return e.scaleAndAdd(b,a,b,0.5)}}(),R=function(){var a=e.create();return function(b,c,d){var e=c.targetGeometry;p(a,e);c=0.5*m(c);b.xmin=a[0]-c*d[0];b.ymin=a[1]-c*d[1];b.xmax=a[0]+c*d[0];b.ymax=a[1]+c*d[1];b.spatialReference=
e.spatialReference;return b}}(),G=function(a,b,c){a=v(a,b,c);return k.invert(a,a)},H=function(a,b,c){var d=l.toRadian(b.rotation)||0;b=Math.abs(Math.cos(d));d=Math.abs(Math.sin(d));a=e.copy(a,c.size);return e.set(a,Math.round(a[1]*d+a[0]*b),Math.round(a[1]*b+a[0]*d))},J=function(){var a=e.create();return function(b,c,d){return e.sub(b,I(b,c),F(a,c,d))}}(),K=function(){var a=k.create(),b=e.create();return function(c,d,g,f){var n=m(d);d=l.toRadian(d.rotation)||0;e.set(b,n,n);k.fromScaling(a,b);k.rotate(a,
a,d);k.translate(a,a,J(b,g,f));e.set(c,a[4],a[5]);return c}}(),m=function(a){return a.scale*L(a.targetGeometry.spatialReference)},L=function(a){return 1/(96*39.37*(B.getUnitValueForSR(a)||C))},E=function(a){return 96*39.37*(B.getUnitValueForSR(a)||C)},I=function(a,b){return e.scale(a,b,0.5)},M=function(){var a=e.create(),b=e.create(),c=e.create();return function(d,g,f,n,h){e.negate(a,g);e.scale(b,f,0.5);e.set(c,1/n,-1/n);k.identity(d);k.translate(d,d,b);h&&k.rotate(d,d,h);k.scale(d,d,c);k.translate(d,
d,a);return d}}(),v=function(){var a=e.create();return function(b,c,d){var e=m(c),f=l.toRadian(c.rotation)||0;p(a,c.targetGeometry);return M(b,a,d,e,f)}}(),S=function(){var a=e.create();return function(b,c,d){var e=m(c);p(a,c.targetGeometry);return M(b,a,d,e,0)}}(),T=function(){var a=e.create(),b=e.create(),c=e.create();return function(d,g,f){e.subtract(a,d,g);e.normalize(a,a);e.subtract(b,d,f);e.normalize(b,b);e.cross(c,a,b);d=Math.acos(e.dot(a,b)/(e.length(a)*e.length(b)))*Q;0>c[2]&&(d=-d);isNaN(d)&&
(d=0);return d}}(),U=function(){var a=e.create();return function(b,c,d,e,f){f=b.targetGeometry;h(b,c);K(a,c,d,e);f.x+=a[0];f.y+=a[1];return b}}(),N=function(){var a=e.create();return function(b,c,d){h(b,c);c=b.targetGeometry;var e=r(d),f=r(c);p(a,d);D(a,a,e,f);c.x=a[0];c.y=a[1];return b}}(),V=function(){var a=e.create();return function(b,c,d,g,f){f||(f="center");e.sub(a,d,g);e.scale(a,a,0.5);d=a[0];g=a[1];switch(f){case "center":e.set(a,0,0);break;case "left":e.set(a,-d,0);break;case "top":e.set(a,
0,g);break;case "right":e.set(a,d,0);break;case "bottom":e.set(a,0,-g);break;case "top-left":e.set(a,-d,g);break;case "bottom-left":e.set(a,-d,-g);break;case "top-right":e.set(a,d,g);break;case "bottom-right":e.set(a,d,-g)}s(b,c,a);return b}}(),W=function(){var a=e.create();return function(b,c,d,g,f){h(b,c);0!==d&&(w(a,g,c,f),b.scale=c.scale/d,x(a,a,b,f),s(b,b,e.set(a,a[0]-g[0],g[1]-a[1])));return b}}(),X=function(){var a=e.create();return function(b,c,d,g,f,k){h(b,c);0!==d&&(w(a,f,c,k),b.scale=c.scale/
d,b.rotation+=g,x(a,a,b,k),s(b,b,e.set(a,a[0]-f[0],f[1]-a[1])));return b}}(),w=function(){var a=k.create();return function(b,c,d,g){return e.transformMat2d(b,c,G(a,d,g))}}(),x=function(){var a=k.create();return function(b,c,d,g){return e.transformMat2d(b,c,v(a,d,g))}}(),s=function(){var a=e.create(),b=k.create();return function(c,d,g){h(c,d);var f=m(d),n=c.targetGeometry;k.fromRotation(b,l.toRadian(d.rotation)||0);k.scale(b,b,e.fromValues(f,f));e.transformMat2d(a,g,b);n.x+=a[0];n.y+=a[1];return c}}();
return{create:function(a,b){if(!a)return new y({targetGeometry:new t,scale:0,rotation:0});var c=b.spatialReference,d=b.size,g=b.currentViewpoint,f=b.tileInfo,k=null!=b.snapToZoom?b.snapToZoom:!0;if("esri.Viewpoint"===a.declaredClass)return a;var h=null,f=a.viewpoint&&a.viewpoint.targetGeometry&&"point"===a.viewpoint.targetGeometry.type?a.viewpoint.scale:null!=a.scale?a.scale:f&&null!=a.zoom?f.zoomToScale(a.zoom):null,l=a.viewpoint?a.viewpoint.rotation:null!=a.rotation?a.rotation:g?g.rotation:0;a=
a.viewpoint&&a.viewpoint.targetGeometry||a instanceof z&&a||q(a.center,c)||q(a.extent,c)||q(a.target,c)||q(a,c)||g&&g.targetGeometry||b.extent;var m=r(a);c||(c=r(b.spatialReference||b.extent||a));h=a.center?a.center:a;h=p(e.create(),h);h=new t(D(h,h,m,c),c);null===f&&(f=Array.isArray(a)||"point"===a.type?b.extent?u(b.extent,d):g.scale:u(a.extent,d));b.extent&&(b.tileInfo&&k)&&(f=b.tileInfo.snapScale(f));return new y({targetGeometry:h,scale:f,rotation:l})},copy:h,getAnchor:F,getExtent:R,setExtent:function(a,
b,c,d,e){N(a,b,c.center);a.scale=u(c,d);e&&e.tileInfo&&(b=e.tileInfo,e=null==e.snapToZoom?!0:e.snapToZoom,b&&e&&(a.scale=b.snapScale(a.scale)));return a},getPaddingMapTranslation:K,getPaddingScreenTranslation:J,getResolution:m,getScreenCenter:I,getTransform:v,getTransformNoRotation:S,getInverseTransform:G,getOuterExtent:function(a,b,c){var d=p(e.create(),b.targetGeometry),g=0.5*m(b);c=H(e.create(),b,c);a.set({xmin:d[0]-g*c[0],ymin:d[1]-g*c[1],xmax:d[0]+g*c[0],ymax:d[1]+g*c[1],spatialReference:b.targetGeometry.spatialReference});
return a},getOuterSize:H,getResolutionToScaleFactor:E,getScaleToResolutionFactor:L,angleBetween:T,addPadding:U,centerAt:N,pixelSizeAt:function(a,b,c){return m(b)},removePadding:function(a,b,c,d){h(a,b);return a},resize:V,rotateBy:function(a,b,c){h(a,b);a.rotation+=c;return a},rotateTo:function(a,b,c){h(a,b);a.rotation=c;return a},scaleBy:W,scaleTo:function(a,b,c){h(a,b);a.scale=c;return a},scaleAndRotateBy:X,toMap:w,toScreen:x,translateBy:s}});