// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define({defaultWebSceneName:"Eigene Szene",menu:{titleLayers:"Layer",titleEnvironmentSettings:"Umgebung",titleSearch:"Suchen",titleBasemap:"Grundkarte",errorSceneServiceLoad:"Fehler beim Laden des Szenen-Service",errorLayerName:"Layer-Name:",titleLegend:"Legende",titleSettings:"Einstellungen",titleShare:"Freigeben",moreTools:"Weitere Werkzeuge"},dialogs:{webscene:"Webszene",addLayer:"Layer hinzuf\u00fcgen",layerDidNotDrawCompletely:"Der Layer wurde nicht vollst\u00e4ndig gezeichnet",webglCheck:"WebGL-\u00dcberpr\u00fcfung",
browserCheck:"\u00dcberpr\u00fcfung des Browsers",browserFail:"Scene Viewer kann in Ihrem Browser nicht ge\u00f6ffnet werden.",unsupportedBasemap:"Grundkarte wird nicht unterst\u00fctzt"},messages:{addLayerFailed:"Layer kann nicht hinzugef\u00fcgt werden",layerAddedSuccess:"Layer erfolgreich hinzugef\u00fcgt.",layerDidNotDrawCompletely:"wurde nicht vollst\u00e4ndige gezeichnet, da das Transferlimit des Servers von ${limit} Features \u00fcberschritten wurde.",layerTypeNotSupported:"Layer-Typ wird nicht unterst\u00fctzt:",
onlyTiledLayerSupported:"Nur gekachelte Karten-Layer werden unterst\u00fctzt.",layerItemTypeNotSupported:"Layer-Elementtyp nicht unterst\u00fctzt:",layerItemPropertiesFromMapServer:"Die in Map Layer-Elementen gespeicherten Anzeigeeigenschaften werden nicht unterst\u00fctzt.",layerItemPropertiesNotApplied:"Die im Layer-Element gespeicherten Anzeigeeigenschaften wurden nicht angewendet.",itemId:"Element-ID:",itemType:"Elementtyp:",websceneLoadFail:"Webszene kann nicht geladen werden.",websceneLoadFailNoVersion:"Keine Version in Webszene gefunden.",
websceneLoadFailBadVersion:"Ung\u00fcltige Version ${websceneVersion} in Webszene.",websceneLoadFailIncompatVersion:"Webszene-Version ${websceneVersion} ist mit diesem Viewer nicht kompatibel",websceneVersionRequires:"(erfordert ${websceneRequiredVersion})",websceneVersionMoreRecent:"Die Webszene (version ${websceneVersion}) ist neuer als die Viewer-Version {$viewerVersion}.",webscenePotentiallyUnsupported:"Teile des Webszeneninhalts werden m\u00f6glicherweise nicht unterst\u00fctzt und k\u00f6nnten nicht wie erwartet angezeigt werden.",
websceneGlobalSR:"Globale Webszene muss in Web Mercator vorliegen.",websceneGlobalEmbeddedSR:"Raumbez\u00fcge in globalen Webszenen m\u00fcssen in Web Mercator oder WGS84 GCS vorliegen.",websceneLocalSRGCS:"Lokale Webszenen in geographischen Koordinaten werden nicht unterst\u00fctzt.",tiledMapServicesMinVersion:"Gekachelte Karten-Layer auf Servern vor 10.2.2 werden nicht unterst\u00fctzt.",tiledMapServicesMinVersionPatch:"Gekachelte Karten-Layer von Servern der Version 10.2.2 werden nur unterst\u00fctzt, wenn alle Serveraktualisierungen angewendet wurden.",
sceneLayerVersion:"Die Version des Szenen-Layers wird nicht unterst\u00fctzt.",sceneLayerSRWM:"Szenen-Layer m\u00fcssen in Web Mercator vorliegen.",sceneLayerSR:"Szenen-Layer m\u00fcssen dem Raumbezug der Szene entsprechen.",sceneLayerSRGCS:"Szenen-Layer in geographischen Koordinatensystemen werden in lokalen Szenen nicht unterst\u00fctzt.",tiledMapServicesSR:"Gekachelte Karten-Layer m\u00fcssen in Web Mercator vorliegen.",tiledMapServicesSRGeneric:"Gekachelte Kachel-Layer m\u00fcssen dem Raumbezug und dem Kachelschema der Szene entsprechen.",
tiledMapServiceSRGCS:"Gekachelte Karten-Layer in geographischen Koordinatensystemen werden nicht unterst\u00fctzt.",tiledImageServicesSRGeneric:"Gekachelte Bild-Layer m\u00fcssen dem Raumbezug und dem Kachelschema der Szene entsprechen.",tiledImageServiceSRGCS:"Gekachelte Bild-Layer in geographischen Koordinatensystemen werden nicht unterst\u00fctzt.",tiledElevationServicesSRGeneric:"H\u00f6hen-Layer m\u00fcssen dem Raumbezug und dem Kachelschema der Szene entsprechen.",tilingSchemePowerOfTwo:"Inkompatibles Kachelschema: jeder Ma\u00dfstab muss genau halb so gro\u00df sein wie der Ma\u00dfstab der vorherigen Ebene.",
tilingSchemeTileSize:"Inkompatibles Kachelschema: nur Kacheln mit einer Breite und H\u00f6he von 256 werden unterst\u00fctzt.",tilingSchemeGaps:"Inkompatibles Kachelschema: L\u00fccken zwischen Ebenen werden nicht unterst\u00fctzt.",tilingSchemeGeneric:"Inkompatibles Kachelschema.",patchRequired:"Patch(es) erforderlich:",elevationImageServicesSR:"H\u00f6hen-Layer m\u00fcssen in Web Mercator vorliegen.",imageServicesSR:"Gekachelte Bild-Layer m\u00fcssen in Web Mercator vorliegen.",tiledMapServicesTilingScheme:"Gekachelte Karten-Layer m\u00fcssen dem Kachel-Schema von ArcGIS Online entsprechen.",
tiledImageServicesTilingScheme:"Gekachelte Bild-Layer m\u00fcssen dem Kachel-Schema von ArcGIS Online entsprechen.",elevationImageServicesTilingScheme:"H\u00f6hen-Layer m\u00fcssen dem Kachel-Schema von ArcGIS Online entsprechen.",imageServicesCached:"Es werden nur gecachte Image Server unterst\u00fctzt.",elevationImageServicesCached:"Es werden nur Image Server mit LERC-Codierung unterst\u00fctzt.",elevationBasemapTitle:"Standard-H\u00f6hen-Layer k\u00f6nnen nicht hinzugef\u00fcgt werden",elevationBasemapSR:"Der Raumbezug des H\u00f6hen-Layers stimmt nicht mit dem Raumbezug der Grundkarte \u00fcberein.",
elevationBasemapTS:"Das Kachelschema des H\u00f6hen-Layers ist nicht mit dem Kachelschema der Grundkarte kompatibel.",featureServiceNotSupportedTable:"Typ Tabelle wird nicht unterst\u00fctzt.",featureServiceNotSupportedMultipatch:"Multipatch-Feature-Services werden nicht unterst\u00fctzt.",featureServiceNotSupportedNoRenderer:"Services ohne Renderer werden nicht unterst\u00fctzt.",featureServiceNotSupportedRendererType:"Renderer-Typ wird nicht unterst\u00fctzt:",featureServiceNotSupportedMaxFeatures:"Feature-Service \u00fcberschreitet die maximal zul\u00e4ssige Anzahl von Features:",
featureServiceNotSupportedMaxVertices:"Feature-Service \u00fcberschreitet die maximal zul\u00e4ssige Anzahl von St\u00fctzpunkten:",splashSignInToEdit:"Melden Sie sich an, um die Welt in 3D zu erkunden, und f\u00fcgen Sie Layer von Esri und Tausenden von Organisationen hinzu, um neue Szenen zu erstellen.",splashShowThisOnStart:"dies beim Start anzeigen",splashNewToArcGIS:"Sie sind neu bei ArcGIS? Registrieren Sie sich noch heute f\u00fcr eine Testsubskription.",splashLookAtOtherScenes:"Nachfolgend finden Sie einige der Szenen, die Sie erkunden k\u00f6nnen.",
selectedBasemapMismatchTitle:"Ausgew\u00e4hlte Grundkarte kann nicht verwendet werden",selectedBasemapMismatch:"Der Raumbezug und das Kachelschema der Grundkarte sind nicht kompatibel mit der Szene.\nErstellen Sie eine neue Szene, um diese Grundkarte zu verwenden.",serviceName:"Service-Name",basemapDrop:"Der Layer hat einen anderen Raumbezug und ein anderes Kachelschema als die Grundkarte.\x3cBR\x3eM\u00f6chten Sie die Grundkarte l\u00f6schen, um den Layer hinzuzuf\u00fcgen?",basemapDropConfirm:"Grundkarte l\u00f6schen",
basemapDropTitle:"Datenkonflikt",BasemapDropWarningTitle:"Grundkarte wurde gel\u00f6scht",BasemapDropWarning:"Der Raumbezug und das Kachelschema der Grundkarte sind nicht mit dem Layer kompatibel und wurden daher gel\u00f6scht.",sceneRejectTitle:"Szene kann nicht importiert werden",sceneRejectG2L:"Eine globale Szene kann nicht in eine lokale Szene importiert werden.",sceneRejectL2G:"Eine lokale Szene kann nicht in eine globale Szene importiert werden.",sceneRejectSRTS:"Der Raumbezug der ausgew\u00e4hlten Szene entspricht nicht dem Raumbezug der aktuellen Szene.",
unsupportedSymbolType:"Symbol wird nicht unterst\u00fctzt",unsupportedSymbolLayerType:"Symbol-Layer wird nicht unterst\u00fctzt",unsupportedSymbology:"Teile der Symbolisierung werden nicht unterst\u00fctzt",layerDisplaysWithServiceSymbology:"Layer wird mit Service- Symbolisierung angezeigt.",layerDisplaysWithItemSymbology:"Layer wird mit Elementsymbolisierung angezeigt.",layerDisplaysWithDefaultSymbology:"Layer wird mit Standardsymbolisierung angezeigt.",layerDisplaysWithFallbackSymbology:"Layer wird mit Alternativ-Symbolisierung angezeigt.",
layerCreationErrorGeneric:"Fehler beim Erstellen des Layers.",layerDisplaysNotAsExpected:"Layer wird m\u00f6glicherweise nicht wie erwartet angezeigt.",byReferenceRendererUnsupported:"Renderer nach Referenz konnte nicht erstellt werden",geometryServiceUnavailableTitle:"Problem beim Geometrie-Service",geometryServiceUnavailable:"Der Geometrie-Service antwortet nicht oder ist nicht richtig konfiguriert. Die Beleuchtung in der Szene ist m\u00f6glicherweise falsch.",invalidUrl:"Ung\u00fcltige URL",unsupportedUrl:"Nicht unterst\u00fctzte URL"},
webglMessages:{badhardware:"WebGL-Kontext kann nicht erstellt werden.\x3cbr\x3eM\u00f6glicherweise ist WebGL in Ihrem Browser deaktiviert oder Ihre Hardware unterst\u00fctzt WebGL nicht.",troubleshoot:'Probleme beheben unter \x3ca href\x3d"http://get.webgl.org" target\x3d"_blank"\x3eget.webgl.org\x3c/a\x3e',badbrowser:"Offenbar wird WebGL von Ihrem Browser nicht unterst\u00fctzt.",help:"Hilfe",mobile:"Web Scene Viewer wird auf mobilen Ger\u00e4ten nicht unterst\u00fctzt.",learnMore:"Weitere Informationen",
layerInfo:"${LayerType} nach ${Author}"},buttons:{signIn:"Anmelden",tryArcGIS:"ArcGIS testen",visitGallery:"Galerie besuchen",fullScreen:"Vollbild",exitFullScreen:"Vollbild beenden"},appName:"3D Scene Viewer"});