// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("../../../../core/declare ./Canvas3DSymbolBase ./Canvas3DGraphic ./Canvas3DDrapedGraphic ./ElevationAligners ./Canvas3DSymbolCommonCode ../../../../geometry/Polygon ../../lib/glMatrix ../../webgl-engine/Stage ../../webgl-engine/lib/Object3D ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/GeometryData ../../webgl-engine/lib/RenderGeometry ../../webgl-engine/materials/ColorMaterial ../../webgl-engine/lib/Util ./earcut/earcut".split(" "),function(B,C,D,E,x,m,F,u,v,G,H,y,I,J,K,z){var r=
K.VertexAttrConstants,A=u.vec3d,w=u.mat4d;return B([C],{_prepareResources:function(){var a=this._getStageIdHint(),b=this._getMaterialOpacityAndColor(),b={color:b,transparent:1>b[3]||this._isPropertyDriven("opacity"),polygonOffset:!1,vertexColors:!0};this._material=new J(b,a+"_colormat");this._context.stage.add(v.ModelContentType.MATERIAL,this._material);this.resolve()},destroy:function(){this._context.stage.remove(v.ModelContentType.MATERIAL,this._material.getId())},createCanvas3DGraphic:function(a,
b){var f=a.geometry;if("polyline"!==f.type&&"polygon"!==f.type&&"extent"!==f.type)return this._logWarning("unsupported geometry type for line symbol: "+f.type),null;var f="polygon"===f.type||"extent"===f.type?"rings":"paths",c="graphic"+a.id,h=this._getVertexOpacityAndColor(b,Uint8Array,255),e=this._getGraphicElevationInfo(a);return e.mode===m.ELEV_MODES.ON_THE_GROUND?this._createAsOverlay(a,f,h,e,c):this._createAs3DShape(a,f,h,e,c,a.id)},layerPropertyChanged:function(a,b,f){if("opacity"===a)return b=
this._material.getColor(),b[3]=this._getMaterialOpacity(),this._material.setColor(b),this._material.setTransparent(1>b[3]),!0;if("elevationInfo"===a){a=this._elevationInfo.mode;this._updateElevationInfo();var c=this._elevationInfo.mode;if(null==a||null==c)return!1;var h=m.ELEV_MODES;if(a===h.ON_THE_GROUND&&c===h.ON_THE_GROUND)return!0;if(a!==c&&(a===h.ON_THE_GROUND||c===h.ON_THE_GROUND))return!1;a=c===h.RELATIVE_TO_GROUND?x.perVertexElevationAligner:null;var c=this._context.elevationProvider,h=this._context.renderCoordsHelper,
e=this._context.mapCoordsHelper,g;for(g in b){var k=b[g],d=k._graphics[f];d&&(k=k.graphic,d.elevationAligner=a,d.elevationInfo.set(this._getGraphicElevationInfo(k)),x.perVertexElevationAligner(d,c,h,e))}return!0}return!1},_getGeometry:function(a){a=a.geometry;"extent"===a.type&&(a=F.fromExtent(a));return a},_createAs3DShape:function(a,b,f,c,h,e){var g=this._getGeometry(a),k=g.hasZ,d=g[b];if(0<d.length){b=[];a=[];for(var l=[],p=A.create(),q=Array(6),d=m.getGeometryVertexData3D(d,k,g.spatialReference,
this._context.renderSpatialReference,this._context.elevationProvider,c),g=d.geometryData.polygons,k=d.eleVertexData,d=d.vertexData,r=0;r<g.length;++r){var s=g[r],n=s.count,t=s.index;if(this._context.clippingExtent&&(m.computeBoundingBox(k,t,n,q),m.boundingBoxClipped(q,this._context.clippingExtent)))continue;var u=new Float64Array(k.buffer,3*t*k.BYTES_PER_ELEMENT,3*n),v=new Float64Array(d.buffer,3*t*d.BYTES_PER_ELEMENT,3*n),s=s.holeIndices.map(function(a){return a-t}),s=z(u,s,3);0<s.length&&(m.chooseOrigin(d,
t,n,p),m.subtractCoordinates(d,t,n,p),n=this._createFillGeometry(s,0,v,u,f,!1),n=new H(n,h),n.singleUse=!0,b.push(n),a.push([this._material]),n=w.identity(),w.translate(n,p,n),l.push(n))}return 0<b.length?(f=this._context.layer.get("id"),h=new G({geometries:b,materials:a,transformations:l,castShadow:!1,metadata:{layerId:f,graphicId:e},idHint:h}),e=null,c.mode===m.ELEV_MODES.RELATIVE_TO_GROUND&&(e=x.perVertexElevationAligner),new D(this,h,b,null,null,e,c)):null}this._logWarning("no paths found for line symbol");
return null},_createAsOverlay:function(a,b,f,c,h){var e=this._getGeometry(a),g=e[b];this._material.setRenderPriority(this._symbolLayerOrder);if(0<g.length){b=[];a=A.create();c=Array(6);for(var g=m.getGeometryVertexDataDraped(g,e.spatialReference,this._context.overlaySR),e=g.vertexData,g=g.geometryData.polygons,k=0;k<g.length;++k){var d=g[k],l=d.count,p=d.index,q=new Float64Array(e.buffer,3*p*e.BYTES_PER_ELEMENT,3*l),d=d.holeIndices.map(function(a){return a-p}),q=z(q,d,3);0<q.length&&(m.computeBoundingBox(e,
p,l,c),m.boundingBoxClipped(c,this._context.clippingExtent)||(m.chooseOrigin(e,p,l,a),m.subtractCoordinates(e,p,l,a),m.setZ(e,p,l,this._getDrapedZ()),l=w.identity(),w.translate(l,a,l),q=this._createFillGeometry(q,p,e,null,f,!0),d=new I(q),d.material=this._material,d.center=[0.5*(c[0]+c[3]),0.5*(c[1]+c[4]),0],d.bsRadius=0.5*Math.sqrt((c[3]-c[0])*(c[3]-c[0])+(c[4]-c[1])*(c[4]-c[1])),d.transformation=l,d.name=h,d.uniqueName=h+"#"+q.id,b.push(d)))}return 0<b.length?new E(this,b,null,null):null}return null},
_createFillGeometry:function(a,b,f,c,h,e){for(var g=a.length,k=new Uint32Array(g),d=new Uint32Array(g),l=0;l<g;l++)k[l]=a[l]+b,d[l]=0;b={};a={};b[r.POSITION]=k;b[r.COLOR]=d;a[r.POSITION]={size:3,data:f};a[r.COLOR]={size:4,data:h};c&&(a.mapPos={size:3,data:c},b.mapPos=k);f=[{type:"triangle",indices:b,positionKey:r.POSITION}];return e?{faces:f[0],vertexAttr:a,id:y.getNewId().toString()}:new y(f,a)}})});