// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define({moveUp:"Naar boven verplaatsen",moveDown:"Naar beneden verplaatsen",rename:"Naam wijzigen",hideInMapLayers:"Verbergen in lagen",showInMapLayers:"Tonen in lagen",invalidTitle:"De titel mag geen van de volgende tekens bevatten: \x3c or \x3e.",header:{home_link:"Home",simpleHome:"Home",support:"Help",features:"Functies",myAccount:"Mijn Organisatie",myProfile:"Mijn profiel",help:"Help",plans:"Abonnementen",adminGuide:"Beheerdershandleiding",signOut:"Afmelden",signIn:"Aanmelden",newScene:"Nieuwe scene",
gallery:"Galerij",groups:"Groepen",myContent:"Mijn Content",esriCommunity:"Community en forums",myEsri:"My Esri",map:"Kaart",training:"Opleiding",trialDownloads:"Proefabonnementen",fullScreen:"Verkennen in volledige viewer",newGlobal:"Nieuwe mondiale scene",newLocal:"Nieuwe lokale scene",globalScene:"Mondiale scene",localScene:"Lokale scene",spatialRef:"Ruimtelijke referentie"},environmentSettings:{dragSunSliderText:"Sleep de schuifregelaar om de tijd te wijzigen.",dragSunSliderHint:"Schuifregelaar slepen",
sunLight:"Zonlicht",sunrise:"zonsopgang",sunset:"zonsondergang",shadowing:"Schaduwen",directShadow:"Directe schaduw (door zonlicht)",diffuseShadow:"Diffuse schaduwen (omgevingsverberging)"},layerItemEditable:{groupTypeCheckbox:"Selectievakje",groupTypeRadio:"Radio",groupTypeCompact:"Samenvoegen",groupTypeHide:"Verbergen",configureLayer:"Laag configureren",zoomToLayer:"Zoomen naar",deleteLayer:"Verwijderen",dragHere:"Laag hierheen verslepen",changeGroupType:"Groeptype wijzigen"},slideDeckEditable:{addSlide:"Dia opslaan",
slide:"Dia",updateSlide:"Dia bijwerken",deleteSlide:"Dia verwijderen"},symbologyEditor:{symbologyShieldWarning:"De symbolen van deze laag kunnen niet worden gewijzigd. Klik op OK om de bestaande symbolen te verwijderen en nieuwe symbolen te defini\u00ebren.",colorOverride:"Kleur overschrijven",fill:"Vulling",outline:"Omtreklijn",shape:"Vorm",color:"Kleur",size:"Grootte",symbols:"Symbolen",transparency:"Transparantie (%)",ok:"OK",px:"px",points:"punten",meters:"meter",feet:"feet",reset:"Opnieuw instellen",
originalSymbology:"Oorspronkelijke symbolen",modifySymbology:"Symbolen wijzigen",customize:"Aanpassen",type:"Type",icon2d:"2D pictogram",object3D:"3D Object",line2d:"2D Lijn",line3d:"3D Lijn",path3d:"3D Pad",polygon2d:"2D Polygoon",polygon3d:"3D Extrusie",fillColor:"Vulkleur",outlineColor:"Kleur buitenlijn",outlineSize:"Grootte buitenlijn",shapes:{circle:"Cirkel",cone:"Kegel",cross:"Kruis",cube:"Kubus",cylinder:"Cilinder",diamond:"Diamant",kite:"Vlieger",sphere:"Bol",square:"Vierkant",tetrahedron:"Tetraeder",
x:"X"},extrusion:"Extrusie (meter)",rangeMsg:"Waarde buiten bereik. Voer een waarde in tussen ${minSize} en ${maxSize}"},mapControls:{zoomIn:"Inzoomen",zoomOut:"Uitzoomen",rotate:"Draaien",home:"Initi\u00eble weergave",pan:"Pannen",panRotateToggle:"Tik om in 3D te pannen of roteren"},switchControl:{on:"aan",off:"uit"},settings:{navigation:"3D Navigatie",proNav:"ArcGIS Pro",sceneNav:"Standaard",mouseImage:"Toewijzing van muistoetsen voor 3D-navigatie"},share:{text:"Selecteer een van de onderstaande opties om deze scene te delen.",
link:"Een link naar deze scene delen",embed:"Deze scene inbedden in een website",more:"Opties inbedden",smallSize:"Klein",mediumSize:"Middel",largeSize:"Groot",customSize:"Aangepast",shareTwitterTxt:"Verken '${sceneName}'  in 3D met uw browser:n",shareEmailSubject:"${sceneName}  in 3D (Scene Viewer)",shareEmailTxt1:"Neem een kijkje in deze web scene:",shareEmailTxt2:"U kunt uw eigen 3D-web scenes maken en delen met  Esri Scene Viewer. Ga naar http://www.arcgis.com en klik op 'Scene' om het gratis uit te proberen.",
shortenLink:"Korte link",shareUnsaved:"Deze scene bevat niet-opgeslagen wijzigingen. Om de scene te delen, moet u de wijzigingen opslaan.",shareNotPublic:"Deze scene wordt niet gedeeld met het publiek. De scene kan niet worden bekeken.",shareNotPublicLayer:"Minstens \u00e9\u00e9n laag in deze scene is niet openbaar. Niet alle lagen kunnen worden bekeken.",changeShareSettings:"Deelinstellingen wijzigen"},underground:{seeThroughGround:"Doorzichtige grond"},basemapGallery:{SRMismatch:"Ruimtelijke referentie is niet compatibel met de scene",
SRMismatchGlobal:"Ruimtelijke referentie is niet ondersteund in mondiale scenes",TSMismatch:"Tiling schema is niet compatibel met de scene",TilingScheme:"Tiling schema stemt niet overeen met ArcGIS Online tiling schema.",tilingSchemePowerOfTwo:"Niet-compatibel tiling-schema: elke schaal moet exact half zo groot zijn als de schaal van het voorgaande niveau.",tilingSchemeTileSize:"Niet-compatibel tiling-schema: alleen tiles met een breedte en hoogte van 256 worden ondersteund.",tiledMapServiceSRGCS:"Tiled Map lagen in geografische co\u00f6rdinaatsystemen worden niet ondersteund.",
tiledMapServicesMinVersion:"Tiled Map-lagen op servers voor 10.2.2 worden niet ondersteund.",basemapLayerTypeWMS:"OGC Web Map Service (WMTS) wordt niet ondersteund als basiskaart.",basemapLayerTypeWMTS:"OGC Web Tile Map Service (WMTS) wordt niet ondersteund als basiskaart.",basemapLayerTypeWTL:"Web Tiled laag wordt niet ondersteund als basiskaart.",basemapLayerTypeDMS:"Dynamic Map Service laag wordt niet ondersteund als basiskaart.",basemapLayerTypeIS:"Image Service laag wordt niet ondersteund als basiskaart.",
noBasemap:"Geen basiskaart"},compass:{compass:"Kompas"}});