// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define({defaultWebSceneName:"Scena mea",menu:{titleLayers:"Straturi tematice",titleEnvironmentSettings:"Mediu",titleSearch:"C\u0103utare",titleBasemap:"Hart\u0103 fundal",errorSceneServiceLoad:"Eroare de \u00eenc\u0103rcare serviciu scen\u0103",errorLayerName:"Nume strat tematic:",titleLegend:"Legend\u0103",titleSettings:"Set\u0103ri",titleShare:"Partajarea",moreTools:"Mai multe instrumente"},dialogs:{webscene:"Scen\u0103 web",addLayer:"Ad\u0103ugare strat tematic",layerDidNotDrawCompletely:"Stratul tematic nu a fost trasat complet",
webglCheck:"Verificare WebGL",browserCheck:"Verificare browser",browserFail:"Aplica\u0163ia de vizualizare a scenelor nu poate fi deschis\u0103 \u00een browserul dvs.",unsupportedBasemap:"Harta de fundal nu este acceptat\u0103"},messages:{addLayerFailed:"Stratul tematic nu poate fi ad\u0103ugat",layerAddedSuccess:"Stratul tematic a fost ad\u0103ugat cu succes.",layerDidNotDrawCompletely:"nu a fost trasat complet, deoarece limita de transfer a serverului de ${limit} de obiecte spa\u0163iale a fost dep\u0103\u015fit\u0103.",
layerTypeNotSupported:"Tip de strat tematic neacceptat:",onlyTiledLayerSupported:"Doar straturile tematice cu segmente tile sunt acceptate.",layerItemTypeNotSupported:"Tipul de element Strat tematic nu este suportat:",layerItemPropertiesFromMapServer:"Propriet\u0103\u0163ile de afi\u015fare salvate \u00een elemente Strat tematic de hart\u0103 nu sunt suportate.",layerItemPropertiesNotApplied:"Propriet\u0103\u0163ile de afi\u015fare salvate \u00een elementul Strat tematic nu au fost aplicate.",itemId:"ID element:",
itemType:"Tip element:",websceneLoadFail:"Scena web nu poate fi \u00eenc\u0103rcat\u0103.",websceneLoadFailNoVersion:"\u00cen scena web nu a fost g\u0103sit\u0103 nicio versiune.",websceneLoadFailBadVersion:"Versiune ${websceneVersion} nevalid\u0103 \u00een scena web.",websceneLoadFailIncompatVersion:"Versiunea ${websceneVersion} a scenei web nu este compatibil\u0103 cu aceast\u0103 aplica\u0163ie de vizualizare",websceneVersionRequires:"(necesit\u0103 ${websceneRequiredVersion})",websceneVersionMoreRecent:"Scena web (versiunea ${websceneVersion}) este mai recent\u0103 dec\u00e2t aplica\u0163ia de vizualizare versiunea {$viewerVersion}.",
webscenePotentiallyUnsupported:"Este posibil ca o parte din con\u0163inutul scenei web s\u0103 nu fie acceptat\u0103 \u015fi s\u0103 nu fie afi\u015fat\u0103 conform a\u015ftept\u0103rilor.",websceneGlobalSR:"Scena web global\u0103 trebuie s\u0103 fie \u00een Web Mercator.",websceneGlobalEmbeddedSR:"Referin\u0163ele spa\u0163iale din scena global\u0103 web trebuie s\u0103 fie \u00een Web Mercator sau WGS84 GCS.",websceneLocalSRGCS:"Scenele web locale din coordonatele geografice nu sunt acceptate.",
tiledMapServicesMinVersion:"Straturile tematice de tip tile de pe servere cu versiune mai veche de 10.2.2 nu sunt suportate.",tiledMapServicesMinVersionPatch:"Straturile tematice de tip tile de pe servere cu versiune mai veche de 10.2.2 sunt suportate doar dac\u0103 au fost aplicate toate actualiz\u0103rile de server.",sceneLayerVersion:"Versiunea stratului tematic de scene nu este acceptat\u0103.",sceneLayerSRWM:"Straturile tematice de scene trebuie s\u0103 fie \u00een Web Mercator.",sceneLayerSR:"Straturile tematice de scene trebuie s\u0103 se potriveasc\u0103 cu referin\u0163a spa\u0163ial\u0103 a scenei.",
sceneLayerSRGCS:"Straturile tematice de scene din sistemele de coordonate geografice nu sunt acceptate \u00een scenele locale.",tiledMapServicesSR:"Straturile tematice de tip tile trebuie s\u0103 fie \u00een Web Mercator.",tiledMapServicesSRGeneric:"Straturile tematice de h\u0103r\u0163i cu segmente tile scene trebuie s\u0103 se potriveasc\u0103 cu referin\u0163a spa\u0163ial\u0103 \u015fi cu schema de segmente tile.",tiledMapServiceSRGCS:"Straturile tematice de h\u0103r\u0163i cu segmente tile din sistemele de coordonate geografice nu sunt acceptate.",
tiledImageServicesSRGeneric:"Straturile tematice de imagini cu segmente tile trebuie s\u0103 se potriveasc\u0103 cu referin\u0163a spa\u0163ial\u0103 \u015fi cu schema de segmente tile.",tiledImageServiceSRGCS:"Straturile tematice de imagini cu segmente tile din sistemele de coordonate geografice nu sunt acceptate.",tiledElevationServicesSRGeneric:"Straturile tematice de eleva\u0163ie trebuie s\u0103 se potriveasc\u0103 cu referin\u0163a spa\u0163ial\u0103 \u015fi cu schema de segmente tile.",tilingSchemePowerOfTwo:"Schem\u0103 de segmente tile incompatibil\u0103: fiecare scar\u0103 trebuie s\u0103 reprezinte exact jum\u0103tate din scara nivelului precedent.",
tilingSchemeTileSize:"Schem\u0103 de segmente tile incompatibil\u0103: doar segmentele tile cu l\u0103\u0163imea \u015fi lungimea de 256 sunt acceptate.",tilingSchemeGaps:"Schem\u0103 de segmente tile incompatibil\u0103: distan\u0163ele dintre niveluri nu sunt acceptate.",tilingSchemeGeneric:"Schem\u0103 de segmente tile incompatibil\u0103.",patchRequired:"Corec\u0163ii necesare:",elevationImageServicesSR:"Straturile tematice cu eleva\u0163ii trebuie s\u0103 fie \u00een Web Mercator.",imageServicesSR:"Straturile tematice de imagini cu segmente tile trebuie s\u0103 fie \u00een Web Mercator.",
tiledMapServicesTilingScheme:"Straturile tematice ale h\u0103r\u0163ilor cu tile-uri trebuie s\u0103 respecte schema pentru segmente tile din ArcGIS Online.",tiledImageServicesTilingScheme:"Straturile tematice de imagini cu segmente tile trebuie s\u0103 respecte schema pentru segmente tile din ArcGIS Online.",elevationImageServicesTilingScheme:"Straturile tematice cu eleva\u0163ii trebuie s\u0103 respecte schema pentru segmente tile din ArcGIS Online.",imageServicesCached:"Sunt acceptate doar serverele de imagini memorate \u00een cache.",
elevationImageServicesCached:"Sunt acceptate doar serverele de imagini memorate \u00een cache cu codificare LERC.",elevationBasemapTitle:"Stratul tematic de eleva\u0163ie implicit nu poate fi ad\u0103ugat",elevationBasemapSR:"Referin\u0163a spa\u0163ial\u0103 a stratului tematic de eleva\u0163ie nu se potrive\u015fte cu referin\u0163a spa\u0163ial\u0103 a h\u0103r\u0163ii fundal.",elevationBasemapTS:"Schema de segmente tile a stratului tematic de eleva\u0163ie nu este compatibil\u0103 cu schema de segmente tile a h\u0103r\u0163ii fundal.",
featureServiceNotSupportedTable:"Tipul de tabel nu este acceptat.",featureServiceNotSupportedMultipatch:"Serviciile multipatch de obiecte spa\u0163iale nu sunt suportate.",featureServiceNotSupportedNoRenderer:"Serviciile f\u0103r\u0103 instrument de redare nu sunt suportate.",featureServiceNotSupportedRendererType:"Tipul de instrument de redare nu este suportat:",featureServiceNotSupportedMaxFeatures:"serviciul de obiecte spa\u0163iale dep\u0103\u015fe\u015fte limita maxim\u0103 de obiecte spa\u0163iale:",
featureServiceNotSupportedMaxVertices:"serviciul de obiecte spa\u0163iale dep\u0103\u015fe\u015fte limita maxim\u0103 de noduri:",splashSignInToEdit:"Autentifica\u0163i-v\u0103 pentru a explora lumea \u00een 3D \u015fi ad\u0103uga\u0163i straturi tematice din Esri \u015fi din mii de organiza\u0163ii pentru a crea scene noi.",splashShowThisOnStart:"afi\u015fare la pornire",splashNewToArcGIS:"Utilizator ArcGIS nou? \u00censcrie\u0163i-v\u0103 pentru un abonament de evaluare ast\u0103zi.",splashLookAtOtherScenes:"Iat\u0103 c\u00e2teva dintre scenele pe care le pute\u0163i explora.",
selectedBasemapMismatchTitle:"Harta fundal selectat\u0103 nu poate fi utilizat\u0103",selectedBasemapMismatch:"Referin\u0163a spa\u0163ial\u0103 \u015fi schema de segmente tile a h\u0103r\u0163ii fundal nu sunt compatibile cu scena.\nCrea\u0163i o scen\u0103 nou\u0103 pentru a utiliza aceast\u0103 hart\u0103 fundal.",serviceName:"Nume serviciu",basemapDrop:"Stratul tematic are o referin\u0163\u0103 spa\u0163ial\u0103 \u015fi o schem\u0103 de segmente tile diferite de harta fundal.\x3cBR\x3eDori\u0163i s\u0103 renun\u0163a\u0163i la harta fundal pentru a ad\u0103uga stratul tematic?",
basemapDropConfirm:"Renun\u0163are la harta fundal",basemapDropTitle:"Nepotrivire date",BasemapDropWarningTitle:"S-a renun\u0163at la harta fundal",BasemapDropWarning:"Referin\u0163a spa\u0163ial\u0103 \u015fi schema de segmente tile a h\u0103r\u0163ii fundal nu sunt compatibile cu stratul tematic \u015fi, prin urmare, s-a renun\u0163at la aceasta.",sceneRejectTitle:"Scena nu poate fi importat\u0103",sceneRejectG2L:"O scen\u0103 global\u0103 nu poate fi importat\u0103 \u00eentr-o scen\u0103 local\u0103.",
sceneRejectL2G:"O scen\u0103 local\u0103 nu poate fi importat\u0103 \u00eentr-o scen\u0103 global\u0103.",sceneRejectSRTS:"Referin\u0163a spa\u0163ial\u0103 a scenei selectate nu corespunde cu referin\u0163a spa\u0163ial\u0103 a scenei curente.",unsupportedSymbolType:"Simbol neacceptat",unsupportedSymbolLayerType:"Strat tematic de simboluri neacceptat",unsupportedSymbology:"O parte din simbolistic\u0103 nu este acceptat\u0103",layerDisplaysWithServiceSymbology:"Stratul tematic este afi\u015fat cu simbolistic\u0103 pentru servicii.",
layerDisplaysWithItemSymbology:"Stratul tematic este afi\u015fat cu simbolistic\u0103 pentru elemente.",layerDisplaysWithDefaultSymbology:"Stratul tematic este afi\u015fat cu simbolistica implicit\u0103.",layerDisplaysWithFallbackSymbology:"Stratul tematic este afi\u015fat cu simbolistic\u0103 pentru revenire.",layerCreationErrorGeneric:"Eroare la crearea stratului tematic.",layerDisplaysNotAsExpected:"Este posibil ca stratul tematic s\u0103 nu fie afi\u015fat conform a\u015ftept\u0103rilor.",byReferenceRendererUnsupported:"Instrumentul de redare nu a putut fi creat prin referin\u0163\u0103",
geometryServiceUnavailableTitle:"Problem\u0103 cu serviciul de geometrie",geometryServiceUnavailable:"Serviciul de geometrie nu r\u0103spunde sau nu este configurat corect. Iluminarea din scen\u0103 poate fi incorect\u0103.",invalidUrl:"URL nevalid",unsupportedUrl:"URL neacceptat"},webglMessages:{badhardware:"Nu se poate crea context WebGL.\x3cbr\x3eEste posibil ca WebGL s\u0103 fie afi\u015fat \u00een browser sau ca echipamentele dvs. hardware s\u0103 nu suporte WebGL.",troubleshoot:'Diagnostica\u0163i problemele la \x3ca href\x3d"http://get.webgl.org" target\x3d"_blank"\x3eget.webgl.org\x3c/a\x3e',
badbrowser:"Browserul dvs. nu pare s\u0103 suporte WebGL.",help:"Ajutor",mobile:"Aplica\u0163ia de vizualizare a scenelor web nu este suportat\u0103 pe dispozitive mobile.",learnMore:"Afla\u0163i mai multe",layerInfo:"${LayerType} de ${Author}"},buttons:{signIn:"Autentificare",tryArcGIS:"\u00cencerca\u0163i ArcGIS",visitGallery:"Vizita\u0163i galeria",fullScreen:"Pe tot ecranul",exitFullScreen:"P\u0103r\u0103sire ecran complet"},appName:"Aplica\u0163ie de vizualizare a scenelor 3D"});