// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("../../../core/declare dojo/promise/all dojo/_base/lang ./GraphicsLayerView3D ./i3s/I3SUtil ../support/projectionUtils ../lib/glMatrix ../../../geometry/Point ../../../geometry/Polyline ../../../geometry/Polygon ../../../Graphic ../support/PromiseLightweight".split(" "),function(G,H,I,J,E,K,L,M,N,O,A,P){return G(J,{declaredClass:"esri.views.3d.layers.SceneGraphicsLayerView3D",constructor:function(a){this.nodesAddedToStage={}},getGraphicsFromStageObject:function(a,c){var b=new P.Promise;if(this._graphicsCollection){var d=
a.getMetadata().graphicId,f=this._getObjectIdField(),g=this.layer._companionFeatureLayer;this._graphicsCollection.some(function(a){if(a.id===d)return a._attributesQueried?b.resolve(a):a.attributes&&null!=a.attributes[f]?E.queryAttributesFromFeatureLayer(g,a.attributes[f]).then(function(c){I.mixin(a.attributes,c);a._attributesQueried=!0;b.resolve(a)},function(a){b.reject(a)}):b.reject(Error("No feature ID found on selected graphic.")),!0})||b.reject(Error("No graphic found for selected geometry."))}else b.reject(Error("Graphics layer view not yet initialized."));
return b},_initGraphicsController:function(){var a={addBundle:this._addBundle.bind(this),isBundleAlreadyAddedToStage:this._isBundleAlreadyAddedToStage.bind(this),isOverMemory:this._isOverMemory.bind(this),removeNodeData:this._removeNodeData.bind(this),removeFeatures:this._removeFeatures.bind(this),getAddedFeatures:this._getAddedFeatures.bind(this),areAllBundlesLoaded:this._areAllBundlesLoaded.bind(this),wholeNodeSwitchEnabled:!0},c={traversalOptions:{initDepthFirst:!1,neighborhood:!1,perLevelTraversal:!0,
allowPartialOverlaps:!1,errorMetricToUse:"screenSpaceRelative",elevationInfo:this.layer.elevationInfo},getAllAddedFeatures:this._getAllAddedFeatures.bind(this),_nodeDebugVisualizer:this._nodeDebugVisualizer,getLoadedAttributes:this.getLoadedAttributes.bind(this),setAttributeData:this.setAttributeData.bind(this),nodeElevationUpdate:this.nodeElevationUpdate.bind(this)},a=this.layer.createGraphicsController({layerView:this,layerViewRequiredFunctions:a,layerViewOptionalFunctions:c});H([this,a,this.layer]).then(function(a){this._graphicsCollection=
this.layer.graphics;this._graphicsCollectionEventHandle=this._graphicsCollection.on("change",this._collectionChangeHandler.bind(this));this.add(this._graphicsCollection.getAll())}.bind(this))},_evaluateUpdatingState:function(){},_getAllAddedFeatures:function(){var a={},c;for(c in this.graphics){var b=this.graphics[c];a[b._nodeId]=b._features}return a},_addBundle:function(a,c,b,d,f,g,h){g=this._controller.get("crsIndex");var k=[],s=this._getObjectIdField();null==this.nodesAddedToStage[a.id]&&(this.nodesAddedToStage[a.id]=
{bundles:[],attributeData:b?b.attributeData:null,loadedAttributes:b?b.loadedAttributes:null});this.nodesAddedToStage[a.id].bundles[h]=k;if(null==c)null!=f&&f.done();else{for(b=0;b<c.length;b++)for(var p=c[b],w=p.featureDataPositions[0],y=0;y<p.geometries.length;y++){var t=[],l=p.features[y<p.features.length?y:0],q=l?{}:null;l&&(q[s]=l.id);var l=p.geometries[y],m=l.params.type,e=l.params.vertexAttributes.position;if("ArrayBufferView"===l.type){if(null==e)continue;var n=new E.valueType2TypedArrayClassMap[e.valueType](d[a.geometryData[h].hrefConcat],
e.byteOffset,e.count*e.valuesPerElement),u=e.valuesPerElement}else"Embedded"===l.type&&(n=e,u=3);if("lines"===m){l=[];for(e=0;e<n.length;e+=u)l.push([n[e]+a.mbs[0],n[e+1]+a.mbs[1]]);m=new N(g);m.addPath(l);t.push(new A(m,null,q))}else if("points"===m)for(e=0;e<n.length;e+=u)m=new M({x:n[e]+w[0],y:n[e+1]+w[1],z:2<u?n[e+2]+w[2]:void 0,spatialReference:g}),t.push(new A(m,null,q));else if("polygon"===m){m=new O(g);m._outlineSegments=[];for(var B=0;B<l.params.rings.length;B++){for(var v=l.params.rings[B],
x=v.start,F=[],C=[],r=[-1,-1],z=0;z<v.segments.length;z+=2){var e=v.segments[z+0],D=v.segments[z+1];0===e||1===e?(-1===r[0]&&(r[0]=x-v.start),r[1]=x+D-v.start):-1!==r[0]&&(C.push(r),r=[-1,-1]);for(e=x*u;e<(x+D)*u;e+=u)F.push([n[e]+a.mbs[0],n[e+1]+a.mbs[1]]);x+=D}-1!=r[0]&&C.push(r);m._outlineSegments.push(C);m.addRing(F);null!=v.inner&&console.warn("inner rings not yet supported")}t.push(new A(m,null,q))}for(q=0;q<t.length;q++)t[q]._attributesQueried=!1;this.layer.add(t);k.push({features:p.features,
graphics:t})}a=this.nodesAddedToStage[a.id];this._setBundleAttributes(a.bundles[h],a.loadedAttributes,a.attributeData);f.done()}},_areAllBundlesLoaded:function(a,c){var b=this.nodesAddedToStage[a.id];if(null==b)return!1;for(var d=0;d<a.featureData.length;d++){var f=b.bundles[d];if(null==f)return!1;if(!0!==c)for(var g=a.featureData[d].featureRange[1],h=a.featureData[d].featureRange[0];h<=g;h++)if(!(null==a.features||a.features.length<h)){var k=a.features[h].id;a:{for(var s=f.length;s--;)for(var p=
f[s].features,w=p.length;w--;)if(p[w].id===k){k=!0;break a}k=!1}if(!1===k)return!1}}return!0},_isBundleAlreadyAddedToStage:function(a,c){return null==this.nodesAddedToStage[a.id]?{alreadyLoaded:!1,wasPartiallyHidden:!1}:{alreadyLoaded:this.nodesAddedToStage[a.id].bundles[c],wasPartiallyHidden:!1}},_isOverMemory:function(){return!1},_removeFeatures:function(a,c){var b=this.nodesAddedToStage[a.id];if(null!=b){var b=b.bundles,d;for(d in b)for(var f=0;f<b[d].length;f++){var g=b[d][f],h=!1;if(null!=g){for(var k in g.features)if(-1!==
c.indexOf(g.features[k].id)){h=!0;break}h&&(this.layer.remove(g.graphics),delete b[d][f])}}for(d=0;d<b.length;d++)for(f=0;f<b[d].length;f++)if(g=b[d][f],null!=g&&0<g.graphics.length)return;this._removeNodeData(a)}},_removeNodeData:function(a){var c=this.nodesAddedToStage[a.id];if(null!=c){var c=c.bundles,b;for(b in c)for(var d in c[b])this.layer.remove(c[b][d].graphics);delete this.nodesAddedToStage[a.id]}},_rendererChange:function(a,c,b,d){this._symbolCreationContext.renderer=a;Object.keys(this.nodesAddedToStage).forEach(function(a){this._removeNodeData({id:a})}.bind(this))},
_scaleRangeEnabled:function(){return!1},_visibleAtScaleLabel:function(){return!0},_visibleAtScale:function(){return!0},_graphicVisibleAtScale:function(){return!0},_shouldAddToSpatialIndex:function(){return!1},nodeElevationUpdate:function(a,c,b){a=this.nodesAddedToStage[a];if(null!=a){a=a.bundles;for(var d in a)for(var f in a[d]){c=a[d][f].graphics;for(var g in c)this._markGraphicElevationDirty(c[g].id)}}},_getAddedFeatures:function(a){a=this.nodesAddedToStage[a];if(null==a)return null;a=a.bundles;
var c=[],b;for(b in a)for(var d=0;d<a[b].length;d++)c=c.concat(a[b][d].features);return c},getLoadedAttributes:function(a){if(a=this.nodesAddedToStage[a.id])return a.loadedAttributes},setAttributeData:function(a,c,b){if(a=this.nodesAddedToStage[a.id])a.loadedAttributes=c,a.attributeData=b,this._setNodeAttributes(a,b,c),this.layerLabelsEnabled()&&this._showLabelsChange()},_setNodeAttributes:function(a,c,b){a=a.bundles;for(var d in a)this._setBundleAttributes(a[d],b,c)},_setBundleAttributes:function(a,
c,b){for(var d=0;d<a.length;d++)for(var f=a[d],g=0;g<f.graphics.length;++g){var h=f.graphics[g];h.attributes||(h.attributes={});if(c)for(var k=0;k<c.length;++k){var s=c[k].name;h.attributes[s]=b[s][d]}}},_getObjectIdField:function(){return this.layer.objectIdField||"OBJECTID"},_updateSuspendResumeExtent:function(){this.layer.fullExtent&&this._mapSR?(this._suspendResumeExtent||(this._suspendResumeExtent=L.vec4d.create()),K.extentToBoundingRect(this.layer.fullExtent,this._suspendResumeExtent,this._mapSR)||
(this._suspendResumeExtent=null)):this._suspendResumeExtent=null;this._suspendResumeExtentEngineDirty=this._scaleVisibilityDirty=this._frustumVisibilityDirty=!0},getStats:function(){var a=this.inherited(arguments);a.nodesAddedToStage=Object.keys(this.nodesAddedToStage).length;return a}})});