// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("../../../../core/declare dojo/_base/lang ../../webgl-engine/lib/Util ./I3SUtil ./I3SAttributeReader ../../support/PromiseLightweight ../../support/projectionUtils ../../lib/glMatrix".split(" "),function(H,I,J,s,M,p,W,X){var x=J.assert;return H(null,{constructor:function(N,A,H,B,O,J,P,Y,Z,$,aa,ba,Q,K,F,R){function C(a){return y?(z=!1,a&&a.done(),!0):!1}function S(a,b){if(void 0!==a)for(var e=0;e<a.length;e++)2>a[e].length||(b[a[e][0]]=a[e][1])}function ca(a,b,e){var c=[];a=e[a.sharedResource.hrefConcat];
x(a);for(var f in a.materialDefinitions)if(a.materialDefinitions.hasOwnProperty(f)&&(e=a.materialDefinitions[f],e.href)){var n=s.concatUrl(b,e.href)+"/";e.hrefConcat=n;c.push(D.request(n,"json"))}return c}var da=X.vec4d,D=N,z=!1,y=!1;this.cancel=function(){y=!0};this.isLoading=function(){return z};var T=function(a,b,e){b=b.textureDefinitions;if(void 0!==b)for(var c in b)if(b.hasOwnProperty(c)){var f=b[c],n=Array.isArray(f.encoding)?f.encoding.length:-1,m=e;f.href&&(m=s.concatUrl(m,f.href),f=a[m].textureDefinitions,
x(f));for(var l=0;l<f.images.length;l++){var k=f.images[l];k.hrefConcat=-1<n?k.href.map(function(a){return s.concatUrl(m,a)}):s.concatUrl(m,k.href)}}},U=function(a){a=a.textureDefinitions;if(null!=a)for(var b in a){var e=a[b];if(Array.isArray(e.encoding))for(var c=0;c<e.encoding.length;c++)e.encoding[c].startsWith("data:")&&(e.encoding[c]=e.encoding[c].substring(5));else e.encoding=e.encoding.substring(5)}},ea=function(a,b,e){var c,f=new p.Promise;null!=a.sharedResource?(c=s.concatUrl(e,a.sharedResource.href)+
"/",a.sharedResource.hrefConcat=c,D.request(c,"json").then(function(c,m){if(!C()){b[c]=m;U(m);T(b,m,c);var l=ca(a,e,b);0<l.length?p.join(l).then(function(a){if(!C()){S(a,b);U(b[c]);for(var c in b)T(b,b[c],c);f.done()}},function(){f.reject()}):f.done()}},function(a){f.reject()})):f.done();return f},E={},fa=function(a,b,e,c,f,n,m){var l=-1<m?c.encoding[m]:c.encoding;c=l===s.DDS_ENCODING_STRING;var k=Z(f);x(!(c&&k),"DDS in multi texture bundles not supported at the moment");N.request(a,k||c?"binary":
"image").then(function(c,d,v,r){if(!y)if(k){var q;try{var w,s;-1<m?(x(Array.isArray(f.byteOffset)&&Array.isArray(f.length),"texture encoding is array, but image byteOffset/length isn't"),w=f.byteOffset[m],s=f.length[m]):(w=f.byteOffset,s=f.length);var h=new Uint8Array(d,w,s),t=new Blob([h],{type:l});q=window.URL.createObjectURL(t)}catch(u){q="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAIElEQVQ4T2P8zyD6n4ECwDhqAMNoGDCMhgEwDw2DdAAAdzkhQdS8dl8AAAAASUVORK5CYII\x3d",console.error("error loading texture "+
a+" "+u)}var p=new Image;p.onerror=function(){window.URL.revokeObjectURL(q);p.url="";p.onerror=void 0;p.onload=void 0;b.done({})};p.onload=function(){window.URL.revokeObjectURL(q);p.url="";p.onerror=void 0;p.onload=void 0;y?b.reject():b.done({i3sTexId:e,data:p,encoding:l,desiredLOD:n})};p.src=q}else b.done({i3sTexId:e,data:d,encoding:l,desiredLOD:n})},function(){b.done({})},this)},ga=function(a,b,e,c,f,n){f=[];for(n=0;n<a.length;n++){var m=a[n].geometries,l;l=a[n].features;for(var k=[],g=0;g<l.length;g++)k.push(l[g].engineMBS);
l=k;for(k=0;k<m.length;++k)for(var g=m[k],d=g.params.components.length,v=0;v<d;v++){var r=g.params.components[v],q=r.materialID,r=r.textureID||"none";if(!(e[q]&&void 0!==e[q][r])&&void 0===c[r]&&"none"!==r)if(void 0!==E[r])f.push(E[r]);else{(null==b.textureDefinitions||null==b.textureDefinitions[r])&&Q("textureDefinitions missing in shared resource",1,"i3sTexId "+r);q=b.textureDefinitions[r];x(void 0!==q,"geometry wants unknown texture "+r);var w=Y(l,q.images);if(0!==q.images.length){var L=new p.Promise;
f.push(L);E[r]=L;var h=q.images[w],t=s.getAppropriateTextureEncoding(q.encoding,ba());fa(-1<t?h.hrefConcat[t]:h.hrefConcat,L,r,q,h,w,t)}}}}if(0<f.length)return p.join(f)},G=function(a){a=a.split("/");return a[a.length-1]},ha=function(a,b,e){e=e[a.featureData[b].hrefConcat];null==a.features&&(a.features=[]);for(var c in e.featureData)a.features.push({id:e.featureData[c].id,mbs:a.mbs,block:b})},V=function(a,b,e){var c=[],f=!1;if(null==a.featureData[b].featureRange)var n=0,m=a.features.length-1,f=!0;
else n=a.featureData[b].featureRange[0],m=a.featureData[b].featureRange[1];for(;n<=m;++n){var l=a.features[n];if(!l.engineMBS){var k=da.create();W.mbsToMbs(l.mbs,P,k,J.spatialRef);k[3]=l.mbs[3];l.engineMBS=k}if(!(f&&l.block!==b)){for(var k=e[a.featureData[b].hrefConcat],g=k.featureData,d,v=0;v<g.length;v++)if(g[v].id===l.id){d=g[v];break}x(d,"I3S: unable to find feature data in specified block in node.id "+a.id+" feature.id "+l.id);var g=d.geometries,v=[],r=[];if(null!=g)for(var q=0;q<g.length;q++){var p=
d.geometries[q];if("GeometryReference"==p.type){for(var s=G(p.params.$ref),h,t=0;t<k.geometryData.length;t++){var u=k.geometryData[t];if(u.id+""==s){h=u;break}}x(h,"I3S: Unable to find referenced geometry");null==h.params.material&&(Q("material definition is missing in featureData, node ",a.id),t=Object.keys(e[a.sharedResource.hrefConcat].materialDefinitions)[0],h.params.material="/materialDefinitions/"+t);null==h.params.components&&(h.params.components=null!=h.params.texture?[{material:h.params.material,
materialID:G(h.params.material),texture:h.params.texture,textureID:G(h.params.texture),id:1}]:[{material:h.params.material,materialID:G(h.params.material),id:1}],null!=h.params.faces&&null!=h.params.faces.position&&(h.params.faces.position.componentIndices=[0]));u=null;for(t=0;t<c.length;t++)if(1==c[t].geometries.length&&c[t].geometries[0].id+""===s){u=c[t];break}null===u&&(u={features:[],featureDataPositions:[],featureDataAttributes:[],faceRanges:[],geometries:[h]},c.push(u));u.features.push(l);
u.featureDataAttributes.push(d.attributes);u.featureDataPositions.push(d.position);u.faceRanges.push(p.params.faceRange)}else v.push(p),null!=p.params.faceRange&&r.push(p.params.faceRange)}else null!=d.position&&v.push({id:l.id,type:"Embedded",transformation:[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],params:{type:"points",vertexAttributes:{position:[0,0,0]}}});0===r.length&&(r=null);0<v.length&&c.push({features:[l],featureDataAttributes:[d.attributes],featureDataPositions:[d.position],geometries:v,faceRanges:r})}}return c},
ia=function(a,b,e,c){a={featureData:[{id:a,position:[0,0,0],pivotOffset:[0,0,0],mbb:c,layer:"Default",geometries:[{id:1,type:"GeometryReference",params:{$ref:"/geometryData/0",faceRange:[0,0]}}]}],geometryData:[{id:0,type:"ArrayBufferView",transformation:[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],params:{type:"triangles",material:"/materialDefinitions/"+b}}]};null!=e&&(a.geometryData[0].params.texture="/textureDefinitions/"+e);return a},ja=function(a,b,e,c){var f=a.geometries[0],n=M.readBinaryHeader(e,b.header),
m=n.byteCount;a.faceRanges[0][0]=0;a.faceRanges[0][1]=n.fields.vertexCount/3-1;f.params.vertexAttributes=I.clone(b.vertexAttributes);!c&&null==f.params.vertexAttributes.region&&delete f.params.vertexAttributes.region;var l=f.params.vertexAttributes;if(b.faces){f.params.faces=I.clone(b.faces);var k=f.params.faces}for(var g=0;g<b.ordering.length;g++){var d=b.ordering[g];if(c||"region"!==d)l[d].byteOffset=m,l[d].count=n.fields.vertexCount,m+=s.getBytesPerValue(l[d].valueType)*l[d].valuesPerElement*n.fields.vertexCount}if(k){for(g=
0;g<b.ordering.length;g++)d=b.ordering[g],k[d].byteOffset=m,k[d].count=n.fields.vertexCount;m+=s.getBytesPerValue(k[d].valueType)*k[d].valuesPerElement*n.fields.vertexCount;k.position.componentIndices=[0]}if(b.featureAttributes&&b.featureAttributeOrder&&n.fields.featureCount){f.params.featureAttributes=I.clone(b.featureAttributes);c=f.params.featureAttributes;for(g=0;g<b.featureAttributeOrder.length;g++)d=b.featureAttributeOrder[g],c[d].byteOffset=m,c[d].count=n.fields.featureCount,f=s.getBytesPerValue(c[d].valueType),
"UInt64"===c[d].valueType&&(f=8),m+=f*c[d].valuesPerElement*n.fields.featureCount;if(c.faceRange&&c.id){a.faceRanges=[];a.featureIds=[];g=s.valueType2TypedArrayClassMap[c.faceRange.valueType];b=new g(e,c.faceRange.byteOffset,c.faceRange.count*c.faceRange.valuesPerElement);m=1;"UInt64"==c.id.valueType?(g=Uint32Array,m=2):g=s.valueType2TypedArrayClassMap[c.id.valueType];e=new g(e,c.id.byteOffset,c.id.count*c.id.valuesPerElement*m);for(g=0;g<n.fields.featureCount;g++)a.faceRanges[g]=[],a.faceRanges[g][0]=
b[g*c.faceRange.valuesPerElement],a.faceRanges[g][1]=b[g*c.faceRange.valuesPerElement+1],a.featureIds[g]=e[g*c.id.valuesPerElement*m],2===m&&(d=e[g*c.id.valuesPerElement*m+1],x(2097150>d,"ID exceeded maximum range supported by javascript (max \x3d 53bit-1 \x3d 9007199254740991)"),a.featureIds[g]+=4294967296*d)}}};this.loadAttributes=function(a,b,e){for(var c={},f=[],n=0;n<e.length;n++){var m=e[n];f.push(M.load(D,b,m.attributeStorageInfo,a.attributeData[m.index]))}var l=new p.Promise;p.join(f).then(function(a){try{for(var b=
0;b<e.length;++b)a[b][0]&&(c[e[b].name]=a[b][0]);l.done(c)}catch(f){l.cancel(f)}},function(a){l.cancel(a)});return l};this.loadNodeData=function(a,b,e,c,f){function n(a){if(e){var b=[],c;for(c in a)b.push(a[c]);p.join(b).then(function(a){e.done();z=!1},function(a){e.done();z=!1})}}e&&(z=!0);var m=null==a.features,l=s.getNodeURL(H,a.id),k={},g,d=[];d.push(ea(a,k,l));null!=F&&d.push(this.loadAttributes(a,l,F));p.join(d).then(function(d){if(null!=F)var r=d[1][0];if(!C(e)){var q={},w={};if(null!=a.featureData)for(var x in b){var h=
b[x];g=s.concatUrl(l,a.featureData[h].href);a.featureData[h].hrefConcat=g;d={};d.featureDataPath=g;if(R&&K){var t=a.id,u=Object.keys(k[a.sharedResource.hrefConcat].materialDefinitions)[0];if(null!=k[a.sharedResource.hrefConcat].textureDefinitions)var z=Object.keys(k[a.sharedResource.hrefConcat].textureDefinitions)[0];t=ia(t,u,z,null);d.promiseFeatureData=new p.Promise;d.promiseFeatureData.resolve(a.featureData[h].hrefConcat,t,"json",h)}else d.promiseFeatureData=D.request(g,"json",{metadata:h});q[h]=
d;e&&(w[h]=new p.Promise)}for(var y in q)d=q[y],d.promiseFeatureData.then(function(b,d,n,h){C(e)||(k[b]=d,b=[],q[h].alreadyLoaded?(q[h].collectedGeometries=V(a,h,k),B(A,void 0,[a,q[h].collectedGeometries,null,k,w[h],void 0,h,f])):(m&&ha(a,h,k),q[h].collectedGeometries=V(a,h,k),null!=a.geometryData&&a.geometryData.length>h&&(g=s.concatUrl(l,a.geometryData[h].href),a.geometryData[h].hrefConcat=g,d=D.request(g,"binary",{metadata:h}),b.push(d)),c&&(d=ga(q[h].collectedGeometries,k[a.sharedResource.hrefConcat],
$,aa,k,a),void 0!==d&&b.push(d)),(0<b.length?p.join(b):{then:function(a){a([[0,0,0,h]])}}).then(function(b){if(!C(e)){if(null!=b){S(b,k);for(var c={},d=0;d<b.length;d++)if(1===b[d].length)for(var g=0;g<b[d][0].length;g++){var h=b[d][0][g][0],l=h.i3sTexId;c[l]={data:h.data,encoding:h.encoding,desiredLOD:h.desiredLOD,createdTextureForDomImage:function(){E[l]&&delete E[l]}}}}void 0!==O&&O.show(a,P,"green");b=b[0][3];R&&K&&(d=Object.keys(k[a.sharedResource.hrefConcat].materialDefinitions)[0],ja(q[b].collectedGeometries[0],
K,k[a.geometryData[0].hrefConcat],k[a.sharedResource.hrefConcat].materialDefinitions[d].params.vertexRegions));d=null;r&&(d={attributeData:r,loadedAttributes:F});B(A,void 0,[a,q[b].collectedGeometries,d,k,w[b],c,b,f])}},function(b){B(A,void 0,[a,null,null,k,w[h],null,h,f])})))},function(b){B(A,void 0,[a,null,null,k,w[y],null,y,f])});n(w)}},function(c){c=[];for(var d in b){var e=b[d];c[e]=new p.Promise;B(A,void 0,[a,null,null,k,c[e],null,e,f]);z=!1}n(c)});return e}}})});