// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define({moveUp:"Mover para cima",moveDown:"Mover para baixo",rename:"Renomear",hideInMapLayers:"Ocultar em Camadas",showInMapLayers:"Exibir em Camadas",invalidTitle:"O t\u00edtulo n\u00e3o pode conter qualquer um destes caracteres: \x3c or \x3e.",header:{home_link:"In\u00edcio",simpleHome:"In\u00edcio",support:"Ajuda",features:"Elementos",myAccount:"A Organiza\u00e7\u00e3o",myProfile:"O Meu Perfil",help:"Ajuda",plans:"Planos",adminGuide:"Guia do Administrador",signOut:"Terminar sess\u00e3o",signIn:"Iniciar sess\u00e3o",
newScene:"Nova Cena 3D",gallery:"Galeria",groups:"Grupos",myContent:"O Meu Conte\u00fado",esriCommunity:"Comunidade e F\u00f3runs",myEsri:"My Esri",map:"Mapa",training:"Forma\u00e7\u00e3o",trialDownloads:"Transfer\u00eancias de Teste",fullScreen:"Explorar Vista Completa",newGlobal:"Nova Cena Global",newLocal:"Nova Cena Local",globalScene:"Cena Global",localScene:"Cena Local",spatialRef:"Refer\u00eancia Espacial"},environmentSettings:{dragSunSliderText:"Arrastar a barra deslizante para alterar a hora do dia.",
dragSunSliderHint:"Arrastar Controlo Deslizante",sunLight:"Luz do Sol",sunrise:"nascer do sol",sunset:"p\u00f4r do sol",shadowing:"Sombreamento",directShadow:"Sombra Direta (a partir da luz do sol)",diffuseShadow:"Sombras Difusas (oclus\u00e3o do ambiente)"},layerItemEditable:{groupTypeCheckbox:"Caixa de Sele\u00e7\u00e3o",groupTypeRadio:"R\u00e1dio",groupTypeCompact:"Juntar",groupTypeHide:"Esconder",configureLayer:"Configurar Camada",zoomToLayer:"Aplicar zoom em",deleteLayer:"Remover",dragHere:"Arrastar Camada para aqui",
changeGroupType:"Alterar Tipo de Grupo"},slideDeckEditable:{addSlide:"Captura de Slide",slide:"Slide",updateSlide:"Atualizar Slide",deleteSlide:"Remover Slide"},symbologyEditor:{symbologyShieldWarning:"A simbologia desta camada n\u00e3o pode ser modificada. Clique em ok para remover a simbologia existente e definir nova simbologia.",colorOverride:"Substitui\u00e7\u00e3o de cor",fill:"Preencher",outline:"Contorno",shape:"Forma",color:"Cor",size:"Dimens\u00e3o",symbols:"S\u00edmbolos",transparency:"Transpar\u00eancia (%)",
ok:"OK",px:"px",points:"pontos",meters:"metros",feet:"p\u00e9s",reset:"Repor defini\u00e7\u00f5es padr\u00e3o",originalSymbology:"S\u00edmbolos originais",modifySymbology:"Alterar s\u00edmbolos",customize:"Personalizar",type:"Tipo",icon2d:"\u00cdcone 2D",object3D:"Objeto 3D",line2d:"Linha 2D",line3d:"Linha 3D",path3d:"Caminho 3D",polygon2d:"Pol\u00edgono 2D",polygon3d:"Extrus\u00e3o 3D",fillColor:"Cor de Preenchimento",outlineColor:"Cor do Contorno",outlineSize:"Tamanho do Contorno",shapes:{circle:"C\u00edrculo",
cone:"Cone",cross:"Cruz",cube:"Cubo",cylinder:"Cilindro",diamond:"Diamante",kite:"Papagaio",sphere:"Esfera",square:"Quadrado",tetrahedron:"Tetraedro",x:"X"},extrusion:"Extrus\u00e3o (metros)",rangeMsg:"Valor fora de alcance. Por favor introduza um valor entre ${minSize} e ${maxSize}"},mapControls:{zoomIn:"Aumentar Zoom",zoomOut:"Reduzir Zoom",rotate:"Rodar",home:"Vista Inicial",pan:"Mover",panRotateToggle:"Alternar para arrastar ou rodar em 3D"},switchControl:{on:"ligado",off:"desligado"},settings:{navigation:"Navega\u00e7\u00e3o 3D",
proNav:"ArcGIS Pro",sceneNav:"Padr\u00e3o",mouseImage:"Tarefas dos bot\u00f5es de rato para navega\u00e7\u00e3o 3D"},share:{text:"Seleccionar uma das op\u00e7\u00f5es abaixo para partilhar esta cena 3D.",link:"Partilhar um link para esta cena 3D",embed:"Embeber esta cena 3D num site web",more:"Op\u00e7\u00f5es de Incorpora\u00e7\u00e3o",smallSize:"Pequeno",mediumSize:"M\u00e9dia",largeSize:"Grande",customSize:"Personalizar",shareTwitterTxt:"Explore '${sceneName}'  in 3D with your browser:\n",shareEmailSubject:"${sceneName}  em 3D (Visualizador de Cena 3D)",
shareEmailTxt1:"Veja esta Web Scene:",shareEmailTxt2:"Pode criar e partilhar as suas pr\u00f3prias Web Scenes 3D com o Visualizador de Cenas 3D Esri. Visite http://www.arcgis.com e clique 'Cena' para testar a vers\u00e3o gratuita.",shortenLink:"Link Pequeno",shareUnsaved:"Esta cena 3D contem altera\u00e7\u00f5es n\u00e3o guardadas. De forma a o partilhar, precisa de guardar estas altera\u00e7\u00f5es.",shareNotPublic:"Esta cena 3D n\u00e3o est\u00e1 partilhada com o p\u00fablico. Pessoas podem n\u00e3o ser capazes de v\u00ea-la.",
shareNotPublicLayer:"Pelo menos uma camada nesta cena 3D n\u00e3o \u00e9 p\u00fablica. Pessoas podem n\u00e3o ser capazes de ver todas as camadas.",changeShareSettings:"Alterar Defini\u00e7\u00f5es de Partilha"},underground:{seeThroughGround:"Visualizar atrav\u00e9s do ch\u00e3o"},basemapGallery:{SRMismatch:"Refer\u00eancia espacial \u00e9 incompat\u00edvel com a cena",SRMismatchGlobal:"Refer\u00eancia espacial n\u00e3o \u00e9 suportada com cenas globais",TSMismatch:"Esquema de mosaico \u00e9 incompat\u00edvel com a cena",
TilingScheme:"Esquema de mosaico n\u00e3o adere aos Esquemas de Mosaico ArcGIS Online.",tilingSchemePowerOfTwo:"Esquema de mosaico incompat\u00edvel: cada escala deve ser exactamente metade da escala do n\u00edvel anterior.",tilingSchemeTileSize:"Esquema de mosaico incompat\u00edvel: apenas t\u00edtulos com largura e comprimento 256 s\u00e3o suportados.",tiledMapServiceSRGCS:"Camadas de Mapa de Mosaicos em sistemas de coordenadas geogr\u00e1ficas n\u00e3o s\u00e3o suportadas.",tiledMapServicesMinVersion:"As Camadas de Mapa de Mosaicos anteriores a 10.2.2 n\u00e3o s\u00e3o suportadas.",
basemapLayerTypeWMS:"OGC Web Map Service (WMS) n\u00e3o \u00e9 suportada como mapa base.",basemapLayerTypeWMTS:"OGC Web Tile Map Service (WMTS) n\u00e3o \u00e9 suportada como mapa base.",basemapLayerTypeWTL:"Web Tile Layer n\u00e3o \u00e9 suportada como mapa base.",basemapLayerTypeDMS:"Camada de Servi\u00e7o de Mapa Din\u00e2mico n\u00e3o \u00e9 suportado como mapa base.",basemapLayerTypeIS:"Camada de Servi\u00e7o de Imagem n\u00e3o \u00e9 suportada como mapa base.",noBasemap:"Sem mapa base"},compass:{compass:"B\u00fassola"}});