// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/_GalleryFiltersMixin",["dojo/_base/declare"],function(){return{rootNodes:{favorites:{all:{},maps:{},layers:{},scenes:{},applications:{},tools:{},files:{}},organization:{all:{},maps:{},layers:{},scenes:{},applications:{},tools:{},files:{}},maps:{all:{},imagery:{tags:["imagery"]},basemaps:{tags:["basemap"]},historical:{tags:["historical"]},demographics:{tags:"demographics"},landscape:{tags:"landscape"},earth:{tags:["earth observations"]},urban:{tags:["urban"]},transportation:{tags:["transportation"]},
boundariesplaces:{tags:["boundaries"]},storymaps:{tags:["story maps"]},scenes:{tags:["scenes"]}},apps:{readytouse:{typekeywords:["Ready To Use"]},configurable:{typekeywords:["Configurable"]},appbuilder:{typekeywords:["Web AppBuilder for ArcGIS"]}}},imagery:{basemapimagery:{parent:"imagery"},multiimagery:{parent:"imagery"},temporalimagery:{parent:"imagery"},eventimagery:{parent:"imagery"}},basemaps:{esribasemaps:{parent:"basemaps"},partnerbasemaps:{parent:"basemaps"},userbasemaps:{parent:"basemaps"}},
demographics:{income:{parent:"demographics"},spending:{parent:"demographics"},population:{parent:"demographics"},segmentation:{parent:"demographics"},business:{parent:"demographics"},atrisk:{parent:"demographics"}},landscape:{climate:{parent:"landscape"},ecology:{parent:"landscape"},biology:{parent:"landscape"},disturbance:{parent:"landscape"},elevation:{parent:"landscape"},landcover:{parent:"landscape"},hazards:{parent:"landscape"},oceans:{parent:"landscape"},soils:{parent:"landscape"},subsurface:{parent:"landscape"},
water:{parent:"landscape"}},urban:{threed:{parent:"urban"},movement:{parent:"urban"},parcels:{parent:"urban"},people:{parent:"urban"},planning:{parent:"urban"},publicFilter:{parent:"urban"},work:{parent:"urban"}},boundariesplaces:{boundaries:{parent:"boundariesplaces"},places:{parent:"boundariesplaces"}},maps:{webmaps:{parent:"maps"},mapfiles:{parent:"maps"}},layers:{weblayers:{parent:"layers"},layerfiles:{parent:"layers"}},applications:{web:{parent:"applications"},mobile:{parent:"applications"},
desktop:{parent:"applications"}},weblayers:{features:{parent:"weblayers"},tiles:{parent:"weblayers"},mapimage:{parent:"weblayers"},imagery:{parent:"weblayers"},tables:{parent:"weblayers"}},readytouse:{web:{parent:"readytouse"},ios:{parent:"readytouse"},android:{parent:"readytouse"},windows:{parent:"readytouse"},desktop:{parent:"readytouse"}},files:{document:{parent:"files"},image:{parent:"files"},pdf:{parent:"files"}},tools:{locators:{parent:"tools"},geodatabase:{parent:"tools"},geometric:{parent:"tools"},
geoprocessing:{parent:"tools"},network:{parent:"tools"}},"imagery-root":{tags:["imagery"]},"imagery-basemapimagery":{tags:["baseimagery"]},"imagery-multiimagery":{tags:["multispectral"]},"imagery-temporalimagery":{tags:["temporal"]},"imagery-eventimagery":{tags:["event_imagery"]},"basemaps-root":{tags:["basemap"]},"basemaps-esribasemaps":{tags:["esri_basemap"]},"basemaps-partnerbasemaps":{tags:["partner_basemap"]},"basemaps-userbasemaps":{tags:["user_basemap"]},"historical-root":{tags:["historical"]},
"demographics-root":{tags:["demographics"]},"demographics-income":{tags:["income"]},"demographics-spending":{tags:["spending","behaviors"]},"demographics-population":{tags:["population","housing"]},"demographics-segmentation":{tags:["segmentation"]},"demographics-business":{tags:["business","jobs"]},"demographics-atrisk":{tags:["at risk","poverty"]},"landscape-root":{tags:["landscape"]},"landscape-climate":{tags:["climate","weather"]},"landscape-ecology":{tags:["ecology"]},"landscape-biology":{tags:["species"]},
"landscape-disturbance":{tags:["disturbance"]},"landscape-elevation":{tags:["elevation"]},"landscape-landcover":{tags:["landcover"]},"landscape-hazards":{tags:["hazards"]},"landscape-oceans":{tags:["oceans"]},"landscape-soils":{tags:["soils","geology"]},"landscape-subsurface":{tags:["subsurface"]},"landscape-water":{tags:["water"]},"earth-root":{tags:["earth observations"]},"urban-root":{tags:["urban"]},"urban-threed":{tags:["3D"]},"urban-movement":{tags:["movement"]},"urban-parcels":{tags:["parcels"]},
"urban-people":{tags:["people"]},"urban-planning":{tags:["planning"]},"urban-publicFilter":{tags:["public"]},"urban-work":{tags:["work"]},"transportation-root":{tags:["transportation"]},"boundariesplaces-root":{tags:["boundaries"]},"boundariesplaces-boundaries":{tags:["boundaries"]},"boundariesplaces-places":{tags:["places"]},"storymaps-root":{tags:["story maps"]},"scenes-root":{tags:["scenes"]},"readytouse-root":{typekeywords:["Ready To Use"]},"configurable-root":{typekeywords:["Configurable"]},
"appbuilder-root":{typekeywords:["Web AppBuilder for ArcGIS"]},"readytouse-web":{typekeywords:["Web Mapping Application"]},"readytouse-ios":{typekeywords:["ArcGIS for iPhone"]},"readytouse-android":{typekeywords:["ArcGIS for Android"]},"readytouse-windows":{typekeywords:["ArcGIS for Windows Phone"]},"readytouse-desktop":{typekeywords:["Application","Desktop Application"]},mappings:{"demographics-behaviors":{mappedCategory:"demographics-spending"}}}});