// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/BasemapGalleryGrid",["dijit","dojo","dojox","dojo/require!arcgisonline/sharing/geow/Content,arcgisonline/sharing/geow/Community,arcgisonline/sharing/dijit/BasemapGallery,arcgisonline/sharing/util"],function(c,a,e){a.provide("arcgisonline.sharing.dijit.BasemapGalleryGrid");a.require("arcgisonline.sharing.geow.Content");a.require("arcgisonline.sharing.geow.Community");a.require("arcgisonline.sharing.dijit.BasemapGallery");a.require("arcgisonline.sharing.util");a.declare("arcgisonline.sharing.dijit.BasemapGalleryGrid",
[c._Widget,c._Templated,c._KeyNavContainer],{_gallery:null,groupId:null,groupQuery:null,sortField:null,sortOrder:null,lastOpenBlurCall:null,templateString:'\x3cdiv\x3e\r\n    \x3cdiv\x3e\r\n        \x3cdiv class\x3d"esriFloatLeading esriLeadingMargin1" style\x3d"padding-top:8px;"\x3e\r\n            \x3cspan id\x3d"basemap-galleryLabel" style\x3d"font-weight: bold;"\x3e\r\n            ${i18n.selectBasemap}\r\n            \x3c/span\x3e\r\n        \x3c/div\x3e\r\n        \x3cdiv class\x3d"esriFloatTrailing esriTrailingMargin1" style\x3d"padding-top:5px;"\x3e\r\n            \x3cA id\x3d"basemap-galleryClose" href\x3d"JavaScript:void(0);" title\x3d"${i18n.close}" alt\x3d"${i18n.close}"\x3e\r\n            \x3c/A\x3e\r\n        \x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv style\x3d"clear:both;"\x3e\x3c/div\x3e\r\n    \x3cdiv style\x3d"padding-right:10px; padding-left:10px;"\x3e\x3chr/\x3e\x3c/div\x3e\r\n    \x3cdiv id\x3d"containerNode"\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e',
i18n:null,postMixInProperties:function(){this.inherited(arguments);this.i18n=a.i18n.getLocalization("arcgisonline","arcgisonline").common;a.mixin(this.i18n,a.i18n.getLocalization("arcgisonline","arcgisonline").basemapGalleryGrid)},postCreate:function(){this.inherited(arguments);a.connect(a.byId("basemap-galleryClose"),"onclick",this,"close")},onBlur:function(a){this.inherited(arguments);if(!esri.isTouchEnabled){var c=5E3;this.lastOpenBlurCall&&(c=(new Date).getTime()-this.lastOpenBlurCall.getTime());
550>c||(this.lastOpenBlurCall=new Date,this.hide())}},open:function(){var b=5E3;this.lastOpenBlurCall&&(b=(new Date).getTime()-this.lastOpenBlurCall.getTime());550>b||(this.lastOpenBlurCall=new Date,"block"===a.style(a.byId("basemap-gallery"),"display")?this.hide():(null===this._gallery?this.init():a.style(a.byId("basemap-gallery"),"display","block"),setTimeout(function(){c.focus.focus(a.byId("basemap-gallery"))},0)))},close:function(){esri.isTouchEnabled?this.hide():setTimeout(function(){c.focus.focus(c.byId("webmap-basemap").domNode)},
0)},hide:function(b){a.style(a.byId("basemap-gallery"),"display","none");setTimeout(function(){c.byId("webmap-basemap").set("checked",!1)},500)},init:function(){this._gallery=new arcgisonline.sharing.dijit.BasemapGallery({id:this.id+"_Gallery",showNodeLabels:!0},a.create("div",null,this.domNode));this._gallery.startup();var b=a.coords(a.byId("webmap-basemap"));esriGeowConfig.isRightToLeft?a.style(a.byId("basemap-gallery"),"left",b.x+b.w-382+"px"):a.style(a.byId("basemap-gallery"),"left",b.x-4+"px");
a.style(a.byId("basemap-gallery"),"top",b.y+b.h+"px");this.groupQuery&&0<this.groupQuery.length&&arcgisonline.sharing.geow.Community.searchGroups(this.groupQuery,a.hitch(this,this._handleGetGroup),a.hitch(this,this._handleGetGroup));a.byId("basemap-gallery").tabIndex=0;a.style(a.byId("basemap-gallery"),"display","block")},_getItems:function(){var b={q:"group:"+this.groupId+' AND (type:"web map" -type:"web mapping application")',sortField:this.sortField,num:"50"};this.sortOrder&&(b.sortOrder=this.sortOrder);
arcgisonline.sharing.geow.Content.search(esriGeowConfig.restBaseUrl+"search",b,a.hitch(this,this._handleGetItems),a.hitch(this,this._handleGetItems))},_setGroupIdAttr:function(a){null===a||0===a.length||(this.groupId=a,this._getItems())},_handleGetItems:function(b,c){if(b.results&&0<b.results.length){var d=b.results;esri.isDefined(this.sortOrder)||(d=d.sort(function(a,b){var c=a.title.toLowerCase(),d=b.title.toLowerCase();return c==d?0:c<d?-1:1}));a.attr(this._gallery,"items",d)}},_handleGetGroup:function(a,
c){a&&0<a.total?(a.results[0].sortField&&(this.sortField=a.results[0].sortField),this.sortOrder=a.results[0].sortOrder?a.results[0].sortOrder:null,this._setGroupIdAttr(a.results[0].id)):console.error(this.i18n.basemapsNotExist)}})});