// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/BasemapGallery",["dijit","dojo","dojox","dojo/require!dijit/_Widget,dijit/_Templated,dojo/NodeList-fx,dijit/layout/ContentPane,arcgisonline/sharing/util,arcgisonline/sharing/geow/QueryReadStore"],function(e,a,f){a.provide("arcgisonline.sharing.dijit.BasemapGallery");a.require("dijit._Widget");a.require("dijit._Templated");a.require("dojo.NodeList-fx");a.require("dijit.layout.ContentPane");a.require("arcgisonline.sharing.util");a.require("arcgisonline.sharing.geow.QueryReadStore");
a.declare("arcgisonline.sharing.dijit.BasemapGallery",[e._Widget,e._Templated],{widgetsInTemplate:!0,templateString:'\x3cdiv dojoAttachPoint\x3d"containerNode" style\x3d"clear:both; min-height:100px;"\x3e\r\n  \x3cdiv class\x3d"galleryBackground"\x3e\r\n    \x3cdiv dojoAttachPoint\x3d"flowContainer"\x3e\r\n      \x3cdiv class\x3d"throb-loading"\x3e\x3cdiv class\x3d"throb-loading-text"\x3e${i18n.loadingShort}\x3c/div\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e',showNodeLabels:!0,
fadeOutOtherNodes:!0,animFadeOut:!0,unfocusedOpacity:0.5,flowContainer:null,nodeClass:"galleryNode",thumbClass:"galleryThumbnail",messageClass:"galleryMessage",_galleryFadeIn:null,_galleryFadeOut:null,_galleryFadeOutTotal:null,noResultsMessage:null,items:null,postMixInProperties:function(){this.inherited(arguments);this.i18n=a.i18n.getLocalization("arcgisonline","arcgisonline").arcGISServerServices},postCreate:function(){this._galleryFadeIn=a.animateProperty({node:this.flowContainer,properties:{opacity:1}});
this._galleryFadeOut=a.animateProperty({node:this.flowContainer,properties:{opacity:this.unfocusedOpacity}});this._galleryFadeOutTotal=a.animateProperty({node:this.flowContainer,properties:{opacity:0}})},_setItemsAttr:function(b){this.items=this.includeNode?a.filter(b,this.includeNode):b;this._loadItems(b)},_loadItems:function(b){this._galleryFadeIn.stop();this._galleryFadeOut.stop();this._galleryFadeOutTotal.onEnd=a.hitch(this,function(b){a.empty(this.flowContainer);0<b.length?(a.forEach(b,a.hitch(this,
function(a,b){if(esriGeowConfig.self.bingKey||!(-1<a.title.indexOf("Bing")))a.id||(a.id=b),this.flowContainer.appendChild(this._buildNodeLayout(a))})),a.create("br",{style:{clear:"both"}},this.flowContainer)):a.create("span",{innerHTML:this.noResultsMessage,"class":this.messageClass},this.flowContainer);this._galleryFadeIn.play();this._galleryFadeOut.onEnd=null},b);this._galleryFadeOutTotal.play()},_buildNodeLayout:function(b){var c=a.create("div",{id:"galleryNode_"+b.id,"class":this.nodeClass});
a.addClass(c,"mini");var d=a.create("a",{href:"#"},c);a.connect(d,"onclick",a.hitch(this,"onNodeClick",b));a.create("img",{"class":this.thumbClass,src:b.thumbnail?this._getThumbailUrl(b):arcgisonline.sharing.util.relativeToExplicitUrl("images/transparent.gif")},d);this.showNodeLabels&&(d=a.create("div",{"class":"galleryLabelContainer"},c),b=b.title||"",a.create("span",{innerHTML:b,alt:b,title:b},d));return c},_getThumbailUrl:function(a){var c=arcgisonline.sharing.util.getToken();return esriGeowConfig.restBaseUrl+
"content/items/"+a.id+"/info/"+a.thumbnail+(c?"?token\x3d"+c:"")},onNodeClick:function(a,c){c.preventDefault();arcgisonline.map.save_open.switchBaseMapWithWebMap(a);e.byId("basemap-gallery").close()}})});