// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/GroupMembershipRequestsGrid",["dijit","dojo","dojox","dojo/require!dijit/_Widget,dijit/_Templated,dojox/grid/DataGrid,dojox/rpc/Service,dojo/rpc/JsonService,dijit/Toolbar,arcgisonline/sharing/geow/MemberReadStore,arcgisonline/sharing/dijit/ProfilePopup"],function(g,a,h){a.provide("arcgisonline.sharing.dijit.GroupMembershipRequestsGrid");a.require("dijit._Widget");a.require("dijit._Templated");a.require("dojox.grid.DataGrid");a.require("dojox.rpc.Service");a.require("dojo.rpc.JsonService");
a.require("dijit.Toolbar");a.require("arcgisonline.sharing.geow.MemberReadStore");a.require("arcgisonline.sharing.dijit.ProfilePopup");a.declare("arcgisonline.sharing.dijit.GroupMembershipRequestsGrid",[g._Widget,g._Templated],{widgetsInTemplate:!0,groupId:null,initialized:!1,templateString:' \x3cdiv id\x3d"esriGroupMambershipRequestsGrid" style\x3d"width: 100%; height: 100%; margin:auto;"\x3e\r\n    \x3ctable dojotype\x3d"dojox.grid.DataGrid" jsid\x3d"grid" id\x3d"groupMembershipRequestsNode" rowsperpage\x3d"10"\r\n        delayscroll\x3d"true" class\x3d"esriGrid" style\x3d"height:100%; width:100%;"\x3e\r\n    \x3cthead\x3e\r\n        \x3ctr\x3e\r\n\t\t\t\x3cth get\x3d"arcgisonline.sharing.dijit.GroupMembershipRequestsGrid.formatters.name" formatter\x3d"arcgisonline.sharing.util.fix" width\x3d"30%" name\x3d"Name"\x3ex\x3c/th\x3e\r\n\t\t\t\x3cth get\x3d"arcgisonline.sharing.dijit.GroupMembershipRequestsGrid.formatters.received" formatter\x3d"arcgisonline.sharing.util.fix" width\x3d"30%" name\x3d"Received"\x3ex\x3c/th\x3e\r\n\t\t\t\x3cth get\x3d"arcgisonline.sharing.dijit.GroupMembershipRequestsGrid.formatters.yourResponse" formatter\x3d"arcgisonline.sharing.util.fix" width\x3d"40%" name\x3d"Your Response"\x3ex\x3c/th\x3e\r\n        \x3c/tr\x3e\r\n    \x3c/thead\x3e\r\n    \x3c/table\x3e\r\n \x3c/div\x3e   \r\n',
_eventConnections:[],i18n:null,postMixInProperties:function(){this.inherited(arguments);this.i18n=a.i18n.getLocalization("arcgisonline","arcgisonline").common;a.mixin(this.i18n,a.i18n.getLocalization("arcgisonline","arcgisonline").groupMembershipRequestsGrid)},postCreate:function(){a.subscribe("onApplicationAccept",this.refreshGrid);a.subscribe("onApplicationDecline",this.refreshGrid);this._applyGridPatches();if(esri.isTouchEnabled){var c=esri.setScrollable(grid.views.views[0].scrollboxNode);this._eventConnections.push(c[0],
c[1])}},_applyGridPatches:function(){var c=grid.adaptWidth;grid.adaptWidth=function(){for(var d=this.views.views,e=0,b;b=d[e];e++){a.style(b.headerNode,"display","block");var f=b.adaptWidth;b.adaptWidth=function(){this.flexCells&&null==this.headerContentNode.firstChild||f.apply(this,arguments)}}c.apply(this,arguments);for(e=0;b=d[e];e++)a.style(b.headerNode,"display","none")}},loadGrid:function(c){this.groupId=c;a.byId("membership-groupId").value=this.groupId;c=new arcgisonline.sharing.geow.MemberReadStore;
c.url=esriGeowConfig.restBaseUrl+"community/groups/"+this.groupId+"/applications";grid.noDataMessage="\x3cspan style\x3d'font-size:1.2em;color:#7a7979;'\x3e"+this.i18n.noMembershipRequests+"\x3c/span\x3e";grid.setStore(c)},onAppCount:function(c){0<c?(a.style(a.byId("membership-requests-has_no_requests"),"display","none"),a.style(a.byId("membership-requests-has_requests"),"display","block")):(a.style(a.byId("membership-requests-has_requests"),"display","none"),a.style(a.byId("membership-requests-has_no_requests"),
"display","block"))},refreshGrid:function(){grid.setQuery()},destroy:function(){this.inherited(arguments);a.forEach(this._eventConnections,a.disconnect)}});arcgisonline.sharing.dijit.GroupMembershipRequestsGrid.formatters={i18n:null,name:function(a,d){return!d?this.defaultValue:'\x3cspan id\x3d"esriMemberInfo" class\x3d"esriItemLinks"\x3e\x3ca href\x3d"#" onclick\x3d"arcgisonline.sharing.dijit.ProfilePopup.prototype.statics.getInstance().showProfile(\''+d.i.name+"', this);\"\x3e"+d.i.fullname+"\x3c/span\x3e"},
received:function(c,d){if(!d)return this.defaultValue;var e='\x3cspan id\x3d"esriMemberInfo"\x3e',b=d.i.received;-1<b&&(b=new Date(parseFloat(b)),e+=a.date.locale.format(b,{selector:"date",formatLength:"long"}));return e+"\x3c/span\x3e"},yourResponse:function(c,d){if(!d)return this.defaultValue;this.i18n=a.i18n.getLocalization("arcgisonline","arcgisonline").common;a.mixin(this.i18n,a.i18n.getLocalization("arcgisonline","arcgisonline").groupMembershipRequestsGrid);var e=a.byId("membership-groupId").value,
b="",f=d.i.name,b='\x3cdiv class\x3d"list-links" style\x3d"padding-left:20px;"\x3e\x3cspan class\x3d"approveApplication"\x3e\x3c/span\x3e\x3ca href\x3d"JavaScript:arcgisonline.sharing.geow.Group.acceptApplication(\''+e+"','"+f+"')\"\x3e"+this.i18n.approve+"\x3c/a\x3e";return b+='  \x3cspan class\x3d"declineApplication"\x3e\x3c/span\x3e\x3ca href\x3d"JavaScript:arcgisonline.sharing.geow.Group.declineApplication(\''+e+"','"+f+"')\"'\x3e"+this.i18n.decline+"\x3c/a\x3e\x3c/div\x3e"}}});