// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/ItemRating",["dijit","dojo","dojox","dojo/require!arcgisonline/sharing/util,arcgisonline/sharing/geow/Content,dojox/form/Rating"],function(e,b,d){b.provide("arcgisonline.sharing.dijit.ItemRating");b.require("arcgisonline.sharing.util");b.require("arcgisonline.sharing.geow.Content");b.require("dojox.form.Rating");b.declare("arcgisonline.sharing.dijit.ItemRating",d.form.Rating,{util:arcgisonline.sharing.util,content:arcgisonline.sharing.geow.Content,numStars:5,item:null,
isOwned:!1,isSignedIn:!1,labelNodeClass:"itemRatingLabel",_numRatings:-1,_connections:[],_disabled:!1,_currentStarValue:0,constructor:function(a){null==a.item&&console.error("error while initializing item rating widget.  item cannot be null.")},postMixInProperties:function(){this.inherited(arguments);this.i18n=b.i18n.getLocalization("arcgisonline","arcgisonline").common;b.mixin(this.i18n,b.i18n.getLocalization("arcgisonline","arcgisonline").ratings);this._helperSummary=this.i18n.helperSummary},postCreate:function(){this.inherited(arguments);
var a=this.util.getUser();if(a)this.isSignedIn=!0,this._loadConnections();else{var b="";-1==esriGeowConfig.signin.indexOf("http")&&(b=esriGeowConfig.baseUrl,!1!==esriGeowConfig.useSSL&&(b=b.replace("http:","https:")));this.setLabel("\x3cspan class\x3d'esriItemLinks'\x3e\x3ca href\x3d'"+b+esriGeowConfig.signin+"?returnUrl\x3d"+window.location.href+"'\x3e"+this.i18n.signIn+"\x3c/a\x3e "+this.i18n.toRate+".\x3c/span\x3e")}a&&a.email==this.item.owner&&(this.isOwned=!0);this.set("value",this.item.avgRating);
this._numRatings=this.item.numRatings},_loadConnections:function(){this._connections.push(b.connect(this,"onMouseOver",this,this.handle_mouseOver));this._connections.push(b.connect(this,"onMouseOut",this,this.handle_mouseOut))},_unloadConnections:function(){b.forEach(this._connections,b.disconnect);this._connections=[]},_setItemAttr:function(a){this.item=a;this.set("value",this.item.avgRating)},_setValueAttr:function(a){this.value=a=Math.round(a);this._renderStars(a)},_setDisabledAttr:function(a){this._disabled=
a;this.inherited(arguments);a?this._unloadConnections():this._loadConnections()},_renderStars:function(a,b){isNaN(a)||this.inherited(arguments)},_onMouse:function(a){if(this.isSignedIn){var c=+b.attr(a.target,"value");this.onMouseOver(a,c);this._renderStars(c,!0);this.isOwned||(a=this._hovering?b.attr(a.target,"value"):this.value,this._renderStars(a,this._hovering))}},handle_mouseOver:function(a,b){this._currentStarValue=b;this.isOwned?this.setLabel(this.i18n.cantRate,!0):1==b?this.setLabel(this.i18n.poor):
2==b?this.setLabel(this.i18n.fair):3==b?this.setLabel(this.i18n.average):4==b?this.setLabel(this.i18n.good):5==b&&this.setLabel(this.i18n.great)},handle_mouseOut:function(a){this._currentStarValue=0;window.setTimeout(b.hitch(this,this._clearLabel),100);this.set("value",this.item.avgRating)},onStarClick:function(a){!this._disabled&&(this.isSignedIn&&!this.isOwned)&&(a=+b.attr(a.target,"value"),this.set("value",a),this._renderStars(this.value),this.onChange(this.value),this.set("disabled",!0),this.content.addRating(this.item.id,
this.value,b.hitch(this,this.handle_ratingResponse),b.hitch(this,this.handle_ratingResponse)))},setLabel:function(a,c){b.query("."+this.labelNodeClass).forEach(function(c){c.innerHTML=a;b.style(c,"display","block")},this)},_clearLabel:function(){0===this._currentStarValue&&b.query("."+this.labelNodeClass).forEach(function(a){b.style(a,"display","none")},this)},handle_ratingResponse:function(a,c){if(a.success)this.content.getItem(this.item.id,b.hitch(this,this.handle_ratingResponse)),this.set("disabled",
!1);else if(a.numRatings)this.onRatingUpdate({numRatings:a.numRatings,avgRating:a.avgRating})},_onRatingUpdate:function(a){this._numRatings!=a.numRatings?this.setLabel(this.i18n.thanksForRating,!0):this.setLabel(this.i18n.ratingChanged,!0);this._numRatings=a.numRatings;this.set("value",a.avgRating)},onRatingUpdate:function(a){this._onRatingUpdate(a)}})});