// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
require({cache:{"url:arcgisonline/sharing/dijit/templates/PrintTemplates.html":'\x3cdiv\x3e\r\n  \x3cspan class\x3d"statusError" data-dojo-attach-point\x3d"_statusError"\x3e\x3c/span\x3e\r\n  \x3cbutton type\x3d"button" class\x3d"calcite tertiary small" data-dojo-type\x3d"dijit/form/Button"\r\n          data-dojo-attach-point\x3d"_createTemplate"\x3e${i18n.createTemplate}\x3c/button\x3e\r\n  \x3cbutton type\x3d"button" class\x3d"calcite transparent small" data-dojo-type\x3d"dijit/form/Button"\r\n          data-dojo-attach-point\x3d"_resetTemplate"\x3e${i18n.resetTemplates}\x3c/button\x3e\r\n  \x3cbr\x3e\x3cbr\x3e\r\n  \x3c!-- grid container added dynamically here --\x3e\r\n\x3c/div\x3e\r\n'}});
define("arcgisonline/sharing/dijit/PrintTemplates","require dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-attr dojo/dom-construct dojo/dom-style dojo/on dojo/topic dojo/Deferred dojo/store/Memory dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/form/Button dijit/Dialog dijit/Tooltip esri/request arcgisonline/sharing/dijit/Grid arcgisonline/sharing/dijit/dialog/PrintTemplateDlg arcgisonline/sharing/geow/Account arcgisonline/sharing/util dojo/i18n!arcgisonline/nls/arcgisonline dojo/text!arcgisonline/sharing/dijit/templates/PrintTemplates.html".split(" "),
function(y,z,k,K,v,n,p,t,w,A,B,C,D,E,L,F,M,G,N,H,I,q,x,J){return z("arcgisonline.sharing.dijit.PrintTemplates",[C,D,E],{declaredClass:"arcgisonline.sharing.dijit.PrintTemplates",baseClass:"esriPrintTemplates",basePath:y.toUrl("arcgisonline/sharing/dijit"),templateString:J,widgetsInTemplate:!0,formatPNG:"PNG32",formatPDF:"PDF",defaultLayout:{layout:"MAP_ONLY",format:"PNG32"},rowsPerPage:5,printTask:null,_setPrintTaskAttr:function(b){this._set("printTask",b);this._loadTemplateInfoFromPrintTask()},_getTemplatesAttr:function(){var b=
this._get("i18n"),a=this._grid.get("store").query(),c=[],d,e;for(e=0;e<a.length;e++)d=k.clone(a[e]),delete d.id,c.push(d);0===c.length&&(a=k.clone(this.defaultLayout),a.label=b.mapOnly,c.push(a));return c},postMixInProperties:function(){this.inherited(arguments);this._mixinI18N()},postCreate:function(){this.inherited(arguments);this._createConnections();this._printTemplateDlg=H.prototype.statics.getInstance()},startup:function(){this.inherited(arguments);this._initUI()},refresh:function(){this._grid&&
this._grid._started&&(this._grid._grid.resize(),this._grid._grid.refresh())},_mixinI18N:function(){var b={};k.mixin(b,x.common);k.mixin(b,x.printTemplates);this._set("i18n",b)},_createConnections:function(){this.own(this._createTemplate.on("click",k.hitch(this,this._createTemplateClick)),this._resetTemplate.on("click",k.hitch(this,this._resetTemplatesClick)))},_initUI:function(){var b=this;I.getSelf(function(a){b._set("printTask",a.helperServices.printTask||{});b._createTemplateGrid();b._createTooltipDialog()})},
_createTooltipDialog:function(){this._tooltipDialog=new F({style:{width:"315px",maxWidth:"315px",outline:"none"},content:""})},_createTemplateGrid:function(){this._grid=new arcgisonline.sharing.dijit.Grid({columns:this._createTemplateGridColumns(),id:"printTemplatesGrid",region:"center",noDataMessage:this._get("i18n").noTemplates,showLoadingMessage:!0,showHeader:!0,showFooter:!0,rowsPerPage:this.rowsPerPage,pagingLinks:!0,selectionMode:"none",store:this._createTemplateGridStore(),sort:[{attribute:"id",
descending:!1}]},n.create("div",null,this.domNode));this._grid.startup();this._grid.refresh();w.subscribe("printTemplate-add",k.hitch(this,this._templateAdded));w.subscribe("printTemplate-edit",k.hitch(this,this._templateAltered))},_setTemplateGridStore:function(b){this._grid.get("store")?(this._clearTemplateGridStore(),this._addDataToTemplateGridStore(b)):this._grid.set("store",this._createTemplateGridStore(b))},_addDataToTemplateGridStore:function(b){var a=this._grid.get("store"),c=a.query().length,
d;if(b&&0<b.length)for(d=0;d<b.length;d++)b[d].id=c+d,a.put(b[d])},_clearTemplateGridStore:function(){var b=this._grid.get("store"),a=b.query(),c;if(a&&0<a.length)for(c=0;c<a.length;c++)b.remove(a[c].id)},_createTemplateGridStore:function(b){return new B({identifier:"id",label:"label",data:b||[]})},_createTemplateGridColumns:function(){var b=this._get("i18n");return{move:{label:" ",sortable:!1,renderCell:k.hitch(this,function(a){var c=n.create("span"),d=q.relativeToExplicitUrl("js/arcgisonline/map/css/images/LayerUp16.png"),
e=q.relativeToExplicitUrl("js/arcgisonline/map/css/images/LayerDown16.png"),g=b.moveUp,h=b.moveDown;0!==a.id&&(d=n.create("img",{src:d,title:g,alt:g,className:"clickable"},c),this.own(t(d,"click",k.hitch(this,this._gridMoveUpClickHandler,a))));a.id<this._grid.store.query().length-1&&(e=n.create("img",{src:e,title:h,alt:h,className:"clickable"},c),this.own(t(e,"click",k.hitch(this,this._gridMoveDownClickHandler,a))));return c})},label:{label:b.templateName,sortable:!1,formatter:function(a){return'\x3cspan class\x3d"esriContentTypeName"\x3e'+
a+"\x3c/span\x3e"}},info:{label:"  ",sortable:!1,renderCell:k.hitch(this,function(a){var c=b.templateInfo,d=q.relativeToExplicitUrl("js/arcgisonline/css/images/info.png"),c=n.create("img",{src:d,title:c,alt:c,className:"clickable"});this.own(t(c,"click",k.hitch(this,this._gridInfoClickHandler,a)));return c})},alter:{label:"  ",sortable:!1,renderCell:k.hitch(this,function(a){var c=b.editTemplate,d=q.relativeToExplicitUrl("js/arcgisonline/css/images/edit.png"),c=n.create("img",{src:d,title:c,alt:c,
className:"clickable"});this.own(t(c,"click",k.hitch(this,this._gridEditClickHandler,a)));return c})},remove:{label:"  ",sortable:!1,renderCell:k.hitch(this,function(a){var c=b.deleteTemplate,d=q.relativeToExplicitUrl("images/delete_20x20.png"),c=n.create("img",{src:d,title:c,alt:c,className:"clickable"});this.own(t(c,"click",k.hitch(this,this._gridRemoveClickHandler,a)));return c})}}},_moveTemplate:function(b,a){var c=this._grid.get("store"),d=k.clone(c.query()),e,g,h;for(h=0;h<d.length;h++)c.remove(h);
g=a+1<this._grid._grid.rowsPerPage?1:Math.ceil((a+1)/this._grid._grid.rowsPerPage);d.splice(b.id,1);d.splice(a,0,b);for(h=0;h<d.length;h++)d[h].id=h,c.put(d[h]);e=this._grid._grid.on("dgrid-refresh-complete",function(a){a.grid._currentPage!==g&&a.grid.gotoPage(g);e.remove()});this.refresh()},_gridMoveUpClickHandler:function(b){this._moveTemplate(b,b.id-1)},_gridMoveDownClickHandler:function(b){this._moveTemplate(b,b.id+1)},_gridInfoClickHandler:function(b){var a=this._get("i18n"),c=b.description&&
0<b.description.length?b.description:a.info.noDescription,d=b.layoutOptions&&b.layoutOptions.legend&&!0===b.layoutOptions.legend,e=a.formats.image;b.format&&(b.format.toLowerCase()===this.formatPNG.toLowerCase()?e=a.formats.image:b.format.toLowerCase()===this.formatPDF.toLowerCase()&&(e=a.formats.pdf));a='\x3cdiv class\x3d"templateSummary"\x3e\x3cstrong\x3e'+a.info.descriptionLabel+"\x3c/strong\x3e\x3cp\x3e"+c+"\x3c/p\x3e\x3cstrong\x3e"+a.info.settingsLabel+'\x3c/strong\x3e\x3cdiv class\x3d"templateSummaryList"\x3e\x3cul class\x3d"templateSettingList"\x3e\x3cli\x3e'+
a.info.formatLabel+" "+e+"\x3c/li\x3e\x3cli\x3e"+a.info.layoutLabel+" "+b.layout+"\x3c/li\x3e\x3cli\x3e"+a.info.legendLabel+" "+(d?a.info.trueLabel:a.info.falseLabel)+"\x3c/li\x3e\x3c/ul\x3e\x3c/div\x3e\x3c/div\x3e";this._tooltipDialog.set("title",b.label);this._tooltipDialog.set("content",a);this._tooltipDialog.show();this._tooltipDialog.focus()},_gridEditClickHandler:function(b){this._printTemplateDlg.show(this._get("serviceInfo"),k.clone(b))},_gridRemoveClickHandler:function(b){var a=this._grid.get("store"),
c=dojo.clone(a.query()),d=this._grid._grid?this._grid._grid._currentPage:1,e,g;for(g=0;g<c.length;g++)a.remove(c[g].id);c.splice(b.id,1);for(g=0;g<c.length;g++)c[g].id=g,a.put(c[g]);b=Math.ceil(c.length/this.rowsPerPage);d>b&&(d=b);e=this._grid._grid.on("dgrid-refresh-complete",function(a){a.grid._currentPage!==d&&0<c.length&&a.grid.gotoPage(d);e.remove()});this._grid._grid.refresh()},_templateAdded:function(b){var a=this._grid.get("store"),c=this._grid._grid?this._grid._grid._currentPage:1,d,e;b.id=
a.query().length;a.put(b);d=this._grid._grid.on("dgrid-refresh-complete",function(a){e=Math.ceil(a.grid._total/a.grid.rowsPerPage);(c!==e||1!==c)&&a.grid.gotoPage(e);d.remove()});this._grid._grid.refresh()},_templateAltered:function(b){var a=this._grid.get("store"),c=this._grid._grid?this._grid._grid._currentPage:1,d,a=a.get(b.id);a.label=b.label;a.description=b.description;a.format=b.format;a.layout=b.layout;a.layoutOptions?a.layoutOptions.legend=b.layoutOptions.legend:a.layoutOptions=b.layoutOptions;
d=this._grid._grid.on("dgrid-refresh-complete",function(a){a.grid._currentPage!==c&&a.grid.gotoPage(c);d.remove()});this._grid._grid.refresh()},_createTemplateClick:function(b){b&&b.preventDefault();this._printTemplateDlg.show(this._get("serviceInfo"))},_resetTemplatesClick:function(b){b&&b.preventDefault();this._loadTemplateInfoFromPrintTask(!0)},_loadTemplateInfoFromPrintTask:function(b){var a=this,c=this._get("printTask"),d=this._get("i18n"),e=[],g,h,n,q,t,s,r,f,l;c&&c.url&&0<c.url.length?a._loadDataFromService().then(function(m){a._clearErrorMessage();
if(b){var u=k.clone(a._grid.get("store").query()),p=[];a._clearTemplateGridStore();if(m&&m.parameters&&0<m.parameters.length){n=a.defaultLayout.format;for(f=0;f<m.parameters.length;f++)if(g=m.parameters[f],"Layout_Template"===g.name){q=g.defaultValue;for(l=0;l<g.choiceList.length;l++)s=g.choiceList[l],s===q&&(t=l),r={label:s,format:n,layout:s},s!==a.defaultLayout.layout&&(r.layoutOptions={legend:!1}),e.push(r);break}}else e.push({label:d.mapOnly,format:a.defaultLayout.format,layout:a.defaultLayout.layout});
for(f=0;f<u.length;f++){m=!1;for(l=0;l<e.length;l++)if(u[f].layout===e[l].layout){m=!0;break}m||p.push(f)}for(f=p.length-1;0<=f;f--)u.splice(p[f],1);for(f=0;f<e.length;f++){m=!1;for(l=0;l<u.length;l++)if(e[f].layout===u[l].layout){m=!0;break}m||u.push(k.clone(e[f]))}for(f=0;f<u.length;f++)u[f].id=f;a._grid.set("store",a._setTemplateGridStore(u));a.refresh()}else if(c.templates&&0<c.templates.length){h=k.clone(c.templates);for(f=0;f<h.length;f++)h.id=f;a._grid.set("store",a._setTemplateGridStore(h));
a._grid.refresh()}else{h=[];if(m&&m.parameters&&0<m.parameters.length){n=a.defaultLayout.format;for(f=0;f<m.parameters.length;f++)if(g=m.parameters[f],"Layout_Template"===g.name){q=g.defaultValue;for(l=0;l<g.choiceList.length;l++)s=g.choiceList[l],s===q&&(t=l),r={label:s,format:n,layout:s},s!==a.defaultLayout.layout&&(r.layoutOptions={legend:!1}),e.push(r);break}r=e.splice(t,1)[0];r.id=0;h.push(r);for(f=0;f<e.length;f++)r=e[f],r.id=f+1,h.push(r)}else h.push({id:0,label:d.mapOnly,format:a.defaultLayout.format,
layout:a.defaultLayout.layout});a._grid.set("store",a._setTemplateGridStore(h));a.refresh()}},function(){a._set("serviceInfo",null);p.set(a._createTemplate.domNode,"display","none");p.set(a._resetTemplate.domNode,"display","none");p.set(a._grid.domNode,"display","none");v.set(a._statusError,"innerHTML",a.i18n.unreachableService);p.set(a._statusError,"display","");a.refresh()}):(a._set("serviceInfo",null),a._setTemplateGridStore([]))},_clearErrorMessage:function(){p.set(this._statusError,"display",
"none");v.set(this._statusError,"innerHTML","");p.set(this._createTemplate.domNode,"display","");p.set(this._resetTemplate.domNode,"display","");p.set(this._grid.domNode,"display","")},_isThroughSecureProxy:function(b){b=(b||"").toLowerCase();return 0<b.length&&-1<b.indexOf("/sharing/servers/")&&-1<b.indexOf("/rest/services/")},_loadDataFromService:function(){var b=this,a=new A,c=b._get("printTask").url||"",d=b._isThroughSecureProxy(c),e=q.isPortal()&&q.onFederatedServer(c);G({url:c,content:{f:"json"},
timeout:5E3,callbackParamName:"callback"},{disableIdentityLookup:!d&&!e}).then(function(c){b._set("serviceInfo",c);a.resolve(c)},function(b){console.log("unable to load service info",b);a.reject(b)});return a.promise}})});