// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/ProfilePopup",["dijit","dojo","dojox","dojo/require!arcgisonline/sharing/dijit/views,arcgisonline/sharing/geow/Community,dijit/layout/ContentPane"],function(e,a,f){a.provide("arcgisonline.sharing.dijit.ProfilePopup");a.require("arcgisonline.sharing.dijit.views");a.require("arcgisonline.sharing.geow.Community");a.require("dijit.layout.ContentPane");a.declare("arcgisonline.sharing.dijit.ProfilePopup",e.layout.ContentPane,{"class":"profilePopup",_lastTrigger:null,_resizeConnect:null,
_blurConnect:null,_profileContentPane:null,animateShowHide:!0,fadeDuration:300,statics:{cache:[],_instance:null,getInstance:function(){null===this._instance&&(this._instance=new arcgisonline.sharing.dijit.ProfilePopup,this._instance.startup());return this._instance},showProfilePopup:function(b){var c=arcgisonline.sharing.dijit.ProfilePopup.prototype.statics.getInstance();null!==c&&c.showProfile(a.attr(b.currentTarget,"owner"),b.currentTarget)}},postCreate:function(){this.inherited(arguments);a.style(this.domNode,
{position:"absolute",top:"-1000px",left:"-1000px",opacity:0});this.fadeIn=a.fadeIn({node:this.domNode,duration:this.fadeDuration,onEnd:function(){e.focus(this.node)}});this.fadeOut=a.fadeOut({node:this.domNode,duration:this.fadeDuration,onEnd:a.hitch(this,"_afterFade")})},startup:function(){this.inherited(arguments);var b=a.create("div",{style:{position:"relative",top:0,left:0}},this.domNode);this._profileContentPane=new e.layout.ContentPane;this._profileContentPane.placeAt(b);b=a.create("div",{"class":"dijitDialogCloseIcon",
style:{position:"absolute",top:"-5px"}},b);a.style(b,esriGeowConfig.isRightToLeft?{left:"-5px"}:{right:"-5px"});a.connect(b,"onclick",this,this.hide)},showProfile:function(b,c){this._lastTrigger=c;var d=arcgisonline.sharing.dijit.ProfilePopup.prototype.statics.cache[b];d&&null!==d?(this._profileContentPane.set("content",d),d=arcgisonline.sharing.dijit.views.profile.medium(d,{showThumb:!0,showProfilePopup:!0,align:"left"}),this._placeNextTo(d,c)):(arcgisonline.sharing.geow.Community.getProfile(b,a.hitch(this,
this._handleGetProfile),a.hitch(this,this._handleGetProfile)),this._profileContentPane.set("content",a.create("span",{innerHTML:"loading..."})))},showProfileFromPopup:function(b,c){a.style(this.domNode,{zIndex:1E3,opacity:1});this.showProfile(b,c)},_handleGetProfile:function(a,c){if(a){var d=arcgisonline.sharing.dijit.views.profile.medium(a,{showThumb:!0,showProfilePopup:!0,align:"left"});arcgisonline.sharing.dijit.ProfilePopup.prototype.statics.cache[a.username]=a;this._placeNextTo(d,this._lastTrigger)}},
_placeNextTo:function(a,c){e.placeOnScreenAroundNode(this.domNode,c,esriGeowConfig.isRightToLeft?{BR:"TR",BL:"TL",TR:"BR",TL:"BL"}:{BL:"TL",BR:"TR",TL:"BL",TR:"BR"});this._profileContentPane.set("content",a);this.show()},_afterFade:function(){a.style(this.domNode,{top:"-1000px",left:"-1000px"})},show:function(b){this.isShowing=!0;this.animateShowHide?(this.fadeOut.stop(),this.fadeIn.play()):(a.style(this.domNode,"display","block"),e.focus(this.domNode));this._clearConnects();this._resizeConnect=a.connect(window,
"onresize",this,this.hide)},hide:function(){this._clearConnects();this.animateShowHide?(this.fadeIn.stop(),this.fadeOut.play()):a.style(this.domNode,"display","none")},_clearConnects:function(){null!==this._resizeConnect&&(a.disconnect(this._resizeConnect),this._resizeConnect=null);null!==this._blurConnect&&(a.disconnect(this._blurConnect),this._blurConnect=null)}})});