// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/RendererGrid",["dijit","dojo","dojox","dojo/require!dijit/_Widget,dgrid/extensions/DnD,dojo/dnd/Source"],function(n,a,p){a.provide("arcgisonline.sharing.dijit.RendererGrid");a.require("dijit._Widget");a.require("dgrid.extensions.DnD");a.require("dojo.dnd.Source");a.declare("arcgisonline.sharing.dijit.RendererGrid",[n._Widget],{i18n:null,id:"",grid:null,baseClass:"esriAGORendererGrid",lastDefaultLabel:null,lastDefaultSymbol:null,ordersList:null,didDragFromSource:!1,
constructor:function(a,c){null!=a&&(a.id&&(this.id=a.id),a.renderer&&(this.renderer=a.renderer),a.style&&(this.style=a.style),a.onSymbolClick&&(this.onSymbolClick=a.onSymbolClick),a.onLabelClick&&(this.onLabelClick=a.onLabelClick),a.datePattern&&(this.datePattern=a.datePattern),a.defaultSymbol&&(this.defaultSymbol=a.defaultSymbol),a.backgroundSymbol&&(this.backgroundSymbol=a.backgroundSymbol))},postMixInProperties:function(){this.inherited(arguments);this.i18n=a.i18n.getLocalization("arcgisonline",
"arcgisonline").common;a.mixin(this.i18n,a.i18n.getLocalization("arcgisonline","arcgisonline").rendererPanel)},postCreate:function(){this.createGrid()},destroy:function(){this.onRendererItemChangeHandler&&a.unsubscribe(this.onRendererItemChangeHandler);this.grid&&(delete this.store,this.grid.destroy(),delete this.grid);this.inherited(arguments)},hide:function(){},updateRenderer:function(a){this.renderer=a;this.createGrid()},createGrid:function(){this.grid&&(delete this.store,this.grid.destroy(),delete this.grid);
a.byId(this.id+"_rendererGrid")||a.create("div",{id:this.id+"_rendererGrid"},this.domNode);this.columns={};this.columns.symbol={className:"symbolCell",field:"symbol",label:"symbol"};this.columns.label={className:"labelCell",field:"rendLabel",label:"rendLabel"};this.columns.symbol.renderCell=a.hitch(this,function(c,b,e,g){a.style(e,"width",this.maxSymbolWidth+10+"px");if(b){var h=a.create("div",{style:"width:"+c.symbolSize.width+"px;height:"+c.symbolSize.height+"px;"});a.connect(e,"onclick",a.hitch(this,
function(a){this.didDragFromSource||(this.grid.clearSelection&&this.grid.clearSelection(),this.grid.dndSource&&this.grid.dndSource.selectNone(),this.onRowClickSymbolHandler(a))},c));9>a.isIE?setTimeout(a.hitch(this,function(a,c,b){this.drawSymbol(a,c,b.symbolSize.width,b.symbolSize.height,null,1)},h,b,c),100):this.drawSymbol(h,b,c.symbolSize.width,c.symbolSize.height,null,1)}return h});this.columns.label.renderCell=a.hitch(this,function(c,b,e,g){"\x3cbackground\x3e"!==c.value?a.connect(e,"onclick",
a.hitch(this,function(a){this.didDragFromSource||(this.grid.clearSelection&&this.grid.clearSelection(),this.grid.dndSource&&this.grid.dndSource.selectNone(),this.onRowClickLabelHandler(a))},c)):a.addClass(e,"noHover");return a.create("span",{innerHTML:c.rendLabel})});this.data=[];this.maxSymbolWidth=30;if("esri.renderer.UniqueValueRenderer"==this.renderer.declaredClass){if(this.data=a.map(this.renderer.infos,function(a,c){var b=this._calcSymbolWidthHeight(a.symbol);this.maxSymbolWidth=Math.max(this.maxSymbolWidth,
b.width);return{symbol:a.symbol,symbolSize:b,label:a.label,value:a.value,rendLabel:a.label,id:c,order:c+1}},this),this.renderer.defaultSymbol&&this.renderer.defaultLabel){this.lastDefaultSymbol=esri.symbol.fromJson(this.renderer.defaultSymbol.toJson());this.lastDefaultLabel=this.renderer.defaultLabel;var b=this._calcSymbolWidthHeight(this.renderer.defaultSymbol);this.maxSymbolWidth=Math.max(this.maxSymbolWidth,b.width);this.data.push({symbol:this.renderer.defaultSymbol,symbolSize:b,label:this.renderer.defaultLabel||
this.i18n.other,value:null,rendLabel:this.renderer.defaultLabel||this.i18n.other,id:this.renderer.infos.length,order:this.renderer.infos.length+1})}}else"esri.renderer.ClassBreaksRenderer"==this.renderer.declaredClass&&(this.data=a.map(this.renderer.infos,function(a,c){var b=this._calcSymbolWidthHeight(a.symbol);this.maxSymbolWidth=Math.max(this.maxSymbolWidth,b.width);return{symbol:a.symbol,symbolSize:b,label:a.label,minValue:a.minValue,maxValue:a.maxValue,rendLabel:a.label,id:c+1}},this),this.renderer.defaultSymbol&&
this.renderer.defaultLabel&&(this.lastDefaultSymbol=esri.symbol.fromJson(this.renderer.defaultSymbol.toJson()),this.lastDefaultLabel=this.renderer.defaultLabel,b=this._calcSymbolWidthHeight(this.renderer.defaultSymbol),this.maxSymbolWidth=Math.max(this.maxSymbolWidth,b.width),this.data.push({symbol:this.renderer.defaultSymbol,symbolSize:b,label:this.renderer.defaultLabel||this.i18n.other,minValue:null,maxValue:null,rendLabel:this.renderer.defaultLabel||this.i18n.other,id:this.renderer.infos.length+
1})),this.renderer.backgroundFillSymbol&&(this.lastBackgroundSymbol=esri.symbol.fromJson(this.renderer.backgroundFillSymbol.toJson()),b=this._calcSymbolWidthHeight(this.renderer.backgroundFillSymbol),this.maxSymbolWidth=Math.max(this.maxSymbolWidth,b.width),this.data.push({symbol:this.renderer.backgroundFillSymbol,symbolSize:b,label:this.i18n.background,value:"\x3cbackground\x3e",rendLabel:this.i18n.background,id:this.renderer.infos.length+2})));var c=null;"esri.renderer.UniqueValueRenderer"==this.renderer.declaredClass&&
(c=[{attribute:"order"}]);this.store=a.store.Observable(new a.store.Memory({data:this.data,idProperty:"id",put:a.partial(function(c,b,e){e&&c.ordersList&&(e.before?a.forEach(c.ordersList,function(a,h){a===e.before.order&&(b.order=0===h?a/2:(a+c.ordersList[h-1])/2)},this):b.order=c.ordersList[c.ordersList.length-1]+1);return a.store.Memory.prototype.put.call(this,b,e)},this),query:function(b,f){f=f||{};c&&(f.sort=c);return a.store.Memory.prototype.query.call(this,b,f)}}));b=null;b="esri.renderer.UniqueValueRenderer"==
this.renderer.declaredClass?a.declare([dgrid.OnDemandGrid,dgrid.Selection,dgrid.extensions.DnD]):a.declare([dgrid.OnDemandGrid]);this.grid=new b({store:this.store,selectionMode:"esri.renderer.UniqueValueRenderer"==this.renderer.declaredClass?"single":"none",columns:this.columns,style:this.style?this.style:"width: 200px;",showHeader:!1},this.id+"_rendererGrid");"esri.renderer.UniqueValueRenderer"==this.renderer.declaredClass&&(this.onDndStartHandler&&a.disconnect(this.onDndStartHandler),this.onMouseMoveHandler&&
a.disconnect(this.onMouseMoveHandler),this.onDndCancelHandler&&a.disconnect(this.onDndCancelHandler),this.onDndStartHandler=a.connect(this.grid.dndSource,"onDndStart",a.hitch(this,"handleDragStart")),this.onMouseMoveHandler=a.connect(this.grid.dndSource,"onMouseMove",a.hitch(this,"handleDragMove")),this.onDndCancelHandler=a.connect(this.grid.dndSource,"onDndCancel",a.hitch(this,"handleDragEnd")));this.resize()},handleDragStart:function(b,c,d){if("rendererStack"===leftPanel.visibleStack)if(this.sourceItem=
this.grid.row(c[0]).data,null==this.sourceItem.value)a.topic.publish("/dnd/cancel"),a.dnd.Manager.manager().stopDrag(),this.grid.clearSelection(),this.grid.dndSource.selectNone();else return this.ordersList=a.map(this.data,function(a){return a.order}),this.ordersList=this.ordersList.sort(function(a,c){return a-c}),this.sourceOrdersPos=a.indexOf(this.ordersList,this.sourceItem.order),this.didDragFromSource=!1,a.dnd.Avatar.prototype._generateText=a.partial(function(a){return"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+
a+"\x26nbsp;\x26nbsp;"},this.sourceItem.rendLabel),a.dnd.Manager.manager().updateAvatar(),!0},handleDragMove:function(b){if("rendererStack"===leftPanel.visibleStack&&this.sourceItem){var c=function(){9>a.isIE&&(!0!==a.dnd.Manager.manager().canDropFlag&&a.dnd.Manager.manager().avatar)&&(a.dnd.Manager.manager().canDropFlag=!0,a.toggleClass(a.dnd.Manager.manager().avatar,"dojoDndAvatarCanDrop",a.dnd.Manager.manager().canDropFlag),a.dnd.Manager.manager().updateAvatar())},d=function(){!1!==a.dnd.Manager.manager().canDropFlag&&
(a.dnd.Manager.manager().canDropFlag=!1,a.toggleClass(a.dnd.Manager.manager().avatar,"dojoDndAvatarCanDrop",a.dnd.Manager.manager().canDropFlag),a.dnd.Manager.manager().updateAvatar())};a.query(".canDragBefore",a.byId("renderer-main")).forEach(function(c){a.removeClass(c,"canDragBefore")});a.query(".canDragAfter",a.byId("renderer-main")).forEach(function(c){a.removeClass(c,"canDragAfter")});var f=!0;if(this.grid.dndSource.current){b=this.grid.row(this.grid.dndSource.current).data;!this.didDragFromSource&&
b.id!==this.sourceItem.id&&(this.didDragFromSource=!0);if(this.ordersList[this.sourceOrdersPos]==b.order)d(),f=!1;else if(this.sourceOrdersPos<this.ordersList.length-1&&this.ordersList[this.sourceOrdersPos+1]==b.order){var e=a.query(".dojoDndItemBefore",a.byId("renderer-main"));e.length?(d(),f=!1):c()}else 0<this.sourceOrdersPos&&this.ordersList[this.sourceOrdersPos-1]==b.order?(e=a.query(".dojoDndItemAfter",a.byId("renderer-main")),e.length?(d(),f=!1):c()):c();f&&(!this.grid.dndSource.before&&!b.value&&
!b.minValue&&!b.maxValue?(d(),f=!1):c())}else a.forEach(this.data,function(b,e){null==b.value?(a.dnd.Manager.manager().avatar&&d(),f=!1):c()},this);f&&(e=a.query(".dojoDndItemBefore",a.byId("renderer-main")),e.length&&a.addClass(e[0],"canDragBefore"),e=a.query(".dojoDndItemAfter",a.byId("renderer-main")),e.length&&a.addClass(e[0],"canDragAfter"))}},handleDragEnd:function(){"rendererStack"===leftPanel.visibleStack&&(a.query(".canDragBefore",a.byId("renderer-main")).forEach(function(b){a.removeClass(b,
"canDragBefore")}),a.query(".canDragAfter",a.byId("renderer-main")).forEach(function(b){a.removeClass(b,"canDragAfter")}),this.ordersList=this.sourceOrdersPos=this.sourceItem=null,setTimeout(a.hitch(this,function(){this.didDragFromSource=!1}),1E3))},updateStyle:function(b,c){a.style(this.grid.domNode,b,c)},resize:function(){this.updateStyle("height",a.style(this.domNode,"height")+"px");this.updateStyle("width",a.style(this.domNode,"width")+"px")},toggleDefaultSymbol:function(){var b=!1;a.forEach(this.data,
function(a,d){if("esri.renderer.UniqueValueRenderer"==this.renderer.declaredClass&&null==a.value||"esri.renderer.ClassBreaksRenderer"==this.renderer.declaredClass&&null==a.minValue&&null==a.maxValue&&"\x3cbackground\x3e"!==a.value)b=!0},this);b?this.hideDefaultSymbol():this.showDefaultSymbol()},hideDefaultSymbol:function(){var b=-1;a.forEach(this.data,function(a,d){if("esri.renderer.UniqueValueRenderer"==this.renderer.declaredClass&&null==a.value||"esri.renderer.ClassBreaksRenderer"==this.renderer.declaredClass&&
null==a.minValue&&null==a.maxValue&&"\x3cbackground\x3e"!==a.value)this.lastDefaultSymbol=esri.symbol.fromJson(a.symbol.toJson()),this.lastDefaultLabel=a.rendLabel,b=a.id},this);-1<b&&this.store.remove(b)},showDefaultSymbol:function(){var b=this._calcSymbolWidthHeight(this.lastDefaultSymbol||this.defaultSymbol),c={symbol:this.lastDefaultSymbol||this.defaultSymbol,symbolSize:b,label:this.lastDefaultLabel||this.i18n.other,rendLabel:this.lastDefaultLabel||this.i18n.other,id:this.renderer.infos.length+
1};if("esri.renderer.UniqueValueRenderer"==this.renderer.declaredClass){c.value=null;var d=0;a.forEach(this.data,function(a){d=Math.max(d,a.order)});c.order=d+1;this.store.add(c)}else if("esri.renderer.ClassBreaksRenderer"==this.renderer.declaredClass){c.minValue=null;c.maxValue=null;var f=!1;a.forEach(this.data,function(a,b){"\x3cbackground\x3e"==a.value&&(f=!0,this.store.remove(a.id),this.store.add(c),this.store.add(a))},this);f||this.store.add(c)}},toggleBackgroundSymbol:function(){var b=!1;a.forEach(this.data,
function(a,d){"\x3cbackground\x3e"==a.value&&(b=!0)},this);b?this.hideBackgroundSymbol():this.showBackgroundSymbol()},hideBackgroundSymbol:function(){var b=-1;a.forEach(this.data,function(a,d){"\x3cbackground\x3e"==a.value&&(this.lastBackgroundSymbol=esri.symbol.fromJson(a.symbol.toJson()),b=a.id)},this);-1<b&&this.store.remove(b)},showBackgroundSymbol:function(){var a=this._calcSymbolWidthHeight(this.lastDefaultSymbol||this.defaultSymbol);this.store.add({symbol:this.lastBackgroundSymbol||this.backgroundSymbol,
symbolSize:a,label:this.i18n.background,rendLabel:this.i18n.background,id:this.renderer.infos.length+2,value:"\x3cbackground\x3e"})},getUpdatedRenderer:function(){if("esri.renderer.UniqueValueRenderer"==this.renderer.declaredClass){for(var b=this.renderer.infos.length-1;0<=b;b--)this.renderer.removeValue(this.renderer.infos[b].value);delete this.renderer.defaultSymbol;delete this.renderer.defaultLabel;b=a.clone(this.data);b=b.sort(function(a,b){var f=a.order,e=b.order;return f==e?0:f<e?-1:1});a.forEach(b,
function(a){esri.isDefined(a.value)?this.renderer.addValue({value:a.value,symbol:esri.symbol.fromJson(a.symbol.toJson()),label:a.rendLabel,description:null}):(this.renderer.defaultSymbol=esri.symbol.fromJson(a.symbol.toJson()),this.renderer.defaultLabel=a.rendLabel)},this);return new esri.renderer.UniqueValueRenderer(this.renderer.toJson())}"esri.renderer.ClassBreaksRenderer"==this.renderer.declaredClass&&(this.renderer.clearBreaks(),delete this.renderer.backgroundFillSymbol,delete this.renderer.defaultSymbol,
delete this.renderer.defaultLabel,a.forEach(this.data,function(a){esri.isDefined(a.minValue)||esri.isDefined(a.maxValue)?this.renderer.addBreak({minValue:a.minValue,maxValue:a.maxValue,symbol:esri.symbol.fromJson(a.symbol.toJson()),label:a.rendLabel,description:null}):"\x3cbackground\x3e"===a.value?this.renderer.backgroundFillSymbol=esri.symbol.fromJson(a.symbol.toJson()):(this.renderer.defaultSymbol=esri.symbol.fromJson(a.symbol.toJson()),this.renderer.defaultLabel=a.rendLabel)},this),b=this.renderer.isMaxInclusive,
(new esri.renderer.ClassBreaksRenderer(this.renderer.toJson())).setMaxInclusive(b));return this.renderer},onRowClickLabelHandler:function(b){this.onRendererItemChangeHandler&&a.unsubscribe(this.onRendererItemChangeHandler);this.onRendererItemChangeHandler=a.subscribe("onRendererItemChange",a.hitch(this,function(b,c,d){if(c){var h=this._calcSymbolWidthHeight(c),k={symbol:c,symbolSize:h,rendLabel:d,label:b.rendLabel};a.forEach(this.data,function(c){b.id==c.id&&(c=a.mixin(c,k),this.store.put(c))},this);
this.maxSymbolWidth=this._calcTotalSymbolWidthHeight().width}else d&&(k={rendLabel:d,label:b.label},a.forEach(this.data,function(c){b.id==c.id&&(c=a.mixin(c,k),this.store.put(c))},this));if(this.onLabelClick)this.onLabelClick(b);this.grid.refresh({keepScrollPosition:!0})},b));var c;if("esri.renderer.UniqueValueRenderer"==this.renderer.declaredClass)c=b.value,this.datePattern&&(c&&0<c.toString().length)&&(c=a.date.locale.format(new Date(c),{datePattern:this.datePattern.datePattern,timePattern:this.datePattern.timePattern,
selector:this.datePattern.datePattern&&this.datePattern.timePattern?null:this.datePattern.datePattern?"date":"time"}));else if("esri.renderer.ClassBreaksRenderer"==this.renderer.declaredClass)if(this.datePattern){if(0<b.minValue.toString().length&&(c=a.date.locale.format(new Date(b.minValue),{datePattern:this.datePattern.datePattern,timePattern:this.datePattern.timePattern,selector:this.datePattern.datePattern&&this.datePattern.timePattern?null:this.datePattern.datePattern?"date":"time"}),c=a.date.locale.format(new Date(b.minValue),
{datePattern:this.i18n.datePattern,timePattern:this.i18n.minuteTimePattern})),0<b.maxValue.toString().length){var d=a.date.locale.format(new Date(b.maxValue),{datePattern:this.datePattern.datePattern,timePattern:this.datePattern.timePattern,selector:this.datePattern.datePattern&&this.datePattern.timePattern?null:this.datePattern.datePattern?"date":"time"}),d=a.date.locale.format(new Date(b.maxValue),{datePattern:this.i18n.datePattern,timePattern:this.i18n.minuteTimePattern});c+=(0<c.length?" - ":
"")+d}}else c=null===b.value?b.value:this._buildRangeText(b.minValue,b.maxValue);arcgisonline.sharing.dijit.dialog.RendererDlg.prototype.statics.getInstance().show({symbol:b.symbol,value:c,label:b.rendLabel})},onRowClickSymbolHandler:function(b,c){this.onRendererItemChangeHandler&&a.unsubscribe(this.onRendererItemChangeHandler);var d=function(b,c,d){if(d){var h=this._calcSymbolWidthHeight(d),k={symbol:d,symbolSize:h,rendLabel:b.rendLabel,label:b.label};a.forEach(this.data,function(c){b.id==c.id&&
(c=a.mixin(c,k),this.store.put(c))},this);this.maxSymbolWidth=this._calcTotalSymbolWidthHeight().width}"apply"===c&&a.publish("saveRenderer",[]);if(this.onSymbolClick)this.onSymbolClick(b)};arcgisonline.sharing.dijit.dialog.SymbolDlg.prototype.statics.getInstance().showSymbol(b.symbol,{applyHandler:a.hitch(this,d,b,"apply"),okHandler:a.hitch(this,d,b,"done")})},drawSymbol:function(b,c,d,f,e,g){c=esri.symbols.jsonUtils.fromJson(c.toJson());if("simplelinesymbol"===c.type||"cartographiclinesymbol"===
c.type||"textsymbol"===c.type){if(!c.color)return;e=c.color.toRgba();e[3]*=g;c.color.setColor(e)}else if("simplemarkersymbol"===c.type||"simplefillsymbol"===c.type){if(!c.color)return;e=c.color.toRgba();e[3]*=g;c.color.setColor(e);c.outline&&c.outline.color&&(e=c.outline.color.toRgba(),e[3]*=g,c.outline.color.setColor(e))}else"picturemarkersymbol"===c.type&&(b.style.opacity=g,b.style.filter="alpha(opacity\x3d("+100*g+"))");b=p.gfx.createSurface(b,d,f);a.has("ie")&&(g=b.getEventSource(),a.style(g,
"position","relative"),a.style(g.parentNode,"position","relative"));g=esri.symbols.jsonUtils.getShapeDescriptors(c);var h;try{h=b.createShape(g.defaultShape).setFill(g.fill).setStroke(g.stroke)}catch(k){b.clear();b.destroy();return}var l=h.getBoundingBox();g=l.width;c=l.height;e=-(l.x+g/2);var l=-(l.y+c/2),m=b.getDimensions();e={dx:e+m.width/2,dy:l+m.height/2};if(g>d||c>f)d=((d<f?d:f)-5)/(g>c?g:c),a.mixin(e,{xx:d,yy:d});h.applyTransform(e);return b},_calcSymbolWidthHeight:function(a){var c=30,d=30;
"simplemarkersymbol"==a.type?(c=Math.min(Math.max(c,a.size+12),125),d=Math.min(Math.max(d,a.size+12),125)):"picturemarkersymbol"==a.type&&(c=Math.min(Math.max(c,a.width),125),d=Math.min(a.height?a.height:d,125));return{width:c,height:d}},_calcTotalSymbolWidthHeight:function(){var b=30,c=30;a.forEach(this.data,function(a){a=this._calcSymbolWidthHeight(a.symbol);b=Math.max(b,a.width);c=Math.max(c,a.height)},this);return{width:b,height:c}},_buildRangeText:function(b,c){return b===c?""+a.number.format(b,
{pattern:this.pattern}):(-Infinity==b||b==-Number.MAX_VALUE)&&c?"\x3c "+a.number.format(c,{pattern:this.pattern}):b&&(Infinity==c||c==Number.MAX_VALUE)?"\x3e\x3d "+a.number.format(b,{pattern:this.pattern}):""+a.number.format(b,{pattern:this.pattern})+" - "+a.number.format(c,{pattern:this.pattern})}})});