// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/SearchResultsSimple",["dijit","dojo","dojox","dojo/require!dijit/_Widget,dijit/_Templated,dojox/grid/DataGrid,dijit/Toolbar,arcgisonline/sharing/_Search,arcgisonline/sharing/geow/Account,arcgisonline/sharing/geow/Content,arcgisonline/sharing/dijit/views,arcgisonline/sharing/util"],function(c,a,g){a.provide("arcgisonline.sharing.dijit.SearchResultsSimple");a.require("dijit._Widget");a.require("dijit._Templated");a.require("dojox.grid.DataGrid");a.require("dijit.Toolbar");
a.require("arcgisonline.sharing._Search");a.require("arcgisonline.sharing.geow.Account");a.require("arcgisonline.sharing.geow.Content");a.require("arcgisonline.sharing.dijit.views");a.require("arcgisonline.sharing.util");a.declare("arcgisonline.sharing.dijit.SearchResultsSimple",[c._Widget,c._Templated,arcgisonline.sharing._Search],{widgetsInTemplate:!0,templateString:'\x3cdiv dojoAttachPoint\x3d"containerNode"\x3e\r\n\r\n  \x3cdiv style\x3d"width: 100%; background-color: light-blue;" dojoAttachPoint\x3d"_resultsNode"\x3e\r\n\r\n  \x3c/div\x3e\r\n  \x3c!-- \r\n  \x3cdiv style\x3d"width: 100%; display:none; margin: 2em;" class\x3d"dim" dojoAttachPoint\x3d"_noResultsNode"\x3e\r\n\r\n  \x3c/div\x3e\r\n  --\x3e\r\n\r\n\x3c/div\x3e',
resultCount:0,start:0,nextStart:0,pageCount:0,resultsPerPage:10,queryFocus:null,_views:arcgisonline.sharing.dijit.views,doAjax:!1,noResultsMessage:"",simpleList:!1,_resultsNode:null,_noResultsNode:null,_user:null,_organization:null,_unshareHandler:null,pageQuery:null,i18n:null,postMixInProperties:function(){this.inherited(arguments);this.i18n=a.i18n.getLocalization("arcgisonline","arcgisonline").common;a.mixin(this.i18n,a.i18n.getLocalization("arcgisonline","arcgisonline").searchResults)},postCreate:function(){var b=
window.location.pathname.toLowerCase();this.isGroupsPage=-1!==b.indexOf("groups.html");-1==b.indexOf("group.html")&&(null===window.location.search||""===window.location.search)&&null===this.pageQuery?console.error("Search results widget was not provided any query parameters"):(this.inherited(arguments),a.connect(this,"onQueryResult",this,this._handleSearchResult),this._queryStringParams=null===window.location.search||""===window.location.search||"?"===window.location.search?this.pageQuery:a.queryToObject(window.location.search.slice(1)),
a.connect(this,"onDisplayResults",this,this._updateNoResultsMessage))},startup:function(){this.inherited(arguments);arcgisonline.sharing.geow.Account.getSelf(a.hitch(this,this.handleGetSelf))},handleGetSelf:function(b){var d=arcgisonline.sharing.util.isPortal();if((this._user=arcgisonline.sharing.util.getUser())&&this._user.accountId)if(b&&b.id&&b.id===this._user.accountId){this._organization=b;if(this._organization.thumbnail&&0<this._organization.thumbnail.length){var f=this.getOrganizationThumbnailUrl(this._organization),
e=a.create("span",{innerHTML:" "+this.i18n.searchResults},a.byId("searchResultsPageTitle"),"only"),f=a.create("img",{src:f,alt:this._organization.name,align:"center"},e,"first");a.addClass(f,"groupThumbnail")}if(d)esri.isDefined(this._queryStringParams.t)&&"groups"===this._queryStringParams.t&&(this._queryStringParams.q+=" orgid:"+b.id);else{this._queryStringParams.q_orig||(this._queryStringParams.q_orig=this._queryStringParams.q);if(b.canSearchPublic||this._user.accountId===b.id&&esriGeowConfig.userRole.isAdmin())if(d=
a.string.substitute(this.i18n.restrictSearch,{name:b.name}),a.attr(a.byId("restrictSearchLabel"),"innerHTML",d),a.style(a.byId("restrictSearchSection"),"display","block"),void 0!==this._queryStringParams.restrict&&null!==this._queryStringParams.restrict&&("true"===this._queryStringParams.restrict||"false"===this._queryStringParams.restrict))this._queryStringParams.restrict="false"!==this._queryStringParams.restrict,c.byId("filtersWidget")&&c.byId("filtersWidget").setRestrict(this._queryStringParams.restrict),
c.byId("sorters")&&c.byId("sorters").setRestrict(this._queryStringParams.restrict),c.byId("restrictSearch").set("checked",this._queryStringParams.restrict);a.connect(c.byId("restrictSearch"),"onClick",this,this.onRestrictSearchChange);d=c.byId("restrictSearch").get("checked");this._queryStringParams.q=d?this._queryStringParams.q_orig+" orgid:"+b.id:this._queryStringParams.q_orig}}else this._organization=null;else b&&b.id&&!d&&b.urlKey&&b.customBaseUrl?(this._organization=b,this._queryStringParams.q_orig||
(this._queryStringParams.q_orig=this._queryStringParams.q),this.isGroupsPage||(d=a.string.substitute(this.i18n.restrictSearch,{name:b.name}),a.attr(a.byId("restrictSearchLabel"),"innerHTML",d),a.style(a.byId("restrictSearchSection"),"display","block"),this._queryStringParams=a.mixin(this._queryStringParams,{restrict:"false"!==this._queryStringParams.restrict}),c.byId("filtersWidget")&&c.byId("filtersWidget").setRestrict(this._queryStringParams.restrict),c.byId("sorters")&&c.byId("sorters").setRestrict(this._queryStringParams.restrict),
c.byId("restrictSearch").set("checked",this._queryStringParams.restrict),a.connect(c.byId("restrictSearch"),"onClick",this,this.onRestrictSearchChange),d=c.byId("restrictSearch").get("checked"),this._queryStringParams.q=d?this._queryStringParams.q_orig+" orgid:"+b.id:this._queryStringParams.q_orig),this.simpleList||(c.byId("filtersWidget")&&c.byId("filtersWidget").setRestrict(this._queryStringParams.restrict),c.byId("sorters")&&c.byId("sorters").setRestrict(this._queryStringParams.restrict)),this._queryStringParams.restrict&&
(this._queryStringParams.q=this._queryStringParams.q+" orgid:"+b.id)):b&&(b.id&&d&&esri.isDefined(this._queryStringParams.t)&&"groups"===this._queryStringParams.t)&&(this._queryStringParams.q+=" orgid:"+b.id);this.doQuery(this._queryStringParams)},onRestrictSearchChange:function(b){b=c.byId("restrictSearch").get("checked");a.publish("onRestrictSearchChange",[{restrictSearch:b}]);this._queryStringParams.restrict=b;c.byId("filtersWidget")&&c.byId("filtersWidget").setRestrict(this._queryStringParams.restrict);
c.byId("sorters")&&c.byId("sorters").setRestrict(this._queryStringParams.restrict);this._queryStringParams.q=b?this._queryStringParams.q_orig+" AND orgid:"+this._organization.id:this._queryStringParams.q_orig;var d=a.mixin({},this._queryStringParams);b&&delete d.start;this.doQuery(d)},getOrganizationThumbnailUrl:function(b){var a=arcgisonline.sharing.util.getToken();return esriGeowConfig.restBaseUrl+"portals/self/resources/"+b.thumbnail+(a?"?token\x3d"+a:"")},_updateNoResultsMessage:function(){var a=
"\x3cp\x3e"+this.i18n.noResults+"\x3c/p\x3e\x3cp\x3e"+this.i18n.suggestionsLabel+"\x3cul\x3e",a=a+("\x3cli\x3e"+this.i18n.spellingCheck+"\x3c/li\x3e\x3cli\x3e"+this.i18n.tryDiffWords+"\x3c/li\x3e\x3cli\x3e"+this.i18n.tryGeneralWords+"\x3c/li\x3e\x3c/ul\x3e\x3c/p\x3e");this.noResultsMessage="\x3cp class\x3d'esriItemLinks'\x3e"+a+"\x3c/p\x3e"},_setDefaultSortFieldAttr:function(a){this.defaultSortField=a},_handleSearchResult:function(b,d){this.start=b.start;this.nextStart=b.nextStart;this.resultCount=
b.total;this.pageCount=Math.ceil(this.resultCount/this.resultsPerPage);var c="groups"==this._queryStringParams.t?a.hitch(this._views.group,this._views.group.medium):a.hitch(this._views.item,this._views.item.medium);this.onDisplayResults(this.resultCount);a.empty(this._resultsNode);if(b.total&&0<b.total)a.forEach(b.results,function(b){var d={showThumb:!0,align:"left",showProfilePopup:!0};this._unshareHandler&&(d.unshareHandler=this._unshareHandler);a.place(a.partial(c,b,d)(),this._resultsNode)},this);
else{var e="";esri.isDefined(this._queryStringParams.q)&&0<this._queryStringParams.q.length&&(e="- '"+this._queryStringParams.q+"' - ");e=a.replace(this.noResultsMessage,{query:e});a.attr(this._resultsNode,"innerHTML",e)}this.afterDisplayResults()},onDisplayResults:function(a){},afterDisplayResults:function(){},nextPage:function(){if(0<this.nextStart){var b=a.clone(this._queryStringParams);b.start=this.nextStart;this._page(b)}},previousPage:function(){if(1<this.start){var b=a.clone(this._queryStringParams);
b.start=1>b.start-this.resultsPerPage?1:b.start-this.resultsPerPage;this._page(b)}},goToPage:function(b){if(0<b){var d=a.clone(this._queryStringParams);d.start=1+this.resultsPerPage*(b-1);this._page(d)}},_page:function(b){this.doAjax?this.doQuery(b):(b=a.mixin(b,{q:c.byId("search-box").get("value")}),this.goToSearch(b,{useCurrentPageLocation:!0}))},sort:function(b,d){if("groups"!==this._queryStringParams.t){var c=a.clone(this._queryStringParams);b&&(c.sortField=b);c.sortOrder=d?"desc":"asc";this.doAjax?
this.doQuery(c):this.goToSearch(c,{useCurrentPageLocation:!0})}},_setNoResultsMessageAttr:function(a){this.noResultsMessage=a}});a.declare("arcgisonline.sharing.dijit.RelatedSearchResults",[c._Widget,c._Templated],{templateString:'\x3cdiv dojoAttachPoint\x3d"containerNode"\x3e\r\n\r\n  \x3cdiv dojoAttachPoint\x3d"_groupsNode"\x3e\x3c/div\x3e\r\n  \x3cdiv dojoAttachPoint\x3d"_esriNode"\x3e\x3c/div\x3e\r\n  \x3cdiv dojoAttachPoint\x3d"_otherNode"\x3e\x3c/div\x3e\r\n\r\n\x3c/div\x3e',searchResults:null,
_content:arcgisonline.sharing.geow.Content,_util:arcgisonline.sharing.util,_views:arcgisonline.sharing.dijit.views,_query:null,_keywords:null,_groupsNode:null,_esriNode:null,_otherNode:null,maxRecords:4,i18n:null,postMixInProperties:function(){this.inherited(arguments);this.i18n=a.i18n.getLocalization("arcgisonline","arcgisonline").common;a.mixin(this.i18n,a.i18n.getLocalization("arcgisonline","arcgisonline").relatedSearch)},constructor:function(b){null!==b.searchResults&&a.connect(b.searchResults,
"onQueryExecute",this,this._search)},_search:function(b,d){this._query=b;this._keywords=d;null!==this._groupsNode&&(d&&0<d.length)&&this._content.search(esriGeowConfig.restBaseUrl+"community/groups",{q:this._keywords,num:this.maxRecords},a.hitch(this,this._handleGroupSearch));null!==this._esriNode&&this._content.search(esriGeowConfig.restBaseUrl+"search",{q:this._query.q+" "+esriGeowConfig.publisherESRI,num:this.maxRecords},a.hitch(this,this._handleSearchB))},_handleGroupSearch:function(b,d){b.results&&
0<b.results.length&&(a.create("span",{"class":"section",innerHTML:a.string.substitute(this.i18n.groupResults,[this._keywords])},this._groupsNode,"only"),a.forEach(b.results,function(b){a.place(this._views.group.small(b,!0,"left"),this._groupsNode)},this))},_handleSearchB:function(b,d){b.results&&0<b.results.length&&(a.create("span",{"class":"section",innerHTML:a.string.substitute(this.i18n.esriContent,[this._keywords])},this._esriNode,"only"),a.forEach(b.results,function(b){a.place(this._views.item.small(b,
!0,"left"),this._esriNode)},this))},_handleSearchC:function(b,d){b.results&&0<b.results.length&&a.forEach(b.results,function(b){a.place(this._views,this._otherNode)},this)}});a.declare("arcgisonline.sharing.dijit.SearchResultsPaging",[c._Widget,c._Templated],{templateString:'\x3cdiv dojoAttachPoint\x3d"containerNode"\x3e\r\n  \x3cspan dojoType\x3d"dijit.form.Button" type\x3d"button" class\x3d"calcite light" dojoAttachPoint\x3d"_prev" dojoAttachEvent\x3d"onClick:previous" alt\x3d"${i18n.prevPage}" title\x3d"${i18n.prevPage}"\x3e${i18n.previous}\x3c/span\x3e\r\n  \x3cspan dojoAttachPoint\x3d"_pages" dojoAttachEvent\x3d"onClick:page" class\x3d"esriItemLinks esriPagingLinks" style\x3d"vertical-align: middle;"\x3e\x3c/span\x3e\r\n  \x3cspan dojoType\x3d"dijit.form.Button" type\x3d"button" class\x3d"calcite light" dojoAttachPoint\x3d"_next" dojoAttachEvent\x3d"onClick:next" alt\x3d"${i18n.nextPage}" title\x3d"${i18n.nextPage}"\x3e${i18n.next}\x3c/span\x3e\r\n\x3c/div\x3e',
widgetsInTemplate:!0,_prev:null,_next:null,_pages:null,searchResults:null,pageBuffer:3,_queryParams:null,i18n:null,postMixInProperties:function(){this.inherited(arguments);this.i18n=a.i18n.getLocalization("arcgisonline","arcgisonline").common;a.mixin(this.i18n,a.i18n.getLocalization("arcgisonline","arcgisonline").searchResultsPaging)},postCreate:function(){null!==this.searchResults&&a.connect(this.searchResults,"onQueryResult",this,this._layout);this._queryParams=a.queryToObject(window.location.search.slice(1));
a.connect(this._prev,"onClick",this,this._disable);a.connect(this._next,"onClick",this,this._disable);this.searchResults.doAjax&&(a.connect(this,"first",this,this._disable),a.connect(this,"last",this,this._disable),a.connect(this,"page",this,this._disable));this._disable()},_disable:function(){this._prev.set("disabled","true");this._next.set("disabled","true")},_layout:function(){a.empty(this._pages);var b=1;this.searchResults.start&&(b=Math.ceil(this.searchResults.start/this.searchResults.resultsPerPage));
b>this.searchResults.pageCount&&(b=this.searchResults.pageCount);if(0===this.searchResults.resultCount)esri.hide(this._prev),esri.hide(this._next);else if(1<this.searchResults.pageCount){var d=Math.max(1,b-this.pageBuffer),c=Math.min(this.searchResults.pageCount,b+this.pageBuffer);1<d&&(a.create("span",{innerHTML:"1"},a.create("a",{onclick:a.hitch(this,this.page,1)},this._pages)),2<d&&a.create("span",{innerHTML:"...","class":"dim"},this._pages));for(;d<=c;d++){var e=a.create("span",{innerHTML:d},
a.create("a",{onclick:a.hitch(this,this.page,d)},this._pages));d==b&&a.addClass(e,"currentPage")}c<this.searchResults.pageCount&&(c<this.searchResults.pageCount-1&&a.create("span",{innerHTML:"...","class":"dim"},this._pages),a.create("span",{innerHTML:this.searchResults.pageCount},a.create("a",{onclick:a.hitch(this,this.page,this.searchResults.pageCount)},this._pages)))}this._prev.set("disabled",1!==this.searchResults.start?!1:!0);this._next.set("disabled",-1!==this.searchResults.nextStart?!1:!0)},
previous:function(){this.searchResults.previousPage()},next:function(){this.searchResults.nextPage()},first:function(){this.page(1)},last:function(){this.page(this.searchResults.pageCount)},page:function(a){this.searchResults.goToPage(a)}})});