// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
require({cache:{"url:arcgisonline/sharing/dijit/templates/SecuredHosts.html":'\x3cdiv\x3e\r\n  \x3cinput type\x3d"text" class\x3d"hostInput" data-dojo-type\x3d"dijit/form/TextBox" data-dojo-attach-point\x3d"_host" data-dojo-props\x3d"trim: true"\x3e\r\n  \x3cbutton type\x3d"button" class\x3d"calcite tertiary small" data-dojo-type\x3d"dijit/form/Button"\r\n          data-dojo-attach-point\x3d"_addHost"\x3e${i18n.addHost}\x3c/button\x3e\r\n  \x3cbr\x3e\x3cbr\x3e\r\n  \x3c!-- grid container added dynamically here --\x3e\r\n\x3c/div\x3e\r\n'}});
define("arcgisonline/sharing/dijit/SecuredHosts","require dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/url dojo/dom-attr dojo/dom-construct dojo/on dojo/topic dojo/keys dojo/Deferred dojo/store/Memory dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/form/Button dijit/form/TextBox dijit/Dialog dijit/Tooltip esri/lang esri/request arcgisonline/sharing/dijit/Grid arcgisonline/sharing/geow/Account arcgisonline/sharing/util arcgisonline/sharing/dijit/dialog/GeneralDlg dojo/i18n!arcgisonline/nls/arcgisonline dojo/text!arcgisonline/sharing/dijit/templates/SecuredHosts.html".split(" "),
function(p,q,e,C,r,D,k,s,E,t,F,u,v,w,x,G,H,I,J,g,K,L,y,z,A,m,B){return q("arcgisonline.sharing.dijit.SecuredHosts",[v,w,x],{declaredClass:"arcgisonline.sharing.dijit.SecuredHosts",baseClass:"esriSecuredHosts",basePath:p.toUrl("arcgisonline/sharing/dijit"),templateString:B,widgetsInTemplate:!0,rowsPerPage:5,hosts:[],_setHostsAttr:function(a){var c=[],b;if(g.isDefined(a)&&0<a.length){this._set("hosts",a);for(b=0;b<a.length;b++)c.push({id:b,label:a[b]})}else this._set("hosts",c);this._setHostsGridStore(c)},
postMixInProperties:function(){this.inherited(arguments);var a={};e.mixin(a,m.common);e.mixin(a,m.securedHosts);this._set("i18n",a)},constructor:function(a){g.isDefined(a.preload)?this._set("preload",!!a.preload):this._set("preload",!0)},postCreate:function(){this.inherited(arguments);this._generalDlg=A.prototype.statics.getInstance();this._createConnections()},startup:function(){this.inherited(arguments);this._initUI()},refresh:function(){this._grid&&this._grid._started&&(this._grid._grid.resize(),
this._grid._grid.refresh())},_createConnections:function(){this.own(this._addHost.on("click",e.hitch(this,this._addHostClick)),this._host.on("keydown",e.hitch(this,this._hostKeyDown)))},_initUI:function(){var a=this,c=a._get("preload");y.getSelf(function(b){a._createHostsGrid();c?a.set("hosts",b.authorizedCrossOriginDomains||[]):a.set("hosts",[])})},_createHostsGrid:function(){this._grid=new arcgisonline.sharing.dijit.Grid({columns:this._createHostsGridColumns(),id:"hostsGrid",region:"center",noDataMessage:this._get("i18n").noHosts,
showLoadingMessage:!0,showHeader:!0,showFooter:!0,rowsPerPage:this.rowsPerPage,pagingLinks:!0,selectionMode:"none",store:this._createHostsGridStore(),sort:[{attribute:"id",descending:!1}]},k.create("div",null,this.domNode));this._grid.startup();this._grid.refresh()},_setHostsGridStore:function(a){this._grid&&(this._grid.get("store")?(this._clearHostsGridStore(),this._addDataToHostsGridStore(a)):this._grid.set("store",this._createHostsGridStore(a)))},_addDataToHostsGridStore:function(a){var c=this._grid.get("store"),
b=c.query().length,d;if(a&&0<a.length)for(d=0;d<a.length;d++)a[d].id=b+d,c.put(a[d])},_clearHostsGridStore:function(){var a=this._grid.get("store"),c=a.query(),b;if(c&&0<c.length)for(b=0;b<c.length;b++)a.remove(c[b].id)},_createHostsGridStore:function(a){return new u({identifier:"id",label:"label",data:a||[]})},_createHostsGridColumns:function(){var a=this._get("i18n");return{label:{label:a.hosts,sortable:!1,formatter:function(a){return'\x3cspan class\x3d"esriContentTypeName"\x3e'+a+"\x3c/span\x3e"}},
remove:{label:"  ",sortable:!1,renderCell:e.hitch(this,function(c){var b=a.deleteHost,d=z.relativeToExplicitUrl("images/delete_20x20.png"),b=k.create("img",{src:d,title:b,alt:b,className:"clickable"});this.own(s(b,"click",e.hitch(this,this._gridRemoveClickHandler,c)));return b})}}},_hostKeyDown:function(a){a.keyCode===t.ENTER&&this._addHostClick(a)},_addHostClick:function(a){a&&a.preventDefault();a=this._grid.get("store");var c=this._grid._grid?this._grid._grid._currentPage:1,b={id:a.query().length,
label:this._host.get("value")},d=a.query(),n=[],e=!1,f,g,k,l,h;if(this._isValidHost(b)){if(d&&0<d.length){g=!1;for(h=0;h<d.length;h++)if(f=d[h],f.label===b.label){g=!0;break}g||(a.put(b),e=!0)}else a.put(b),e=!0;if(e){d=a.query();for(h=0;h<d.length;h++)f=d[h],n.push(f.label);this._set("hosts",n)}k=this._grid._grid.on("dgrid-refresh-complete",function(a){l=Math.ceil(a.grid._total/a.grid.rowsPerPage);(c!==l||1!==c)&&a.grid.gotoPage(l);k.remove()});this._grid._grid.refresh();this._host.set("value","")}},
_isValidHost:function(a){var c,b;if(!g.isDefined(a)||!g.isDefined(a.label)||0===a.label.length)return this._generalDlg.show({title:this.i18n.notice,message:this.i18n.noHostDefined}),!1;if(-1<a.label.indexOf("*"))return this._generalDlg.show({title:this.i18n.notice,message:this.i18n.wildcardsNotSupported}),!1;if(-1<a.label.indexOf("://"))try{c=new r(a.label);b=c.authority||c.path;if(g.isDefined(c.scheme)&&!("http"===c.scheme||"https"===c.scheme))return this._generalDlg.show({title:this.i18n.notice,
message:g.substitute({scheme:c.scheme},this.i18n.schemeNotAllowed)}),!1;if(b&&0===b.indexOf("-"))return this._generalDlg.show({title:this.i18n.notice,message:this.i18n.startWithHyphen}),!1;if(!this._isValidDomainName(b))return this._generalDlg.show({title:this.i18n.notice,message:this.i18n.hostInvalid}),!1}catch(d){return console.log(d),this._generalDlg.show({title:this.i18n.notice,message:this.i18n.hostInvalid}),!1}else{if(a.label&&0===a.label.indexOf("-"))return this._generalDlg.show({title:this.i18n.notice,
message:this.i18n.startWithHyphen}),!1;if(!this._isValidDomainName(a.label))return this._generalDlg.show({title:this.i18n.notice,message:this.i18n.hostInvalid}),!1}return!0},_isValidDomainName:function(a){var c=/^((?:(?:(?:\w[\.\-\+]?)*)\w)+)((?:(?:(?:\w[\.\-\+]?){0,62})\w)+)\.(\w{2,6})$/ig,b=/^:(\d)+$/ig,d=a&&0<a.length?a.indexOf(":"):-1,e;return-1<d?(e=a.substring(0,d),a=a.substring(d),e&&0<e.length&&c.test(e)&&a&&0<a.length&&b.test(a)):a&&0<a.length&&c.test(a)},_gridRemoveClickHandler:function(a){var c=
this._grid.get("store"),b=dojo.clone(c.query()),d=this._grid._grid?this._grid._grid._currentPage:1,e=[],g,f;for(f=0;f<b.length;f++)c.remove(b[f].id);a=b.splice(a.id,1);for(f=0;f<b.length;f++)b[f].id=f,c.put(b[f]),e.push(b[f].label);a&&0<a.length&&this._set("hosts",e);c=Math.ceil(b.length/this.rowsPerPage);d>c&&(d=c);g=this._grid._grid.on("dgrid-refresh-complete",function(a){a.grid._currentPage!==d&&0<b.length&&a.grid.gotoPage(d);g.remove()});this._grid._grid.refresh()}})});