// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/ServiceInfo",["dijit","dojo","dojox","dojo/require!dijit/_WidgetBase,dijit/registry,arcgisonline/sharing/util,esri/IdentityManagerBase,arcgisonline/sharing/dijit/dialog/GeneralDlg"],function(g,b,h){b.provide("arcgisonline.sharing.dijit.ServiceInfo");b.require("dijit._WidgetBase");b.require("dijit.registry");b.require("arcgisonline.sharing.util");b.require("esri.IdentityManagerBase");b.require("arcgisonline.sharing.dijit.dialog.GeneralDlg");b.declare("arcgisonline.sharing.dijit.ServiceInfo",
[g._WidgetBase,esri.IdentityManagerBase],{baseClass:"esriSvcAuth",onCredentialChange:function(){},postMixInProperties:function(){this.inherited(arguments);this._util=arcgisonline.sharing.util;this._isSecuredUrl=esriGeowConfig.restBaseUrl.replace("rest/","")+"checkUrl.jsp";this._errorDlg=arcgisonline.sharing.dijit.dialog.GeneralDlg.prototype.statics.getInstance();this.i18n=b.mixin({},b.i18n.getLocalization("arcgisonline","arcgisonline").common);this._tokenAuthentication=[499,498];this._overrideUrls=
"geocode.arcgis.com geocodedev.arcgis.com geocodeqa.arcgis.com route.arcgis.com routedev.arcgis.com routeqa.arcgis.com".split(" ")},buildRendering:function(){var a=document.createDocumentFragment(),c=b.create("fieldset",{"class":"esriSvcAuth"},a);b.create("label",{"for":"proxyUsername",innerHTML:this.i18n.userLabel,"class":"esriUsernameLbl"},c);this._username=new g.form.TextBox({name:"serviceUsername",trim:"true"},b.create("input",{},c));b.create("br",{},c);b.create("label",{"for":"proxyPassword",
innerHTML:this.i18n.passwordLabel,"class":"esriPasswordLbl"},c);this._password=new g.form.TextBox({name:"servicePassword",trim:"true",type:"password"},b.create("input",{},c));this.inherited(arguments);this.domNode.appendChild(a)},postCreate:function(){this.connect(this._password,"onChange",b.hitch(this,"_onCredential"));this.connect(this._username,"onChange",b.hitch(this,"_onCredential"))},_setDisabledAttr:function(a){b.forEach(g.registry.findWidgets(this.domNode,this.containerNode),function(b){b.set("disabled",
a)})},getIsSecured:function(a){a=a.split("?")[0];var c;(this.isOverrideUrl=b.some(this._overrideUrls,function(b){return-1!==a.indexOf(b)}))?(esri.show(this.domNode),c=new b.Deferred,c.resolve({secured:!0,isOverride:!0})):c=this._util.request({url:this._isSecuredUrl+"?url\x3d"+escape(a+"?f\x3djson")},{addToken:!1}).then(b.hitch(this,function(a){a.secured&&(403===a.httpStatusCode?a.secured=!1:401===a.httpStatusCode?esri.show(this.domNode):0<=b.indexOf(this._tokenAuthentication,a.httpStatusCode)&&esri.show(this.domNode));
return a}));return c},signIn:function(a,c,d){this._pendingDfd=new b.Deferred;this._serverInfo=c;this.userInfo&&(this.userInfo.username&&this.userInfo.password)&&this._generateToken();return this._pendingDfd},isFederatedWithWebTierAuth:function(a,c){var d=new b.Deferred,f,e=!1;c&&499===c.httpStatusCode?this._getTokenSvcUrl(a).then(b.hitch(this,function(a){(f=a&&a.authInfo&&a.authInfo.tokenServicesUrl)?this.getIsSecured(f).then(b.hitch(this,function(a){e=a&&a.secured&&401===a.httpStatusCode;d.resolve(e)}),
b.hitch(this,function(a){d.resolve(a&&a.message&&-1<a.message.indexOf("Http StatusCode: -1")?-1:!1)})):d.resolve(!1)})):d.resolve(!1);return d},getServiceInfo:function(a,c){var d=new b.Deferred,d=this.userInfo,f=this._util.isHostedService(a),e={useProxy:!1,timeout:!1===esriGeowConfig.isMultiTenant?6E4:5E3,addSSL:f,addToken:c&&f&&!1!==esriGeowConfig.isMultiTenant||!1};d&&d.username&&d.password?(this._prevIdMgr=esri.id,esri.id=this,this._svcUrl=a.split("?")[0],d=this.isOverrideUrl?this._signIn(a,this.userInfo).then(b.hitch(this,
function(b){return this._getServiceInfo(a,e)})):this._getServiceInfo(a,e).then(b.hitch(this,function(b){b.credential=esri.id.findCredential(a);esri.id=this._prevIdMgr;b.credential&&esri.id.registerToken({server:a,token:b.credential.token,userId:b.credential.userId,expires:b.credential.expires,ssl:b.credential.ssl});return b}))):(e.disableIdentityLookup=!0,d=this._getServiceInfo(a,e).then(b.hitch(this,function(a){return a}),b.hitch(this,function(a){esri.show(this.domNode);throw a;})));return d},_generateToken:function(){return this.generateToken(this._serverInfo,
{username:this.userInfo.username,password:this.userInfo.password}).then(b.hitch(this,function(a){if(a)this._pendingDfd.callback(new esri.Credential({userId:this.userInfo.username,server:this._serverInfo.server,token:a.token,expires:esri.isDefined(a.expires)?Number(a.expires):null,ssl:a.ssl,validity:this._serverInfo.shortLivedTokenValidity}));else return null}),b.hitch(this,function(a){a.code=403;this._pendingDfd.errback(a)}))},getServiceInfoOverProxy:function(a,c){var d=this._util.isHostedService(a)||
this._util.isAgolService(a),f={useProxy:!1,timeout:5E3,addSSL:d,addToken:d&&!1!==esriGeowConfig.isMultiTenant};this._svcUrl=a.split("?")[0];return!1===c?this._getServiceInfo(a):this._signIn(this._svcUrl,this.userInfo).then(b.hitch(this,function(c){b.mixin(f,{disableIdentityLookup:c?!1:!0,useProxy:!0});return this._getServiceInfo(a,f)}))},_getServiceInfo:function(a,c){if((esriGeowConfig.allSSL||"https:"===window.location.protocol)&&(this._util.isHostedService(a)||this._util.supportsHttps(a)))a=a.replace("http:/",
"https:/");return this._util.request({url:a,content:{}},c).then(b.hitch(this,function(a){this._editingCredential=!1;return this.serviceInfo=a}),b.hitch(this,function(a){this._editingCredential=!1;a&&-1!==b.indexOf(this._tokenAuthentication,a.code)?esri.show(this.domNode):a&&403===a.code?esri.show(this.domNode):esri.hide(this.domNode);throw a;}))},_onCredential:function(){this.credentials=[];this.userInfo={username:this._username.get("value"),password:this._password.get("value")};this._editingCredential=
!0;this.onCredentialChange(this.userInfo)},_onChangeCredential:function(a){this._editingCredential=a},_findServerInfo:function(a){var c=esri.id.findServerInfo(a);c?(a=new b.Deferred,a.resolve(c)):(c=new esri.ServerInfo,c.server=esri.id._getOrigin(a),a=esri.id._getTokenSvcUrl(a).then(b.hitch(this,function(a){c.tokenServiceUrl=b.getObject("authInfo.tokenServicesUrl",!1,a)||b.getObject("authInfo.tokenServiceUrl",!1,a)||b.getObject("tokenServiceUrl",!1,a);c.currentVersion=a.currentVersion;c.hasServer=
!0;esri.id.registerServers([c]);return c})));return a},_signIn:function(a,c){var d;c&&c.username&&c.password?d=this._findServerInfo(a).then(b.hitch(this,function(d){if(esri.id._checkProtocol(a,d,function(a){console.log(a)}))return esri.id.generateToken(d,c).then(b.hitch(this,function(e){var g=esri.isDefined(e.expires)?Number(e.expires):null;e=new esri.Credential({userId:c.username,server:d.server,token:e.token,expires:g,ssl:!!e.ssl,validity:d.shortLivedTokenValidity,resources:[a],scope:"server"});
-1===b.indexOf(esri.id.credentials,e)&&esri.id.credentials.push(e);return c}),b.hitch(this,function(a){a.code=403;throw a;}))})):(d=new b.Deferred,d.resolve(null));return d}})});