// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("esri/core/declare dojo/_base/lang dojo/dom-construct dojo/promise/all dojo/Deferred dojo/dom-class dojo/on dojo/keys dojo/mouse dojo/query ./WebSceneEditorPaneBase dijit/form/TextBox dojo/i18n!../nls/editor".split(" "),function(C,x,d,D,s,g,u,E,y,F,G,H,n){function z(a,b){for(var e in a)if(a.hasOwnProperty(e)){b[e]||(b[e]=[]);for(var c=a[e],m={"Scene Service":[],"Feature Service":[]},f=0;f<c.length;f++)"Feature Service"===c[f].type?m["Feature Service"][c[f].title]=f:"Scene Service"===c[f].type&&
(m["Scene Service"][c[f].title]=f);for(f=0;f<c.length;f++)"Feature Service"===c[f].type&&c[f].title in m["Feature Service"]&&c[f].title in m["Scene Service"]&&(b[e][c[f].title]=f)}return b}function A(a,b,e,c,m,f){var w=d.create("div",{id:a.id,"class":"layerListItem"},b);c.push(u(w,y.enter,function(){f(a.id,m,!0)}));c.push(u(w,y.leave,function(){f(a.id,m,!1);g.remove(w,"hover")}));b=d.create("tr",{},w);var k=d.create("td",{},b),k=d.create("div",{className:"thumbOther"},k);if(null!=a.thumbnailUrl)k.style.backgroundImage=
"url("+a.thumbnailUrl+")";else if("scene service"===(a.type&&a.type.toLowerCase()||""))k.className="thumbScene";var k=d.create("td",{"class":"thumbDesc"},b),l=d.create("div",{},k);d.create("div",{className:"layerTypeIcon"},l).style.backgroundImage="url("+a.iconUrl+")";d.create("div",{"class":"title",innerHTML:a.title,title:a.title},l);if(a.displayName){var k=d.create("div",{"class":"sub",title:a.displayName+" "+n.addLayerPane.by+" "+a.owner},k),l=d.create("div",{innerHTML:a.displayName,"class":"layerLink"},
k),h=a.portal.getBaseUrl(),p=a.id;c.push(u(l,"click",function(a,b){b.preventDefault();b.stopPropagation();window.open(h+"item.html?id\x3d"+p,"_blank")}.bind(h,p)));d.create("div",{innerHTML:"\x26nbsp;"+n.addLayerPane.by+"\x26nbsp;","class":"inlineContainer"},k);d.create("div",{innerHTML:a.owner,"class":"inlineContainer"},k)}c="featured"===m?"importLayerAddButton":"searchLayerAddButton";var q=d.create("td",{},b);d.create("div",{"class":c,title:"featured"===m?n.buttons.importLayer:n.buttons.add},q).onclick=
function(b){g.add(w,"added");e&&(g.add(q.firstChild,"searchLayerLoading"),e(a.url,a.id,a.title,a.displayName,q,m))}}var B={user:n.addLayerPane.myContent,portal:n.addLayerPane.content,featured:n.addLayerPane.featuredContent};!0===window._demo&&(B.base="3D Base Layers");var I=[{title:"Thematic Buildings",url:"http://web3d.esri.com/SceneServerLocal/juneDemo/BuildingShell/",thumbnailUrl:"http://devext.arcgis.com/sharing/rest/content/items/ed9998f9deb9457381bd90efbaed70a9/info/thumbnail/ThematicBuildings.jpg"},
{title:"Thematic Trees",url:"http://web3d.esri.com/SceneServerLocal/juneDemo/Trees_3k/",thumbnailUrl:"http://devext.arcgis.com/sharing/rest/content/items/16fe4f3ca22e4f5999ed9e34750e3443/info/thumbnail/ThematicTrees.jpg"},{title:"Realistic Buildings",url:"http://web3d.esri.com/SceneServerLocal/juneDemo/SF_v12_lod_ccw",thumbnailUrl:"http://devext.arcgis.com/sharing/rest/content/items/6796812ee198446287581c2359f0e28a/info/thumbnail/RealisticBuildings.jpg"}];return C([G],{_onHandles:void 0,_moreButtonHandles:void 0,
_numberOfMoreItem:10,_featuredContentGroupId:void 0,constructor:function(){this._onHandles=[];this._moreButtonHandles=[];x.mixin(this,{id:"addLayer",title:n.panes.addLayers,actionButton:{title:n.buttons.done,action:"_navBackBtnNodeClickHandler"}});g.add(this.content,"addLayerPane");this.editor.portal?this._queryFeaturedContentGroup().then(function(a){this._updateContent()}.bind(this)):this.editor.watch("portal",function(){this._queryFeaturedContentGroup().then(function(a){this._updateContent()}.bind(this))}.bind(this))},
destroy:function(){this.emit("layer-found-visible",{clear:!0});this._onHandles.forEach(function(a){a.remove()});for(var a in this._moreButtonHandles)this._moreButtonHandles[a].remove()},_updateContent:function(){function a(){""!==e._textBox.get("value")&&g.contains(e._searchButton,"searchCross")&&e._textBox.set("value","");b()}function b(){var a=e._textBox.get("value");e._performSearch(e._textBox.get("value"));""!==a?g.replace(e._searchButton,"searchCross","searchButton"):g.replace(e._searchButton,
"searchButton","searchCross")}var e=this,c=d.create("div",{className:""});null==this.editor?d.place("\x3cp\x3einitialization problem\x3c/p\x3e",c):this.editor.portal&&(this._textBox=new H({className:"searchBox",placeHolder:n.addLayerPane.searchForLayer}),this._searchButton=d.create("div",{className:"searchButton",title:n.addLayerPane.search},this._textBox.domNode),u(this._searchButton,"click",a),this._textBox.placeAt(this.paneTopContainer),u(this._textBox,"keypress",function(a){(a.charOrCode||a.keyCode)==
E.ENTER&&b()}),this._loadingContainer=d.create("div",{className:"centered loading"},c),this._noResultContainer=d.create("div",{className:"centered hide"},c),this._noResultContainer.innerHTML=n.addLayerPane.noResult,this._domNodeResults=d.create("div",{className:"searchResultsDiv"},c),0<this.paneScrollableContainer.children.length&&this.paneScrollableContainer.removeChild(this.content.children[0]),this.paneScrollableContainer.appendChild(c))},_removeLayer:function(a,b,e,c,m,f,d){for(var k=0;k<a.length;k++)this.editor.map.remove(a[k]);
this.emit("layer-found-visible",{clear:!1,category:d,id:c});g.remove(b.firstChild,"searchLayerRemoveButton");b.firstChild.title="featured"===d?n.buttons.importLayer:n.buttons.add;b.firstChild.onclick=function(){g.add(b.parentNode.parentNode,"added");g.add(b.firstChild,"searchLayerLoading");this._addLayer(e,c,m,f,b,d)}.bind(this)},_addLayer:function(a,b,e,c,m,f){this.editor.addContentByItemId(b,"featured"===f).then(function(d){var k=d.layers,l=d.slides;this.editor.setWebSceneChanged();this.emit("layer-found-visible",
{clear:!1,category:f,id:b});g.remove(m.firstChild,"searchLayerLoading");g.remove(m.parentNode.parentNode,"added");g.add(m.firstChild,"searchLayerRemoveButton");m.firstChild.title=n.buttons.remove;m.firstChild.onclick=function(){this._removeLayer(k,m,a,b,e,c,f);l&&l.forEach(function(a){this.editor.webScene.presentation.removeSlideById(a.id);this.editor.webScene.set("presentation",this.editor.webScene.presentation.toJSON());this.editor.setWebSceneChanged()}.bind(this))}.bind(this)}.bind(this),function(a){g.remove(m.firstChild,
"searchLayerLoading");g.remove(m.parentNode.parentNode,"added")})},_toggleLayerPopup:function(a,b,e){this.emit("layer-toggle-popup",{itemID:a,category:b,show:e})},setLayerHover:function(a){F(".layerListItem").forEach(function(b){null!==a&&b.id===a?g.add(b,"hover"):g.remove(b,"hover")})},_performSearch:function(a){g.remove(this._loadingContainer,"hide");-1===this._noResultContainer.className.indexOf("hide")&&g.add(this._noResultContainer,"hide");console.log("searching for "+a);this._onHandles.forEach(function(a){a.remove()});
for(var b in this._moreButtonHandles)this._moreButtonHandles[b].remove();d.empty(this._domNodeResults);var e=(b=this.editor.portal)&&this.editor.portal.getPortalUser(),c=void 0!==a&&""!==a;this.editor.portal?(this.emit("layer-found-visible",{clear:!0}),this._performContentSearch(a,e,b,c,{base:[],featured:[],user:[],portal:[]})):d.create("p",{innerHTML:"You need to be signed in to add layers from portal"},this._domNodeResults)},_queryFeaturedContentGroup:function(){var a=this.editor.portal.queryGroups({q:'title:"Featured Maps And Apps" AND owner:esri'},
!0);a.then(function(a){0<a.results.length&&(this._featuredContentGroupId=a.results[0].id)}.bind(this));return a},_getContentQuery:function(a,b,e,c,d,f){var g='(type:"Scene Service" OR type:"Feature Service" OR type:"Map Service" OR type:"Image Service" OR typekeywords:"Elevation 3D Layer") -typekeywords:"Table"',k='(group:"'+this._featuredContentGroupId+'" AND tags:"scenes" AND type:"Web Scene")';b.role||(g+=' -typekeywords:"Requires Credits" -typekeywords:"Requires Subscription"');var l="";e&&(c=
"("+c+") AND ");switch(a){case "user":a={q:c+" owner:"+b.username+" AND "+g};break;case "portal":b&&(l=" -owner:"+b.username+" AND ");a={q:c+l+g+"AND -"+k,sortField:"numViews",sortOrder:"desc"};break;default:a={q:c+" "+k,sortField:"numViews",sortOrder:"desc"}}0<f&&(a.start=f);a.num=d;return a},_performContentSearch:function(a,b,e,c,d){var f=Math.ceil((this.paneScrollableContainer.clientHeight-60*(b?3:2))/64),f=9>f?9:f,g=this,k,l,h=new s,p=new s,q=new s;b&&(k=this._getContentQuery("user",b,c,a,2*f,
0));l=this._getContentQuery("portal",b,c,a,2*f,0);b=this._getContentQuery("featured",b,c,a,2*f,0);!c&&!0===window._demo&&(d.base=I);k?h=e.queryItems(k,e.canSearchPublic):h.resolve();l?p=e.queryItems(l,e.canSearchPublic):p.resolve();b?q=e.queryItems(b,!0):q.resolve();D([h,p,q]).then(function(b){b[0]&&(d.user=b[0].results);b[1]&&(d.portal=b[1].results);b[2]&&(d.featured=b[2].results);this._populateResults(g._domNodeResults,d,f,a)}.bind(this),function(){console.log(arguments)})},_populateResults:function(a,
b,e,c){g.add(this._loadingContainer,"hide");var m=!1,f=this._addLayer.bind(this),w=this._toggleLayerPopup.bind(this);d.empty(a);var k=z(b,{}),l=0;e=Math.ceil(e/3);for(var h in b){var p=b[h].length<e+l?b[h].length:e+l;if(0<p){var q=d.create("div",{},a);d.create("br",{},q);var v=d.create("h3",{},q),v=d.create("div",{className:"collapsibleContainerHeader"},v);this._onHandles.push(u(v,"click",x.hitch(this,function(a){this._toggleSearchContainerVisibility(a)})));d.create("div",{className:"portal"===h&&
""===c?"collapseIcon collapsed":"collapseIcon"},v);d.create("div",{className:"clickable"},v).textContent=B[h];var r=""===c?"portalContentIcon contentDisabledIcon":"portalContentIcon";switch(h){case "featured":r="featuredContentIcon";break;case "user":r="userContentIcon"}d.create("div",{className:r},v);v=d.create("div",{className:"portal"===h&&""===c?"resultLayerItems hideResultLayerItems":"resultLayerItems"},q);b[h].length<p&&(p=b[h].length);for(r=0;r<p&&!(b[h].length<p&&r>=b[h].length);r++){var t=
b[h][r];if("Feature Service"===t.type&&t.title in k[h])p++;else{if("featured"===h||"portal"===h||"user"===h)this.emit("layer-found",{item:t,category:h,showCategory:"portal"!==h||""!==c}),m=!0;A(t,v,f,this._onHandles,h,w)}}p<b[h].length&&(q=d.create("div",{className:"portal"===h&&""===c?"MoreButton hide":"MoreButton"},q),q.innerHTML=n.addLayerPane.more,this._moreButtonHandles[h]=u(q,"click",function(a,b,c,d,e){this._moreResults(a,this._numberOfMoreItem,b,e,c,d)}.bind(this,h,c,k,p+1)))}"base"!==h&&
(l+=e-p)}m||g.remove(this._noResultContainer,"hide")},onPaneSelected:function(){this._textBox&&this._performSearch(this._textBox.get("value"))},_moreResults:function(a,b,d,c,g,f){var n=c.target?c.target:c.srcElement,k=n.previousSibling,l=this.editor.portal&&this.editor.portal.getPortalUser();c=new s;var l=this._getContentQuery(a,l,void 0!==d&&""!==d,d,2*b,f),h=b;l&&(c=this.editor.portal.queryItems(l,"featured"===a));c.then(function(b){if(b){var c=this._addLayer.bind(this),l=this._toggleLayerPopup.bind(this);
b=b.results;var r=[];r[a]=b;g=z(r,g);r=!1;b.length<h&&(h=b.length,r=!0);for(var t=0;t<h&&!(b.length<h&&t>=b.length);t++){var s=b[t];if("Feature Service"===s.type&&s.title in g[a])h++;else{if("featured"===a||"portal"===a||"user"===a)this.emit("layer-found",{item:s,category:a,showCategory:"portal"!==a||""!==d});A(s,k,c,this._onHandles,a,l)}}r&&n.parentNode.removeChild(n);this._moreButtonHandles[a]&&this._moreButtonHandles[a].remove();this._moreButtonHandles[a]=u(n,"click",function(a,b,c,d,e){this._moreResults(a,
this._numberOfMoreItem,b,e,c,d)}.bind(this,a,d,g,h+f))}}.bind(this),function(){console.log(arguments)})},_toggleContentIconVisibility:function(a){-1!==a.className.indexOf("featuredContentIcon")?(this.emit("layer-found-visible",{clear:!1,category:"featured"}),g.toggle(a,"contentDisabledIcon")):-1!==a.className.indexOf("portalContentIcon")?(this.emit("layer-found-visible",{clear:!1,category:"portal"}),g.toggle(a,"contentDisabledIcon")):-1!==a.className.indexOf("userContentIcon")&&(this.emit("layer-found-visible",
{clear:!1,category:"user"}),g.toggle(a,"contentDisabledIcon"))},_toggleSearchContainerVisibility:function(a){a=a.target?a.target:a.srcElement;-1===a.className.indexOf("collapsibleContainerHeader")&&(a=a.parentNode);var b=a.childNodes[0];this._toggleContentIconVisibility(a.childNodes[2]);g.toggle(b,"collapsed");(a=a.parentNode.nextSibling)&&g.toggle(a,"hideResultLayerItems");(a=a.nextSibling)&&g.toggle(a,"hide")}})});