// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("require dojo/_base/array ../core/declare dojo/_base/lang dojo/Deferred dojo/number ../request ../renderers/support/jsonUtils ./QueryTask ./Task ./support/StatisticDefinition ./support/Query".split(" "),function(p,m,q,e,r,l,s,t,u,v,n,w){return q(v,{declaredClass:"esri.tasks.GenerateRendererTask",constructor:function(){this._handler=e.hitch(this,this._handler);this._handleExecuteResponse=this._handleExecuteResponse.bind(this)},normalizeCtorArgs:function(a,c){if(e.isObject(a)&&("esri.layers.FeatureLayer"===
a.declaredClass||"esri.layers.CSVLayer"===a.declaredClass)){var d=a,g=e.mixin({featureLayer:d},c);"string"===typeof d.url&&"esri.layers.CSVLayer"!==d.declaredClass&&(g.url=d.url);return g}return this.inherited(arguments)},_parsedUrlGetter:function(a){var c=this.inherited(arguments);c.path+="/generateRenderer";return c},source:null,gdbVersion:null,checkValueRange:null,_handleExecuteResponse:function(a){var c;"esri.renderer.ClassBreaksRenderer"===a.declaredClass||"esri.renderer.UniqueValueRenderer"===
a.declaredClass?c=a:(c=t.fromJSON(a),"classBreaks"===a.type&&c.setMaxInclusive(!0));if(!this.checkValueRange)return this._processRenderer(c,this._prefix,this._unitLabel,this._formatLabel,this._precision);a=new u(this.url);var d=new n({statisticType:"min",onStatisticField:this._field}),g=new n({statisticType:"max",onStatisticField:this._field}),d=new w({outStatistics:[d,g]});return a.execute(d).then(e.hitch(this,function(a){a=a.features[0].attributes;for(var d in a)if(0===d.toLowerCase().indexOf("min"))var f=
a[d];else var b=a[d];return this._processRenderer(c,this._prefix,this._unitLabel,this._formatLabel,this._precision,f,b)}))},_processRenderer:function(a,c,d,g,h,k,f){"esri.renderer.ClassBreaksRenderer"===a.declaredClass?m.forEach(a.infos,function(b,e){0===e&&(void 0!==k&&null!==k)&&(b.minValue=k);e===a.infos.length-1&&(void 0!==f&&null!==f)&&(b.classMaxValue=b.maxValue=f);h&&(b.classMaxValue=b.maxValue=Math.round(b.maxValue/h)*h,b.minValue=Math.round(b.minValue/h)*h);g&&(b.label=l.format(b.minValue)+
" - "+l.format(b.maxValue));c&&(b.label=c+" "+b.label);d&&(b.label=b.label+" "+d)}):m.forEach(a.infos,function(b,e){0===e&&(void 0!==k&&null!==k)&&(b.value=k);e===a.infos.length-1&&(void 0!==f&&null!==f)&&(b.value=f);g&&(b.label=l.format(b.value));c&&(b.label=c+" "+b.label);d&&(b.label=b.label+" "+d)});return a},execute:function(a){var c;this._precision=a.precision;this._prefix=a.prefix;this._unitLabel=a.unitLabel;this._formatLabel=a.formatLabel;if(this._features=a.features||this._getCollectionFeatures()){c=
new r;var d=this._features;p(["./support/generateRenderer"],function(e){var f;"esri.tasks.ClassBreaksDefinition"===a.classificationDefinition.declaredClass?f=e.createClassBreaksRenderer({features:d,definition:a.classificationDefinition}):"esri.tasks.UniqueValueDefinition"===a.classificationDefinition.declaredClass&&(f=e.createUniqueValueRenderer({features:d,definition:a.classificationDefinition}));f?c.resolve(this._handleExecuteResponse(f)):c.reject()});return c.promise}var g=e.mixin(a.toJSON(),{f:"json"});
this._field="esri.tasks.ClassBreaksDefinition"===a.classificationDefinition.declaredClass?a.classificationDefinition.classificationField:a.classificationDefinition.attributeField;if(this.source){var h={source:this.source.toJSON()};g.layer=JSON.stringify(h)}this.gdbVersion&&(g.gdbVersion=this.gdbVersion);return s({url:this.parsedUrl.path,content:g,callbackParamName:"callback"}).then(this._handleExecuteResponse)},_getCollectionFeatures:function(){var a=this.featureLayer;return a&&a.hasMemorySource&&
a.graphics}})});