// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/on ../../core/declare ../../core/Accessor ../../core/Evented ../../core/watchUtils ../../geometry/Point ../../geometry/support/webMercatorUtils ../../geometry/SpatialReference ./support/ViewReadyMixin ./support/sunUtils ./support/earthUtils ./environment/EnvironmentRenderer".split(" "),function(m,f,n,p,q,b,h,r,k,s,l,g,t){function e(a){a.remove()}var d=new Date,u={hours:0,minutes:0,seconds:0};return n([p,q,s],{declaredClass:"esri.views.3d.SceneViewEnvironmentManager",referencePointUpdateInterval:3E3,
referencePointUpdateDistThreshold:1E6,classMetadata:{properties:{realisticAtmosphere:{getter:function(){return this._realisticAtmosphere},setter:function(a){a=!!a;a!==this._realisticAtmosphere&&(this._transparentGround?this._realisticAtmosphere=!1:(this._realisticAtmosphere=a,this._environmentRenderer.realistic=a));return this._realisticAtmosphere}},transparentGround:{getter:function(){return this._transparentGround},setter:function(a){a=!!a;a!==this._transparentGround&&(this._transparentGround=a,
this._environmentRenderer.transparent=a,this.realisticAtmosphere=!a&&this.realisticAtmosphere);return a}},lightingReady:{readOnly:!0,getter:function(){return this._lightingReady}},updating:{readOnly:!0,getter:function(){return!!this._referencePosUpdateQuery||null!=this._referencePosUpdateTimer}}}},getDefaults:function(){return m.mixin({autoAdjustTimezone:!0},this.inherited(arguments))},constructor:function(){this._lightingReady=!1;this._lastTz={hours:0,minutes:0,seconds:0};this._viewHandles=[];this._environmentHandles=
[];this._lightingHandles=[];this._atmosphereHandles=[];this._autoAdjustTimezone=!0;this._pendingCameraChange=this._cameraHandle=null;this._realisticAtmosphere=!1;this._basemapTerrainLoadHandle=this._environmentRenderer=null;this._blockUpdate=!1;this._resetReferencePosition();for(var a="environment spatialReference globeMode camera interacting lighting atmosphere lightingDate lightingDirectShadows lightingAmbientOcclusion atmosphereEnabled".split(" "),c=0;c<a.length;c++){var b="_"+a[c]+"Handler";this[b]=
this[b].bind(this)}},dispose:function(){this._disconnectView();this._resetReferencePosition()},_viewSetter:function(a){this.inherited(arguments);this._autoAdjustTimezoneDisconnect();this._cancelReferencePosUpdates();a&&(this._autoAdjustTimezoneConnect(a),this._viewHandles.push(a.watch("spatialReference",this._spatialReferenceHandler)));return a},_connectView:function(a){this._blockUpdate=!0;this._viewHandles.push(a.watch("interacting",this._interactingHandler),b.init(a,"environment",this._environmentHandler),
b.init(a,"globeMode",this._globeModeHandler),b.init(a.basemapTerrain,"opacity,wireframe",function(){this._environmentRenderer&&(this.transparentGround=this._testTerrainTransparency())}.bind(this)));this._blockUpdate=!1;(a=this.get("view.environment.lighting.date"))&&this._updateLight(a);this._pendingCameraChange&&(this._cameraHandler(this._pendingCameraChange),this._pendingCameraChange=null)},_disconnectView:function(a){this._viewHandles.forEach(e);this._viewHandles.length=0;this._environmentHandler(null)},
_spatialReferenceHandler:function(){this._resetReady()},_globeModeHandler:function(a){this._environmentRenderer&&(this._environmentRenderer.planar="planar"===a);this._resetReady();this._updateLight(this.get("view.environment.lighting.date"))},_resetReady:function(){var a="spherical"===this.view.globeMode;a!==this._lightingReady&&(this._lightingReady=a,this._resetReferencePosition(),this.notifyChange("lightingReady"));this._pushReadyToLighting()},_setReady:function(){this._lightingReady||(this._lightingReady=
!0,this._updateLight(this.get("view.environment.lighting.date")),this.notifyChange("lightingReady"));this._pushReadyToLighting()},_pushReadyToLighting:function(){var a=this.view.environment.lighting;a.ready!==this._lightingReady&&(a._ready=this._lightingReady,a.notifyChange("ready"))},_environmentHandler:function(a){this._environmentHandles.forEach(e);this._environmentHandles.length=0;a?this._environmentHandles.push(b.init(this.view.get("environment"),"lighting",this._lightingHandler),b.init(this.view.get("environment"),
"atmosphere",this._atmosphereHandler)):(this._lightingHandler(null),this._atmosphereHandler(null))},_disableAtmosphere:function(){this._basemapTerrainLoadHandle&&(this._basemapTerrainLoadHandle.remove(),this._basemapTerrainLoadHandle=null);this._environmentRenderer&&(this._environmentRenderer.destroy(),this._environmentRenderer=null)},_atmosphereHandler:function(a){this._atmosphereHandles.forEach(e);this._atmosphereHandles.length=0;a?this._atmosphereHandles.push(b.init(a,"enabled",this._atmosphereEnabledHandler)):
this._disableAtmosphere()},_testTerrainTransparency:function(){return this.view.basemapTerrain&&this.view.basemapTerrain._renderer.isTransparent()},_atmosphereEnabledHandler:function(a){var c="planar"===this.view.globeMode;a=a&&this.view.basemapTerrain;!a&&this._environmentRenderer?this._disableAtmosphere():a&&!this._environmentRenderer&&(this._environmentRenderer=new t({view:this.view,realistic:this._realisticAtmosphere,planar:c,transparent:this._testTerrainTransparency()}),this.view.basemapTerrain.loaded||
c?this._environmentRenderer.init():this._basemapTerrainLoadHandle=this.view.basemapTerrain.on("load",function(){this._environmentRenderer.init();this._basemapTerrainLoadHandle.remove();this._basemapTerrainLoadHandle=null}.bind(this)))},_lightingHandler:function(a){this._lightingHandles.forEach(e);this._lightingHandles.length=0;return a?(this._lightingHandles.push(b.init(a,"date",this._lightingDateHandler),b.init(a,"directShadows",this._lightingDirectShadowsHandler),b.init(a,"ambientOcclusion",this._lightingAmbientOcclusionHandler)),
this._pushReadyToLighting(),!0):!1},_lightingDateHandler:function(a){this.lightingReady&&this._updateLight(a)},_lightingDirectShadowsHandler:function(a){this.view.setRenderingParameters({shadowMap:a})},_lightingAmbientOcclusionHandler:function(a){this.view.setRenderingParameters({ssao:a})},_autoAdjustTimezoneDisconnect:function(){this._cameraHandle&&(this._cameraHandle.remove(),this._cameraHandle=null)},_autoAdjustTimezoneConnect:function(a){this._cameraHandle=a.watch("camera",this._cameraHandler);
b.whenOnce(a,"camera",function(a){g.positionToTimezone(a.position,this._lastTz);this.autoAdjustTimezone&&f.emit(this,"_timezone-change",this._lastTz.hours)})},_autoAdjustTimezoneGetter:function(){return this._autoAdjustTimezone},_autoAdjustTimezoneSetter:function(a){this._autoAdjustTimezone!==a&&(this._autoAdjustTimezone=a)&&(this.view&&this.view.camera)&&g.positionToTimezone(this.view.camera.position,this._lastTz)},_cameraHandler:function(a){if(a){var c=a.position;"spherical"===this.view.globeMode?
(this._referencePosWGS84||(this._referencePosWGS84=new h({spatialReference:k.WGS84})),r.webMercatorToGeographic(c,!1,this._referencePosWGS84),this._referencePosWGS84.z=c.z,this.view.mapCoordsHelper&&(this._referencePosWGS84.z*=this.view.mapCoordsHelper.mapUnitInMeters),this.autoAdjustTimezone&&this._updateTimezone(c)):this.view.ready?(!this._referencePosMapCoords||this._exceedsReferencePosDistThreshold(c))&&this._requestReferencePositionUpdate(c):this._pendingCameraChange=a}},_interactingHandler:function(a){a||
this._executePendingReferencePositionUpdate()},_updateLight:function(a){if(!this._blockUpdate)if(this._referencePosWGS84){var c=l.computeColorAndIntensity(a,this._referencePosWGS84);l.computeDirection(a,this._referencePosWGS84,this.view.globeMode,c.diffuse.direction);this.view.setLightingParameters(c);f.emit(this,"_date-change",a)}else this.view.setLightingParameters({diffuse:{color:[1,1,1],intensity:0.5,direction:this.view.renderCoordsHelper.worldUp},ambient:{color:[1,1,1],intensity:0.5}})},_updateTimezone:function(a){d.setTime(this.view.get("environment").lighting.date.getTime());
a=g.positionToTimezone(a,u);var c=d.getUTCHours()-(a.hours-this._lastTz.hours),b=d.getUTCMinutes()-(a.minutes-this._lastTz.minutes),e=d.getUTCSeconds()-(a.seconds-this._lastTz.seconds);d.setUTCHours(c);d.setUTCMinutes(b);d.setUTCSeconds(e);a.hours!==this._lastTz.hours&&f.emit(this,"_timezone-change",a.hours);this._blockUpdate=!0;this.view.get("environment").lighting.date=d;this._blockUpdate=!1;this._updateLight(d);this._lastTz.hours=a.hours;this._lastTz.minutes=a.minutes;this._lastTz.seconds=a.seconds},
_resetReferencePosition:function(){this._cancelReferencePosUpdates();this._referencePosWGS84=this._referencePosMapCoordsDesired=this._referencePosMapCoords=null},_requestReferencePositionUpdate:function(a){this.view.mapCoordsHelper.canProject()&&(this._referencePosUpdateQuery||null!=this._referencePosUpdateTimer||this.view.interacting?this._referencePosMapCoordsDesired?this._referencePosMapCoordsDesired.copy(a):this._referencePosMapCoordsDesired=a.clone():(this._referencePosMapCoords?this._referencePosMapCoords.copy(a):
this._referencePosMapCoords=a.clone(),this._referencePosUpdateQuery=this.view.mapCoordsHelper.toGeographic(this._referencePosMapCoords).then(function(a){this._referencePosUpdateQuery=null;if(!isNaN(a[0])&&!isNaN(a[1])){var b=this._referencePosMapCoords.z*this.view.mapCoordsHelper.mapUnitInMeters;this._referencePosWGS84?(this._referencePosWGS84.x=a[0],this._referencePosWGS84.y=a[1],this._referencePosWGS84.z=b):this._referencePosWGS84=new h({x:a[0],y:a[1],z:b,spatialReference:k.WGS84});this._referencePosChanged();
null==this._referencePosUpdateTimer&&this._executePendingReferencePositionUpdate()}this.notifyChange("updating")}.bind(this),function(a){this._referencePosUpdateQuery=null;this.notifyChange("updating")}.bind(this)),this._referencePosUpdateTimer=window.setTimeout(function(){this._referencePosUpdateTimer=null;this._referencePosUpdateQuery||this._executePendingReferencePositionUpdate();this.notifyChange("updating")}.bind(this),this.referencePointUpdateInterval),this.notifyChange("updating")))},_executePendingReferencePositionUpdate:function(){var a=
this._referencePosMapCoordsDesired;a&&this._exceedsReferencePosDistThreshold(a)&&(this._referencePosMapCoordsDesired=null,this._requestReferencePositionUpdate(a))},_referencePosChanged:function(){this.autoAdjustTimezone&&this._updateTimezone(this._referencePosWGS84);this._setReady()},_exceedsReferencePosDistThreshold:function(a){return this._referencePosMapCoords?(a=this._referencePosMapCoords.distance(a),this.view.mapCoordsHelper&&(a*=this.view.mapCoordsHelper.mapUnitInMeters),a>this.referencePointUpdateDistThreshold):
!0},_cancelReferencePosUpdates:function(){this._referencePosUpdateQuery&&(this._referencePosUpdateQuery.cancel(),this._referencePosUpdateQuery=null);null!=this._referencePosUpdateTimer&&(window.clearTimeout(this._referencePosUpdateTimer),this._referencePosUpdateTimer=null)}})});