// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define({moveUp:"Flyt op",moveDown:"Flyt ned",rename:"Omd\u00f8b",hideInMapLayers:"Skjul i lag",showInMapLayers:"Vis i lag",invalidTitle:"Titlen m\u00e5 ikke indeholde f\u00f8lgende tegn: \x3c or \x3e.",header:{home_link:"Hjem",simpleHome:"Hjem",support:"Hj\u00e6lp",features:"Funktioner",myAccount:"Min organisation",myProfile:"Min profil",help:"Hj\u00e6lp",plans:"Planer",adminGuide:"Administratorvejledning",signOut:"Log ud",signIn:"Log ind",newScene:"Ny scene",gallery:"Galleri",groups:"Grupper",myContent:"Mit indhold",
esriCommunity:"F\u00e6llesskab og fora",myEsri:"My Esri",map:"Kort",training:"Uddannelse",trialDownloads:"Download af pr\u00f8veversioner",fullScreen:"Udforsk i Fuld visning",newGlobal:"Ny global scene",newLocal:"Ny lokal scene",globalScene:"Global scene",localScene:"Lokal scene",spatialRef:"Spatial reference"},environmentSettings:{dragSunSliderText:"Tr\u00e6k skyderen for at \u00e6ndre tidspunkt.",dragSunSliderHint:"Tr\u00e6k skyder",sunLight:"Solskin",sunrise:"solopgang",sunset:"solnedgang",shadowing:"Skygger",
directShadow:"Direkte skygge (kastet af solskinnet)",diffuseShadow:"Diffuse skygger (omgivende okklusion)"},layerItemEditable:{groupTypeCheckbox:"Afkrydsningsfelt",groupTypeRadio:"Radio",groupTypeCompact:"Sammenl\u00e6g",groupTypeHide:"Skjul",configureLayer:"Konfigur\u00e9r lag",zoomToLayer:"Zoom til",deleteLayer:"Fjern",dragHere:"Tr\u00e6k laget herhen",changeGroupType:"Redig\u00e9r gruppetype"},slideDeckEditable:{addSlide:"Optag dias",slide:"Dias",updateSlide:"Opdat\u00e9r dias",deleteSlide:"Fjern dias"},
symbologyEditor:{symbologyShieldWarning:"Dette lags symbologi kan ikke redigeres. Klik p\u00e5 OK for at fjerne den eksisterende symbologi og definere ny symbologi.",colorOverride:"Tilsides\u00e6tning af farver",fill:"Fyld",outline:"Yderlinje",shape:"Form",color:"Farve",size:"St\u00f8rrelse",symbols:"Symboler",transparency:"Gennemsigtighed (%)",ok:"OK",px:"px",points:"punkter",meters:"meter",feet:"fod",reset:"Nulstil",originalSymbology:"Originale symboler",modifySymbology:"Redig\u00e9r symboler",
customize:"Tilpas",type:"Type",icon2d:"2D-ikon",object3D:"3D-objekt",line2d:"2D-linje",line3d:"3D-linje",path3d:"3D-sti",polygon2d:"2D-polygon",polygon3d:"3D-ekstrudering",fillColor:"Fyldfarve",outlineColor:"Konturfarve",outlineSize:"Konturst\u00f8rrelse",shapes:{circle:"Cirkel",cone:"Kegle",cross:"Kors",cube:"Terning",cylinder:"Cylinder",diamond:"Diamant",kite:"Drage",sphere:"Sf\u00e6re",square:"Firkant",tetrahedron:"Pyramideform",x:"X"},extrusion:"Ekstrudering (meter)",rangeMsg:"V\u00e6rdi er uden for omr\u00e5det. Angiv en v\u00e6rdi mellem ${minSize} og ${maxSize}"},
mapControls:{zoomIn:"Zoom ind",zoomOut:"Zoom ud",rotate:"Rot\u00e9r",home:"F\u00f8rste visning",pan:"Panor\u00e9r",panRotateToggle:"Skift for at panorere eller rotere i 3D"},switchControl:{on:"til",off:"fra"},settings:{navigation:"3D-navigation",proNav:"ArcGIS Pro",sceneNav:"Standard",mouseImage:"Tildeling af museknapper til 3D-navigation"},share:{text:"V\u00e6lg en af nedenst\u00e5ende indstillinger for at dele denne scene.",link:"Del et link til denne scene",embed:"Indlejr denne scene i et websted",
more:"Indlejringsindstillinger",smallSize:"Lille",mediumSize:"Mellem",largeSize:"Stor",customSize:"Brugerdefineret",shareTwitterTxt:"Udforsk '${sceneName}'  i 3D med din browser:n",shareEmailSubject:"${sceneName}  i 3D (Sceneviser)",shareEmailTxt1:"Kast et blik p\u00e5 denne webscene:",shareEmailTxt2:"Du kan oprette og dele dine egne 3D-webscener med Esri-sceneviseren. Bes\u00f8g http://www.arcgis.com, og klik p\u00e5 'Scene' for at pr\u00f8ve det gratis.",shortenLink:"Kort link",shareUnsaved:"Denne scene indeholder ikke-gemte \u00e6ndringer. Du skal gemme \u00e6ndringerne for at kunne dele scenen.",
shareNotPublic:"Denne scene er ikke blevet delt med offentligheden. Folk vil muligvis ikke kunne se den.",shareNotPublicLayer:"Mindst \u00e9t lag i denne scene er ikke offentligt tilg\u00e6ngeligt. Folk kan muligvis ikke se alle lagene.",changeShareSettings:"Redig\u00e9r delingsindstillinger"},underground:{seeThroughGround:"Se gennem jorden"},basemapGallery:{SRMismatch:"Spatial reference er inkompatibel med scenen",SRMismatchGlobal:"Spatial reference underst\u00f8ttes ikke i globale scener",TSMismatch:"Tile-skema er inkompatibel med scenen",
TilingScheme:"Tile-skema overholder ikke ArcGIS Online-tile-skemaet.",tilingSchemePowerOfTwo:"Ikke-kompatibelt tile-skema: hver m\u00e5lestok skal v\u00e6re n\u00f8jagtigt halvt s\u00e5 stor som m\u00e5lestokken for det forrige niveau.",tilingSchemeTileSize:"Ikke-kompatibelt tile-skema: kun tiles med en bredde og h\u00f8jde p\u00e5 256 underst\u00f8ttes.",tiledMapServiceSRGCS:"Tile-kortlag i geografiske koordinatsystemer underst\u00f8ttes ikke.",tiledMapServicesMinVersion:"Tile-kortlag p\u00e5 servere f\u00f8r version 10.2.2 underst\u00f8ttes ikke.",
basemapLayerTypeWMS:"OGC Web Map Service (WMS) underst\u00f8ttes ikke som baggrundskort.",basemapLayerTypeWMTS:"OGC Web Tile Map Service (WMTS) underst\u00f8ttes ikke som baggrundskort.",basemapLayerTypeWTL:"Web-tile-lag underst\u00f8ttes ikke som baggrundskort.",basemapLayerTypeDMS:"Dynamisk korttjenestelag underst\u00f8ttes ikke som baggrundskort.",basemapLayerTypeIS:"Billedtjenestelag underst\u00f8ttes ikke som baggrundskort.",noBasemap:"Intet baggrundskort"},compass:{compass:"Kompas"}});