// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/map/dijit/toc/filterEdits",["dijit","dojo","dojox","dojo/require!arcgisonline/map/main"],function(m,b,n){b.provide("arcgisonline.map.dijit.toc.filterEdits");b.require("arcgisonline.map.main");arcgisonline.map.dijit.toc.filterEdits={filterEditsUserOptions:null,filterEditsTimeOptions:null,filterEditsLayerId:-1,filterEditsUserOptionsChangeHandler:null,filterEditsTimeOptionsChangeHandler:null,isShowAllEdits:function(a){if(arcgisonline.map.editTracking.hasEditTracking(a)){var b=a.layer.getDefinitionExpression();
if(b){var d=a.serviceInfo.editFieldsInfo.creatorField,f=a.serviceInfo.editFieldsInfo.creationDateField,e=a.serviceInfo.editFieldsInfo.editorField;a=a.serviceInfo.editFieldsInfo.editDateField;if(d&&-1<b.indexOf(d)||f&&-1<b.indexOf(f)||e&&-1<b.indexOf(e)||a&&-1<b.indexOf(a))return!0}}return!1},showAllEdits:function(a){var g="";a.layerDefinition&&a.layerDefinition.definitionExpression&&(g=a.layerDefinition.definitionExpression);a.layer.setDefinitionExpression(g);delete a.editTrackingFilter;arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions&&
arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions.set("value",esri.i18nBundle.tocPanel.everyone);arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions&&arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions.set("value",esri.i18nBundle.tocPanel.timeRangeAll);b.style(b.byId("layerMenu.showAllEdits"),"display","none");b.style(b.byId("layerMenu.filterSeparator"),"display","none")},filterEdits:function(a){esriGeowConfig.isRightToLeft?b.attr(b.byId("layerMenu.filterEditsDlg"),
"class","dijitTooltipDialog dijitTooltipABRight dijitTooltipLeft"):b.attr(b.byId("layerMenu.filterEditsDlg"),"class","dijitTooltipDialog dijitTooltipABLeft dijitTooltipRight");b.forEach(b.query(".dijitTooltipConnector"),function(a){b.style(a,"top","6px")});arcgisonline.map.dijit.toc.filterEdits.displayFilterEdits(a)},displayFilterEdits:function(a){if(!arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions){arcgisonline.map.dijit.toc.filterEdits._filterEditsQuery(a);var g=-1,d=esri.i18nBundle.tocPanel.filterEditsText.indexOf("${",
g),f=esri.i18nBundle.tocPanel.filterEditsText.substring(g+1,d),g=esri.i18nBundle.tocPanel.filterEditsText.indexOf("}",d),d=esri.i18nBundle.tocPanel.filterEditsText.length,g=esri.i18nBundle.tocPanel.filterEditsText.substring(g+1,d);b.byId("layerMenu.filterEditsText1").innerHTML=f;b.byId("layerMenu.filterEditsText2").innerHTML=g;arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions=m.byId("layerMenu.filterEditsUserOptions");options=new b.data.ItemFileWriteStore({data:{identifier:"name",items:[]}});
options.newItem({name:esri.i18nBundle.tocPanel.everyone,id:"0"});arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions.set("store",options);a.editTrackingFilter&&a.editTrackingFilter.user?arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions.set("value",a.editTrackingFilter.user):arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions.set("value",esri.i18nBundle.tocPanel.everyone);arcgisonline.map.dijit.toc.filterEdits._fixComboboxWidth(arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions);
arcgisonline.sharing.util.isHostedService(a.url)&&(b.style(b.byId("layerMenu.filterEditsTimeOptionsDiv"),"display","inline"),arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions=m.byId("layerMenu.filterEditsTimeOptions"),options=new b.data.ItemFileWriteStore({data:{identifier:"name",items:[]}}),options.newItem({name:esri.i18nBundle.tocPanel.timeRangeAll,id:"0"}),arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions.set("store",options),a.editTrackingFilter&&a.editTrackingFilter.time?
arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions.set("value",a.editTrackingFilter.time):arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions.set("value",esri.i18nBundle.tocPanel.timeRangeAll),arcgisonline.map.dijit.toc.filterEdits._fixComboboxWidth(arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions));setTimeout(function(){arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptionsChangeHandler=b.connect(arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions,
"onChange",function(){arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions&&arcgisonline.map.dijit.toc.filterEdits._updateFilterEditsTimeOptions(a);arcgisonline.map.dijit.toc.filterEdits._updateLayerFilter(a)});arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions&&(arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptionsChangeHandler=b.connect(arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions,"onChange",function(){arcgisonline.map.dijit.toc.filterEdits._updateLayerFilter(a)}))},
1E3)}},_filterEditsQuery:function(a){arcgisonline.map.editTracking.filterEditsQuery(a,function(){arcgisonline.map.dijit.toc.filterEdits._updateFilterEditsUserOptions(a,!0);arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions&&arcgisonline.map.dijit.toc.filterEdits._updateFilterEditsTimeOptions(a,!0)})},_updateFilterEditsUserOptions:function(a,g){if(a.trackedEdits){var d=new b.data.ItemFileWriteStore({data:{identifier:"name",items:[]}});d.newItem({name:esri.i18nBundle.tocPanel.everyone});
var f=[];a.trackedEdits.created&&b.forEach(a.trackedEdits.created.features,function(b,g){var c=b.attributes[a.serviceInfo.editFieldsInfo.creatorField];c&&(d.newItem({name:c}),f.push(c))});a.trackedEdits.edited&&b.forEach(a.trackedEdits.edited.features,function(e,g){var c=e.attributes[a.serviceInfo.editFieldsInfo.editorField];c&&-1==b.indexOf(f,c)&&d.newItem({name:c})});arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions.set("store",d);g&&a.editTrackingFilter&&a.editTrackingFilter.user?arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions.set("value",
a.editTrackingFilter.user):arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions.set("value",esri.i18nBundle.tocPanel.everyone);arcgisonline.map.dijit.toc.filterEdits._fixComboboxWidth(arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions)}},_updateFilterEditsTimeOptions:function(a,g){if(arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions&&a.trackedEdits){var d=new b.data.ItemFileWriteStore({data:{identifier:"name",items:[]}});d.newItem({name:esri.i18nBundle.tocPanel.timeRangeAll});
if(arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions.get("value")==esri.i18nBundle.tocPanel.everyone){var f=a.trackedEdits.all.attributes.MinCreateDate,e=a.trackedEdits.all.attributes.MaxCreateDate;a.trackedEdits.all.attributes.MinEditedDate&&a.trackedEdits.all.attributes.MaxEditedDate&&(f=!f?a.trackedEdits.all.attributes.MinEditedDate:Math.min(f,a.trackedEdits.all.attributes.MinEditedDate),e=!e?a.trackedEdits.all.attributes.MaxEditedDate:Math.max(e,a.trackedEdits.all.attributes.MaxEditedDate));
d=arcgisonline.map.editTracking.filterTimeRangeOptions(d,f,e)}else if(a.trackedEdits.created)for(var h=0;h<a.trackedEdits.created.features.length;h++){var c=a.trackedEdits.created.features[h];if(c.attributes[a.serviceInfo.editFieldsInfo.creatorField]==arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions.get("value")){f=c.attributes.MinCreateDate;e=c.attributes.MaxCreateDate;if(a.trackedEdits.edited){for(var l=!1,k=0;k<a.trackedEdits.edited.features.length;k++)if(c=a.trackedEdits.edited.features[k],
c.attributes.MinEditedDate&&c.attributes.MaxEditedDate&&c.attributes[a.serviceInfo.editFieldsInfo.editorField]==arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions.get("value")){f=!f?c.attributes.MinEditedDate:Math.min(f,c.attributes.MinEditedDate);e=!e?c.attributes.MaxEditedDate:Math.max(e,c.attributes.MaxEditedDate);d=arcgisonline.map.editTracking.filterTimeRangeOptions(d,f,e);l=!0;break}l||(d=arcgisonline.map.editTracking.filterTimeRangeOptions(d,f,e))}else d=arcgisonline.map.editTracking.filterTimeRangeOptions(d,
f,e);break}else{l=!1;for(k=0;k<a.trackedEdits.edited.features.length;k++)if(c=a.trackedEdits.edited.features[k],c.attributes.MinEditedDate&&c.attributes.MaxEditedDate&&c.attributes[a.serviceInfo.editFieldsInfo.editorField]==arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions.get("value")){f=c.attributes.MinEditedDate;e=c.attributes.MaxEditedDate;d=arcgisonline.map.editTracking.filterTimeRangeOptions(d,f,e);l=!0;break}if(l)break}}else if(a.trackedEdits.edited)for(h=0;h<a.trackedEdits.edited.features.length&&
!(c=a.trackedEdits.edited.features[h],c.attributes[a.serviceInfo.editFieldsInfo.editorField]==arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions.get("value"));h++);arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions.set("store",d);g&&a.editTrackingFilter&&a.editTrackingFilter.time?arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions.set("value",a.editTrackingFilter.time):arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions.set("value",esri.i18nBundle.tocPanel.timeRangeAll);
arcgisonline.map.dijit.toc.filterEdits._fixComboboxWidth(arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions)}},_updateLayerFilter:function(a){arcgisonline.map.editTracking.setDefinitionExpression(a,arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions.get("value"),arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions?arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions.get("value"):null);b.style(b.byId("layerMenu.showAllEdits"),"display",10>b.isIE?"inline":"");
b.style(b.byId("layerMenu.filterSeparator"),"display",10>b.isIE?"inline":"")},_clearFilterEdits:function(){b.style(b.byId("layerMenu.filterEditsTimeOptionsDiv"),"display","none");arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptionsChangeHandler&&b.disconnect(arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptionsChangeHandler);arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptionsChangeHandler&&b.disconnect(arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptionsChangeHandler);
arcgisonline.map.dijit.toc.filterEdits.filterEditsUserOptions=null;arcgisonline.map.dijit.toc.filterEdits.filterEditsTimeOptions=null},_fixComboboxWidth:function(a){var g=function(){var a=b.query("tester");if(a.length)return a;a=document.createElement("tester");document.body.appendChild(a);b.style(a,"left","-1000px");return b.query("tester")},d=function(a){var c=b.getComputedStyle(a);return a.clientWidth+parseInt(c.paddingLeft)+parseInt(c.paddingRight)},f=function(a){var b=g();b[0].innerHTML=a;return d(b[0])},
e=g();b.style(e[0],{position:"absolute",top:-9999,left:-9999,width:"auto",whiteSpace:"nowrap"});var h=a.textbox;b.style(e[0],{fontSize:b.style(h,"fontSize"),fontFamily:b.style(h,"fontFamily"),fontWeight:b.style(h,"fontWeight"),letterSpacing:b.style(h,"letterSpacing")});var c=0;a.store.fetch({query:{},onComplete:function(e){for(var g=0;g<e.length;g++){var h=a.store.getValue(e[g],"name");c=Math.max(c,f(h)+5)}c>d(a.textbox)&&(b.style(a.textbox,{width:c+"px"}),b.style(a.domNode,{width:c+25+5+"px"}))}})}}});