// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/map/dijit/toc/legend",["dijit","dojo","dojox","dojo/require!arcgisonline/map/main"],function(m,c,n){c.provide("arcgisonline.map.dijit.toc.legend");c.require("arcgisonline.map.main");arcgisonline.map.dijit.toc.legend={onRendererMouseHandlers:{move:[],out:[]},rendererToolTipOpen:!1,rendererLegendRefreshHandlers:[],showLegend:function(b,d){var a;a=b?arcgisonline.map.main.getParameterListById(b):this.isTable?this.mapTables[this.menuLayerPos]:this.mapLayers[this.menuLayerPos];var e=
a.layer instanceof esri.layers.ArcGISImageServiceLayer,g=a.layer instanceof esri.layers.ArcGISImageServiceVectorLayer,f=a.layer instanceof esri.layers.ArcGISDynamicMapServiceLayer,l=a.layer instanceof esri.layers.ArcGISTiledMapServiceLayer,h=-1;c.forEach(arcgisonline.map.main.mapLayers,function(a,c){a.id===b&&(h=c)});if(a.layers&&esri.isDefined(d)){var k=-1;c.forEach(a.layers,function(a,b){a.id==d&&(k=b)});!c.byId(a.id+"_"+d+"_legend")||0===c.byId(a.id+"_"+d+"_legend").innerHTML.length?(arcgisonline.map.dijit.toc.legend.requestLegend(h,
k),arcgisonline.map.dijit.toc.options.updateLegendTool(a,d)):c.byId(a.id+"_"+d+"_legend")&&"none"===c.style(c.byId(a.id+"_"+d+"_legend"),"display")&&(arcgisonline.map.dijit.toc.legend.displayLegend(h,k),arcgisonline.map.dijit.toc.options.updateLegendTool(a,d))}else if((f||l)&&esri.isDefined(d))d=parseInt(d),e=a.layer.dynamicLayerInfos||a.layer.layerInfos,k=-1,c.forEach(e,function(a,b){a.id==d&&(k=b)}),!c.byId(a.id+"_"+d+"_legend")||0===c.byId(a.id+"_"+d+"_legend").innerHTML.length?arcgisonline.map.dijit.toc.legend.requestLegend(h,
k,function(){arcgisonline.map.dijit.toc.options.updateLegendTool(a,d)}):c.byId(a.id+"_"+d+"_legend")&&"none"===c.style(c.byId(a.id+"_"+d+"_legend"),"display")&&(arcgisonline.map.dijit.toc.legend.displayLegend(h,k),arcgisonline.map.dijit.toc.options.updateLegendTool(a,d));else if(a.layer&&(a.layer.renderer||10.2<=a.layer.version&&(e||g)))!c.byId(a.id+"_legend")||0===c.byId(a.id+"_legend").innerHTML.length?arcgisonline.map.dijit.toc.legend.requestLegend(h,-1):c.byId(a.id+"_legend")&&"none"===c.style(c.byId(a.id+
"_legend"),"display")&&arcgisonline.map.dijit.toc.legend.displayLegend(h,-1),arcgisonline.map.dijit.toc.options.updateLegendTool(a)},hideLegend:function(b,d){var a;b?a=arcgisonline.map.main.getParameterListById(b):(a=this.isTable?this.mapTables[this.menuLayerPos]:this.mapLayers[this.menuLayerPos],b=a.id);esri.isDefined(d)?c.byId(b+"_"+d+"_legend")&&(c.style(c.byId(b+"_"+d+"_legend"),"display","none"),arcgisonline.map.dijit.toc.options.updateLegendTool(a,d)):c.byId(b+"_legend")&&(c.style(c.byId(b+
"_legend"),"display","none"),arcgisonline.map.dijit.toc.options.updateLegendTool(a))},requestLegend:function(b,d,a){var e=arcgisonline.map.main.mapLayers[b];if(e.layer&&e.layer.layerInfos||e.layer&&e.layer.renderer||e.layer&&10.2<=e.layer.version&&e.layer instanceof esri.layers.ArcGISImageServiceLayer||e.layers&&e.layers[d].renderer||e.layer instanceof esri.layers.GeoRSSLayer)if(e.legendInfo||e.layer&&e.layer.renderer||e.layers||e.layer instanceof esri.layers.GeoRSSLayer)arcgisonline.map.dijit.toc.legend.buildLegend(e),
arcgisonline.map.dijit.toc.legend.displayLegend(b,d),a&&a();else{var g;if(10.01<=e.layer.version)g=e.layer.url+"/legend",e.layer instanceof esri.layers.ArcGISImageServiceLayer&&e.layer.renderingRule&&(g+="?renderingRule\x3d"+c.toJson(e.layer.renderingRule.toJson()));else{var f=e.url.toLowerCase().indexOf("/rest/");g=e.url.substring(0,f)+e.url.substring(f+5,e.url.length)}var l={};e.layer._params&&e.layer._params.dynamicLayers&&(l.dynamicLayers=c.json.stringify(arcgisonline.map.dijit.toc.legend._createDynamicLayers(e.layer)),
"[{}]"===l.dynamicLayers&&(l.dynamicLayers="[]"));for(var f=!1,h=arcgisonline.map.main.allLegendInfos,k=0;k<h.length;k++)if(h[k].legendURL==g)if(l.dynamicLayers){if(l.dynamicLayers===h[k].dynamicLayers){e.legendInfo=h[k].legendInfo;arcgisonline.map.dijit.toc.legend.buildLegend(e);arcgisonline.map.dijit.toc.legend.displayLegend(b,d);a&&a();f=!0;break}}else{e.legendInfo=h[k].legendInfo;arcgisonline.map.dijit.toc.legend.buildLegend(e);arcgisonline.map.dijit.toc.legend.displayLegend(b,d);a&&a();f=!0;
break}f||(e.legendInfo={layers:[]},f=g,10.01>e.layer.version&&(f=esriGeowConfig.legend+"?soapUrl\x3d"+escape(g),9>c.isIE||(f+="\x26returnbytes\x3dtrue")),f+=(-1<f.indexOf("?")?"\x26":"?")+"f\x3djson",(h=e.layer._getToken())&&(f+="\x26token\x3d"+h),esri.request({url:f,content:l,callbackParamName:"callback",load:function(c,f){c&&c.layers&&(arcgisonline.map.main.allLegendInfos.push({legendURL:g,legendInfo:c,dynamicLayers:l.dynamicLayers?l.dynamicLayers:null}),e.legendInfo=c,arcgisonline.map.dijit.toc.legend.buildLegend(e),
arcgisonline.map.dijit.toc.legend.displayLegend(b,d),a&&a())},error:function(a,b){}}))}},buildLegend:function(b){if(b.layer&&b.layer.layerInfos)if(arcgisonline.map.main.hasDynamicLayers(b))c.forEach(b.layer.dynamicLayerInfos,function(a){(!b.thematicGroup||!(b.thematicGroup.layerIds&&-1==c.indexOf(b.thematicGroup.layerIds,a.id)))&&arcgisonline.map.dijit.toc.legend.buildLegendItems_Service(b.id+"_"+a.id,b,a)});else for(var d=0;d<b.layer.layerInfos.length;d++)arcgisonline.map.dijit.toc.legend.buildLegendItems_Service(b.id+
"_"+b.layer.layerInfos[d].id,b,b.layer.layerInfos[d]);else b.layers?c.forEach(b.layers,function(a,c){arcgisonline.map.dijit.toc.legend.buildLegendItems_Renderer(b.id+"_"+a.id,a.renderer,a,b)}):b.layer instanceof esri.layers.GeoRSSLayer?(d=b.layer.getFeatureLayers(),1===d.length?arcgisonline.map.dijit.toc.legend.buildLegendItems_Renderer(b.id,d[0].renderer,d[0],b):c.forEach(d,function(a,c){arcgisonline.map.dijit.toc.legend.buildLegendItems_Renderer(b.id+"_"+a.id,a.renderer,a,b)})):b.layer&&10.2<=b.layer.version&&
b.layer instanceof esri.layers.ArcGISImageServiceLayer?arcgisonline.map.dijit.toc.legend.buildLegendItems_Service(b.id,b,{id:0}):b.layer.renderer&&!(b.layer instanceof esri.layers.ArcGISImageServiceVectorLayer)?arcgisonline.map.dijit.toc.legend.buildLegendItems_Renderer(b.id,b.layer.renderer,b.layer,b):b.layer.renderer&&b.layer.renderer.renderer&&arcgisonline.map.dijit.toc.legend.buildLegendItems_Renderer(b.id,b.layer.renderer.renderer,b.layer,b)},buildLegendItems_Service:function(b,d,a){var e=c.byId(b+
"_legend");if(e){var g=[];d.layer.dynamicLayerInfos?c.forEach(d.layer.dynamicLayerInfos,function(b){b.id!==a.id&&!b.subLayerIds&&g.push(b.id)}):d.layer.layerInfos&&c.forEach(d.layer.layerInfos,function(b){b.id!==a.id&&!b.subLayerIds&&g.push(b.id)});d=[{layer:d.layer,hideLayers:g,title:" "}];m.byId(b+"_legend")&&m.byId(b+"_legend").destroy();(new esri.dijit.Legend({layerInfos:d,map:arcgisonline.map.main.map,arrangement:esri.dijit.Legend.ALIGN_LEFT,respectCurrentMapScale:!1,respectVisibility:!1},e)).startup()}},
buildLegendItems_Renderer:function(b,d,a,e){e=c.byId(b+"_legend");var g=[{layer:a,title:" ",defaultSymbol:d.defaultSymbol&&d.defaultLabel?!0:!1}];m.byId(b+"_legend")&&m.byId(b+"_legend").destroy();g=new esri.dijit.Legend({layerInfos:g,map:arcgisonline.map.main.map,arrangement:esri.dijit.Legend.ALIGN_LEFT,respectCurrentMapScale:!1,respectVisibility:!1},e);arcgisonline.map.dijit.toc.legend.rendererLegendRefreshHandlers[a.id]&&(c.disconnect(arcgisonline.map.dijit.toc.legend.rendererLegendRefreshHandlers[a.id]),
delete arcgisonline.map.dijit.toc.legend.rendererLegendRefreshHandlers[a.id]);var f=function(a,b,d){return d&&(d=c.filter(d,function(c){return esri.isDefined(b)?c.type===a&&c.target===b:c.type===a&&!c.target}),d.length)?d[0]:null}("sizeInfo",null,a.renderer.visualVariables);f&&"object"===typeof f.minSize&&(arcgisonline.map.dijit.toc.legend.rendererLegendRefreshHandlers[a.id]=arcgisonline.map.main.map.on("extent-change",c.hitch(this,function(a,b,c,d){d.levelChange&&c.refresh([{layer:a,title:" ",defaultSymbol:b.defaultSymbol&&
b.defaultLabel?!0:!1}])},a,d,g)));g.startup();a=!1;if(d instanceof esri.renderer.TemporalRenderer||d instanceof esri.renderer.UniqueValueRenderer||d instanceof esri.renderer.ClassBreaksRenderer||d instanceof esri.renderer.SimpleRenderer||d instanceof esri.renderer.HeatmapRenderer||d.defaultSymbol&&d.defaultLabel)a=!0;if(!a&&(c.style(e,"height","0px"),b=c.byId(b+"_a")))b.onclick=null,c.removeClass(b,"toc_name")},displayLegend:function(b,d){var a=arcgisonline.map.main.mapLayers[b];if(a.legendInfo||
a.layer&&a.layer.renderer||a.layers||a.layer instanceof esri.layers.GeoRSSLayer)if(-1<d)if(a.layers)c.style(c.byId(a.id+"_"+a.layers[d].id+"_legend"),"display","block");else if(a.layer instanceof esri.layers.GeoRSSLayer)c.style(c.byId(a.id+"_"+a.layer.getFeatureLayers()[d].id+"_legend"),"display","block");else if(arcgisonline.map.main.hasDynamicLayers(a)){var e=a.layer.dynamicLayerInfos[d];c.style(c.byId(a.id+"_"+e.id+"_legend"),"display","block")}else a.layer&&(e=a.layer.layerInfos[d],c.style(c.byId(a.id+
"_"+e.id+"_legend"),"display","block"));else c.style(c.byId(a.id+"_legend"),"display","block")},buildRendererHover:function(b,d){if(d){var a=c.byId(b+"_legend");arcgisonline.map.dijit.toc.legend.onRendererMouseHandlers.move[b]=c.connect(a,"onmousemove",c.partial(function(a,b){arcgisonline.map.dijit.toc.legend.mouseX=b.clientX;arcgisonline.map.dijit.toc.legend.mouseY=b.clientY;arcgisonline.map.dijit.toc.legend.rendererToolTipOpen&&(arcgisonline.map.dijit.toc.legend.rendererToolTipOpen=!1,c.style(c.byId("toc_rendererHoverTooltip"),
"display","none"));setTimeout(c.partial(function(a,b,d){a==arcgisonline.map.dijit.toc.legend.mouseX&&(b==arcgisonline.map.dijit.toc.legend.mouseY&&!arcgisonline.map.dijit.toc.legend.rendererToolTipOpen)&&(arcgisonline.map.dijit.toc.legend.rendererToolTipOpen=!0,c.byId("toc_rendererHoverTooltip")?(c.byId("toc_rendererHoverTooltip").innerHTML="\x3cspan\x3e"+d+"\x3c/span\x3e",c.style(c.byId("toc_rendererHoverTooltip"),"top",b+"px"),c.style(c.byId("toc_rendererHoverTooltip"),"left",a+15+"px"),c.style(c.byId("toc_rendererHoverTooltip"),
"display","")):c.create("div",{innerHTML:"\x3cspan\x3e"+d+"\x3c/span\x3e",id:"toc_rendererHoverTooltip","class":"rendererHoverTooltip",style:{top:b+"px",left:a+15+"px"}},document.body))},b.clientX,b.clientY,a),500)},d));arcgisonline.map.dijit.toc.legend.onRendererMouseHandlers.out[b]=c.connect(a,"onmouseout",function(a){arcgisonline.map.dijit.toc.legend.mouseX=a.clientX;arcgisonline.map.dijit.toc.legend.mouseY=a.clientY;arcgisonline.map.dijit.toc.legend.rendererToolTipOpen&&(arcgisonline.map.dijit.toc.legend.rendererToolTipOpen=
!1,c.style(c.byId("toc_rendererHoverTooltip"),"display","none"))})}},_createDynamicLayers:function(b){var d=[];c.forEach(b.dynamicLayerInfos||b.layerInfos,function(a){var c={id:a.id};c.source=a.source&&a.source.toJson();var g;b.layerDefinitions&&b.layerDefinitions[a.id]&&(g=b.layerDefinitions[a.id]);g&&(c.definitionExpression=g);var f;b.layerDrawingOptions&&b.layerDrawingOptions[a.id]&&(f=b.layerDrawingOptions[a.id]);f&&(c.drawingInfo=f.toJson());c.minScale=a.minScale||0;c.maxScale=a.maxScale||0;
d.push(c)});return d}}});