// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/map/dijit/toc/scale",["dijit","dojo","dojox","dojo/require!arcgisonline/map/main"],function(r,b,s){b.provide("arcgisonline.map.dijit.toc.scale");b.require("arcgisonline.map.main");arcgisonline.map.dijit.toc.scale={scaleOptions:null,layerScale:function(h,a,d,g){esriGeowConfig.isRightToLeft?(b.attr(b.byId("layerMenu.layerScaleDlg"),"class","dijitTooltipDialog dijitTooltipABRight dijitTooltipLeft"),b.attr(b.byId("subLayerMenu.layerScaleDlg"),"class","dijitTooltipDialog dijitTooltipABRight dijitTooltipLeft")):
(b.attr(b.byId("layerMenu.layerScaleDlg"),"class","dijitTooltipDialog dijitTooltipABLeft dijitTooltipRight"),b.attr(b.byId("subLayerMenu.layerScaleDlg"),"class","dijitTooltipDialog dijitTooltipABLeft dijitTooltipRight"));var c=Math.round(arcgisonline.map.main.map.getScale()),c=b.number.format(c,{pattern:"#,###,###,##0"});b.byId("layerMenu.scaleCurrent").innerHTML=b.string.substitute(esri.i18nBundle.tocPanel.mapScale,{scale:c});b.byId("subLayerMenu.scaleCurrent").innerHTML=b.string.substitute(esri.i18nBundle.tocPanel.mapScale,
{scale:c});var e=arcgisonline.map.main.mapLayers[h],f=null;if(f=e.layers?-1==a?e.layers[0]:e.layers[a]:-1<a?e.layer.dynamicLayerInfos&&arcgisonline.map.main.hasDynamicLayers(e)?e.layer.dynamicLayerInfos[a]:e.layer.layerInfos[a]:e.layer){h=f.minScale;c=f.maxScale;if(!h||isNaN(h))h=0;if(!c||isNaN(c))c=0;-1==a?d.set("layer",f):-1<a&&e.layers?g.set("layer",e.layers[a]):-1<a&&e.layer?(g.set("layer",null),b.forEach(e.layer.layerInfos,function(a){f.source?a.id==f.source.mapLayerId&&(a=arcgisonline.map.dijit.toc.scale.getEffectiveScale(e,
a),g.set("minScale",esri.isDefined(f.minScale)?f.minScale:a.minScale||0),g.set("maxScale",esri.isDefined(f.maxScale)?f.maxScale:a.maxScale||0)):a.id==f.id&&(a=arcgisonline.map.dijit.toc.scale.getEffectiveScale(e,a),g.set("minScale",a.minScale||0),g.set("maxScale",a.maxScale||0))})):g.set("layer",f)}return f},onClickTocScaleSuggest:function(h,a,d,g){var c=arcgisonline.map.main.mapLayers[h],e=null,f=null;c.layers?e=-1==a?c.layers[0]:c.layers[a]:-1<a?c.layer.dynamicLayerInfos&&arcgisonline.map.main.hasDynamicLayers(c)?
(e=c.layer.dynamicLayerInfos[a],f=new esri.layers.FeatureLayer(c.url+"/dynamicLayer",{outFields:["*"],resourceInfo:null,source:e.source,minScale:e.minScale||0,maxScale:e.maxScale||0})):(e=c.layer.layerInfos[a],f=new esri.layers.FeatureLayer(c.url+"/"+e.id,{outFields:["*"],resourceInfo:null,minScale:e.minScale||0,maxScale:e.maxScale||0})):e=c.layer;var n=null,n=-1==a?d:g;(f||e).addPlugin("esri/plugins/FeatureLayerStatistics").then(b.hitch(this,function(d){(f||e).statisticsPlugin.getSuggestedScaleRange({map:arcgisonline.map.main.map}).then(b.hitch(this,
function(d,b){console.log("getSuggestedScaleRange returns",b.relaxedMinScale,b.minScale,b.maxScale,b);d.set("minScale",b.minScale);d.set("maxScale",b.maxScale);(e.minScale!==b.minScale||e.maxScale!==b.maxScale)&&arcgisonline.map.dijit.toc.scale.applyScaleToLayer(c,e,b.minScale,b.maxScale,-1<a,h)},d),b.hitch(this,function(a){console.log("getSuggestedScaleRange error",a)}))},n))},updateScale:function(b,a,d,g){var c=arcgisonline.map.main.mapLayers[b],e=null,e=c.layers?-1==a?c.layers[0]:c.layers[a]:-1<
a?c.layer.dynamicLayerInfos&&arcgisonline.map.main.hasDynamicLayers(c)?c.layer.dynamicLayerInfos[a]:c.layer.layerInfos[a]:c.layer;(e.minScale!==d||e.maxScale!==g)&&arcgisonline.map.dijit.toc.scale.applyScaleToLayer(c,e,d,g,-1<a,b)},applyScaleToLayer:function(b,a,d,g,c,e){if(arcgisonline.map.dijit.toc.scale.checkScale(d,g)){d=d===Number.POSITIVE_INFINITY?0:d;arcgisonline.map.dijit.toc.scale.setLayerScaleRange(a,d,g,e);if(b.layers&&!c)for(a=1;a<b.layers.length;a++)b.layers[a].setScaleRange(d,g);b.scaleChanged=
!0}},checkScale:function(b,a){return 0<b&&0<a&&b<a?(arcgisonline.sharing.dijit.dialog.GeneralDlg.prototype.statics.getInstance().show({title:esri.i18nBundle.tocPanel.errorTitle,message:esri.i18nBundle.tocPanel.error.scaleRangeMsg}),!1):!0},setLayerScaleRange:function(h,a,d,g){if(!(h.minScale==a&&h.maxScale===d)){if(h instanceof esri.layers.KMLLayer)h.setScaleRange(a,d);else if(h instanceof esri.layers.GeoRSSLayer)h.setScaleRange(a,d);else if("esri.layers.LayerInfo"===h.declaredClass||"esri.layers.DynamicLayerInfo"===
h.declaredClass){var c=arcgisonline.map.main.mapLayers[g];arcgisonline.map.dynLayer.checkDynamicLayers(c);b.forEach(c.itemLayers,function(b){if(b.id==h.id&&(b.minScale!==a||b.maxScale!==d))b.minScale=a,b.maxScale=d,arcgisonline.map.dynLayer.refreshDynamicLayers(c)})}else h.setScaleRange(a,d);arcgisonline.map.dijit.toc.scale.checkLayersInMapScale()}},getEffectiveScale:function(b,a){var d=a.minScale,g=a.maxScale;if(esri.isDefined(a.parentLayerId))for(var c=b.layer.layerInfos,e=a.parentLayerId,f=c.length-
1;0<=f;f--)if(c[f].id==e)if(0==d&&0<c[f].minScale?d=c[f].minScale:0<d&&0==c[f].minScale||0<d&&0<c[f].minScale&&(d=Math.min(d,c[f].minScale)),g=Math.max(g||0,c[f].maxScale||0),-1<c[f].parentLayerId)e=c[f].parentLayerId;else break;return{minScale:d,maxScale:g}},checkLayersInMapScale:function(){if("contentStack"===arcgisonline.map.leftPanel.getLeftContentPanelStack()){var h=arcgisonline.map.main.map.getScale();b.forEach(arcgisonline.map.main.mapLayers,b.hitch(this,function(a){if(b.byId(a.id+"_title")){var d,
g;if(a.layers){var c=arcgisonline.map.dijit.toc.scale.mergeSubLayerScales(a.layers,null,a);d=c.minScale;g=c.maxScale}else if(a.layer)if(d=a.layer.minScale||0,g=a.layer.maxScale||0,a.layer.dynamicLayerInfos&&arcgisonline.map.main.hasDynamicLayers(a))c=arcgisonline.map.dijit.toc.scale.mergeSubLayerScales(a.layer.dynamicLayerInfos,a.layer.layerInfos,a),c=arcgisonline.map.dijit.toc.scale.mergeScale(c.minScale,c.maxScale,d,g),d=c.minScale,g=c.maxScale;else if(a.layer.layerInfos&&a.layer.layerInfos.length&&
(a.layer instanceof esri.layers.ArcGISDynamicMapServiceLayer||a.layer instanceof esri.layers.ArcGISTiledMapServiceLayer)){if(10===a.layer.version&&!a.layersInfo){arcgisonline.map.main.getLayersInfo(a,function(){arcgisonline.map.dijit.toc.scale.checkLayersInMapScale()});return}c=arcgisonline.map.dijit.toc.scale.mergeSubLayerScales(10===a.layer.version&&a.layersInfo&&a.layersInfo.layers||a.layer.layerInfos,null,a);c=arcgisonline.map.dijit.toc.scale.mergeScale(c.minScale,c.maxScale,d,g);d=c.minScale;
g=c.maxScale}else a.layer.folders&&(c=arcgisonline.map.dijit.toc.scale.mergeSubLayerScales(a.layer.folders,null,a),c=arcgisonline.map.dijit.toc.scale.mergeScale(c.minScale,c.maxScale,d,g),d=c.minScale,g=c.maxScale);h>=g&&(5<d&&h<=d||5>=d)?b.removeClass(b.byId(a.id+"_title"),"outOfScaleRange"):a.layer instanceof esri.layers.TiledMapServiceLayer&&a.layer._isMapAtVisibleScale()?b.removeClass(b.byId(a.id+"_title"),"outOfScaleRange"):b.addClass(b.byId(a.id+"_title"),"outOfScaleRange")}}))}},mergeScale:function(b,
a,d,g){0==b&&0<d?b=d:0<b&&0==d||0<b&&0<d&&(b=Math.min(b,d));a=Math.max(a,g);return{minScale:b,maxScale:a}},mergeSubLayerScales:function(h,a,d){var g=d.layer?d.layer.minScale||0:0,c=d.layer?d.layer.maxScale||0:0,e=arcgisonline.map.main.map.getScale(),f=-1*Number.MAX_VALUE,n=Number.MAX_VALUE;b.forEach(h,b.hitch(this,function(l){var p=l.parentLayerId,m=l.minScale||0,k=l.maxScale||0;if(a&&l.source)for(var q=0;q<a.length;q++)if(origLayer=a[q],origLayer.id===l.source.mapLayerId){k=arcgisonline.map.dijit.toc.scale.mergeScale(m,
k,origLayer.minScale||0,origLayer.maxScale||0);m=k.minScale;k=k.maxScale;p=origLayer.parentLayerId;break}f=0===f||0===m?0:Math.max(f,m);n=Math.min(n,k);k=arcgisonline.map.dijit.toc.scale.mergeScale(m,k,g,c);m=k.minScale;k=k.maxScale;esri.isDefined(p)&&-1<p&&(k=arcgisonline.map.dijit.toc.scale.mergeScaleOfGroupSubLayers(p,m,k,a||h),m=k.minScale,k=k.maxScale);e>=k&&(5<m&&e<=m||5>=m)?((p=b.byId(d.id+"_"+l.id+"_title"))&&b.removeClass(p,"outOfScaleRange"),esri.isDefined(l.networkLinkIds)&&l.networkLinkIds.length&&
b.forEach(l.networkLinkIds,function(a){a=d.id+"_"+l.id+"_netLink"+a;b.byId(a+"_title")&&b.removeClass(b.byId(a+"_title"),"outOfScaleRange")})):((p=b.byId(d.id+"_"+l.id+"_title"))&&b.addClass(p,"outOfScaleRange"),esri.isDefined(l.networkLinkIds)&&l.networkLinkIds.length&&b.forEach(l.networkLinkIds,function(a){a=d.id+"_"+l.id+"_netLink"+a;b.byId(a+"_title")&&b.addClass(b.byId(a+"_title"),"outOfScaleRange")}))}));return{minScale:f,maxScale:n}},mergeScaleOfGroupSubLayers:function(h,a,d,g){var c;b.forEach(g,
b.hitch(this,function(a){a.id===h&&(c=a)}));if(c){var e=c.parentLayerId,f=c.minScale||0,n=c.maxScale||0;0==a&&0<f?a=f:0<a&&0==f||0<a&&0<f&&(a=Math.min(a,f));d=Math.max(d,n);esri.isDefined(e)&&-1<e&&(d=arcgisonline.map.dijit.toc.scale.mergeScaleOfGroupSubLayers(e,a,d,g),a=d.minScale,d=d.maxScale)}return{minScale:a,maxScale:d}}}});