// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("esri/core/declare dojo/_base/kernel dojo/dom-construct dojo/on dijit/form/HorizontalSlider dijit/form/CheckBox esri/core/watchUtils esri/views/3d/support/earthUtils dojo/i18n!../nls/widgets".split(" "),function(x,C,b,m,D,z,p,E,q){var f=new Date,c=new Date,F={hour:"numeric",minute:"numeric"};return x(null,{constructor:function(b,e){this._seasons={date:{},nice:{}};this._timeoutId=0;this._sliderFlag=!1;for(var c=this._sliderPos=0;11>=c;c++)this._seasons.date[c]=new Date(2013,c,15),this._seasons.nice[c]=
this._seasons.date[c].toLocaleString(C.locale,{month:"long"});p.whenOnce(e,"ready",function(){this.create(b,e)}.bind(this))},create:function(x,e){function y(a){n=a;s(e.environment.lighting.date);e.environment.lighting.displayUTCOffset=a}var k=function(){var a=e.environment.lighting.date,g=E.positionToTimezone(e.get("camera").position);return{date:a,hour:a.getUTCHours()+g.hours+a.getUTCMinutes()/60,monthIdx:a.getMonth(),timezoneOffset:g.hours}}(),t=b.create("div",{id:"lightingDiv"},x);b.create("div",
{"class":"paneSubTitle",innerHTML:q.environmentSettings.dragSunSliderText},t);var r=b.create("div",{id:"sunSettingsContainer","class":"sliderContainer"},t),d=b.create("div",{"class":"sliderContainer sunSliderContainer"},r),u=new D({"class":"envSunHorizontalSlider",maximum:23.99,minimum:0,value:k.hour,intermediateChanges:!0,showButtons:!1},d);m(u,"change",function(a){if(this._sliderFlag)this._sliderFlag=!1;else{f.setTime(e.environment.lighting.date.getTime());var g=f.getTime(),b=((Math.floor(a)-n)%
24+24)%24;a=60*(a-Math.floor(a));var h=a%1;a-=h;h=Math.round(60*h);f.setUTCHours(b);f.setUTCMinutes(a);f.setUTCSeconds(h);f.getTime()!==g&&(e.environment.lighting.date=f);0!==this._timeoutId&&(clearTimeout(this._timeoutId),this._timeoutId=0);c.setTime(f.getTime());g=((f.getUTCHours()+n)%24+24)%24;b=f.getUTCMinutes();a=f.getUTCSeconds();c.setHours(g);c.setMinutes(b);c.setSeconds(a);A.value=c.toLocaleString("en-us",{hour:"numeric",minute:"numeric"})}}.bind(this));for(var n=k.timezoneOffset,A=b.create("input",
{id:"sunTime",title:q.environmentSettings.dragSunSliderHint,readonly:"readonly"},r),d=b.create("div",{"class":"sunDropdownDiv",id:"gmtDropdownDiv"},r),l=b.create("select",{id:"gmtSelect"},d),d=12;0<d;d--)b.create("option",{innerHTML:"GMT-"+d,value:-d},l);b.create("option",{innerHTML:"GMT-0",value:0},l);for(d=1;12>=d;d++)b.create("option",{innerHTML:"GMT+"+d,value:d},l);l.selectedIndex=k.timezoneOffset+12;m(l,"change",function(a){y(parseInt(a.currentTarget.value,10))});p.init(e,"environment.lighting",
function(a){a&&void 0===a.displayUTCOffset&&(a.displayUTCOffset=n)});var d=b.create("div",{"class":"sunDropdownDiv",id:"seasonDropdownDiv"},r),v=b.create("select",{id:"seasonSelect",selectedIndex:k.monthIdx},d);m(v,"change",function(a){a=a.target;var g=e.environment.lighting.date,b=new Date(g);b.setMonth(this._seasons.date[a.options[a.selectedIndex].value].getMonth());b.setUTCHours(g.getUTCHours());b.setUTCMinutes(g.getUTCMinutes());b.setUTCSeconds(g.getUTCSeconds());e.environment.lighting.date=b}.bind(this));
for(var w in this._seasons.date)this._seasons.date.hasOwnProperty(w)&&b.create("option",{id:w+"_button","class":"seasonButton",innerHTML:this._seasons.nice[w],value:w},v);v.selectedIndex=k.monthIdx;b.create("div",{"class":"clr"},r);var s=function(a){c.setTime(a.getTime());a=((c.getUTCHours()+n)%24+24)%24;var b=c.getUTCMinutes(),e=c.getUTCSeconds();a=a+b/60+e/3600;b=u.get("value");this._sliderPos=a;a!==b&&(this._sliderFlag=!0,0===this._timeoutId&&(this._timeoutId=setTimeout(B,200)))},s=s.bind(this),
B=function(){c.setTime(e.environment.lighting.date.getTime());var a=((c.getUTCHours()+n)%24+24)%24,b=c.getUTCMinutes(),d=c.getUTCSeconds(),h=a+b/60+d/3600,f=u.get("value");h!==f&&u.set("value",h);h=c.getUTCMonth();v.selectedIndex=h;c.setHours(a);c.setMinutes(b);c.setSeconds(d);A.value=c.toLocaleString("en-us",F);this._timeoutId=0}.bind(this),k=function(){0===this._timeoutId&&(this._timeoutId=setTimeout(B,500))}.bind(this);e.watch("camera",k);k();m(e.environmentManager,"_date-change",function(a){s(a)});
m(e.environmentManager,"_timezone-change",function(a){l.selectedIndex=a+12;y(a)});b.create("div",{"class":"paneSubTitle",innerHTML:q.environmentSettings.shadowing},t);p.init(e,"environment.lighting.displayUTCOffset",function(a){if(void 0!==a){var b=Math.round(a)+12;l.selectedIndex!==b&&(l.selectedIndex=b);n!==a&&y(a)}});(function(a){a=b.create("div",{id:"sunSettingsContainer","class":"sliderContainer"},a);var c,d;void 0!==e._stage.getRenderParams().shadowMap&&(c=new z({"class":"shadowButton",value:"shadow"}),
c.placeAt(a),b.create("label",{"for":"shadowButton"},a).textContent=q.environmentSettings.directShadow,m(c,"change",function(a){e.environment.lighting.directShadows=c.checked}),p.init(e,"environment.lighting.directShadows",function(a){c.set("checked",a)}));void 0!==e._stage.getRenderParams().ssao&&(b.create("br",{},a),b.create("br",{},a),d=new z({"class":"ssaoButton",value:"ssao"}),d.placeAt(a),b.create("label",{"for":"ssaoButton"},a).textContent=q.environmentSettings.diffuseShadow,m(d,"change",function(a){e.environment.lighting.ambientOcclusion=
d.checked}),p.init(e,"environment.lighting.ambientOcclusion",function(a){d.set("checked",a)}));this.set=function(a,b){c&&c.set("checked",a);d&&d.set("checked",b)}}).call(this,t)}})});