// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define({defaultWebSceneName:"Min scene",menu:{titleLayers:"Lag",titleEnvironmentSettings:"Milj\u00f8",titleSearch:"S\u00f8g",titleBasemap:"Baggrundskort",errorSceneServiceLoad:"Fejl ved indl\u00e6sning af scenetjeneste",errorLayerName:"Lagnavn:",titleLegend:"Signaturforklaring",titleSettings:"Indstillinger",titleShare:"Del",moreTools:"Flere v\u00e6rkt\u00f8jer"},dialogs:{webscene:"Webscene",addLayer:"Tilf\u00f8j lag",layerDidNotDrawCompletely:"Laget blev ikke trukket helt",webglCheck:"WebGL-kontrol",
browserCheck:"Browserkontrol",browserFail:"Scenevisning kan ikke \u00e5bnes i din browser.",unsupportedBasemap:"Baggrundskort underst\u00f8ttes ikke"},messages:{addLayerFailed:"Lag kan ikke tilf\u00f8jes",layerAddedSuccess:"Lag blev tilf\u00f8jet uden fejl.",layerDidNotDrawCompletely:"blev ikke trukket helt, fordi serverens overf\u00f8rselsbegr\u00e6nsning p\u00e5 ${limit} objekter blev overskredet.",layerTypeNotSupported:"Lagtype underst\u00f8ttes ikke:",onlyTiledLayerSupported:"Kun tile-kortlag underst\u00f8ttes.",
layerItemTypeNotSupported:"Lagelementtypen underst\u00f8ttes ikke:",layerItemPropertiesFromMapServer:"De visningsegenskaber, der er gemt i kortlagelementerne, underst\u00f8ttes ikke.",layerItemPropertiesNotApplied:"De visningsegenskaber, der er gemt i lagelementet, blev ikke anvendt.",itemId:"Element-id:",itemType:"Elementtype:",websceneLoadFail:"Kan ikke indl\u00e6se webscene.",websceneLoadFailNoVersion:"Ingen version fundet i webscene.",websceneLoadFailBadVersion:"Ugyldig version ${websceneVersion} i webscene.",
websceneLoadFailIncompatVersion:"Webscene version ${websceneVersion} er ikke kompatibel med dette visningsprogram",websceneVersionRequires:"(kr\u00e6ver ${websceneRequiredVersion})",websceneVersionMoreRecent:"Webscene (version ${websceneVersion}) er nyere end visningsversionen {$viewerVersion}.",webscenePotentiallyUnsupported:"Dele af websceneindholdet underst\u00f8ttes muligvis ikke og bliver muligvis ikke vist som forventet.",websceneGlobalSR:"Global Web Scene skal v\u00e6re i Web Mercator.",websceneGlobalEmbeddedSR:"Spatiale referencer i globale webscener skal v\u00e6re i Web Mercator eller WGS84 GCS.",
websceneLocalSRGCS:"Lokale webscener med geografiske koordinater underst\u00f8ttes ikke.",tiledMapServicesMinVersion:"Tile-kortlag p\u00e5 servere f\u00f8r version 10.2.2 underst\u00f8ttes ikke.",tiledMapServicesMinVersionPatch:"Tile-kortlag fra version 10.2.2-servere underst\u00f8ttes kun, hvis alle serveropdateringer er blevet anvendt.",sceneLayerVersion:"Scenelagversion underst\u00f8ttes ikke.",sceneLayerSRWM:"Scenelag skal v\u00e6re i Web Mercator.",sceneLayerSR:"Scenelag skal stemme overens med scenens spatiale reference.",
sceneLayerSRGCS:"Scenelag i geografiske koordinatsystemer underst\u00f8ttes ikke i lokale scener.",tiledMapServicesSR:"Tile-kortlag skal v\u00e6re i Web Mercator.",tiledMapServicesSRGeneric:"Tile-kortlag skal stemme overens med scenens spatiale reference og tile-skema.",tiledMapServiceSRGCS:"Tile-kortlag i geografiske koordinatsystemer underst\u00f8ttes ikke.",tiledImageServicesSRGeneric:"Tile-billedlag skal stemme overens med scenens spatiale reference og tile-skema.",tiledImageServiceSRGCS:"Tile-billedlag i geografiske koordinatsystemer underst\u00f8ttes ikke.",
tiledElevationServicesSRGeneric:"H\u00f8jdelag skal stemme overens med scenens spatiale reference og tile-skema.",tilingSchemePowerOfTwo:"Ikke-kompatibelt tile-skema: hver m\u00e5lestok skal v\u00e6re n\u00f8jagtigt halvt s\u00e5 stor som m\u00e5lestokken for det forrige niveau.",tilingSchemeTileSize:"Ikke-kompatibelt tile-skema: kun tiles med en bredde og h\u00f8jde p\u00e5 256 underst\u00f8ttes.",tilingSchemeGaps:"Ikke-kompatibelt tile-skema: afstand mellem niveauerne underst\u00f8ttes ikke.",tilingSchemeGeneric:"Ikke-kompatibelt tile-skema.",
patchRequired:"P\u00e5kr\u00e6vede programrettelser:",elevationImageServicesSR:"H\u00f8jdelag skal v\u00e6re i Web Mercator.",imageServicesSR:"Tile-billedlag skal v\u00e6re i Web Mercator.",tiledMapServicesTilingScheme:"Tile-kortlag skal overholde ArcGIS Online-tiling-skemaet.",tiledImageServicesTilingScheme:"Tile-billedlag skal overholde ArcGIS Online-tile-skemaet.",elevationImageServicesTilingScheme:"H\u00f8jdelag skal overholde ArcGIS Online-tiling-skemaet.",imageServicesCached:"Kun cachede billedservere underst\u00f8ttes.",
elevationImageServicesCached:"Kun cachede billedservere med LERC-kodning underst\u00f8ttes.",elevationBasemapTitle:"Standardh\u00f8jdelag kan ikke tilf\u00f8jes",elevationBasemapSR:"H\u00f8jdelagets spatiale reference stemmer ikke overens med baggrundskortets spatiale reference.",elevationBasemapTS:"H\u00f8jdelagets tile-skema er ikke kompatibelt med baggrundskortets tile-skema.",featureServiceNotSupportedTable:"Type Table underst\u00f8ttes ikke.",featureServiceNotSupportedMultipatch:"Multipatch Feature Services underst\u00f8ttes ikke.",
featureServiceNotSupportedNoRenderer:"Tjenester uden et gengivelsesv\u00e6rkt\u00f8j underst\u00f8ttes ikke",featureServiceNotSupportedRendererType:"Gengivelsesv\u00e6rkt\u00f8jstype underst\u00f8ttes ikke:",featureServiceNotSupportedMaxFeatures:"featuretjeneste overskrider den maksimale objektgr\u00e6nse:",featureServiceNotSupportedMaxVertices:"featuretjeneste overskrider den maksimale gr\u00e6nse for koordinatpunkter:",splashSignInToEdit:"Log ind for at udforske verden i 3D, og tilf\u00f8j lag fra Esri og tusindvis af organisationer for at oprette nye scener.",
splashShowThisOnStart:"vis dette ved start",splashNewToArcGIS:"Ny i ArcGIS? Tilmeld dig et pr\u00f8veabonnement i dag.",splashLookAtOtherScenes:"Her er et kig p\u00e5 nogle af de scener, du kan udforske.",selectedBasemapMismatchTitle:"Det valgte baggrundskort kan ikke bruges",selectedBasemapMismatch:"Baggrundskortets spatiale reference og tile-skemaet er ikke kompatible med scenen.\nOpret en ny scene for at bruge dette baggrundskort.",serviceName:"Tjenestenavn",basemapDrop:"Laget har en anden spatial reference og et andet tile-skema end baggrundskortet.\x3cBR\x3eVil du tilsides\u00e6tte baggrundskortet for at kunne tilf\u00f8je laget?",
basemapDropConfirm:"Tilsides\u00e6t baggrundskort",basemapDropTitle:"Data-uoverensstemmelse",BasemapDropWarningTitle:"Baggrundskort blev tilsidesat",BasemapDropWarning:"Baggrundskortets spatiale reference og tile-skemaet er ikke kompatible med laget og blev derfor tilsidesat.",sceneRejectTitle:"Scene kan ikke importeres",sceneRejectG2L:"En global scene kan ikke importeres ind i en lokal scene.",sceneRejectL2G:"En lokal scene kan ikke importeres ind i en global scene.",sceneRejectSRTS:"Den valgte scenes spatiale reference stemmer ikke overens med den aktuelle scenes spatiale reference.",
unsupportedSymbolType:"Symbol underst\u00f8ttes ikke",unsupportedSymbolLayerType:"Symbollaget underst\u00f8ttes ikke",unsupportedSymbology:"Dele af symbologien underst\u00f8ttes ikke",layerDisplaysWithServiceSymbology:"Lag vises med tjenestesymbologi.",layerDisplaysWithItemSymbology:"Lag vises med elementsymbologi.",layerDisplaysWithDefaultSymbology:"Lag vises med standardsymbologi.",layerDisplaysWithFallbackSymbology:"Lag vises med fallback-symbologi.",layerCreationErrorGeneric:"Fejl under oprettelse af lag.",
layerDisplaysNotAsExpected:"Lag bliver muligvis ikke vist som forventet.",byReferenceRendererUnsupported:"Gengivelsesv\u00e6rkt\u00f8j kunne ikke oprettes efter reference",geometryServiceUnavailableTitle:"Problem med geometritjeneste",geometryServiceUnavailable:"Geometritjeneste responderer ikke eller er ikke konfigureret korrekt. Belysning i scenen er muligvis forkert.",invalidUrl:"Ugyldig URL",unsupportedUrl:"Ikke-underst\u00f8ttet URL"},webglMessages:{badhardware:"Kan ikke oprette WebGL-kontekst.\x3cbr\x3eM\u00e5ske er WebGL blevet deaktiveret i din browser, eller din hardware underst\u00f8tter ikke WebGL.",
troubleshoot:'Fejls\u00f8gningsproblemer p\u00e5 \x3ca href\x3d"http://get.webgl.org" target\x3d"_blank"\x3eget.webgl.org\x3c/a\x3e',badbrowser:"Din browser ser ikke ud til at underst\u00f8tte WebGL.",help:"Hj\u00e6lp",mobile:"Webscenevisning er ikke underst\u00f8ttet p\u00e5 mobile enheder.",learnMore:"L\u00e6r mere",layerInfo:"${LayerType} af ${Author}"},buttons:{signIn:"Log ind",tryArcGIS:"Pr\u00f8v ArcGIS",visitGallery:"Bes\u00f8g galleriet",fullScreen:"Fuld sk\u00e6rm",exitFullScreen:"Afslut Fuld sk\u00e6rm-tilstand"},
appName:"3D Webscenevisning"});