// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("dojo/_base/array dojo/_base/lang ../../Color ../../core/screenUtils ../../symbols/support/jsonUtils ../SimpleRenderer ../UniqueValueRenderer ../ClassBreaksRenderer ../VectorFieldRenderer ../DotDensityRenderer ../ScaleDependentRenderer ../TimeClassBreaksAger ../TimeRampAger ../TemporalRenderer ../HeatmapRenderer".split(" "),function(g,k,f,n,l,p,q,r,s,t,u,e,v,w,x){var m={fromJson:function(a){try{throw Error("fromJson is deprecated, use fromJSON instead");}catch(b){console.warn(b.stack)}return m.fromJSON(a)},
fromJSON:function(a){var b;switch(a.type||""){case "simple":b=new p(a);break;case "uniqueValue":b=new q(a);break;case "classBreaks":b=new r(a);break;case "vectorField":b=new s(a);break;case "scaleDependent":b=this._scaleDependentFromJson(a);break;case "dotDensity":b=this._dotDensityFromJson(a);break;case "temporal":b=this._temporalFromJson(a);break;case "heatmap":b=this._heatmapFromJson(a)}return b},_scaleDependentFromJson:function(a){var b={},c=a.minScale;b.rendererInfos=g.map(a.rendererInfos,function(a){var b=
a.maxScale;a={minScale:c,maxScale:b,renderer:a.renderer&&this.fromJSON(a.renderer)};c=b;return a},this);return new u(b)},_dotDensityFromJson:function(a){a.backgroundColor&&k.isArray(a.backgroundColor)&&(a.backgroundColor=f.fromJSON(a.backgroundColor));0<a.dotSize&&(a.dotSize=n.pt2px(a.dotSize));a.fields&&g.forEach(a.fields,function(a){a&&k.isArray(a.color)&&(a.color=f.fromJSON(a.color))});a.legendOptions&&(a.legendOptions.backgroundColor&&k.isArray(a.legendOptions.backgroundColor)&&(a.legendOptions.backgroundColor=
f.fromJSON(a.legendOptions.backgroundColor)),a.legendOptions.outline&&(a.legendOptions.outline=l.fromJSON(a.legendOptions.outline)));a.outline&&(a.outline=l.fromJSON(a.outline));return new t(a)},_temporalFromJson:function(a){var b,c,d;a=a||{};b=this.fromJSON(a.observationRenderer);c=a.latestObservationRenderer?this.fromJSON(a.latestObservationRenderer):null;d=a.trackRenderer?this.fromJSON(a.trackRenderer):null;a=this._agerFromJson(a.observationAger);return new w(b,c,d,a)},_agerFromJson:function(a){var b;
a=a||{};a.colorRange||a.sizeRange||a.alphaRange?b=this._timeRampFromJson(a):a.agerClassBreakInfos&&(b=this._timeClassBreaksFromJson(a));return b},_timeRampFromJson:function(a){var b,c,d;a.colorRange&&1<a.colorRange.length&&(b=[f.fromJSON(a.colorRange[0]),f.fromJSON(a.colorRange[1])]);a.sizeRange&&1<a.sizeRange.length&&(c=[a.sizeRange[0],a.sizeRange[1]]);a.alphaRange&&1<a.alphaRange.length&&(d=[a.alphaRange[0]/255,a.alphaRange[1]/255]);return new v(b,c,d)},_timeClassBreaksFromJson:function(a){var b=
a.agerClassBreakInfos,c,d,g=[],h;c=e.UNIT_DAYS;switch(a.timeUnits){case "esriTimeUnitsSeconds":c=e.UNIT_SECONDS;break;case "esriTimeUnitsMilliseconds":c=e.UNIT_MILLISECONDS;break;case "esriTimeUnitsHours":c=e.UNIT_HOURS;break;case "esriTimeUnitsMinutes":c=e.UNIT_MINUTES;break;case "esriTimeUnitsMonths":c=e.UNIT_MONTHS;break;case "esriTimeUnitsWeeks":c=e.UNIT_WEEKS;break;case "esriTimeUnitsYears":c=e.UNIT_YEARS}for(h=0;h<b.length;h+=1)a=b[h],d={minAge:0,maxAge:a.oldestAge||Infinity},a.color&&(d.color=
f.fromJSON(a.color)),a.alpha&&(d.alpha=a.alpha/255),d.size=a.size,g[h]=d;return new e(g,c)},_heatmapFromJson:function(a){var b=a.colorStops;b&&b instanceof Array&&g.forEach(b,function(a){a.color=f.fromJSON(a.color)});return new x(a)}};return m});