// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("../lib/Renderer ../lib/SSAOHelperObscurance ../lib/ShadowMap ../lib/NearFarCalc ../lib/Util ../lib/gl-matrix".split(" "),function(w,x,y,z,m,g){var h=g.vec3d,r=g.mat4,A=m.assert;return function(q,g,B,t,n){var d=new w(q,g,B,t,n),b=new y(q,n),c=new x(q,t,n),C=new z,k={},u=!1,v=!1,s=!0;this.getCombinedStats=function(){return d.getCombinedStats()};this.dispose=function(){d.dispose();b.getEnableState()&&b.disable();c.getEnableState()&&c.disable()};this.setLightingData=function(a){d.setLightingData(a)};
this.getLightingData=function(){return d.getLightingData()};this.getViewParams=function(a){var f=a||{};if(!a||a.pixelRatio)f.pixelRatio=d.getPixelRatio();return f};this.setViewParams=function(a){null!=a.pixelRatio&&d.setPixelRatio(a.pixelRatio)};this.setRenderParams=function(a){void 0!==a.shadowMapResolution&&!1===b.getEnableState()&&b.setTextureResolution(a.shadowMapResolution);void 0!==a.shadowMap&&a.shadowMap!==b.getEnableState()&&b.setEnableState(a.shadowMap);void 0!==a.shadowMapMaxCascades&&
b.setMaxNumCascades(a.shadowMapMaxCascades);void 0!==a.ssao&&a.ssao!==c.getEnableState()&&c.setEnableState(a.ssao);void 0!==a.ssaoAttenuation&&c.setAttenuation(a.ssaoAttenuation);void 0!==a.ssaoRadius&&c.setRadius(a.ssaoRadius);void 0!==a.ssaoFilterRadius&&c.setFilterRadius(a.ssaoFilterRadius);void 0!==a.ssaoSamples&&c.setSamples(a.ssaoSamples);void 0!==a.debugInstanceThreshold&&d.setThreshold(a.debugInstanceThreshold);void 0!==a.drawShadowMapDebugQuad&&(u=a.drawShadowMapDebugQuad);void 0!==a.drawSSAODebugQuad&&
(v=a.drawSSAODebugQuad);c.getEnableState()?d.ssaoEnabled=!0:d.ssaoEnabled=!1;s=!0};this.getRenderParams=function(){var a={};b.getIsSupported()&&(a.shadowMap=b.getEnableState(),a.shadowMapResolution=b.getTextureResolution(),a.shadowMapMaxCascades=b.getMaxNumCascades());c.getIsSupported()&&(a.ssao=c.getEnableState(),a.ssaoAttenuation=c.getAttenuation(),a.ssaoRadius=c.getRadius(),a.ssaoFilterRadius=c.getFilterRadius(),a.ssaoSamples=c.getSamples());return a};this.modify=function(a,f,b,e,c){d.modify(a,
f,b,e);e=0;for(c=f.length;e<c;++e)delete k[f[e].uniqueName];e=0;for(c=a.length;e<c;++e)k[a[e].uniqueName]=a[e];e=0;for(c=b.length;e<c;++e)A(k[b[e].renderGeometry.uniqueName]===b[e].renderGeometry)};this.getContent=function(){return k};this.getPickRay=function(a,c,b,e,d,k){h.unproject(h.createFrom(a[0],a[1],0),e,b.projectionMatrix,b.fullViewport,d);h.unproject(h.createFrom(a[0],a[1],1),e,b.projectionMatrix,b.fullViewport,k)};this.getSideIndexForPoint=function(a,b){return 0};this.getProjectionMatrix=
function(a,b,c,e,d){b=m.fovx2fovy(b,a[2],a[3]);r.perspective(180*b/Math.PI,a[2]/a[3],c,e,d)};this.setSelectionObject=function(a,b){d.setSelectionObject(a,b)};this.setHighlightObjects=function(a,b){d.setHighlightObjects(a,b)};this.addExternalRenderer=function(a,b){return d.addExternalRenderer(a,b)};this.removeExternalRenderer=function(a,b){return d.removeExternalRenderer(a,b)};this.getExternalRenderers=function(){return d.getExternalRenderers()};this.resetNeedsRender=function(){s=!1;d.resetNeedsRender()};
this.needsRender=function(){return s||d.needsRender()};this.render=function(a,f,p,e){var l=a.viewport,g;if(b.getEnableState()||c.getEnableState())g=C.calculateSceneNearFar(a,k,p);if(b.getEnableState()){b.prepare(a,f,k,p,g);f=b.getCascades();for(var h=0;h<f.length;++h){var m=f[h];m.camera.setGLViewport(n);d.renderSimple(m.camera,p,"materialDepthShadowMap",m.camera.viewport)}b.finish(e);a.setGLViewport(n)}b.bindAll(q);d.renderAuxiliaryBuffers(a,p,b,c,g,e);d.render(a,p,b,c,e);u&&b.getEnableState()&&
(a=r.ortho(l[0],l[2],l[1],l[3],-1,1),b.drawDebugQuad(a));v&&c.getEnableState()&&(a=r.ortho(l[0],l[2],l[1],l[3],-1,1),c.drawQuad(a))};this._getModule=function(a){if("renderer"===a)return d;m.assert(!1,"Unknown module: "+a)}}});