// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define(["require","dojo/i18n!./nls/jsapi"],function(a,b){var c={id:"globalElevation",url:"//elevation3d.arcgis.com/arcgis/rest/services/WorldElevation3D/Terrain3D/ImageServer",layerType:"ArcGISTiledElevationServiceLayer",showLegend:!1};return{streets:{title:b.basemaps.streets,thumbnailUrl:a.toUrl("./images/basemap/streets.jpg"),itemId:"d8855ee4d3d74413babfb0f41203b168",baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer",showLegend:!1}],elevationLayers:[c]},
satellite:{title:b.basemaps.satellite,thumbnailUrl:a.toUrl("./images/basemap/satellite.jpg"),itemId:"86de95d4e0244cba80f0fa2c9403a7b2",baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer",showLegend:!1}],elevationLayers:[c]},hybrid:{title:b.basemaps.hybrid,thumbnailUrl:a.toUrl("./images/basemap/hybrid.jpg"),itemId:"413fd05bbd7342f5991d5ec96f4f8b18",baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer",showLegend:!1},
{url:"//services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer",isReference:!0,showLegend:!1}],elevationLayers:[c]},terrain:{title:b.basemaps.terrain,thumbnailUrl:a.toUrl("./images/basemap/terrain.jpg"),itemId:"aab054ab883c4a4094c72e949566ad40",baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/World_Terrain_Base/MapServer",showLegend:!1},{url:"//services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Reference_Overlay/MapServer",isReference:!0,
showLegend:!1}],elevationLayers:[c]},topo:{title:b.basemaps.topo,thumbnailUrl:a.toUrl("./images/basemap/topo.jpg"),itemId:"6e03e8c26aad4b9c92a87c1063ddb0e3",baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer",showLegend:!1}],elevationLayers:[c]},gray:{title:b.basemaps.gray,thumbnailUrl:a.toUrl("./images/basemap/gray.jpg"),itemId:"8b3b470883a744aeb60e5fff0a319ce7",baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer",
showLegend:!1},{url:"//services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Reference/MapServer",isReference:!0,showLegend:!1}],elevationLayers:[c]},"dark-gray":{title:b.basemaps["dark-gray"],thumbnailUrl:a.toUrl("./images/basemap/dark-gray.jpg"),itemId:"da65bacab5bd4defb576f839b6b28098",baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Base/MapServer",showLegend:!1},{url:"//services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Reference/MapServer",
isReference:!0,showLegend:!1}],elevationLayers:[c]},oceans:{title:b.basemaps.oceans,thumbnailUrl:a.toUrl("./images/basemap/oceans.jpg"),itemId:"48b8cec7ebf04b5fbdcaf70d09daff21",baseMapLayers:[{url:"//services.arcgisonline.com/arcgis/rest/services/Ocean/World_Ocean_Base/MapServer",showLegend:!1},{url:"//services.arcgisonline.com/arcgis/rest/services/Ocean/World_Ocean_Reference/MapServer",isReference:!0,showLegend:!1}],elevationLayers:[c]},"national-geographic":{title:b.basemaps["national-geographic"],
thumbnailUrl:a.toUrl("./images/basemap/national-geographic.jpg"),itemId:"509e2d6b034246d692a461724ae2d62c",baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer",showLegend:!1}],elevationLayers:[c]},osm:{title:b.basemaps.osm,thumbnailUrl:a.toUrl("./images/basemap/osm.jpg"),itemId:"5d2bfa736f8448b3a1708e1f6be23eed",baseMapLayers:[{layerType:"OpenStreetMap",showLegend:!1}],elevationLayers:[c]},"vector-streets":{title:"Vector Streets",thumbnailUrl:a.toUrl("./images/basemap/streets.jpg"),
baseMapLayers:[{id:"vector-streets",layerType:"VectorTiledLayer",url:"//basemapsbeta.arcgis.com/arcgis/rest/services/World_Basemap/VectorTileServer",showLegend:!1}]},"vector-streets-night":{title:"Vector Streets Night",thumbnailUrl:a.toUrl("./images/basemap/streets.jpg"),baseMapLayers:[{id:"vector-streets-night",layerType:"VectorTiledLayer",url:"//basemapsbeta.arcgis.com/arcgis/rest/services/World_Basemap/VectorTileServer",styleUrl:"//basemapsbeta.arcgis.com/preview/styles/StreetMapNight/data.json",
showLegend:!1}]},"vector-streets-relief":{title:"Vector Streets Relief",thumbnailUrl:a.toUrl("./images/basemap/streets.jpg"),baseMapLayers:[{id:"hillshade",url:"//services.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer ",showLegend:!1},{id:"vector-streets-relief",layerType:"VectorTiledLayer",url:"//basemapsbeta.arcgis.com/arcgis/rest/services/World_Basemap/VectorTileServer",styleUrl:"//basemapsbeta.arcgis.com/preview/styles/StreetMapRelief/data.json",showLegend:!1}]},"vector-streets-mobile":{title:"Vector Streets Mobile",
thumbnailUrl:a.toUrl("./images/basemap/streets.jpg"),baseMapLayers:[{id:"vector-streets-mobile",layerType:"VectorTiledLayer",url:"//basemapsbeta.arcgis.com/arcgis/rest/services/World_Basemap/VectorTileServer",styleUrl:"//basemapsbeta.arcgis.com/preview/styles/StreetMapMobile/data.json",showLegend:!1}]},"vector-canvas-light":{title:"Vector Light Canvas",thumbnailUrl:a.toUrl("./images/basemap/gray.jpg"),baseMapLayers:[{id:"vector-canvas-light",layerType:"VectorTiledLayer",url:"//basemapsbeta.arcgis.com/arcgis/rest/services/World_Basemap/VectorTileServer",
styleUrl:"//basemapsbeta.arcgis.com/preview/styles/CanvasLight/data.json",showLegend:!1}]},"vector-canvas-dark":{title:"Vector Dark Canvas",thumbnailUrl:a.toUrl("./images/basemap/dark-gray.jpg"),baseMapLayers:[{id:"vector-canvas-dark",layerType:"VectorTiledLayer",url:"//basemapsbeta.arcgis.com/arcgis/rest/services/World_Basemap/VectorTileServer",styleUrl:"//basemapsbeta.arcgis.com/preview/styles/CanvasDark/data.json",showLegend:!1}]}}});