// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/map/dijit/renderer/_OpacityMixin","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/_base/array dojo/Deferred dojo/dom dojo/dom-construct esri/dijit/OpacitySlider".split(" "),function(q,d,r,s,l,n,p,m){return{createAttributeTransparencySlider:function(a,b){b||(b=new l,setTimeout(function(){b.progress(b)},1));this.destroyAttributeTransparencySlider();var c=this.getRendererDataRange("transparencyInfo");if(!a.statistics)return(this.fLayer||this.layer).addPlugin("esri/plugins/FeatureLayerStatistics").then(d.hitch(this,
function(){b.isRejected()||(this.fLayer||this.layer).statisticsPlugin.getFieldStatistics({field:a.opacityInfo.field,normalizationType:a.opacityInfo.normalizationField?"field":null,normalizationField:a.opacityInfo.normalizationField}).then(d.hitch(this,function(c){b.isRejected()||(a.statistics=c,this.createAttributeTransparencySlider(a,b))}),d.hitch(this,function(a){b.isRejected()||(this.handleError(a,"getFieldStatistics",!1),b.reject())}))}),d.hitch(this,function(a){b.isRejected()||(this.handleError(a,
"addPlugin",!1),b.reject())})),b;this.displayZeroFeaturesMsg(a.statistics.count);this.onCalculationsSource(a.statistics.source,a.statistics.count);esri.isDefined(a.statistics.count)&&0===a.statistics.count||!esri.isDefined(a.statistics.count)&&null===a.statistics.min?(this.opacitySlider=new m({statistics:a.statistics,opacityInfo:d.clone(a.opacityInfo),showHistogram:!1,minValue:c.min||0,maxValue:c.max||100,showLabel:!0,showTick:!0},"rendererAttributeTransparencySlider"),this.opacitySlider.startup(),
this.enableOpacitySliderChangeEvent(a),b.resolve(a.opacityInfo)):this.getOpacityHistogram({field:a.opacityInfo.field,numBins:10,classificationMethod:"equal-interval",minValue:c.min,maxValue:c.max,normalizationField:a.opacityInfo.normalizationField,normalizationType:a.opacityInfo.normalizationField?"field":null}).then(d.hitch(this,function(e){b.isRejected()||(this.opacitySlider=new m({statistics:a.statistics,opacityInfo:d.clone(a.opacityInfo),histogram:e,minValue:esri.isDefined(c.min)?c.min:a.statistics.min,
maxValue:esri.isDefined(c.max)?c.max:a.statistics.max,showLabel:!0,showTick:!0},"rendererAttributeTransparencySlider"),this.opacitySlider.startup(),this.enableOpacitySliderChangeEvent(a),b.resolve(a.opacityInfo))}),d.hitch(this,function(e){b.isRejected()||(this.opacitySlider=new m({statistics:a.statistics,opacityInfo:d.clone(a.opacityInfo),showHistogram:!1,minValue:esri.isDefined(c.min)?c.min:a.statistics.min,maxValue:esri.isDefined(c.max)?c.max:a.statistics.max,showLabel:!0,showTick:!0},"rendererAttributeTransparencySlider"),
this.opacitySlider.startup(),this.enableOpacitySliderChangeEvent(a),b.resolve(a.opacityInfo))}));return b},zoomInOpacitySlider:function(a){var b=new l;setTimeout(function(){b.progress(b)},1);a=a||{};var c=this.opacitySlider.get("statistics"),e=this.opacitySlider.get("values"),h=e[0].value,e=e[1].value,k=e-h,f,g;c.min===c.max?(f=h-k/3,g=e+k/3,h=f,c=g):(f=Math.max(h-k/3,c.min),g=Math.min(e+k/3,c.max),h=esri.isDefined(a.minValue)?a.minValue:c.min,c=esri.isDefined(a.maxValue)?a.maxValue:c.max);f===h&&
g===c?(console.log("Can't zoom in slider"),b.reject()):(this.fLayer||this.layer).addPlugin("esri/plugins/FeatureLayerStatistics").then(d.hitch(this,function(){b.isRejected()||this.getOpacityHistogram({field:a.opacityInfo.field,normalizationType:a.opacityInfo.normalizationField?"field":null,normalizationField:a.opacityInfo.normalizationField,minValue:f,maxValue:g}).then(d.hitch(this,function(c){b.isRejected()||(this.onCalculationsSource(c.source),c={histogram:c,minSliderValue:f,maxSliderValue:g},this.disableSliderChangeEvent(),
this.opacitySlider.set("zoomOptions",c),setTimeout(d.hitch(this,function(){this.enableOpacitySliderChangeEvent(a)}),1E3),b.resolve())}),d.hitch(this,function(c){b.isRejected()||(c={histogram:null,minSliderValue:f,maxSliderValue:g},this.disableSliderChangeEvent(),this.opacitySlider.set("zoomOptions",c),setTimeout(d.hitch(this,function(){this.enableOpacitySliderChangeEvent(a)}),1E3),b.resolve())}))}),d.hitch(this,function(a){b.isRejected()||(this.handleError(a,"addPlugin",!1),b.reject())}));return b},
zoomOutOpacitySlider:function(){this.disableSliderChangeEvent();this.opacitySlider.set("zoomOptions",null);setTimeout(d.hitch(this,function(){this.enableOpacitySliderChangeEvent()}),1E3)},updateAttributeTransparencySlider:function(a){this.opacitySlider&&this.opacitySlider.set("opacityInfo",d.clone(this.opacityInfo))},enableOpacitySliderChangeEvent:function(a){this.sliderZoomedHandler=this.opacitySlider.on("zoomed",d.hitch(this,function(a){!1===a&&this.clearZoom()}));this.sliderChangeHandler=this.opacitySlider.on("handle-value-change",
d.hitch(this,function(a){this.opacityInfo=a}));this.sliderChangeHandler2=this.opacitySlider.on("data-value-change",d.hitch(this,function(a){this.authoringInfo=this.renderer.authoringInfo||{};this.replaceVisualVariable("transparencyInfo",null,{type:"transparencyInfo",minSliderValue:a.minValue,maxSliderValue:a.maxValue},this.authoringInfo)}))},disableSliderChangeEvent:function(){this.sliderChangeHandler&&this.sliderChangeHandler.remove();this.sliderChangeHandler=null;this.sliderChangeHandler2&&this.sliderChangeHandler2.remove();
this.sliderChangeHandler2=null},destroyAttributeTransparencySlider:function(){this.opacitySlider&&this.opacitySlider.destroy();n.byId("rendererAttributeTransparencySlider")||p.create("div",{id:"rendererAttributeTransparencySlider"},n.byId("rendererAttributeTransparencySliderDiv"))},getOpacityHistogram:function(a){var b=new l,c=this.getRendererDataRange("transparencyInfo");setTimeout(function(){b.progress(b)},1);this.histogramInfo&&this.histogramInfo.field===a.field&&this.histogramInfo.normalizationType===
a.normalizationType&&this.histogramInfo.normalizationField===a.normalizationField&&this.histogramInfo.minValue===c.min&&this.histogramInfo.maxValue===c.max?b.resolve(this.histogramInfo.histogram):(this.fLayer||this.layer).addPlugin("esri/plugins/FeatureLayerStatistics").then(d.hitch(this,function(){b.isRejected()||(this.fLayer||this.layer).statisticsPlugin.getHistogram({field:a.field,numBins:10,classificationMethod:"equal-interval",normalizationType:a.normalizationType,normalizationField:a.normalizationField,
minValue:c.min,maxValue:c.max}).then(d.hitch(this,function(d){b.isRejected()||(this.histogramInfo={histogram:d,field:a.field,normalizationType:a.normalizationType,normalizationField:a.normalizationField,minValue:c.min,maxValue:c.max},b.resolve(d))}),d.hitch(this,function(a){b.isRejected()||(this.handleError(a,"getOpacityHistogram",!1),b.reject())}))}),d.hitch(this,function(a){b.isRejected()||(this.handleError(a,"addPlugin",!1),b.reject())}));return b},getOpacityInfo:function(){return this.getVisualVariableByType("opacityInfo",
null,this.renderer.visualVariables)}}});