// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/map/dijit/renderer/_PredominanceMixin","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/_base/array dojo/_base/Color dojo/Deferred dojo/dom dojo/dom-construct esri/lang esri/symbols/jsonUtils esri/styles/basic esri/styles/type esri/renderers/smartMapping esri/tasks/query esri/tasks/QueryTask esri/tasks/UniqueValueDefinition esri/tasks/GenerateRendererParameters esri/tasks/GenerateRendererTask esri/tasks/StatisticDefinition esri/renderers/SimpleRenderer esri/renderers/UniqueValueRenderer esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/dijit/OpacitySlider".split(" "),
function(p,d,q,e,r,m,s,t,u,v,w,x,n,y,z,A,B,C,D,E,F,G,H,I){return{allUniqueValues:null,maxCount:200,defaultColors:"#ed5151 #149ece #a7c636 #9e559c #fc921f #ffde3e #f789d8 #b7814a #3caf99 #6b6bd6 #b54779 #7f7f7f".split(" "),buildPredominanceRenderer:function(b){var a=new m;setTimeout(function(){a.progress(a)},1);b=b||{};if(this.isFeatColl||this.isCSV||this.hasDynamic)this.buildPredominanceRendererGo(!1,b,a);else if("UniqueValueRenderer"!==this.renderer.declaredClass)if(this.isOwnerOfHostedFS){var c=
this.layer.getEditCapabilities();!this.layer.isEditable()||!c.canCreate&&(c.canUpdate||c.canDelete)||this.mapLayer.featureTemplatesChanged?this.buildPredominanceRendererGo(!0,b,a):arcgisonline.map.edit.hasDefaultTypesAndTemplates(this.layer)?this.buildPredominanceRendererGo(!0,b,a):(c=arcgisonline.sharing.dijit.dialog.ChoiceDlg.prototype.statics.getInstance(),c.show({title:this.i18n.warning,message:this.i18n.featureTypesAndTemplatesWarning,choiceOneTitle:this.i18n.yesLabel,choiceOneHandler:d.hitch(this,
function(){this.buildPredominanceRendererGo(!0,b,a)}),choiceTwoTitle:this.i18n.noLabel,choiceTwoHandler:d.hitch(this,function(){a.reject()})}))}else this.buildPredominanceRendererGo(!1,b,a);else this.attributeItem.name!==this.renderer.attributeField?this.isOwnerOfHostedFS?(c=this.layer.getEditCapabilities(),!this.layer.isEditable()||!c.canCreate&&(c.canUpdate||c.canDelete)||this.mapLayer.featureTemplatesChanged?this.buildPredominanceRendererGo(!0,b,a):arcgisonline.map.edit.hasDefaultTypesAndTemplates(this.layer)?
this.buildPredominanceRendererGo(!0,b,a):(c=arcgisonline.sharing.dijit.dialog.ChoiceDlg.prototype.statics.getInstance(),c.show({title:this.i18n.warning,message:this.i18n.featureTypesAndTemplatesWarning,choiceOneTitle:this.i18n.yesLabel,choiceOneHandler:d.hitch(this,function(){this._onSaveRendererGo(!0,b,a)}),choiceTwoTitle:this.i18n.noLabel,choiceTwoHandler:d.hitch(this,function(){})}))):this.buildPredominanceRendererGo(!1,b,a):this.isOwnerOfHostedFS?(c=this.layer.getEditCapabilities(),!this.layer.isEditable()||
!c.canCreate&&(c.canUpdate||c.canDelete)||this.mapLayer.featureTemplatesChanged?this.buildPredominanceRendererGo(!0,b,a):arcgisonline.map.edit.hasDefaultTypesAndTemplates(this.layer)?this.buildPredominanceRendererGo(!0,b,a):(c=arcgisonline.sharing.dijit.dialog.ChoiceDlg.prototype.statics.getInstance(),c.show({title:this.i18n.warning,message:this.i18n.featureTypesAndTemplatesWarning,choiceOneTitle:this.i18n.yesLabel,choiceOneHandler:d.hitch(this,function(){this._onSaveRendererGo(!0,b,a)}),choiceTwoTitle:this.i18n.noLabel,
choiceTwoHandler:d.hitch(this,function(){this._onSaveRendererGo(!1,b,a)})}))):this.buildPredominanceRendererGo(!1,b,a);return a},buildPredominanceRendererGo:function(b,a,c){arcgisonline.map.dynLayer.checkDynamicLayers(this.mapLayer);var e=a.attributeItem||this.attributeItem,l=a.attributeItem2||this.attributeItem2,g=a.attributeItem3||this.attributeItem3,h=a.attributeItem4||this.attributeItem4,k=a.attributeItem5||this.attributeItem5,f=[];f.push({label:e.alias,name:e.name});f.push({label:l.alias,name:l.name});
g&&(f.push({label:g.alias,name:g.name}),h&&(f.push({label:h.alias,name:h.name}),k&&f.push({label:k.alias,name:k.name})));n.createPredominanceRenderer({layer:this.fLayer||this.layer,fields:f,theme:"default",basemap:this.getBasemapType(),scheme:this.scheme,showOthers:!0,optimizeOutline:!0,includeOpacityInfo:!0}).then(d.hitch(this,function(d){c.isRejected()||(this.scheme=d.scheme,b&&(arcgisonline.map.edit.removeTypesAndTemplatesOnLayer(this.mapLayer.layer),this.mapLayer.featureTemplatesChanged=!0),delete this.authoringInfo,
d.renderer=this.updateRendererProperties(a,d.renderer),c.resolve(d.renderer))}),d.hitch(this,function(a){c.isRejected()||(this.handleError(a,"createPredominanceRenderer",!0),c.reject())}))},applyPredominanceRenderer:function(b){var a=this.getRendererStyle((this.fLayer||this.layer).renderer);this.setRenderer(b);!this.hasDynamic&&("predominance"!==a&&this.scheme&&esri.isDefined(this.scheme.opacity))&&(this.layer.setOpacity(this.scheme.opacity),this.transparencySlider&&this.transparencySlider.set("value",
1-this.scheme.opacity));(arcgisonline.map.featColl.isFeatureCollection(this.mapLayer)||this.isCSV)&&arcgisonline.map.main.markMapAsChanged("onRendererChange");this.isOwnerOfHostedFS&&!this.layer.types.length&&arcgisonline.map.edit.createTypesAndTemplatesOnLayer(this.layer);this.updateLegendPopup()},updatePredominanceRenderer:function(b){if(esri.isDefined(b)&&"esriGeometryPolygon"===this.geometryType)if(b){var a=[];e.forEach(this.renderer.infos,function(c){a.push(d.clone(c))});e.forEach(a,function(a){this.renderer.removeValue(a.value)},
this);e.forEach(a,function(a){this.renderer.addValue({value:a.value,symbol:this.setOutlineWidthOfSymbol(a.symbol,1),label:a.label})},this);this.portalPanel.lastUniqueDefaultSymbol=this.setOutlineWidthOfSymbol(this.portalPanel.lastUniqueDefaultSymbol,1);this.renderer.defaultSymbol&&(this.renderer.defaultSymbol=this.setOutlineWidthOfSymbol(this.renderer.defaultSymbol,1));this.defaultInfo&&this.defaultInfo.defaultSymbol&&(this.defaultInfo.defaultSymbol=this.setOutlineWidthOfSymbol(this.defaultInfo.defaultSymbol,
1));this.getSuggestedOutline().then(d.hitch(this,function(a){this.replaceVisualVariable("sizeInfo","outline",a.widthInfo,this.renderer);this.applyPredominanceRenderer(this.renderer)}),d.hitch(this,function(a){a=this.getVisualVariablesExceptTypes([{type:"sizeInfo",target:"outline"}],this.renderer.visualVariables);this.renderer.setVisualVariables(a);this.applyPredominanceRenderer(this.renderer)}))}else b=this.getVisualVariablesExceptTypes([{type:"sizeInfo",target:"outline"}],this.renderer.visualVariables),
this.renderer.setVisualVariables(b),this.applyPredominanceRenderer(this.renderer);else this.applyPredominanceRenderer(this.renderer)},updateRendererProperties:function(b,a){a=a||this.renderer;b=b||{};b.showOthers?(a.defaultSymbol=b.defaultSymbol,a.defaultLabel=b.defaultLabel):b.showOthers||(delete a.defaultSymbol,delete a.defaultLabel);b.rotationInfo&&a.setRotationInfo(b.rotationInfo);return a}}});