// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/map/dijit/renderer/_RendererMixin","dojo/_base/declare dojo/number dojo/date/locale dojo/json dojo/string dojo/has dojo/dom dojo/dom-construct dojo/dom-style dojo/Deferred dojo/_base/connect dojo/_base/lang dojo/_base/array dojo/_base/fx dijit/registry esri/renderers/jsonUtils esri/renderers/utils esri/dijit/util/busyIndicator esri/styles/type esri/styles/choropleth esri/styles/heatmap esri/layers/FeatureLayer esri/tasks/QueryTask esri/dijit/Legend esri/dijit/HorizontalSlider dijit/form/HorizontalRule esri/dijit/VisibleScaleRangeSlider".split(" "),
function(D,q,E,r,F,w,s,l,g,p,k,e,f,n,G,x,t,y,H,I,J,u,z,v,A,B,C){return{numberFormatPattern:"#,###,###,##0.##",setRenderer:function(a){a.authoringInfo=this.authoringInfo?e.clone(this.authoringInfo):a.authoringInfo;a.visualVariables||delete a.visualVariables;var b=arcgisonline.map.main.map.infoWindow;b.hide();b.clearFeatures();if(this.hasDynamic){f.forEach(this.mapLayer.itemLayers,function(b){b.id==this.layer.id&&(b.layerDefinition=b.layerDefinition||{},b.layerDefinition.drawingInfo={renderer:a.toJson()},
this.renderer=a)},this);arcgisonline.map.dynLayer.refreshDynamicLayers(this.mapLayer);this.serviceLayerInfo||(this.serviceLayerInfo=this.layer,this.layer=this.mapLayer.layer.dynamicLayerInfos[this.subLayerId]);delete this.mapLayer.legendInfo;for(var b=this.mapLayer.layer.url+"/legend",c=arcgisonline.map.main.allLegendInfos,d=0;d<c.length;d++)if(c[d].legendURL==b){c.splice(d,1);break}}else this.mapLayer.layer instanceof esri.layers.GeoRSSLayer?(this.layer.setRenderer(a),this.layer.redraw(),this.renderer=
this.layer.renderer,"esriGeometryPoint"==this.geometryType||"esriGeometryMultipoint"==this.geometryType?this.mapLayer.layer.pointSymbol=esri.symbol.fromJson(a.symbol.toJson()):"esriGeometryPolyline"==this.geometryType?this.mapLayer.layer.polylineSymbol=esri.symbol.fromJson(a.symbol.toJson()):"esriGeometryPolygon"==this.geometryType&&(this.mapLayer.layer.polygonSymbol=esri.symbol.fromJson(a.symbol.toJson()))):(this.layer.setRenderer(a),this.layer.redraw(),this.renderer=this.layer.renderer)},dismissRendererChanges:function(a){a=
a||this.origRenderer;this.authoringInfo=null;var b=!1;"heatMap"===this.getRendererStyle(this.renderer)&&9>w("ie")?b=!1:r.stringify(this.renderer.toJson())===r.stringify(a.renderer)&&(b=!0);if(this.hasDynamic)f.forEach(this.mapLayer.itemLayers,function(c){c.id==this.layer.id&&(esri.isDefined(a.minScale)&&esri.isDefined(a.maxScale)?(c.minScale=a.minScale,c.maxScale=a.maxScale):(delete c.minScale,delete c.maxScale),b||(c.layerDefinition=c.layerDefinition||{},c.layerDefinition.drawingInfo={renderer:a.renderer}))},
this),arcgisonline.map.dynLayer.refreshDynamicLayers(this.mapLayer);else if(b||(this.setRenderer(x.fromJson(a.renderer)),this.layer.types=a.types,this.layer.templates=a.templates),esri.isDefined(a.opacity)&&(this.isGeoRSS?this.mapLayer.layer.setOpacity(a.opacity):this.layer.setOpacity(a.opacity)),esri.isDefined(a.minScale)||esri.isDefined(a.maxScale))this.layer.setScaleRange(esri.isDefined(a.minScale)?a.minScale:0,esri.isDefined(a.maxScale)?a.maxScale:0)},setOpacity:function(a){!this.hasDynamic&&
(esri.isDefined(a)&&this.layer.opacity!==a)&&(this.layer.setOpacity(a),this.updateLegendPopup())},buildCurrentRendererInfo:function(){var a=this.layer.minScale,b=this.layer.maxScale;if(this.hasDynamic){var c;c=this.mapLayer.layer.dynamicLayerInfos?this.mapLayer.layer.dynamicLayerInfos[this.subLayerId]:this.mapLayer.layer.layerInfos[this.subLayerId];f.forEach(this.mapLayer.itemLayers,function(d){d.id==c.id&&(a=d.minScale,b=d.maxScale)},this)}return{renderer:this.renderer.toJson(),types:this.layer.types,
templates:this.layer.templates,minScale:a,maxScale:b,opacity:this.hasDynamic?null:this.isGeoRSS?this.mapLayer.layer.opacity:this.layer.opacity}},getRendererType:function(a){a=this.getRendererStyle(a);"classedColor"===a?a="color":"classedSize"===a&&(a="size");return a},getRendererStyle:function(a){if("esri.renderer.TemporalRenderer"!=a.declaredClass)if("esri.renderer.SimpleRenderer"==a.declaredClass){if(this.getVisualVariableByType("colorInfo",null,a.visualVariables))return"color";if(this.getVisualVariableByType("sizeInfo",
null,a.visualVariables))return"size"}else{if("esri.renderer.UniqueValueRenderer"==a.declaredClass)return"function"===typeof a.attributeField?this.getVisualVariableByType("sizeInfo",null,a.visualVariables)?"predominancesize":"predominance":this.getVisualVariableByType("sizeInfo",null,a.visualVariables)?"uniquesize":"type";if("esri.renderer.ClassBreaksRenderer"==a.declaredClass){var b=this.getVisualVariableByType("colorInfo",null,a.visualVariables);if(b){var c=a.authoringInfo||this.authoringInfo,d=
this.getVisualVariableByType("colorInfo",null,c.visualVariables);return c&&d.style&&b.normalizationField?"ratio":this.getVisualVariableByType("sizeInfo",null,a.visualVariables)?"colorsize":"color"}if(this.getVisualVariableByType("sizeInfo",null,a.visualVariables))return"size";c=a.authoringInfo||this.authoringInfo;if(a.authoringInfo)return"classedColor"===c.type?"classedColor":"classedSize";if("esriGeometryPolygon"===this.geometryType)return a.backgroundFillSymbol?"classedSize":"classedColor";for(b=
0;b<a.infos.length;b++){d=a.infos[b].symbol;for(c=0;c<a.infos.length;c++){var h=a.infos[c].symbol;if(b!==c&&this.hasSameColor(d,h))return"classedSize"}}return"classedColor"}if("esri.renderer.HeatmapRenderer"==a.declaredClass)return"heatMap";if("esri.renderer.BlendRenderer"==a.declaredClass)return"watercolor"}return"simple"},getVisualVariableByType:function(a,b,c){return c&&(c=f.filter(c,function(c){return esri.isDefined(b)?c.type===a&&c.target===b:c.type===a&&!c.target}),c.length)?e.clone(c[0]):null},
getVisualVariablesExceptType:function(a,b,c){return c&&(c=f.filter(c,function(c){return esri.isDefined(b)?c.type!==a||c.target!==b:c.type!==a||c.target}),c.length)?e.clone(c):null},getVisualVariablesExceptTypes:function(a,b){if(!a||!a.length)return null;if(b){var c=f.filter(b,function(b){if("string"===typeof a[0])return-1===f.indexOf(a,b.type);for(var c=!0,e=0;e<a.length;e++){var m=a[e];if(m.type===b.type&&m.target===b.target){c=!1;break}}return c});if(c.length)return e.clone(c)}return null},replaceVisualVariable:function(a,
b,c,d){a=this.getVisualVariablesExceptType(a,b,d.visualVariables)||[];a.push(c);d.setVisualVariables?d.setVisualVariables(a):d.visualVariables=a},hasSameColor:function(a,b){return"picturemarkersymbol"==a.type?!1:"cross"===a.style||"x"===a.style?"cross"===b.style||"x"===b.style?a.outline.color.toString()===b.outline.color.toString():a.outline.color.toString()===b.color.toString():"cross"===b.style||"x"===b.style?a.color.toString()===b.outline.color.toString():a.color.toString()===b.color.toString()},
getRendererDataRange:function(a){var b,c;if(this.authoringInfo){var d=this.getVisualVariableByType(a,null,this.authoringInfo.visualVariables);if(d)b=d.minSliderValue,c=d.maxSliderValue;else if(("colorInfo"===a||"sizeInfo"===a)&&this.renderer.infos&&this.renderer.infos.length&&"esri.renderer.ClassBreaksRenderer"===this.renderer.declaredClass)if(!(1===this.renderer.infos.length&&(-9007199254740991===this.renderer.infos[0].minValue||9007199254740991===this.renderer.infos[0].maxValue))){b=this.renderer.infos[0].minValue;
c=this.renderer.infos[0].maxValue;for(a=1;a<this.renderer.infos.length;a++)b=Math.min(b,this.renderer.infos[a].minValue),c=Math.max(c,this.renderer.infos[a].maxValue)}}else if(("colorInfo"===a||"sizeInfo"===a)&&this.renderer.infos&&this.renderer.infos.length&&"esri.renderer.ClassBreaksRenderer"===this.renderer.declaredClass){b=this.renderer.infos[0].minValue;c=this.renderer.infos[0].maxValue;for(a=1;a<this.renderer.infos.length;a++)b=Math.min(b,this.renderer.infos[a].minValue),c=Math.max(c,this.renderer.infos[a].maxValue);
a=Math.pow(2,53)-1;if(b==-a||b==-Number.MAX_VALUE)b=null;if(c==a||c==Number.MAX_VALUE)c=null}return{min:b,max:c}},getFeatures:function(a){arcgisonline.map.featColl.isFeatureCollectionLayer(a)||a instanceof esri.layers.CSVLayer?this.features||(this.features=this.layer.toJson().featureSet.features):this.features=this.layer.graphics;return this.features},hasDataNegativeValues:function(a,b){var c=new p;if(a instanceof u&&a.url&&a.supportsStatistics){var d=new esri.tasks.Query;d.outFields=[b.name];d.outStatistics=
[];d.where=a.getDefinitionExpression();var h=new esri.tasks.StatisticDefinition;h.statisticType="min";h.onStatisticField=b.name;h.outStatisticFieldName="minfield";d.outStatistics.push(h);(new z(a.url)).execute(d).then(function(a){a.features&&a.features.length&&(a=a.features[0].attributes.minfield,esri.isDefined(a)?c.resolve(0>a):c.resolve(!0))},function(a){console.log("could not get min value of data - no heatmap renderer option");c.resolve(!0)})}else if(a instanceof u)if(!a.graphics||!a.graphics.length)c.resolve(!0);
else{var e=9007199254740991,m=!1;f.forEach(a.graphics,function(a,c){a&&(a.attributes&&esri.isDefined(a.attributes[b.name])&&!isNaN(a.attributes[b.name]))&&(m=!0,e=Math.min(e,a.attributes[b.name]))},this);m?c.resolve(0>e):c.resolve(!0)}else c.resolve(!0);return c},getDomain:function(a){if(this.attributeItem.domain&&this.attributeItem.domain.codedValues)for(var b=0;b<this.attributeItem.domain.codedValues.length;b++){var c=this.attributeItem.domain.codedValues[b];if(a===c.code)return c.name}return a},
getLabel:function(a){return this.attributeItem.domain&&this.attributeItem.domain.codedValues?this.getDomain(a):"esriFieldTypeDate"===this.attributeItem.type?this.getDateLabel(a):"number"===typeof a&&!isNaN(a)?q.format(a,{pattern:this.numberFormatPattern}):""+a},getBasemapType:function(){var a=arcgisonline.map.main.map.getLayer(arcgisonline.map.main.map.layerIds[0]);if(!a.url)return"esri.layers.OpenStreetMapLayer"===arcgisonline.map.main.map.getLayer(arcgisonline.map.main.map.layerIds[0]).declaredClass?
"osm":"topo";a=a.url.toLowerCase();if(-1<a.indexOf("arcgis/rest/services/world_street_map"))return"streets";if(-1<a.indexOf("arcgis/rest/services/canvas/world_light_gray_base"))return"gray";if(!(-1<a.indexOf("arcgis/rest/services/world_topo_map")||-1<a.indexOf("arcgis/rest/services/usgstopo"))){if(-1<a.indexOf("arcgis/rest/services/world_terrain_base"))return"terrain";if(-1<a.indexOf("arcgis/rest/services/natgeo_world_map"))return"national-geographic";if(-1<a.indexOf("arcgis/rest/services/ocean/world_ocean_base"))return"oceans";
if(-1<a.indexOf("arcgis/rest/services/world_imagery"))return"satellite";if(-1<a.indexOf("arcgis/rest/services/reference/world_boundaries_and_places"))return"hybrid";if(-1<a.indexOf("arcgis/rest/services/canvas/world_dark_gray_base"))return"dark-gray"}return"topo"},getClassificationMethod:function(a){switch(a){case "natural-breaks":return this.i18n.classifyNaturalBreaks;case "equal-interval":return this.i18n.classifyEqualInterval;case "standard-deviation":return this.i18n.classifyStandardDeviation;
case "quantile":return this.i18n.classifyQuantile;default:return this.i18n.classifyManualBreaks}},getClassificationMethodConstant:function(a){switch(a){case "natural-breaks":return"esriClassifyNaturalBreaks";case "equal-interval":return"esriClassifyEqualInterval";case "standard-deviation":return"esriClassifyStandardDeviation";case "quantile":return"esriClassifyQuantile";default:return"esriClassifyManual"}},fromClassificationMethodConstant:function(a){switch(a){case "esriClassifyNaturalBreaks":return"natural-breaks";
case "esriClassifyEqualInterval":return"equal-interval";case "esriClassifyStandardDeviation":return"standard-deviation";case "esriClassifyQuantile":return"quantile";default:return null}},onCalculationsSource:function(a,b){this._estimatedValuesMsg&&("features-in-memory"===a&&!arcgisonline.map.featColl.isFeatureCollection(this.mapLayer)&&(!esri.isDefined(b)||0<b)?g.set(this._estimatedValuesMsg,"display",""):g.set(this._estimatedValuesMsg,"display","none"))},displayZeroFeaturesMsg:function(a){this._zeroFeaturesMsg&&
(0===a?g.set(this._zeroFeaturesMsg,"display",""):g.set(this._zeroFeaturesMsg,"display","none"))},hasOptimizeOutline:function(a){var b=null;"esriGeometryPolygon"===this.geometryType&&!this.hasDynamic&&(b=this.getVisualVariableByType("sizeInfo","outline",a)?!0:!1);return b},getFieldForUniqueRenderer:function(a,b){a=a||this.attributeItem;return(b=b||this.attributeItem2)?this.isTypeString(b)||a.codedValues2?b:a:a},getFieldForSizeRenderer:function(a,b){a=a||this.attributeItem;return(b=b||this.attributeItem2)?
this.isTypeString(b)||a.codedValues2?a:b:a},showLegendPopup:function(a,b){a=a||this.fLayer||this.layer;var c=b||this.renderer||a.renderer;if("simple"!==this.getRendererStyle(c)||this.getVisualVariableByType("opacityInfo",null,c.visualVariables)){this.fLayer&&this.renderer&&this.fLayer.setRenderer(this.renderer);this.hideLegendPopup();arcgisonline.map.main.rendererLegendPopup=l.create("div",{id:"rendererLegendPopup","class":"rendererLegendPopup",style:"position: absolute; max-width:300px;"},document.body);
var d=l.create("div",{id:"rendererLegendPopupContent"},arcgisonline.map.main.rendererLegendPopup),h=function(a){g.set(a,"maxHeight",g.get(s.byId("map"),"height")-185+"px");var b=g.get(s.byId("leftContentPanel"),"width")+18;esriGeowConfig.isRightToLeft?g.set(a,"right",b+"px"):g.set(a,"left",b+"px")};h(arcgisonline.map.main.rendererLegendPopup);arcgisonline.map.main.rendererLegendPopupHandler&&k.disconnect(arcgisonline.map.main.rendererLegendPopupHandler);arcgisonline.map.main.rendererLegendPopupHandler=
k.connect(arcgisonline.map.main.map,"resize",e.hitch(this,h,arcgisonline.map.main.rendererLegendPopup));arcgisonline.map.main.rendererLegend=new v({layerInfos:[{layer:a,title:" ",defaultSymbol:c.defaultSymbol&&c.defaultLabel?!0:!1}],map:arcgisonline.map.main.map,arrangement:v.ALIGN_LEFT,respectCurrentMapScale:!1,respectVisibility:!1},d);arcgisonline.map.main.rendererLegendRefreshHandler&&(k.disconnect(arcgisonline.map.main.rendererLegendRefreshHandler),arcgisonline.map.main.rendererLegendRefreshHandler=
null);this.checkLegendRefreshHandling(a);arcgisonline.map.main.rendererLegend.startup()}},updateLegendPopup:function(a,b){a=a||this.fLayer||this.layer;var c=b||this.renderer||a.renderer;"simple"===this.getRendererStyle(c)&&!this.getVisualVariableByType("opacityInfo",null,c.visualVariables)?this.hideLegendPopup():arcgisonline.map.main.rendererLegendPopup?(this.fLayer&&this.renderer&&this.fLayer.setRenderer(this.renderer),arcgisonline.map.main.rendererLegend.refresh([{layer:a,title:" ",defaultSymbol:c.defaultSymbol&&
c.defaultLabel?!0:!1}]),this.checkLegendRefreshHandling(a)):this.showLegendPopup(a,b)},checkLegendRefreshHandling:function(a){var b=this.getVisualVariableByType("sizeInfo",null,this.renderer.visualVariables);b&&"object"===typeof b.minSize?arcgisonline.map.main.rendererLegendRefreshHandler||(arcgisonline.map.main.rendererLegendRefreshHandler=arcgisonline.map.main.map.on("extent-change",e.hitch(this,function(a,b){b.levelChange&&arcgisonline.map.main.rendererLegend.refresh([{layer:a,title:" ",defaultSymbol:a.renderer.defaultSymbol&&
a.renderer.defaultLabel?!0:!1}])},a))):arcgisonline.map.main.rendererLegendRefreshHandler&&(k.disconnect(arcgisonline.map.main.rendererLegendRefreshHandler),arcgisonline.map.main.rendererLegendRefreshHandler=null)},hideLegendPopup:function(){arcgisonline.map.main.rendererLegendPopup&&(arcgisonline.map.main.rendererLegend&&arcgisonline.map.main.rendererLegend.destroy(),arcgisonline.map.main.rendererLegendPopupHandler&&(k.disconnect(arcgisonline.map.main.rendererLegendPopupHandler),arcgisonline.map.main.rendererLegendPopupHandler=
null),arcgisonline.map.main.rendererLegendRefreshHandler&&(k.disconnect(arcgisonline.map.main.rendererLegendRefreshHandler),arcgisonline.map.main.rendererLegendRefreshHandler=null),f.forEach(document.body.childNodes,function(a){a&&"rendererLegendPopup"===a.id&&document.body.removeChild(a)}),arcgisonline.map.main.rendererLegendPopup=null)},createTransparencySlider:function(a,b){var c=l.create("div",{},a,"first"),c=new B({container:"bottomDecoration",count:5,style:"height: 5px;"},c),d=new A({labels:["0%",
"50%","100%"],minimum:0,maximum:100,value:100*(1-this.layer.opacity),discreteValues:101,intermediateChanges:!0,onChange:e.hitch(this,function(a){a=q.round(1-a/100,2);this.disableAllEvents||(this.isGeoRSS?this.mapLayer.layer.setOpacity(a):this.layer.setOpacity(a),this.mapLayer._opacityChanged=!0,this.updateLegendPopup(),b&&b())})},a);d.startup();c.startup();return d},createScaleSlider:function(a){var b=new p,c=function(a,b){var c=new C({map:arcgisonline.map.main.map,layer:this.fLayer2||this.layer,
region:esriGeowConfig.self.region},a);c.startup();c.on("scale-range-change",e.hitch(this,function(a){var b=c.minScale,d=c.maxScale;if(this.hasDynamic){var e=this.mapLayer.layer.dynamicLayerInfos[this.subLayerId];f.forEach(this.mapLayer.itemLayers,function(a){if(a.id==e.id&&(a.minScale!==b||a.maxScale!==d))a.minScale=b,a.maxScale=d,arcgisonline.map.dynLayer.refreshDynamicLayers(this.mapLayer),this.fLayer2.setScaleRange(b,d),this.mapLayer._scaleChanged=!0},this)}else if(this.layer.minScale!==b||this.layer.maxScale!==
d)this.layer.setScaleRange(b,d),this.mapLayer._scaleChanged=!0}));b.resolve(c)};if(this.hasDynamic){var d=this.mapLayer.layer.dynamicLayerInfos[this.subLayerId];this.fLayer2=new esri.layers.FeatureLayer(this.mapLayer.url+"/dynamicLayer",{outFields:["*"],resourceInfo:null,source:d.source});this.fLayer2.setScaleRange(d.minScale,d.maxScale);this.fLayer2.on("load",e.hitch(this,c,a,b))}else e.hitch(this,c,a,b)();return b},suggestScale:function(a){var b=new p;(this.fLayer2||this.layer).addPlugin("esri/plugins/FeatureLayerStatistics").then(e.hitch(this,
function(){(this.fLayer2||this.layer).statisticsPlugin.getSuggestedScaleRange({map:arcgisonline.map.main.map}).then(e.hitch(this,function(c){console.log("getSuggestedScaleRange returns",c.relaxedMinScale,c.minScale,c.maxScale);a&&a.set("minScale",c.minScale);a&&a.set("maxScale",c.maxScale);b.resolve()}),e.hitch(this,function(a){console.log("getSuggestedScaleRange error",a);b.reject()}))}));return b},getDateLabel:function(a){return"esriFieldTypeDate"===this.attributeItem.type&&esri.isDefined(a)&&a.toString().length&&
"Null"!==a?(a={domain:this.layer.getDomain(this.attributeItem.name),fieldInfo:this.layer.getField(this.attributeItem.name),value:a,dateFormatInterval:t.calculateDateFormatInterval(f.map(this.allUniqueValues,function(a){return a.value}))},t.createUniqueValueLabel(a)):a},showBusy:function(a,b,c,d){this._busyIndicator&&this._busyIndicator.destroy();c&&c.set("disabled",!0);this._busyIndicatorShow=!0;setTimeout(e.hitch(this,function(){this._busyIndicatorShow&&(this._busyIndicator=y.create({target:a,backgroundColor:"#DDDDDD",
zIndex:d||5}),this._busyIndicator.show())}),500);this._busyIndicatorTimeoutHandler=setTimeout(e.hitch(this,function(a){this._busyIndicatorShow&&(console.log("Hide busy indicator without getting a response."),this.hideBusy(),a&&a.reject())},b),135E3)},hideBusy:function(a){this._busyIndicatorShow&&(a&&a.set("disabled",!1),this._busyIndicatorShow=!1,clearTimeout(this._busyIndicatorTimeoutHandler),this._busyIndicator&&this._busyIndicator.hide())},destroyBusy:function(a){this.hideBusy(a);this._busyIndicator&&
this._busyIndicator.destroy()},handleError:function(a,b,c,d){c&&(this.updateUIWithRenderer(),c=!1);this.rendererErrorPopup?this.rendererErrorPopupMsg!==b&&(esri.isDefined(d)&&10<=d||setTimeout(e.hitch(this,function(d){this.handleError(a,b,c,d)},esri.isDefined(d)?d++:0),1E3)):(this.rendererErrorPopupMsg=b,this.rendererErrorPopup=l.create("div",{id:"rendererErrorPopup"+Math.random(),"class":"rendererErrorPopup"},document.body),console.log(b,a),l.create("div",{id:"rendererErrorPopupContent",innerHTML:("getHistogram"===
b?this.i18n.getHistogramErrorMsg:this.i18n.changeRendererErrorMsg)+"\x3cbr/\x3e\x26nbsp;"},this.rendererErrorPopup),n.animateProperty({node:this.rendererErrorPopup,duration:1E3,properties:{top:{start:10,end:50}},onEnd:e.hitch(this,function(){n.animateProperty({node:this.rendererErrorPopup,duration:1E3,properties:{top:{start:50,end:10}},onEnd:e.hitch(this,function(){n.animateProperty({node:this.rendererErrorPopup,duration:1E3,properties:{top:{start:10,end:50}},onEnd:e.hitch(this,function(){n.animateProperty({node:this.rendererErrorPopup,
duration:1E3,properties:{top:{start:50,end:10}}}).play()})}).play()})}).play()})}).play(),setTimeout(e.hitch(this,function(){this.rendererErrorPopup&&f.forEach(document.body.childNodes,function(a){a&&(this.rendererErrorPopup&&a.id===this.rendererErrorPopup.id)&&(document.body.removeChild(a),this.rendererErrorPopup=null)},this)}),6E3))}}});