// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/map/dijit/renderer/_WatercolorMixin","dojo/_base/declare dojo/_base/lang dojo/_base/connect dojo/_base/array dojo/_base/Color dojo/Deferred dojo/dom dojo/dom-construct esri/lang esri/symbols/jsonUtils esri/styles/basic esri/styles/type esri/renderers/smartMapping esri/tasks/query esri/tasks/QueryTask esri/tasks/UniqueValueDefinition esri/tasks/GenerateRendererParameters esri/tasks/GenerateRendererTask esri/tasks/StatisticDefinition esri/renderers/SimpleRenderer esri/renderers/UniqueValueRenderer esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol esri/dijit/OpacitySlider".split(" "),
function(n,d,p,q,r,f,s,t,u,v,w,x,m,y,z,A,B,C,D,E,F,G,H,I){return{buildWatercolorRenderer:function(c){var a=new f;setTimeout(function(){a.progress(a)},1);if(this.isFeatColl||this.isCSV||this.hasDynamic)this.buildWatercolorRendererGo(!1,c,a);else if("UniqueValueRenderer"!==this.renderer.declaredClass)if(this.isOwnerOfHostedFS){var b=this.layer.getEditCapabilities();!this.layer.isEditable()||!b.canCreate&&(b.canUpdate||b.canDelete)||this.mapLayer.featureTemplatesChanged?this.buildWatercolorRendererGo(!0,
c,a):arcgisonline.map.edit.hasDefaultTypesAndTemplates(this.layer)?this.buildWatercolorRendererGo(!0,c,a):(b=arcgisonline.sharing.dijit.dialog.ChoiceDlg.prototype.statics.getInstance(),b.show({title:this.i18n.warning,message:this.i18n.featureTypesAndTemplatesWarning,choiceOneTitle:this.i18n.yesLabel,choiceOneHandler:d.hitch(this,function(){this.buildWatercolorRendererGo(!0,c,a)}),choiceTwoTitle:this.i18n.noLabel,choiceTwoHandler:d.hitch(this,function(){a.reject()})}))}else this.buildWatercolorRendererGo(!1,
c,a);else this.attributeItem.name!==this.renderer.attributeField?this.isOwnerOfHostedFS?(b=this.layer.getEditCapabilities(),!this.layer.isEditable()||!b.canCreate&&(b.canUpdate||b.canDelete)||this.mapLayer.featureTemplatesChanged?this.buildWatercolorRendererGo(!0,c,a):arcgisonline.map.edit.hasDefaultTypesAndTemplates(this.layer)?this.buildWatercolorRendererGo(!0,c,a):(b=arcgisonline.sharing.dijit.dialog.ChoiceDlg.prototype.statics.getInstance(),b.show({title:this.i18n.warning,message:this.i18n.featureTypesAndTemplatesWarning,
choiceOneTitle:this.i18n.yesLabel,choiceOneHandler:d.hitch(this,function(){this._onSaveRendererGo(!0,c,a)}),choiceTwoTitle:this.i18n.noLabel,choiceTwoHandler:d.hitch(this,function(){})}))):this.buildWatercolorRendererGo(!1,c,a):this.isOwnerOfHostedFS?(b=this.layer.getEditCapabilities(),!this.layer.isEditable()||!b.canCreate&&(b.canUpdate||b.canDelete)||this.mapLayer.featureTemplatesChanged?this.buildWatercolorRendererGo(!0,c,a):arcgisonline.map.edit.hasDefaultTypesAndTemplates(this.layer)?this.buildWatercolorRendererGo(!0,
c,a):(b=arcgisonline.sharing.dijit.dialog.ChoiceDlg.prototype.statics.getInstance(),b.show({title:this.i18n.warning,message:this.i18n.featureTypesAndTemplatesWarning,choiceOneTitle:this.i18n.yesLabel,choiceOneHandler:d.hitch(this,function(){this._onSaveRendererGo(!0,c,a)}),choiceTwoTitle:this.i18n.noLabel,choiceTwoHandler:d.hitch(this,function(){this._onSaveRendererGo(!1,c,a)})}))):this.buildWatercolorRendererGo(!1,c,a);return a},buildWatercolorRendererGo:function(c,a,b){a=a||{};arcgisonline.map.dynLayer.checkDynamicLayers(this.mapLayer);
this.hasDynamic=arcgisonline.map.main.hasDynamicLayers(this.mapLayer);var f=a.attributeItem2||this.attributeItem2,g=a.attributeItem3||this.attributeItem3,h=a.attributeItem4||this.attributeItem4,k=a.attributeItem5||this.attributeItem5,e=[];e.push((a.attributeItem||this.attributeItem).name);e.push(f.name);g&&(e.push(g.name),h&&(e.push(h.name),k&&e.push(k.name)));var l=null;dojo.forEach(this.layer.fields,function(a){"TADULTBASE"===a.name&&(l=a.name)});m.createBlendRenderer({layer:this.fLayer||this.layer,
blendedFields:e,normalizationField:l,theme:"default",basemap:this.getBasemapType(),useStdDev:!0,showOthers:!0,minOpacity:0.3,maxOpacity:1,markers:!1}).then(d.hitch(this,function(a){b.isRejected()||(c&&(arcgisonline.map.edit.removeTypesAndTemplatesOnLayer(this.mapLayer.layer),this.mapLayer.featureTemplatesChanged=!0),delete this.authoringInfo,this.defaultInfo={defaultSymbol:a.renderer.defaultSymbol,defaultLabel:a.renderer.defaultLabel},delete a.renderer.defaultSymbol,delete a.renderer.defaultLabel,
b.resolve(a.renderer))}),d.hitch(this,function(a){b.isRejected()||(this.handleError(a,"createTypeRenderer",!0),b.reject())}))},applyWatercolorRenderer:function(c){var a=this.getRendererStyle((this.fLayer||this.layer).renderer);this.setRenderer(c);!this.hasDynamic&&("watercolor"!==a&&this.scheme&&esri.isDefined(this.scheme.opacity))&&(this.layer.setOpacity(this.scheme.opacity),this.transparencySlider&&this.transparencySlider.set("value",1-this.scheme.opacity));(arcgisonline.map.featColl.isFeatureCollection(this.mapLayer)||
this.isCSV)&&arcgisonline.map.main.markMapAsChanged("onRendererChange");this.isOwnerOfHostedFS&&!this.layer.templates.length&&arcgisonline.map.edit.createTypesAndTemplatesOnLayer(this.layer);this.updateLegendPopup()}}});