// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
require({cache:{"url:arcgisonline/map/dijit/renderer/templates/LabelsDlg.html":'\x3cdiv class\x3d"${baseClass}"\x3e\r\n  \x3cdiv id\x3d"labels-dialog" data-dojo-type\x3d"dijit/Dialog" data-dojo-attach-point\x3d"_dialog" title\x3d"${i18n.labelLegend}"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"_labelsContent"\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"_labelsPrecision" style\x3d"padding-top: 15px;"\x3e\r\n      \x3ctable\x3e\r\n        \x3ctbody\x3e\r\n          \x3ctr\x3e\r\n            \x3ctd\x3e\r\n              \x3cspan\x3e${i18n.roundLabels}\x3c/span\x3e\r\n            \x3c/td\x3e\r\n            \x3ctd\x3e\r\n              \x3cselect data-dojo-attach-point\x3d"_rendererLabelsPrecision" data-dojo-attach-event\x3d"onChange:_onChangeLabelsPrecision" data-dojo-type\x3d"dijit.form.Select" maxHeight\x3d"150" sortByLabel\x3d"false" style\x3d"margin: 0 10px;"\x3e\r\n              \x3c/select\x3e\r\n            \x3c/td\x3e\r\n          \x3c/tr\x3e\r\n        \x3c/tbody\x3e\r\n      \x3c/table\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"esriFloatTrailing" style\x3d"margin:10px 0;"\x3e\r\n      \x3cbutton type\x3d"button" data-dojo-attach-point\x3d"_okBtn" data-dojo-type\x3d"dijit/form/Button" data-dojo-attach-event\x3d"onClick:onOk" class\x3d"calcite primary"\x3e${i18n.ok}\x3c/button\x3e\r\n      \x3cbutton type\x3d"button" data-dojo-attach-point\x3d"_cancelBtn" data-dojo-type\x3d"dijit/form/Button" data-dojo-attach-event\x3d"onClick:onCancel" class\x3d"calcite cancel"\x3e${i18n.cancel}\x3c/button\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("arcgisonline/map/dijit/renderer/LabelsDlg","require dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/has dojo/dom-construct dojo/dom-style dojo/string dojo/number dijit/_Widget dijit/_Templated dijit/form/TextBox dojox/data/AndOrWriteStore dojo/i18n!arcgisonline/nls/arcgisonline dojo/text!arcgisonline/map/dijit/renderer/templates/LabelsDlg.html".split(" "),function(g,t,k,q,n,u,e,v,l,c,w,x,r,y,s,z){g=t([w,x],{declaredClass:"arcgisonline.map.dijit.renderer.LabelsDlg",
basePath:g.toUrl("arcgisonline/map/renderer"),baseClass:"esriLabelsDlg",widgetsInTemplate:!0,templateString:z,pattern:"#,###,###,##0.######",statics:{_instance:null,getInstance:function(){null===this._instance&&(this._instance=new arcgisonline.map.dijit.renderer.LabelsDlg);return this._instance}},_connects:[],postMixInProperties:function(){this.inherited(arguments);this.i18n={};k.mixin(this.i18n,s.common);k.mixin(this.i18n,s.rendererLabelsDlg)},destroy:function(){q.forEach(this._connects,n.disconnect);
delete this._connects;this.inherited(arguments)},show:function(a){this.renderer=k.clone(a);"esri.renderer.ClassBreaksRenderer"===a.declaredClass&&(v.set(this._labelsPrecision,"display",""),this.fillLabelsPrecisionSelect(a),this.buildList(),this._dialog.show())},buildList:function(a){e.empty(this._labelsContent);var b=e.create("table",{},this._labelsContent),b=e.create("tbody",{},b),h=e.create("tr",{style:"height:30px;"},b);e.create("td",{style:"font-weight: bold;",innerHTML:this.i18n.textLabelTitle},
h);e.create("td",{style:"font-weight: bold;min-width:80px;",innerHTML:this.i18n.valueTitle},h);var m;for(m=this.renderer.infos.length-1;0<=m;m--){var d=this.renderer.infos[m],g=c.format(d.minValue,{pattern:this.pattern})+" - "+c.format(d.maxValue,{pattern:this.pattern}),h=e.create("tr",{},b),p=e.create("div",{},e.create("td",{},h)),f=d.label||g;esri.isDefined(a)&&("percent-of-total"===this.renderer.normalizationType?0===a?f=l.substitute(this.i18n.percentValue,{num:c.format(d.minValue,{pattern:this.pattern})})+
" - "+l.substitute(this.i18n.percentValue,{num:c.format(d.maxValue,{pattern:this.pattern})}):1>a?(f=c.round(1/a),f=l.substitute(this.i18n.percentValue,{num:c.format(c.round(d.minValue/a)/f,{pattern:this.pattern})})+" - "+l.substitute(this.i18n.percentValue,{num:c.format(c.round(d.maxValue/a)/f,{pattern:this.pattern})})):f=l.substitute(this.i18n.percentValue,{num:c.format(c.round(d.minValue/a)*a,{pattern:this.pattern})})+" - "+l.substitute(this.i18n.percentValue,{num:c.format(c.round(d.maxValue/a)*
a,{pattern:this.pattern})}):0===a?f=c.format(d.minValue,{pattern:this.pattern})+" - "+c.format(d.maxValue,{pattern:this.pattern}):1>a?(f=c.round(1/a),f=c.format(c.round(d.minValue/a)/f,{pattern:this.pattern})+" - "+c.format(c.round(d.maxValue/a)/f,{pattern:this.pattern})):f=c.format(c.round(d.minValue/a)*a,{pattern:this.pattern})+" - "+c.format(c.round(d.maxValue/a)*a,{pattern:this.pattern}));d=new r({trim:!1,value:f,style:"padding:5px; margin: 0 5px;",intermediateChanges:!0},p);this.renderer.infos[m].label=
f;this._connects.push(n.connect(d,"onChange",k.hitch(this,function(a,b,c,d){this._rendererLabelsPrecision.set("value",this.i18n.selectAnOptions);d.length||(d=b,a.set("value",d));this.renderer.infos[c].label=d},d,g,m)));e.create("td",{innerHTML:g},h)}this.renderer.defaultSymbol&&(h=e.create("tr",{},b),e.create("td",{innerHTML:this.i18n.outOfRange},h),p=e.create("div",{},e.create("td",{},h)),d=new r({trim:!1,value:this.renderer.defaultLabel||this.i18n.other,style:"padding:5px; margin: 0 5px;"},p),this._connects.push(n.connect(d,
"onChange",k.hitch(this,function(a,b){b.length||(b=this.i18n.other,a.set("value",b));this.renderer.defaultLabel=b},d))))},fillLabelsPrecisionSelect:function(){var a=[];a.push({name:this.i18n.selectAnOptions,type:"select"});a.push({name:this.i18n.none,type:"none"});var b=0;q.forEach(this.renderer.infos,function(a){b=Math.max(b,this.getPrecision(a.minValue));b=Math.max(b,this.getPrecision(a.maxValue))},this);var c=Math.abs(this.renderer.infos[0].minValue-this.renderer.infos[this.renderer.infos.length-
1].maxValue);1E7<c?(a.push({name:"1000000",type:"1000000"}),a.push({name:"100000",type:"100000"}),a.push({name:"10000",type:"10000"}),a.push({name:"1000",type:"1000"}),a.push({name:"100",type:"100"}),a.push({name:"10",type:"10"}),0<b&&a.push({name:"1",type:"1"}),1<b&&a.push({name:"0.1",type:"0.1"}),2<b&&a.push({name:"0.01",type:"0.01"})):1E6<c?(a.push({name:"100000",type:"100000"}),a.push({name:"10000",type:"10000"}),a.push({name:"1000",type:"1000"}),a.push({name:"100",type:"100"}),a.push({name:"10",
type:"10"}),0<b&&a.push({name:"1",type:"1"}),1<b&&a.push({name:"0.1",type:"0.1"}),2<b&&a.push({name:"0.01",type:"0.01"})):1E5<c?(a.push({name:"10000",type:"10000"}),a.push({name:"1000",type:"1000"}),a.push({name:"100",type:"100"}),a.push({name:"10",type:"10"}),0<b&&a.push({name:"1",type:"1"}),1<b&&a.push({name:"0.1",type:"0.1"}),2<b&&a.push({name:"0.01",type:"0.01"})):1E4<c?(a.push({name:"1000",type:"1000"}),a.push({name:"100",type:"100"}),a.push({name:"10",type:"10"}),0<b&&a.push({name:"1",type:"1"}),
1<b&&a.push({name:"0.1",type:"0.1"}),2<b&&a.push({name:"0.01",type:"0.01"})):1E3<c?(a.push({name:"100",type:"100"}),a.push({name:"10",type:"10"}),0<b&&a.push({name:"1",type:"1"}),1<b&&a.push({name:"0.1",type:"0.1"}),2<b&&a.push({name:"0.01",type:"0.01"}),3<b&&a.push({name:"0.001",type:"0.001"})):100<c?(a.push({name:"10",type:"10"}),0<b&&a.push({name:"1",type:"1"}),1<b&&a.push({name:"0.1",type:"0.1"}),2<b&&a.push({name:"0.01",type:"0.01"}),3<b&&a.push({name:"0.001",type:"0.001"}),4<b&&a.push({name:"0.0001",
type:"0.0001"}),5<b&&a.push({name:"0.00001",type:"0.00001"})):10<c?(0<b&&a.push({name:"1",type:"1"}),1<b&&a.push({name:"0.1",type:"0.1"}),2<b&&a.push({name:"0.01",type:"0.01"}),3<b&&a.push({name:"0.001",type:"0.001"}),4<b&&a.push({name:"0.0001",type:"0.0001"}),5<b&&a.push({name:"0.00001",type:"0.00001"}),6<b&&a.push({name:"0.000001",type:"0.000001"})):1<c?(1<b&&a.push({name:"0.1",type:"0.1"}),2<b&&a.push({name:"0.01",type:"0.01"}),3<b&&a.push({name:"0.001",type:"0.001"}),4<b&&a.push({name:"0.0001",
type:"0.0001"}),5<b&&a.push({name:"0.00001",type:"0.00001"}),6<b&&a.push({name:"0.000001",type:"0.000001"})):0.1<c?(2<b&&a.push({name:"0.01",type:"0.01"}),3<b&&a.push({name:"0.001",type:"0.001"}),4<b&&a.push({name:"0.0001",type:"0.0001"}),5<b&&a.push({name:"0.00001",type:"0.00001"}),6<b&&a.push({name:"0.000001",type:"0.000001"})):0.01<c&&(3<b&&a.push({name:"0.001",type:"0.001"}),4<b&&a.push({name:"0.0001",type:"0.0001"}),5<b&&a.push({name:"0.00001",type:"0.00001"}),6<b&&a.push({name:"0.000001",type:"0.000001"}));
this.precisionStore=new y({data:{label:"name",identifier:"type",items:a}});this._rendererLabelsPrecision.setStore(this.precisionStore,"",{})},getPrecision:function(a){for(var b=1;Math.round(a*b)/b!==a;)b*=10;return Math.log(b)/Math.LN10},onCancel:function(){this._dialog.hide()},onOk:function(){this.onRendererUpdate(this.renderer);this._dialog.hide()},_onChangeLabelsPrecision:function(){var a=this._rendererLabelsPrecision.get("value");"select"!==a&&("none"===a?this.buildList(0):this.buildList(parseFloat(a)))},
onRendererUpdate:function(a){}});u("extend-esri")&&k.setObject("arcgisonline.map.dijit.renderer.LabelsDlg",g);return g});