// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("require ../core/declare dojo/_base/lang dojo/Deferred dojo/io-query ../core/JSONSupport ../core/urlUtils ../request ../geometry/Extent ../geometry/SpatialReference ./GraphicsLayer ./support/LabelClass ./support/Field ../renderers/support/jsonUtils ../widgets/PopupLegacy/PopupTemplate".split(" "),function(k,p,h,l,q,r,f,m,s,n,t,u,v,w,x){return p([t,r],{declaredClass:"esri.layers.SceneLayer",classMetadata:{reader:{add:"copyright initialExtent fullExtent geometryType renderer labelingInfo cachedDrawingInfo spatialReference objectIdField popupTemplate".split(" "),
exclude:"id version name href ZFactor alias description copyrightText popupInfo".split(" ")}},normalizeCtorArgs:function(a,b){var c=a;"string"===typeof a&&(c=h.mixin({},{url:a},b));this._addTrailingSlash&&"/"!==c.url.charAt(c.url.length-1)&&(c.url+="/");return c},initialize:function(){this.addResolvingPromise(this._fetchService())},_canUseXhr:null,_addTrailingSlash:!1,_alreadyIssuedWarnings:{},copyright:null,_copyrightReader:function(a,b){return b.copyrightText},fields:null,_fieldsReader:function(a){return a.map(function(a){return new v(a)})},
fullExtent:null,_fullExtentReader:function(a,b){var c=b.store,d=c.indexCRS||c.geographicCRS,d=d&&parseInt(d.substring(d.lastIndexOf("/")+1,d.length),10);return new s(c.extent[0],c.extent[1],c.extent[2],c.extent[3],new n(d))},elevationInfo:null,geometryType:null,_geometryTypeReader:function(a,b){var c=b.store;switch(c&&c.profile){case "features-points":c="esriGeometryPoint";break;case "features-lines":c="esriGeometryPolyline";break;case "features-polygons":c="esriGeometryPolygon";break;default:c="esriGeometryMesh"}return c},
initialExtent:null,_initialExtentReader:function(a,b){return this._fullExtentReader(a,b)},_labelingInfoReader:function(a,b){if(a=b.drawingInfo&&b.drawingInfo.labelingInfo){var c=/\[([^\[\]]+)\]/ig,d,e=this,g=function(a,c){var d=e.getField(c,b.fields);return"["+(d&&d.name||c)+"]"};a=a.map(function(a){a=new u(a);if(d=a.labelExpression)a.labelExpression=d.replace(c,g);return a})}return a},_rendererReader:function(a,b){(a=b.drawingInfo&&b.drawingInfo.renderer)&&(a=w.fromJSON(a));return a},_cachedDrawingInfoReader:function(a,
b){a=b.cachedDrawingInfo;if(null==a||"object"!==typeof a)a={};null==a.color&&(a.color=!1);return a},_spatialReferenceReader:function(a,b){return null!=b.spatialReference?new n(b.spatialReference):this._fullExtentReader(void 0,b).spatialReference},_popupTemplateReader:function(a,b){return b.popupInfo?new x(b.popupInfo):void 0},_objectIdFieldReader:function(a,b){!a&&b.fields&&b.fields.some(function(b){"esriFieldTypeOID"===b.type&&(a=b.name);return!!a});return a},viewModulePaths:{"3d":"../views/3d/layers/SceneLayerView3DFactory"},
createGraphicsController:function(a){var b=new l;a.layer=this;a.addUrlTokenFunction=this._addUrlToken.bind(this);a.warningEvent=this.warningEvent.bind(this);k(["./graphics/controllers/I3SOnDemandController"],function(c){var d=new c(a);d.then(function(){this.emit("graphics-controller-create",{graphicsController:d});b.resolve(d)}.bind(this),function(a){b.reject(a)})}.bind(this));return b.promise},getField:function(a){return!this._companionFeatureLayer?void 0:this._companionFeatureLayer.getField(a)},
warningEvent:function(a,b){null==this._alreadyIssuedWarnings[a]&&(this._alreadyIssuedWarnings[a]=!0,this.emit("i3s-load-log",{type:1===b?"fatal":"warning",msg:a}),console.warn("i3s-load-log warningEvent severity "+b," message "+a))},_addUrlToken:function(a){var b=h.mixin({},this.parsedUrl.query,{token:this.token}),b=q.objectToQuery(b);a+=b?"?"+b:"";null==this._canUseXhr&&(this._canUseXhr=f.canUseXhr(a));return!this._canUseXhr?f.addProxy(a):a},_fetchService:function(){return m({url:this._addUrlToken(this.parsedUrl.path),
handleAs:"json"}).then(function(a){a._ssl&&(delete a._ssl,this.url=this.url.replace(/^http:/i,"https:"));var b=a.store;null==b.indexCRS&&null==b.geographicCRS&&this.warningEvent("Input data invalid: layer.layerInfo.indexCRS is undefined.",1);this.read(a);a=h.getObject("store.profile",!1,a);if(-1<["meshpyramids","features-points"].indexOf(a)){var c=function(a){console.warn("Companion FeatureLayer could not be loaded. Popups will not work for this SceneLayer: "+this.title);e.resolve(this)}.bind(this),
d=function(a,b){k(["./FeatureLayer"],function(b){this._companionFeatureLayer=new b(a);this._companionFeatureLayer.then(function(a){if(!this.fields||0===this.fields.length)this.fields=a.fields;e.resolve(this)}.bind(this),c)}.bind(this))}.bind(this),e=new l;a=this.url.replace("/SceneServer/","/FeatureServer/");var b=a.indexOf("/layers/"),g;0<=b&&(g=parseInt(a.substr(b+8)),a=a.substr(0,b)+"/"+g);var f=a.replace(/\/[\d]*\/?$/,"");m({url:this._addUrlToken(f),content:{f:"json"},handleAs:"json"}).then(function(a){d(f+
"/"+a.layers[g].id,e)},c);return e.promise}}.bind(this))}})});