// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("../../core/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/event dojo/dom-attr dojo/has dojo/i18n dojo/io-query dojo/i18n!../../nls/jsapi dojo/string dojo/query dojo/dom-style dojo/dom-class dojo/dom-construct dojo/Deferred dojo/data/ItemFileWriteStore dijit/registry dijit/Dialog ../../kernel ../../core/lang ../../request ./HelpWindow ../../tasks/support/Query ../../widgets/BrowseItems ./PluginAnalysisLayers".split(" "),function(r,e,n,v,w,s,I,J,x,q,m,u,p,y,z,A,B,C,D,
K,l,E,F,G,H,L){r={};e.mixin(r,{_helpDialog:null,i18n:null,initHelpLinks:function(a,b,c){this._helpDialog||(this._helpDialog=new F);if(a){var d=C.byNode(a),f=d?d.get("helpFileName"):c&&c.helpFileName?c.helpFileName:null;u("[esriHelpTopic]",a).forEach(function(d,k,h){d&&(p.set(d,"display",!l.isDefined(b)||!0===b?"":"none"),v.connect(d,"onclick",e.hitch(this,function(b){w.stop(b);this._helpDialog.show(b,{helpId:s.get(d,"esriHelpTopic"),helpFileName:f,analysisGpServer:c&&c.analysisGpServer?c.analysisGpServer:
null,helpParentNode:a})})))},this)}},constructAnalysisFeatColl:function(a){var b={},c;b.featureCollection=a.layerDefinition;for(c in b.featureCollection)b.featureCollection.hasOwnProperty(c)&&"objectIdField"===c&&(b.featureCollection.objectIdFieldName=e.clone(b.featureCollection.objectIdField),delete b.featureCollection.objectIdField);b.featureCollection.features=a.featureSet.features;return b},constructAnalysisInputLyrObj:function(a){var b={};if(a.url&&!a._collection)b={url:a.url},a.getDefinitionExpression&&
a.getDefinitionExpression()?b.filter=a.getDefinitionExpression():l.isDefined(a.definitionExpression)&&""!==a.definitionExpression&&(b.filter=a.definitionExpression),a.credential&&(b.serviceToken=a.credential.token),a.analysisReady&&(b.analysisReady=!0),-1!==b.url.indexOf("?")&&(a=b.url.substring(b.url.indexOf("?")+1,b.url.length),a=x.queryToObject(a),e.mixin(b,a),b.url=b.url.substring(0,b.url.indexOf("?")));else if(!a.url||a._collection)b=a.toJSON();return b},buildReport:function(a,b){var c="";b||
(b={},e.mixin(b,q.analysisMsgCodes));n.forEach(a,function(a,f){var g,k,h;"string"===typeof a.message?(g=l.isDefined(b[a.messageCode])?b[a.messageCode]:a.message,c+=a.style.substring(0,a.style.indexOf("\x3c/"))+(!this._isEmptyObject(a.params)?m.substitute(g,a.params):g)+a.style.substring(a.style.indexOf("\x3c/"))):e.isArray(a.message)&&(h=[],k=e.clone(a.style),n.forEach(a.message,function(c,f){k=k.replace(/<\//,"${"+f+"}");g=l.isDefined(b[a.messageCode+"_"+f])?b[a.messageCode+"_"+f]:c;g=!this._isEmptyObject(a.params)?
m.substitute(g,a.params):g;h.push(g+"\x3c/")},this),k=m.substitute(k,h),c+=k)},this);return c},getLayerFeatureCount:function(a,b){var c=new G;c.geometry=b.geometry||"";c.where=b.where||"1\x3d1";c.geometryType=b.geometryType||"esriGeometryEnvelope";return a.queryCount(c)},createPolygonFeatureCollection:function(a){var b;b={layerDefinition:null,featureSet:{features:[],geometryType:"esriGeometryPolygon"}};b.layerDefinition={currentVersion:10.2,copyrightText:"",defaultVisibility:!0,relationships:[],isDataVersioned:!1,
supportsRollbackOnFailureParameter:!0,supportsStatistics:!0,supportsAdvancedQueries:!0,geometryType:"esriGeometryPolygon",minScale:0,maxScale:0,objectIdField:"OBJECTID",templates:[],type:"Feature Layer",displayField:"TITLE",visibilityField:"VISIBLE",name:a,hasAttachments:!1,typeIdField:"TYPEID",capabilities:"Query",allowGeometryUpdates:!0,htmlPopupType:"",hasM:!1,hasZ:!1,globalIdField:"",supportedQueryFormats:"JSON",hasStaticData:!1,maxRecordCount:-1,indexes:[],types:[],drawingInfo:{renderer:{type:"simple",
symbol:{color:[0,0,0,255],outline:{color:[0,0,0,255],width:3,type:"esriSLS",style:"esriSLSSolid"},type:"esriSFS",style:"esriSFSNull"},label:"",description:""},transparency:0,labelingInfo:null,fixedSymbols:!0},fields:[{alias:"OBJECTID",name:"OBJECTID",type:"esriFieldTypeOID",editable:!1},{alias:"Title",name:"TITLE",length:50,type:"esriFieldTypeString",editable:!0},{alias:"Visible",name:"VISIBLE",type:"esriFieldTypeInteger",editable:!0},{alias:"Description",name:"DESCRIPTION",length:1073741822,type:"esriFieldTypeString",
editable:!0},{alias:"Type ID",name:"TYPEID",type:"esriFieldTypeInteger",editable:!0}]};return b},createPointFeatureCollection:function(a){var b;b={layerDefinition:null,featureSet:{features:[],geometryType:"esriGeometryPoint"}};b.layerDefinition={objectIdField:"OBJECTID",templates:[],type:"Feature Layer",drawingInfo:{renderer:{field1:"TYPEID",type:"simple",symbol:{height:24,xoffset:0,yoffset:12,width:24,contentType:"image/png",type:"esriPMS",url:"http://static.arcgis.com/images/Symbols/Basic/GreenStickpin.png"},
description:"",value:"0",label:"Stickpin"}},displayField:"TITLE",visibilityField:"VISIBLE",name:a,hasAttachments:!1,typeIdField:"TYPEID",capabilities:"Query",types:[],geometryType:"esriGeometryPoint",fields:[{alias:"OBJECTID",name:"OBJECTID",type:"esriFieldTypeOID",editable:!1},{alias:"Title",name:"TITLE",length:50,type:"esriFieldTypeString",editable:!0},{alias:"Visible",name:"VISIBLE",type:"esriFieldTypeInteger",editable:!0},{alias:"Description",name:"DESCRIPTION",length:1073741822,type:"esriFieldTypeString",
editable:!0},{alias:"Type ID",name:"TYPEID",type:"esriFieldTypeInteger",editable:!0}]};return b},createFolderStore:function(a,b){var c=new B({data:{identifier:"id",label:"name",items:[]}});c.newItem({name:b,id:""});n.forEach(a,function(a){c.newItem({name:a.title,id:a.id})});return c},setupFoldersUI:function(a){a.folderSelect.set("store",a.folderStore);l.isDefined(a.folderId)?a.folderStore.get(a.folderId).then(e.hitch(this,function(b){l.isDefined(b)?a.folderSelect.set("value",b.name):a.folderStore.get("").then(function(b){a.folderSelect.set("value",
b.name)},this)})):a.folderName?a.folderStore.fetch({query:{name:a.folderName},onComplete:e.hitch(this,function(b){l.isDefined(b)&&0<b.length?a.folderSelect.set("value",b[0].name):a.folderStore.get("").then(function(b){a.folderSelect.set("value",b.name)},this)})}):a.username?a.folderSelect.set("value",a.username):a.folderStore.get("").then(function(b){a.folderSelect.set("value",b.name)},this)},_isEmptyObject:function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},validateServiceName:function(a,
b){var c=/(:|&|<|>|%|#|\?|\\|\"|\/|\+)/.test(a),d=!0,f,g;l.isDefined(b)&&b.textInput&&(g=b.textInput);this.initI18n();if(0===a.length||0===m.trim(a).length)f=this.i18n.requiredValue,d=!1;else if(c)f=this.i18n.invalidServiceName,d=!1;else if(98<a.length||170<encodeURIComponent(a).length)f=this.i18n.invalidServiceNameLength,d=!1;g&&!d&&g.set("invalidMessage",f);return d},getStepNumber:function(a){u(".esriAnalysisNumberLabel",a).forEach(function(a,c){var d=this._getNumberLabel(c);s.set(a,"innerHTML",
d)},this)},_getNumberLabel:function(a){var b="";this.initI18n();switch(a){case 0:b=this.i18n.oneLabel;break;case 1:b=this.i18n.twoLabel;break;case 2:b=this.i18n.threeLabel;break;case 3:b=this.i18n.fourLabel;break;case 4:b=this.i18n.fiveLabel;break;case 5:b=this.i18n.sixLabel;break;case 6:b=this.i18n.sevenLabel;break;case 7:b=this.i18n.eightLabel;break;case 8:b=this.i18n.nineLabel}return b},populateAnalysisLayers:function(a,b,c,d){if(a){var f=[],g=a.get(b);a._titleRow&&p.set(a._titleRow,"display",
"none");a._analysisLabelRow&&p.set(a._analysisLabelRow,"display","table-row");a._selectAnalysisRow&&(p.set(a._selectAnalysisRow,"display","table-row"),y.add(a._analysisSelect.domNode,"esriTrailingMargin3"),p.set(a._analysisSelect.domNode.parentNode,"padding-bottom","1em"));a.domNode&&this.getStepNumber(a.domNode);l.isDefined(d)&&d.chooseLabel&&f.push({value:-1,label:this.i18n.chooseLabel});n.forEach(a.get(c),function(a,b){var c={value:l.isDefined(d)&&d.chooseLabel?b+1:b,label:a.name};g&&a.name===
g.name&&(c.selected=!0);f.push(c)},this);a._analysisSelect.addOption(f);a._analysisSelect.set("required",!0)}},isValidAnalysisLayer:function(a){var b,c,d,f,g,k,h="",e=!0;b={isValid:e,validationMessage:h};var t,q,p=0,r=0,s=0;if(!l.isDefined(a)||!l.isDefined(a.toolName))return b;this.initI18n();b=a.toolName;c=a.featureLayers;d=a.analysisLayer;a=b.charAt(0).toLowerCase()+b.substring(1);k=this.i18n;n.forEach(c,function(a){"esriGeometryPoint"===a.geometryType&&(g=!0,p++);if("esriGeometryPoint"===a.geometryType||
"esriGeometryMultipoint"===a.geometryType)t=!0;"esriGeometryPolyline"===a.geometryType&&(q=!0,s++);"esriGeometryPolygon"===a.geometryType&&(f=!0,r++)},this);-1!==n.indexOf(["CreateDriveTimeAreas","PlanRoutes","ConnectOriginsToDestinations"],b)&&(!g||d&&"esriGeometryPoint"!==d.geometryType)?(h=m.substitute(this.i18n.selectPointLayer,{toolName:k[a]}),e=!1):("AggregatePoints"===b||"InterpolatePoints"===b)&&(d&&!("esriGeometryPoint"===d.geometryType||"esriGeometryMultipoint"===d.geometryType)||!t)?(h=
m.substitute(this.i18n.selectPointLayer,{toolName:k[a]}),e=!1):"CalculateDensity"===b&&(!t&&!q||d&&!("esriGeometryPoint"===d.geometryType||"esriGeometryMultipoint"===d.geometryType||"esriGeometryPolyline"===d.geometryType))?(h=m.substitute(this.i18n.areaFeatureInvalidMsg,{toolName:k[a]}),e=!1):"FindHotSpots"===b&&(!t&&!f||d&&!("esriGeometryPoint"===d.geometryType||"esriGeometryMultipoint"===d.geometryType||"esriGeometryPolygon"===d.geometryType))?(h=m.substitute(this.i18n.hotspotsLineFeatureMsg,{toolName:k[a]}),
e=!1):("OverlayLayers"===b||"AggregatePoints"===b||"SummarizeWithin"===b||"SummarizeNearby"===b||"FindNearest"===b||"MergeLayers"===b)&&(0===c.length||1===c.length&&(c[0]===d||!l.isDefined(d)))?(h=m.substitute(this.i18n.overlayValidationMsg,{toolName:k[a]}),e=!1):"ConnectOriginsToDestinations"===b&&(0===c.length||2>p)?(h=m.substitute(this.i18n.odPointMsg,{toolName:k[a]}),e=!1):"AggregatePoints"===b&&1<c.length?(f=n.some(c,function(a){return"esriGeometryPolygon"===a.geometryType}),f||(h=m.substitute(this.i18n.aggregatePolyMsg,
{toolName:k[a]}),e=!1)):"MergeLayers"===b&&1<c.length?1<p||(1<s||1<r)||(h=this.i18n.mergeValidationMsg,e=!1):("SummarizeWithin"===b||"DissolveBoundaries"===b)&&(d&&"esriGeometryPolygon"!==d.geometryType||!f)?(h=m.substitute(this.i18n.selectPolyLayer,{toolName:k[a]}),e=!1):"ExtractData"===b?(e=n.some(c,function(a){return-1!==a.capabilities.indexOf("Extract")}))||(h=m.substitute(this.i18n.extractValidationMsg)):"ConnectOriginsToDestinations"===b&&1<c.length&&(g=n.some(c,function(a){var b=l.isDefined(d)&&
d.id===a.id;return"esriGeometryPoint"===a.geometryType&&!b}),g||(h=m.substitute(this.i18n.odPointMsg,{toolName:k[a]}),e=!1));return b={isValid:e,validationMessage:h}},initI18n:function(){this.i18n||(this.i18n={},e.mixin(this.i18n,q.common),e.mixin(this.i18n,q.analysisTools),e.mixin(this.i18n,q.analysisMsgCodes),e.mixin(this.i18n,q.browseLayersDlg))},addBrowseAnalysisDialog:function(a){var b=[];if(a&&a.widget)return this.i18n||this.initI18n(),b.push({label:this.i18n.categoryAll,value:""}),b.push({label:this.i18n.categoryHistoricalMaps,
value:"historical"}),b.push({label:this.i18n.categoryDemographics,value:"demographics"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryIncome,value:"income"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryPopulation,value:"population"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategorySegmentation,value:"behaviors"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryBusiness,value:"business"}),
b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryAtRisk,value:'"at risk"'}),b.push({label:this.i18n.categoryLandscape,value:"landscape"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryClimate,value:"climate"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryEcology,value:"ecology"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategorySpecies,value:"species"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+
this.i18n.subCategoryDisturbance,value:"disturbance"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryElevation,value:"elevation"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryLand,value:"landcover"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryHazards,value:"hazards"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryOceans,value:"oceans"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+
this.i18n.subCategorySoils,value:"soils"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategorySubsurface,value:"subsurface"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryWater,value:"water"}),b.push({label:this.i18n.categoryEarthObservations,value:'"earth observations"'}),b.push({label:this.i18n.categoryUrbanSystems,value:"urban"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategory3DCities,value:"3D"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+
this.i18n.subCategoryMovement,value:"movement"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryParcels,value:"parcels"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryPeople,value:"people"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryPlanning,value:"planning"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryPublic,value:"public"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryWork,
value:"work"}),b.push({label:this.i18n.categoryTransportation,value:"transportation"}),b.push({label:this.i18n.categoryBoundaries,value:"boundaries"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryBoundaries,value:"boundaries"}),b.push({label:"\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;"+this.i18n.subCategoryPlaces,value:"places"}),a=new H({portalUrl:a.widget.get("portalUrl"),message:"",plugin:"esri/dijit/analysis/PluginAnalysisLayers",sortDescending:!0,sort:"title",categories:b,
categoryType:"tags",pagingLinks:3,itemsPerPage:6,"class":"esriBrowseAnalysisLayers itemsGallery",galleryTemplate:'\x3cdiv style\x3d\'opacity:1;\' class\x3d\'grid-item gallery-view galleryNode\'\x3e${item:_formatItemTitle}${item:_formatThumbnail}\x3cdiv class\x3d"linksDiv" style\x3d\'display:none;\'\x3e\x3cdiv class\x3d"esriItemLinks"\x3e\x3cdiv class\x3d"esriFloatLeading"\x3e\x3ca style\x3d"text-decoration: none;"\x3e\x3cspan\x3eAdd layer to analysis\x3c/span\x3e\x3cdiv class\x3d"dijitReset dijitInline esriArrows"\x3e\x3c/div\x3e\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e',
formatThumbnail:function(a){return"\x3cimg class\x3d'grid-item galleryThumbnail' width\x3d'120px' height\x3d'80px' alt\x3d'' src\x3d'"+(a.thumbnailUrl||this._portal.staticImagesUrl+"/desktopapp.png")+"'\x3e"},formatItemTitle:function(a){return'\x3cdiv class\x3d"galleryLabelContainer"\x3e\x3cspan alt\x3d\''+(a.title||a.name||"\x3cNo Title\x3e")+"'\x3e"+(a.title.replace(/_/g," ")||a.name.replace(/_/g," ")||"\x3cNo Title\x3e")+"\x3c/span\x3e\x3c/div\x3e"},style:"width:600px;height:100%;"},z.create("div",
{style:"width:100%"},a.widget.domNode,"last")),new D({title:this.i18n.browseAnalysisTitle,content:a.domNode,doLayout:!0,browseItems:a})},addAnalysisReadyLayer:function(a){if(l.isDefined(a)&&l.isDefined(a.item)&&l.isDefined(a.layersSelect)&&l.isDefined(a.layers)&&l.isDefined(a.browseDialog)){a.browseDialog.browseItems._closePopup();a.browseDialog.hide();var b={url:a.item.url+"/0",itemId:a.item.id,title:a.item.title,analysisReady:!0},c,d=n.some(a.layers,function(a,d){var e=a.analysisReady&&b.analysisReady&&
a.itemId===b.itemId;e&&(c=d);return e}),f,g,k,h=new A;d?(a.posIncrement&&(c+=a.posIncrement),a.layersSelect.set("value",c),a.browseDialog.browseItems.clear(),h.resolve()):(h=E({url:b.url,content:{f:"json"}}),h.then(e.hitch(this,function(c){e.mixin(b,c);b.title=b.title.replace(/_/g," ");b.name=b.title;k=a.layersSelect.getOptions();f=k.splice(k.length-2,2);a.layersSelect.removeOption(f);g=a.layers.length;a.posIncrement&&(g+=a.posIncrement);f.unshift({value:g,label:b.title,selected:!0});a.layersSelect.addOption(f);
a.layersSelect.set("value",g);a.layers.push(b);a.browseDialog.browseItems.clear()})));return h.promise}},addReadyToUseLayerOption:function(a,b){a&&a.showReadyToUseLayers&&(b||(b=[]),a.signInPromise.then(e.hitch(this,function(){a._browsedlg=this.addBrowseAnalysisDialog({widget:a});n.forEach(b,function(b){b.addOption({type:"separator",value:""});b.addOption({value:"browse",label:a.i18n.browseAnalysisTitle})},this);a.own(a._browsedlg.browseItems.on("select-change",e.hitch(a,a._handleBrowseItemsSelect)),
a._browsedlg.on("hide",e.hitch(a,function(){n.forEach(b,function(a){"browse"===a.get("value")&&a.reset()})})))})))}});return r});