// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("../core/declare dojo/_base/array dojo/_base/lang dojo/_base/kernel ../core/lang ./SpatialReference ./Geometry ./Point ./support/webMercatorUtils ./support/mathUtils".split(" "),function(x,v,y,u,z,w,A,k,t,B){var p=x(A,{declaredClass:"esri.geometry.Extent",classMetadata:{computed:{cache:"xmin ymin zmin mmin xmax ymax zmax mmax".split(" "),center:["cache"],extent:["cache"],hasM:["mmin","mmax"],hasZ:["zmin","zmax"],height:["ymin","ymax"],width:["xmin","xmax"]}},normalizeCtorArgs:function(a,c,
b,d,e){return this.isSR(a)?{spatialReference:a,xmin:0,ymin:0,xmax:0,ymax:0}:y.isObject(a)?(a.spatialReference=a.spatialReference||w.WGS84,a):{xmin:a,ymin:c,xmax:b,ymax:d,spatialReference:e||w.WGS84}},_centerGetter:function(a){a||(a=new k({spatialReference:this.spatialReference}));a.x=0.5*(this.xmin+this.xmax);a.y=0.5*(this.ymin+this.ymax);this.hasZ&&(a.z=0.5*(this.zmin+this.zmax));this.hasM&&(a.m=0.5*(this.mmin+this.mmax));return a},_extentGetter:function(){return this.clone()},_hasMGetter:function(){return null!=
this.mmin&&null!=this.mmax},_hasZGetter:function(){return null!=this.zmin&&null!=this.zmax},_heightGetter:function(){return Math.abs(this.ymax-this.ymin)},type:"extent",_widthGetter:function(){return Math.abs(this.xmax-this.xmin)},xmin:0,ymin:0,mmin:void 0,zmin:void 0,xmax:0,ymax:0,mmax:void 0,zmax:void 0,centerAt:function(a){var c=this.center;return null!=a.z&&this.hasZ?this.offset(a.x-c.x,a.y-c.y,a.z-c.z):this.offset(a.x-c.x,a.y-c.y)},clone:function(){var a=new p;a.xmin=this.xmin;a.ymin=this.ymin;
a.xmax=this.xmax;a.ymax=this.ymax;a.spatialReference=this.spatialReference;null!=this.zmin&&(a.zmin=this.zmin,a.zmax=this.zmax);null!=this.mmin&&(a.mmin=this.mmin,a.mmax=this.mmax);return a},contains:function(a){if(!a)return!1;var c=a.type;if("point"===c){var b=this.spatialReference,d=a.spatialReference,c=a.x,e=a.y;a=a.z;b&&(d&&!b.equals(d)&&b._canProject(d))&&(b=b.isWebMercator()?k.lngLatToXY(c,e):k.xyToLngLat(c,e,!0),c=b[0],e=b[1]);if(c>=this.xmin&&c<=this.xmax&&e>=this.ymin&&e<=this.ymax)return null!=
a&&this.hasZ?a>=this.zmin&&a<=this.zmax:!0}else if("extent"===c)return this._containsExtent(a);return!1},equals:function(a){if(!a)return!1;var c=this.spatialReference;if(!c.equals(a.spatialReference))if(t.canProject(a.spatialReference,c))a=t.project(a,c);else return!1;return this.xmin===a.xmin&&this.ymin===a.ymin&&this.zmin===a.zmin&&this.mmin===a.mmin&&this.xmax===a.xmax&&this.ymax===a.ymax&&this.zmax===a.zmax&&this.mmax===a.mmax},expand:function(a){var c=0.5*(1-a),b=this.width*c,d=this.height*c;
a=this.clone();a.xmin+=b;a.ymin+=d;a.xmax-=b;a.ymax-=d;this.hasZ&&(b=(this.zmax-this.zmin)*c,a.zmin+=b,a.zmax-=b);this.hasM&&(c*=this.mmax-this.mmin,a.mmin+=c,a.mmax-=c);return a},intersects:function(a){if(!a)return!1;var c=a.type,b=this.spatialReference,d=a.spatialReference;b&&(d&&!b.equals(d)&&b._canProject(d))&&(a=b.isWebMercator()?t.geographicToWebMercator(a):t.webMercatorToGeographic(a,!0));switch(c){case "point":return this.contains(a);case "multipoint":return this._intersectsMultipoint(a);
case "extent":return this._intersectsExtent(a);case "polygon":return this._intersectsPolygon(a);case "polyline":return this._intersectsPolyline(a)}},normalize:function(){var a=this._normalize(!1,!0);Array.isArray(a)||(a=[a]);return a},offset:function(a,c,b){var d=this.clone();d.xmin+=a;d.ymin+=c;d.xmax+=a;d.ymax+=c;null!=b&&(d.zmin+=b,d.zmax+=b);return d},shiftCentralMeridian:function(){return this._normalize(!0)},toJSON:function(){var a=this.spatialReference,a={xmin:this.xmin,ymin:this.ymin,xmax:this.xmax,
ymax:this.ymax,spatialReference:a&&a.toJSON()};this.hasZ&&(a.zmin=this.zmin,a.zmax=this.zmax);this.hasM&&(a.mmax=this.mmax,a.mmin=this.mmin);return a},union:function(a){function c(a,b,c){return null==b?c:null==c?b:a(b,c)}var b={xmin:Math.min(this.xmin,a.xmin),ymin:Math.min(this.ymin,a.ymin),xmax:Math.max(this.xmax,a.xmax),ymax:Math.max(this.ymax,a.ymax),spatialReference:this.spatialReference};if(this.hasZ||a.hasZ)b.zmin=c(Math.min,this.zmin,a.zmin),b.zmax=c(Math.max,this.zmax,a.zmax);if(this.hasM||
a.hasM)b.mmin=c(Math.min,this.mmin,a.mmin),b.mmax=c(Math.max,this.mmax,a.mmax);return new p(b)},_containsExtent:function(a){var c=a.xmin,b=a.ymin,d=a.zmin,e=a.xmax,f=a.ymax,g=a.zmax;a=a.spatialReference;return null!=d&&this.hasZ?this.contains(new k(c,b,d,a))&&this.contains(new k(c,f,d,a))&&this.contains(new k(e,f,d,a))&&this.contains(new k(e,b,d,a))&&this.contains(new k(c,b,g,a))&&this.contains(new k(c,f,g,a))&&this.contains(new k(e,f,g,a))&&this.contains(new k(e,b,g,a)):this.contains(new k(c,b,a))&&
this.contains(new k(c,f,a))&&this.contains(new k(e,f,a))&&this.contains(new k(e,b,a))},_intersectsMultipoint:function(a){var c=a.points.length,b;for(b=0;b<c;b++)if(this.contains(a.getPoint(b)))return!0;return!1},_intersectsExtent:function(a){var c,b,d,e,f,g,h=this.hasZ&&a.hasZ;if(this.xmin<=a.xmin){if(c=a.xmin,this.xmax<c)return!1}else if(c=this.xmin,a.xmax<c)return!1;e=Math.min(this.xmax,a.xmax)-c;if(this.ymin<=a.ymin){if(b=a.ymin,this.ymax<b)return!1}else if(b=this.ymin,a.ymax<b)return!1;f=Math.min(this.ymax,
a.ymax)-b;if(h){if(this.zmin<=a.zmin){if(d=a.zmin,this.zmax<d)return!1}else if(d=this.zmin,a.zmax<d)return!1;g=Math.min(this.zmax,a.zmax)-d}a={xmin:c,ymin:b,xmax:c+e,ymax:b+f,spatialReference:this.spatialReference};h&&(a.zmin=d,a.zmax=d+g);return a=new p(a)},_intersectsPolygon:function(a){var c=[this.xmin,this.ymax],b=[this.xmax,this.ymax],d=[this.xmin,this.ymin],e=[this.xmax,this.ymin],f=[c,b,d,e],c=[[d,c],[c,b],[b,e],[e,d]],d=a.rings,e=d.length,g,h=new k(0,0,this.spatialReference);g=f.length;for(b=
0;b<g;b++)if(h.x=f[b][0],h.y=f[b][1],a.contains(h))return!0;for(var h={x:0,y:0,spatialReference:a.spatialReference,type:"point"},q,m,b=0;b<e;b++)if(f=d[b],g=f.length){q=f[0];h.x=q[0];h.y=q[1];if(this.contains(h))return!0;for(a=1;a<g;a++){m=f[a];h.x=m[0];h.y=m[1];if(this.contains(h)||this._intersectsLine([q,m],c))return!0;q=m}}return!1},_intersectsPolyline:function(a){var c=[[[this.xmin,this.ymin],[this.xmin,this.ymax]],[[this.xmin,this.ymax],[this.xmax,this.ymax]],[[this.xmax,this.ymax],[this.xmax,
this.ymin]],[[this.xmax,this.ymin],[this.xmin,this.ymin]]],b,d=a.paths,e=d.length,f,g,h,q,m={x:0,y:0,spatialReference:a.spatialReference,type:"point"};for(a=0;a<e;a++)if(f=d[a],g=f.length){h=f[0];m.x=h[0];m.y=h[1];if(this.contains(m))return!0;for(b=1;b<g;b++){q=f[b];m.x=q[0];m.y=q[1];if(this.contains(m)||this._intersectsLine([h,q],c))return!0;h=q}}return!1},_intersectsLine:function(a,c){var b=B._getLineIntersection2,d,e=c.length;for(d=0;d<e;d++)if(b(a,c[d]))return!0;return!1},_shiftCM:function(a){var c=
this.cache._shifted;if(!c){var c=this.clone(),b=c.spatialReference;if(a=a||b._getInfo()){var d=this._getCM(a);if(d){var e=b.isWebMercator()?t.webMercatorToGeographic(d):d;c.xmin-=d.x;c.xmax-=d.x;b.isWebMercator()||(e.x=this._normalizeX(e.x,a).x);c.spatialReference=new w(z.substitute({Central_Meridian:e.x},4326===b.wkid?a.altTemplate:a.wkTemplate))}}this.cache._shifted=c}return c},_getCM:function(a){var c,b=a.valid[0];a=a.valid[1];var d=this.xmin,e=this.xmax;if(!(d>=b&&d<=a)||!(e>=b&&e<=a))c=this.center;
return c},_normalize:function(a,c,b){var d=this.clone(),e=d.spatialReference;if(e&&(b=b||e._getInfo())){var f=v.map(this._getParts(b),function(a){return a.extent});if(2<f.length)return a?this._shiftCM(b):d.set({xmin:b.valid[0],xmax:b.valid[1],spatialReference:e});if(2===f.length){if(a)return this._shiftCM(b);if(c)return f;var g=!0,h=!0;v.map(f,function(a){a.hasZ||(g=!1);a.hasM||(h=!1)});return{rings:v.map(f,function(a){var b=[[a.xmin,a.ymin],[a.xmin,a.ymax],[a.xmax,a.ymax],[a.xmax,a.ymin],[a.xmin,
a.ymin]];if(g)for(var c=(a.zmax-a.zmin)/2,d=0;d<b.length;d++)b[d].push(c);if(h){a=(a.mmax-a.mmin)/2;for(d=0;d<b.length;d++)b[d].push(a)}return b}),hasZ:g,hasM:h,spatialReference:e}}return f[0]||d}return d},_getParts:function(a){var c=this.cache._parts;if(!c){var c=[],b=this.xmin,d=this.xmax,e=this.ymin,f=this.ymax,g=this.spatialReference,h=this.width,k=b,m=d,n=0,l=0,r,s;a=a||g._getInfo();r=a.valid[0];s=a.valid[1];l=this._normalizeX(b,a);b=l.x;n=l.frameId;l=this._normalizeX(d,a);d=l.x;l=l.frameId;
a=b===d&&0<h;if(h>2*s){h=new p(k<m?b:d,e,s,f,g);b=new p(r,e,k<m?d:b,f,g);s=new p(0,e,s,f,g);e=new p(r,e,0,f,g);g=[];r=[];h.contains(s)&&g.push(n);h.contains(e)&&r.push(n);b.contains(s)&&g.push(l);b.contains(e)&&r.push(l);for(f=n+1;f<l;f++)g.push(f),r.push(f);c.push({extent:h,frameIds:[n]},{extent:b,frameIds:[l]},{extent:s,frameIds:g},{extent:e,frameIds:r})}else b>d||a?c.push({extent:new p(b,e,s,f,g),frameIds:[n]},{extent:new p(r,e,d,f,g),frameIds:[l]}):c.push({extent:new p(b,e,d,f,g),frameIds:[n]});
this.cache._parts=c}l=this.hasZ;e=this.hasM;if(l||e){n={};l&&(n.zmin=this.zmin,n.zmax=this.zmax);e&&(n.mmin=this.mmin,n.mmax=this.mmax);for(l=0;l<c.length;l++)c[l].extent.set(n)}return c},_normalizeX:function(a,c){var b=0,d=c.valid[0],e=c.valid[1],f=2*e;a>e?(b=Math.ceil(Math.abs(a-e)/f),a-=b*f):a<d&&(b=Math.ceil(Math.abs(a-d)/f),a+=b*f,b=-b);return{x:a,frameId:b}},getWidth:function(){u.deprecated(this.declaredClass+".getWidth","Use .width instead","4.0");return this.width},getHeight:function(){u.deprecated(this.declaredClass+
".getHeight","Use .height instead","4.0");return this.height},getCenter:function(){u.deprecated(this.declaredClass+".getCenter","Use .center instead","4.0");return this.center},update:function(a,c,b,d,e){u.deprecated(this.declaredClass+".update","Use .set instead","4.0");this.set({xmin:a,ymin:c,xmax:b,ymax:d,spatialReference:e})}});return p});