// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define({root:{moveUp:"Move up",moveDown:"Move down",rename:"Rename",hideInMapLayers:"Hide in Layers",showInMapLayers:"Show in Layers",invalidTitle:"The title cannot contain any of these characters: \x3c or \x3e.",header:{home_link:"Home",simpleHome:"Home",support:"Help",features:"Features",myAccount:"My Organization",myProfile:"My Profile",help:"Help",plans:"Plans",adminGuide:"Administrator Guide",signOut:"Sign Out",signIn:"Sign In",newScene:"New Scene",gallery:"Gallery",groups:"Groups",myContent:"My Content",
esriCommunity:"Community and Forums",myEsri:"My Esri",map:"Map",training:"Training",trialDownloads:"Trial Downloads",fullScreen:"Explore in Full Viewer",newGlobal:"New Global Scene",newLocal:"New Local Scene",globalScene:"Global Scene",localScene:"Local Scene",spatialRef:"Spatial Reference"},environmentSettings:{dragSunSliderText:"Drag the slider to change the time of day.",dragSunSliderHint:"Drag Slider",sunLight:"Sunlight",sunrise:"sunrise",sunset:"sunset",shadowing:"Shadowing",directShadow:"Direct Shadow (cast by sunlight)",
diffuseShadow:"Diffuse Shadows (ambient occlusion)"},layerItemEditable:{groupTypeCheckbox:"Checkbox",groupTypeRadio:"Radio",groupTypeCompact:"Merge",groupTypeHide:"Hide",configureLayer:"Configure Layer",zoomToLayer:"Zoom to",deleteLayer:"Remove",dragHere:"Drag Layer here",changeGroupType:"Change Group Type"},slideDeckEditable:{addSlide:"Capture Slide",slide:"Slide",updateSlide:"Update Slide",deleteSlide:"Remove Slide"},symbologyEditor:{symbologyShieldWarning:"This layer's symbology can not be modified. Click ok to remove the existing symbology and define new symbology.",
colorOverride:"Color override",fill:"Fill",outline:"Outline",shape:"Shape",color:"Color",size:"Size",symbols:"Symbols",transparency:"Transparency (%)",ok:"OK",px:"px",points:"points",meters:"meters",feet:"feet",reset:"Reset",originalSymbology:"Original symbols",modifySymbology:"Change symbols",customize:"Customize",type:"Type",icon2d:"2D Icon",object3D:"3D Object",line2d:"2D Line",line3d:"3D Line",path3d:"3D Path",polygon2d:"2D Polygon",polygon3d:"3D Extrusion",fillColor:"Fill Color",outlineColor:"Outline Color",
outlineSize:"Outline Size",shapes:{circle:"Circle",cone:"Cone",cross:"Cross",cube:"Cube",cylinder:"Cylinder",diamond:"Diamond",kite:"Kite",sphere:"Sphere",square:"Square",tetrahedron:"Tetrahedron",x:"X"},extrusion:"Extrusion (meters)",rangeMsg:"Value out of range. Please enter a value between ${minSize} and ${maxSize}"},mapControls:{zoomIn:"Zoom In",zoomOut:"Zoom Out",rotate:"Rotate",home:"Initial View",pan:"Pan",panRotateToggle:"Toggle to pan or rotate in 3D"},switchControl:{on:"on",off:"off"},settings:{navigation:"3D Navigation",
proNav:"ArcGIS Pro",sceneNav:"Default",mouseImage:"Assignment of mouse buttons for 3D navigation"},share:{text:"Select one of the options below to share this scene.",link:"Share a link to this scene",embed:"Embed this scene in a website",more:"Embed Options",smallSize:"Small",mediumSize:"Medium",largeSize:"Large",customSize:"Custom",shareTwitterTxt:"Explore '${sceneName}'  in 3D with your browser:\n",shareEmailSubject:"${sceneName}  in 3D (Scene Viewer)",shareEmailTxt1:"Have a look at this Web Scene:",
shareEmailTxt2:"You can create and share your own 3D Web Scenes with Esri Scene Viewer. Visit http://www.arcgis.com and click 'Scene' to try it for free.",shortenLink:"Short Link",shareUnsaved:"This scene contains unsaved changes. In order to share it, you need to save those changes.",shareNotPublic:"This scene is not shared with the public. People might not be able to view it.",shareNotPublicLayer:"At least one layer in this scene is not public. People might not be able to view all layers.",changeShareSettings:"Change Share Settings"},
underground:{seeThroughGround:"See through ground"},basemapGallery:{SRMismatch:"Spatial reference is incompatible with the scene",SRMismatchGlobal:"Spatial reference is not supported in global scenes",TSMismatch:"Tiling scheme is incompatible with the scene",TilingScheme:"Tiling scheme does not adhere to ArcGIS Online Tiling Scheme.",tilingSchemePowerOfTwo:"Incompatible tiling scheme: each scale must be exactly half of the scale of the preceding level.",tilingSchemeTileSize:"Incompatible tiling scheme: only tiles with width and height 256 are supported.",
tiledMapServiceSRGCS:"Tiled Map Layers in geographic coordinate systems are not supported.",tiledMapServicesMinVersion:"Tiled Map Layers on servers prior to 10.2.2 are not supported.",basemapLayerTypeWMS:"OGC Web Map Service (WMS) is not supported as basemap.",basemapLayerTypeWMTS:"OGC Web Tile Map Service (WMTS) is not supported as basemap.",basemapLayerTypeWTL:"Web Tiled Layer is not supported as basemap.",basemapLayerTypeDMS:"Dynamic Map Service Layer is not supported as basemap.",basemapLayerTypeIS:"Image Service Layer is not supported as basemap.",
noBasemap:"No basemap"},compass:{compass:"Compass"}},ar:1,cs:1,da:1,de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,it:1,ja:1,ko:1,lt:1,lv:1,nl:1,nb:1,pl:1,"pt-br":1,"pt-pt":1,ro:1,ru:1,sv:1,th:1,tr:1,vi:1,"zh-cn":1});