// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define(["dojo/_base/array","../lib/glMatrix","../../../core/watchUtils","../webgl-engine/lib/Util","./NavigationConstants"],function(z,A,K,L,r){var m=function(h,p){function t(a){a.preventDefault();if(0!==e&&!(void 0!==typeof a.movementX&&void 0!==typeof a.movementY&&0===a.movementX&&0===a.movementY)){a=q(a,u);var b=e-1;switch(k){case 1:g("mouseDragLeft",a,b);break;case 2:g("mouseDragMiddle",a,b);break;case 3:case 0:g("mouseDragRight",a,b)}1===e&&!(0===Math.abs(a[0]-x[0])&&0===Math.abs(a[1]-x[1]))?
e=2:3===e&&(s&&window.clearTimeout(s),k=e=0,document.removeEventListener("mousemove",t,!0),document.removeEventListener("mouseup",v,!0))}}function B(a){a.preventDefault();d.focus();x=q(a);s&&window.clearTimeout(s);c.stop();e=1;k=a.which;1===k&&(0<l?(g("mouseClickDouble",q(a,u),2),l=0):l=Date.now());document.addEventListener("mousemove",t,!0);document.addEventListener("mouseup",v,!0)}function v(a){a.preventDefault();var b=q(a,u);1===e&&1===k?0<l&&setTimeout(function(){0<l&&(g("mouseClick",q(a,u)),
l=0)},Math.max(M-(Date.now()-l),0)):l=0;2===e?(e=3,s=setTimeout(function(){if(3===e)switch(k){case 1:g("mouseDragLeft",b,2);break;case 2:g("mouseDragMiddle",b,2);break;case 3:case 0:g("mouseDragRight",b,2)}document.removeEventListener("mousemove",t,!0);document.removeEventListener("mouseup",v,!0);k=e=0},N)):(document.removeEventListener("mousemove",t,!0),document.removeEventListener("mouseup",v,!0),k=e=0)}function C(a){a.preventDefault();if(void 0===typeof a.wheelDeltaY||0!==a.wheelDeltaY)g("mouseWheel",
a.detail?-40*a.detail:a.wheelDelta,q(a,O))}function D(a){a.stopPropagation();var b=a.changedTouches[0],c="";if(!(1<a.touches.length)){var d;switch(a.type){case "touchstart":c="mousedown";break;case "touchmove":c="mousemove";break;case "touchend":c="mouseup";d=document.createEvent("MouseEvent");d.initMouseEvent("click",!0,!0,window,1,b.screenX,b.screenY,b.clientX,b.clientY,!1,!1,!1,!1,0,null);b.target.dispatchEvent(d);a.preventDefault();break;default:return}d=document.createEvent("MouseEvent");d.initMouseEvent(c,
!0,!0,window,1,b.screenX,b.screenY,b.clientX,b.clientY,!1,!1,!1,!1,0,null);b.target.dispatchEvent(d);a.preventDefault()}}function E(a){a.preventDefault()}function F(a){if(!a.shiftKey&&!a.ctrlKey&&!a.altKey&&!a.metaKey){var b=G[a.keyCode];void 0!==b&&(P[b](),a.preventDefault())}}function H(a){var b=G[a.keyCode];void 0!==b&&(b=Q[b],void 0!==b&&b(),a.preventDefault())}function q(a,b){b||(b=y.create());var c=d.getBoundingClientRect();b[0]=a.pageX-c.left;b[1]=c.height-(a.pageY-c.top);return b}function g(a,
b,c){a=p[a];if(void 0!==a)R[a](b,c)}var I=/Firefox/i.test(navigator.userAgent),M=200,N=100,G={37:"panLeft",38:"panForward",39:"panRight",40:"panBackward",66:"lookAround",74:"panDown",78:"lookNorth",80:"lookDown",85:"panUp"},n,y=A.vec2d,S=A.vec3d,w=L.assert,J=["touchmove","touchstart","touchend","touchcancel"],d=null;this.connect=function(){if(d=h.get("canvas"))z.forEach(J,function(a){d.addEventListener(a,D,!0)}),d.addEventListener("mousedown",B,!1),d.addEventListener(I?"DOMMouseScroll":"mousewheel",
C,!1),d.addEventListener("contextmenu",E,!1),d.setAttribute("tabindex","1"),d.addEventListener("keydown",F,!1),d.addEventListener("keyup",H,!1)};this.disconnect=function(){d&&(z.forEach(J,function(a){d.removeEventListener(a,D,!0)}),d.removeEventListener("mousedown",B,!1),d.removeEventListener(I?"DOMMouseScroll":"mousewheel",C,!1),d.removeEventListener("contextmenu",E,!1),d.removeEventListener("keydown",F,!1),d.removeEventListener("keyup",H,!1),d=null)};var T=K.init(h,"canvas",function(){this.disconnect();
this.connect()}.bind(this)),c=h.navigation;this.destroy=function(){this.disconnect();T.remove()};this.setControls=function(a){n?n=a:p=a};this.getControls=function(){return p};var e=0,k=0,l=0,x=null,s,u=y.create(),O=y.create(),R={select:function(a){h.get("ready")&&h._stage._select(a)},frame:function(a,b){if(h.get("ready")){var d=S.create(),e=h._stage._pick(a).getMinResult(),f=e.object;if(f){var g=f.getParentLayer();if(g&&"PICKABLE"===g.getInteraction()){d=f.calcFacerangeBoundingSphere(e.triangleNr);
e=c.targetCamera;c.frame(d.center,e.computeDistanceFromRadius(d.radiusScaled,1.1));return}}e.getIntersectionPoint(d)&&(e=c.targetCamera,c.frame(d,0.66*e.distance))}},pan:function(a,b){switch(b){case 0:c.pan.begin(a);break;case 1:c.pan.update(a);break;case 2:c.pan.end(a);break;default:w(!1)}},tumble:function(a,b){switch(b){case 0:c.rotate.begin(a,r.Rotate.PivotPoint.POI);break;case 1:c.rotate.update(a,r.Rotate.PivotPoint.POI);break;case 2:c.rotate.end(a);break;default:w(!1)}},zoom:function(a,b){switch(b){case 0:c.zoom.begin(a);
break;case 1:c.zoom.update(a);break;case 2:c.zoom.end(a);break;default:w(!1)}},zoomStep:function(a,b){c.zoom.stepScreen(a,b)},lookAround:function(a,b){switch(b){case 0:c.rotate.begin(a,r.Rotate.PivotPoint.EYE);break;case 1:c.rotate.update(a,r.Rotate.PivotPoint.EYE);break;case 2:c.rotate.end(a);break;default:w(!1)}}},f=r.Pan.Direction,P={panLeft:function(){c.pan.beginContinuous(f.LEFT)},panRight:function(){c.pan.beginContinuous(f.RIGHT)},panForward:function(){c.pan.beginContinuous(f.FORWARD)},panBackward:function(){c.pan.beginContinuous(f.BACKWARD)},
panUp:function(){c.pan.beginContinuous(f.UP)},panDown:function(){c.pan.beginContinuous(f.DOWN)},lookAround:function(){n||(n=p,p=m.LOOK_AROUND)},lookNorth:function(){h.animateTo({heading:0})},lookDown:function(){h.animateTo({tilt:0})}},Q={panLeft:function(){c.pan.endContinuous(f.LEFT)},panRight:function(){c.pan.endContinuous(f.RIGHT)},panForward:function(){c.pan.endContinuous(f.FORWARD)},panBackward:function(){c.pan.endContinuous(f.BACKWARD)},panUp:function(){c.pan.endContinuous(f.UP)},panDown:function(){c.pan.endContinuous(f.DOWN)},
lookAround:function(){n&&(p=n,n=void 0)}}};m.PAN={mouseClick:"select",mouseClickDouble:"frame",mouseDragLeft:"pan",mouseDragRight:"tumble",mouseDragMiddle:"zoom",mouseWheel:"zoomStep"};m.TUMBLE={mouseClick:"select",mouseClickDouble:"frame",mouseDragLeft:"tumble",mouseDragRight:"pan",mouseDragMiddle:"zoom",mouseWheel:"zoomStep"};m.LOOK_AROUND={mouseClick:"select",mouseClickDouble:"frame",mouseDragLeft:"lookAround",mouseDragRight:"tumble",mouseDragMiddle:"pan",mouseWheel:"zoomStep"};m.OLD={mouseClick:"select",
mouseClickDouble:"frame",mouseDragMiddle:"tumble",mouseDragRight:"pan",mouseWheel:"zoomStep"};m.PRO_PAN={mouseClick:"select",mouseClickDouble:"frame",mouseDragLeft:"pan",mouseDragMiddle:"tumble",mouseDragRight:"zoom",mouseWheel:"zoomStep"};m.PRO_TUMBLE={mouseClick:"select",mouseClickDouble:"frame",mouseDragLeft:"tumble",mouseDragMiddle:"pan",mouseDragRight:"zoom",mouseWheel:"zoomStep"};return m});