// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/views/3d/environment/materials/SimpleAtmosphereMaterial.xml":'\x3c?xml version\x3d"1.0" encoding\x3d"UTF-8"?\x3e\r\n\r\n\x3csnippets\x3e\r\n\r\n\x3csnippet name\x3d"vsSimpleAtmosphere"\x3e\x3c![CDATA[\r\n  uniform mat4 proj;\r\n  uniform mat4 view;\r\n\r\n#ifndef PANORAMIC\r\n\r\n  const float TWICEPI \x3d 2.0*3.14159265;\r\n  const float ATMOSPHERE_RIM_SEGMENTS \x3d 128.0;\r\n\r\n  uniform vec3 silCircleCenter;\r\n  uniform vec3 silCircleV1;\r\n  uniform vec3 silCircleV2;\r\n  uniform vec2 texV;\r\n\r\n#endif\r\n\r\n  uniform vec3 lightDirection;\r\n\r\n  attribute vec3 $position;\r\n  varying vec2 vtc;\r\n  varying float falloff;\r\n\r\n  void main(void) {\r\n\r\n#ifdef PANORAMIC\r\n\r\n    vec3 pos \x3d $position;\r\n    float ndotl \x3d lightDirection.z;\r\n    vtc \x3d vec2(0, $position.z+0.05);\r\n\r\n#else\r\n\r\n    float phi \x3d $position.x * (TWICEPI / ATMOSPHERE_RIM_SEGMENTS) + 1.0;\r\n    vec3 pos \x3d (sin(phi) * silCircleV1 + cos(phi) * silCircleV2 + silCircleCenter) * $position.y;\r\n    float ndotl \x3d dot(normalize(pos), lightDirection);\r\n\r\n    vtc.x \x3d $position.x / ATMOSPHERE_RIM_SEGMENTS;\r\n    vtc.y \x3d texV.x * (1.0 - $position.z) + texV.y * $position.z;\r\n\r\n#endif\r\n\r\n    falloff \x3d max(0.0, (smoothstep(-1.0, 0.8, ndotl + ndotl)));\r\n\r\n    gl_Position \x3d proj * view * vec4(pos, 1.0);\r\n    gl_Position.z \x3d gl_Position.w; // project atmosphere onto the far plane\r\n  }\r\n]]\x3e\x3c/snippet\x3e\r\n\r\n\x3csnippet name\x3d"fsSimpleAtmosphere"\x3e\x3c![CDATA[\r\n  precision mediump float;\r\n\r\n  uniform sampler2D tex;\r\n  uniform vec4 color;\r\n  varying vec2 vtc;\r\n  varying float falloff;\r\n\r\n  void main() {\r\n    vec4 texColor \x3d texture2D(tex, vtc);\r\n    gl_FragColor \x3d texColor * color * falloff;\r\n  }\r\n]]\x3e\x3c/snippet\x3e\r\n\r\n\x3c/snippets\x3e\r\n'}});
define("dojo/text!./materials/SimpleAtmosphereMaterial.xml ../../../core/declare ../../../core/Accessor ../lib/glMatrix ../webgl-engine/lib/GeometryRenderer ../webgl-engine/lib/GeometryUtil ../webgl-engine/lib/VertexBufferLayout ../webgl-engine/lib/Texture ../webgl-engine/lib/Util ../webgl-engine/lib/GLSLProgram ../webgl-engine/lib/GLTextureRep ./resources/SimpleAtmosphereTexture".split(" "),function(m,n,p,e,q,r,s,t,u,g,v,w){var x=e.vec2d,f=e.vec3d,h=e.mat4d,k=u.VertexAttrConstants,l=h.create();return n([p],
{classMetadata:{properties:{view:{}}},normalizeCtorArgs:function(b){return"esri.views.SceneView"===b.declaredClass?{view:b}:b},constructor:function(){this.geometryData=this._createGeometryData();this.renderData={texV:x.create(),silCircleCenter:f.create(),silCircleV1:f.create(),silCircleV2:f.create()};this.textureRep=this.texture=null;this.slot=0;this.gl=null;this._needsRender=!0;this._didRender=!1},setContext:function(b){this.gl=b;this.renderer=new q(this.geometryData,s.Defaults.Pos,null,this.gl)},
loadShaders:function(b,a,c){b.vsSimpleAtmosphere||b._parse(m);this.program=g.fromSnippets("vsSimpleAtmosphere","fsSimpleAtmosphere",b,this.gl,["PANORAMIC"]);this.programRep=c;this.textureRep=new v({SimpleAtmosphere:new t(w,"SimpleAtmosphere",{wrapClamp:!0})},c,function(){return this.view._stage.getCamera().viewport}.bind(this),this.gl);this.texture=this.textureRep.aquire("SimpleAtmosphere")},render:function(b){if(!(b.slot!==this.slot||"material"!==b.pass||!this.textureRep.getIsLoaded("SimpleAtmosphere"))){var a=
this.gl,c=this.program;c.use();a.bindTexture(a.TEXTURE_2D,this.texture);c.uniform1i("tex",0);c.uniformMatrix4fv("proj",b.camera.projectionMatrix);h.toRotationMat(b.camera.viewMatrix,l);c.uniformMatrix4fv("view",l);c.uniform4f("color",1,1,1,1);c.uniform3fv("lightDirection",b.lightingData.getLightDirection());a.web3DDefaultState.cullEnabled||a.enable(a.CULL_FACE);a.web3DDefaultState.depthFunc!==a.LEQUAL&&a.depthFunc(a.LEQUAL);a.enable(a.BLEND);a.depthMask(!1);this.renderer.render(this.program);this._didRender=
!0;g.unuse(a);a.depthMask(!0);a.disable(a.BLEND);a.web3DDefaultState.depthFunc!==a.LEQUAL&&a.depthFunc(a.web3DDefaultState.depthFunc);a.web3DDefaultState.cullEnabled||a.disable(a.CULL_FACE)}},needsRender:function(){return this._needsRender},resetNeedsRender:function(){this._didRender&&(this._needsRender=!1)},init:function(){},destroy:function(){this.textureRep&&this.textureRep.release(this.texture)},_createGeometryData:function(){for(var b=r.createPolySphereGeometry(1,2),a=b.getFaces(),c=a[0].indices[k.POSITION],
d=0;d<c.length;d+=3){var e=c[d];c[d]=c[d+2];c[d+2]=e}b=b.getVertexAttr();c=b[k.NORMAL].data;for(d=0;d<c.length;d++)c[d]=-c[d];return{faces:a[0],vertexAttr:b}}})});