// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/views/3d/environment/materials/StarMaterial.xml":'\x3c?xml version\x3d"1.0" encoding\x3d"UTF-8"?\x3e\r\n\r\n\x3csnippets\x3e\r\n\r\n\x3csnippet name\x3d"vertexShaderStar"\x3e\x3c![CDATA[\r\n\tprecision mediump float;\r\n\tuniform mat4 proj;\r\n\tuniform mat4 view;\r\n\tuniform mat4 model;\r\n\tuniform vec4 viewport;\r\n\r\n\tattribute vec3 $position;\r\n\tattribute vec4 $color;\r\n  attribute float $size;\r\n\r\n\tvarying vec4 vcolor;\r\n\tvarying float vsize;\r\n\r\n\t$matchPixelCenter\r\n\r\n\tvoid main(void) {\r\n\t\tvec4 posProj \x3d proj * view * model*vec4($position*1.0e25,1.0);//move infinitely far away\r\n\t\tgl_Position \x3d matchPixelCenter(posProj, viewport.zw); //pixel align position\r\n    gl_Position.z \x3d gl_Position.w; // project atmosphere onto the far plane\r\n\t\tvcolor \x3d $color/1.2;\r\n\t\tvsize \x3d size*5.0;\r\n\t\tgl_PointSize \x3d vsize;\r\n\t}\r\n]]\x3e\x3c/snippet\x3e\r\n\r\n\x3csnippet name\x3d"fragmentShaderStar"\x3e\x3c![CDATA[\r\n\tprecision mediump float;\r\n\r\n\tvarying vec4 vcolor;\r\n\tvarying float vsize;\r\n\r\n\tvoid main() {\r\n\t\tfloat cap \x3d 0.7;\r\n\t\tfloat scale \x3d 1.0/cap;\r\n\t\tfloat helper \x3d clamp(length(abs(gl_PointCoord-vec2(0.5))),0.0,cap);\r\n\t\tfloat alpha \x3d clamp((cap-helper)*scale,0.0,1.0);\r\n\t\tfloat intensity \x3d alpha*alpha*alpha;\r\n\t\tif (vsize \x3c 3.0)\r\n\t\t\tintensity *\x3d 0.5;\r\n\t\tgl_FragColor \x3d vec4(1.0,1.0,1.0,intensity);\r\n\t\tgl_FragColor.xyz *\x3d vcolor.xyz;\r\n\t}\r\n]]\x3e\x3c/snippet\x3e\r\n\x3c/snippets\x3e\r\n'}});
define("dojo/text!./materials/StarMaterial.xml require ../../../core/declare ../../../core/Accessor ../../../request ../lib/glMatrix ../webgl-engine/lib/GeometryRenderer ../webgl-engine/lib/Util ../webgl-engine/lib/VertexBufferLayout ../webgl-engine/materials/internal/MaterialUtil ../webgl-engine/lib/GLSLProgram ../webgl-engine/lib/webglConstants".split(" "),function(t,u,v,w,x,k,y,z,A,B,r,q){var g=k.mat4d;k=k.mat3d;var d=z.VertexAttrConstants,C=k.toMat4(k.createFrom(1,0,0,0,0.9174771405229186,0.39778850739794974,
0,-0.39778850739794974,0.9174771405229186)),D=k.toMat4(k.createFrom(1,0,0,0,0.9174771405229186,-0.39778850739794974,0,0.39778850739794974,0.9174771405229186));return v([w],{classMetadata:{properties:{view:{}}},normalizeCtorArgs:function(a){return"esri.views.SceneView"===a.declaredClass?{view:a,initialized:!1,numBinaryFloats:2,numBinaryUInt8:1,bytesPerStar:9}:a},constructor:function(){this.promise=this._loadBrightStarCatalogue();this.renderData={model:g.identity()};this.gl=this.slot=0;this._needsRender=
!0;this._didRender=!1;this.vertexBufferLayout=new A([d.POSITION,d.COLOR,d.SIZE],[3,4,1],[q.FLOAT,q.UNSIGNED_BYTE,q.FLOAT])},fillInterleaved:function(a,b,c,f,m,k,h){c=m.getStride();var l=4*c,s=B.fill;m=m.getAttributes();var n=a.faces.indices[d.POSITION],p=a.vertexAttr[d.POSITION].data;f=h+m[d.POSITION].offset;for(var e=0;e<n.length;++e){var g=3*n[e];s(p,g,k,f,b,3);f+=c}b=a.faces.indices[d.COLOR];n=a.vertexAttr[d.COLOR].data;f=4*(h+m[d.COLOR].offset);p=new Uint8Array(k.buffer);for(e=0;e<b.length;++e)g=
4*b[e],s(n,g,p,f,null,4),f+=l;l=a.faces.indices[d.SIZE];a=a.vertexAttr[d.SIZE].data;f=h+m[d.SIZE].offset;for(e=0;e<l.length;++e)k[f]=a[l[e]],f+=c},setContext:function(a){this.gl=a},loadShaders:function(a,b,c){a.vertexShaderStar||a._parse(t);this.program=r.fromSnippets("vertexShaderStar","fragmentShaderStar",a,this.gl);this.programRep=c},render:function(a){},render_loaded:function(a){if(!(a.slot!==this.slot||"material"!==a.pass)){var b=this.gl,c=this.program;c.use();c.uniformMatrix4fv("view",a.camera.viewMatrix);
c.uniformMatrix4fv("proj",a.camera.projectionMatrix);c.uniform4fv("viewport",a.camera.viewport);c.uniformMatrix4fv("model",this.renderData.model);b.web3DDefaultState.depthFunc!==b.LEQUAL&&b.depthFunc(b.LEQUAL);b.enable(b.BLEND);b.depthMask(!1);this.renderer.render(this.program);this._didRender=!0;r.unuse(b);b.depthMask(!0);b.disable(b.BLEND);b.web3DDefaultState.depthFunc!==b.LEQUAL&&b.depthFunc(b.web3DDefaultState.depthFunc)}},needsRender:function(){return this._needsRender},resetNeedsRender:function(){this._didRender&&
(this._needsRender=!1)},init:function(){this.promise.then(function(a){this.numStars=a.byteLength/this.bytesPerStar;var b=new Float32Array(a,0,this.numStars*this.numBinaryFloats);a=new Uint8Array(a,4*this.numStars*this.numBinaryFloats,this.numStars*this.numBinaryUInt8);this.geometryData=this._createStarGeometryData(b,a);this.renderer=new y(this.geometryData,this.vertexBufferLayout,this.fillInterleaved,this.gl);this.renderer.enablePointRendering(!0);this._dateListener=this.view.environment.lighting.watch("date",
this.update.bind(this));this.initialized=!0;this.update(this.view.environment.lighting.date);this.render=this.render_loaded}.bind(this),function(a){console.error("The stars could not be loaded:");console.error(a)})},destroy:function(){this.promise.cancel("Atmosphere has been removed.");this._dateListener.remove()},_computeDayDuration:function(a){var b=new Date(a.getFullYear(),0,1,11,58,56),c=new Date(a.getFullYear()+1,0,1,11,58,55);return(a-b)/(c-b)},update:function(a){var b=a.getHours()/12,c=a.getMinutes()/
60*(2/24),d=a.getSeconds()/60*(2/1440),b=(b+c+d-0.9972222)%2;a=2*this._computeDayDuration(a);c=g.create(D);g.rotateZ(c,-a*Math.PI);g.multiply(C,c,c);g.rotateZ(c,-b*Math.PI);this.renderData.model=c;this.view._stage.setNeedsRender()},_hexToRGB:function(a){return[parseInt(a.substring(0,2),16),parseInt(a.substring(2,4),16),parseInt(a.substring(4,6),16)]},_unpackUint8Attributes:function(a){return 192<=a?[2.9,a-192]:160<=a?[2.5,a-160]:128<=a?[2,a-128]:96<=a?[1.5,a-96]:64<=a?[1,a-64]:32<=a?[0.7,a-32]:[0.4,
a]},_createStarGeometryData:function(a,b){for(var c="9bb2ff;9eb5ff;aabfff;bbccff;ccd8ff ;dae2ff;e4e9ff;eeefff;f8f6ff;fff9fb;fff5ef;fff1e5;ffeddb;ffe9d2;ffe6ca;ffe3c3;ffe0bb;ffddb4;ffdaad;ffd6a5;ffd29c;ffcc8f;ffc178;ffa94b;ff7b00".split(";"),f=new Float32Array(3*this.numStars),m=new Uint8Array(4*this.numStars),k=new Float32Array(this.numStars),h=new Uint32Array(this.numStars),l=0;l<this.numStars;l++){var g=2*l,n=3*l,p=4*l,e=a[g+0],g=a[g+1];f[n+0]=-Math.cos(e)*Math.sin(g);f[n+1]=-Math.sin(e)*Math.sin(g);
f[n+2]=-Math.cos(g);n=this._unpackUint8Attributes(b[l]);e=this._hexToRGB(c[n[1]]);m[p+0]=255*e[0];m[p+1]=255*e[1];m[p+2]=255*e[2];m[p+3]=255;k[l]=n[0];h[l]=l}c={};c[d.POSITION]=h;c[d.NORMAL]=h;c[d.UV0]=h;c[d.COLOR]=h;c[d.SIZE]=h;h={};h[d.POSITION]={size:3,data:f};h[d.COLOR]={size:4,data:m};h[d.SIZE]={size:1,data:k};return{faces:{type:"point",indices:c,positionKey:d.POSITION},vertexAttr:h}},_loadBrightStarCatalogue:function(){return x({url:u.toUrl("./resources/stars.wsv"),handleAs:"arraybuffer",failOk:!0})}})});