// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/dialog/_AddItemDlgMixin",["dijit","dojo","dojox","dojo/require!dojox/grid/DataGrid"],function(c,b,a){b.provide("arcgisonline.sharing.dijit.dialog._AddItemDlgMixin");b.require("dojox.grid.DataGrid");b.declare("arcgisonline.sharing.dijit.dialog._AddItemDlgMixin",null,{itemInfo:{nmf:{typeKeywords:"Map,Explorer Map,Explorer Document,2D,3D,ArcGIS Explorer,nmf",type:"Explorer Map"},mxd:{typeKeywords:"Map Document, Map, 2D, ArcMap, ArcGIS Server, mxd",type:"Map Document"},
msd:{typeKeywords:"Map Document, Map, 2D, ArcMap, ArcGIS Server, msd",type:"Map Document"},"3dd":{typeKeywords:"Map, Globe Document, 3D, ArcGlobe, ArcGIS Server, 3dd",type:"Globe Document"},"3ws":{typeKeywords:"3D, Map, Scene, Web",type:"CityEngine Web Scene",thumbnailURL:"/cw_webscene.png"},sxd:{typeKeywords:"Map, Scene Document, 3D, ArcScene, sxd",type:"Scene Document"},lpk:{typeKeywords:"",type:"Layer Package"},lpkx:{typeKeywords:"",type:"Layer Package"},mpk:{typeKeywords:"",type:"Map Package"},
mpkx:{typeKeywords:"",type:"Map Package"},wmpk:{typeKeywords:"",type:"Windows Mobile Package"},rpk:{typeKeywords:"",type:"Rule Package"},bpk:{typeKeywords:"",type:"Mobile Basemap Package"},scenepackage:{typeKeywords:"",type:"Scene Package",thumbnailURL:"/desktopapp.png"},mapx:{typeKeywords:"ArcGIS Pro, Map, Map File, mapx",type:"Pro Map"},lyrx:{typeKeywords:"ArcGIS Pro, Layer, Layer File, lyrx",type:"Layer"},pagx:{typeKeywords:"ArcGIS Pro, Layout, Layout File, pagx",type:"Layout"},lyr:{typeKeywords:"Data, Layer, ArcMap,ArcGlobe,ArcGIS Explorer,lyr",
type:"Layer"},servicedefinition:{typeKeywords:"Data, Service, Service Definition",type:"Service Definition"},nmc:{typeKeywords:"Data,Layer,Explorer Layer,ArcGIS Explorer,nmc",type:"Explorer Layer"},ncfg:{typeKeywords:"Map,Explorer Map,Explorer Mapping Application,2D,3D,ArcGIS Explorer,ncfg",type:"Explorer Map"},eaz:{typeKeywords:"Tool,Add In,Explorer Add In,ArcGIS Explorer,eaz",type:"Explorer Add In"},pmf:{typeKeywords:"Map,Published Map,2D,ArcReader,ArcMap,ArcGIS Server,pmf",type:"Published Map"},
gpk:{typeKeywords:"",type:"Geoprocessing Package"},gpkx:{typeKeywords:"Tool, ArcGIS Pro, Toolbox, Model, Script, Result, gpkx",type:"Geoprocessing Package"},gcpk:{typeKeywords:"",type:"Locator Package"},tilepackage:{type:"Tile Package",typeKeywords:""},vectortilepackage:{type:"Vector Tile Package",typeKeywords:""},vectortileserver:{type:"Vector Tile Service",typeKeywords:""},wpk:{type:"Workflow Manager Package",typeKeywords:"",thumbnailURL:"/desktopapp.png"},esriaddin:{type:"Desktop Add In",typeKeywords:"Tool,Add In,Desktop Add In,ArcGIS Desktop,ArcMap,ArcGlobe,ArcScene,esriaddin"},
dtemp:{type:"Desktop Application Template",typeKeywords:"application, template, ArcGIS desktop"},mtemp:{type:"Map Template",typeKeywords:"map, ArcMap, template, ArcGIS desktop"},codesample:{type:"Code Sample",typeKeywords:"Code, Sample",thumbnailURL:"/desktopapp.png"},shapefile:{type:"Shapefile",typeKeywords:"Data, Layer, shapefile"},vieweraddin:{type:"Windows Viewer Add In",typeKeywords:"Application, ArcGIS Windows Viewer, Add In"},opdashboardaddin:{type:"Operations Dashboard Add In",typeKeywords:"Application, ArcGIS Operations Dashboard, Add In"},
desktopapplication:{type:"Desktop Application",typekeywords:"Desktop Application"},csv:{type:"CSV",typeKeywords:"CSV",thumbnailURL:"/desktopapp.png"},gpsample:{type:"Geoprocessing Sample",typeKeywords:"tool, geoprocessing, sample",thumbnailURL:"/desktopapp.png"},kml:{type:"KML",typeKeywords:"Data, Map, kml",thumbnailURL:"/desktopapp.png"},kmz:{type:"KML",typeKeywords:"Data, Map, kmz",thumbnailURL:"/desktopapp.png"},apimobile:{type:"Mobile Application",typeKeywords:"ArcGIS Mobile Map, Mobile Application",
thumbnailURL:"/mobileapp.png"},apimap:{type:"Web Mapping Application",typeKeywords:"Web Map, Map, Online Map, Mapping Site",thumbnailURL:"/webapp.png"},apiapp:{type:"Application",typeKeywords:"Application"},wab:{type:"Web Mapping Application",typeKeywords:"Web Map, Map, Online Map, Mapping Site, Web AppBuilder for ArcGIS",thumbnailURL:"/webapp.png"},configapp:{type:"Web Mapping Application",typeKeywords:"JavaScript, Map, Mapping Site, Online Map, Ready To Use, Web Map",thumbnailURL:"/webapp.png"},
webmap:{type:"Web Map",extent:"-165.4102,-68.7709,165.4102,78.5677",text:'{"operationalLayers":[],"baseMap":{"baseMapLayers":[{"id":"defaultBasemap","layerType":"ArcGISTiledMapServiceLayer","opacity":1,"visibility":true,"url":"http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer"}],"title":"Topographic"},"spatialReference":{"wkid":102100, "latestWkid": 3857}, "authoringApp":"WebMapViewer", "authoringAppVersion":"3.9", "version":"2.2"}'},webscene:{type:"Web Scene",text:'{"operationalLayers":[],"baseMap":{"id":"basemap","title":"Topographic","baseMapLayers":[{"url":"http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer","id":"worldTopoBase","layerType":"ArcGISTiledMapServiceLayer"}],"elevationLayers":[{"url":"http://elevation3D.arcgis.com/arcgis/rest/services/WorldElevation3D/Terrain3D/ImageServer","id":"globalElevation","layerType":"ArcGISTiledElevationServiceLayer"}]},"version":"1.3","authoringApp":"PortalMycontentCreate","authoringAppVersion":"3.10.0.0"}',
thumbnailURL:"/scene.png"},webscene_portal:{type:"Web Scene",text:'{"operationalLayers":[],"baseMap":{"id":"basemap","title":"Topographic","baseMapLayers":[{"url":"http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer","id":"worldTopoBase","layerType":"ArcGISTiledMapServiceLayer"}],"elevationLayers":[{"url":"http://elevation3D.arcgis.com/arcgis/rest/services/WorldElevation3D/Terrain3D/ImageServer","id":"globalElevation","layerType":"ArcGISTiledElevationServiceLayer"}]},"version":"1.3","authoringApp":"PortalMycontentCreate","authoringAppVersion":"10.4.0.0"}',
thumbnailURL:"/scene.png"},featureserver:{type:"Feature Service",typeKeywords:"Data, Service, Feature Service, ArcGIS Server, Feature Access"},mapserver:{type:"Map Service",typeKeywords:"Data, Service, Map Service, ArcGIS Server"},geocodeserver:{type:"Geocoding Service",typeKeywords:"Tool, Service, Geocoding Service, Locator Service, ArcGIS Server",thumbnailURL:"/desktopapp.png"},naserver:{type:"Network Analysis Service",typeKeywords:"Tool, Service, Network Analysis Service, ArcGIS Server"},globeserver:{type:"Globe Service",
typeKeywords:"Data, Service, Globe Service, ArcGIS Server",thumbnailURL:"/desktopapp.png"},gpserver:{type:"Geoprocessing Service",typeKeywords:"Tool, Service, Geoprocessing Service, ArcGIS Server"},geodataserver:{type:"Geodata Service",typeKeywords:"Data, Service, Geodata Service, ArcGIS Server"},imageserver:{type:"Image Service",typeKeywords:"Data, Service, Image Service, ArcGIS Server"},geometryserver:{type:"Geometry Service",typeKeywords:"Tool, Service, Geometry Service, ArcGIS Server",thumbnailURL:"/desktopapp.png"},
wmserver:{type:"Workflow Manager Service",typeKeywords:"Workflow Manager, ArcGIS Server, WMServer, Workflow, JTX, Job Tracking",thumbnailURL:"/desktopapp.png"},sceneserver:{type:"Scene Service",thumbnailURL:"/scene.png",typeKeywords:"Scene Service"},streamserver:{type:"Stream Service",thumbnailURL:"/desktopapp.png",typeKeywords:"Data, Service, Stream Service, ArcGIS Server"},elevationserver:{type:"Image Service",thumbnailURL:"/desktopapp.png",typeKeywords:"Elevation 3D Layer"},ogc:{type:"WMS",typeKeywords:"Data, Service, Web Map Service, OGC"},
arcpadpackage:{type:"ArcPad Package",typeKeywords:"Map, Layer, Data",thumbnailURL:"/desktopapp.png"},kmlcollection:{type:"KML Collection",thumbnailURL:"/desktopapp.png"},csvcollection:{type:"CSV Collection",thumbnailURL:"/desktopapp.png"},filegeodatabase:{type:"File Geodatabase",thumbnailURL:"/desktopapp.png"},caddrawing:{type:"CAD Drawing",thumbnailURL:"/desktopapp.png"},featurecollection:{type:"Feature Collection"},esritasks:{type:"Task File",typeKeywords:"ArcGIS Professional, Task Assistant, esriTasks"},
stylx:{type:"Desktop Style",typeKeywords:"ArcGIS Pro, Symbology, Style, Symbols"},ppkx:{type:"Project Package",typeKeywords:""},aptx:{type:"Project Template",typeKeywords:"ArcGIS Project Template, Project Template, ArcGIS Pro"},mmpk:{type:"Mobile Map Package",typeKeywords:""},mbpk:{type:"Mobile Basemap Package",typeKeywords:""},geojson:{type:"GeoJson",typeKeywords:"Coordinates Type, CRS, Feature, FeatureCollection, GeoJSON, Geometry, GeometryCollection"},json:{type:"GeoJson",typeKeywords:"Coordinates Type, CRS, Feature, FeatureCollection, GeoJSON, Geometry, GeometryCollection"},
rft:{type:"Raster function template",typeKeywords:"Raster, Functions, Processing, rft, srf, function template, templates, ArcGIS Pro",thumbnailURL:"/desktopapp.png"}},orgOnly:{ppt:{type:"Microsoft Powerpoint",typeKeywords:"Data, Document, Microsoft Powerpoint"},pptx:{type:"Microsoft Powerpoint",typeKeywords:"Data, Document, Microsoft Powerpoint"},document:{type:"Document Link",typeKeywords:"Data, Document"},doc:{type:"Microsoft Word",typeKeywords:"Data, Document, Microsoft Word"},docx:{type:"Microsoft Word",
typeKeywords:"Data, Document, Microsoft Word"},xls:{type:"Microsoft Excel",typeKeywords:"Data, Document, Microsoft Excel"},xlsx:{type:"Microsoft Excel",typeKeywords:"Data, Document, Microsoft Excel"},pdf:{type:"PDF",typeKeywords:"Data, Document, PDF"},jpg:{type:"Image",typeKeywords:"Data, Image, jpg"},jpeg:{type:"Image",typeKeywords:"Data, Image, jpeg"},tif:{type:"Image",typeKeywords:"Data, Image, tif"},tiff:{type:"Image",typeKeywords:"Data, Image, tiff"},png:{type:"Image",typeKeywords:"Data, Image, png"},
vsd:{type:"Visio Document",typeKeywords:"Data, Document, Visio Document"},pages:{type:"iWork Pages",typeKeywords:"Data, Document, Mac"},numbers:{type:"iWork Numbers",typeKeywords:"Data, Document, Mac"},keynote:{type:"iWork Keynote",typeKeywords:"Data, Document, Mac"},key:{type:"iWork Keynote",typeKeywords:"Data, Document, Mac"},opext:{type:"Operations Dashboard Extension",typeKeywords:"Extension, Application, ArcGIS Operations Dashboard"}},gridInfo:{csv:[{width:"170px",field:"name",name:"fieldName"},
{width:"160px",field:"type",name:"fieldType",select:"fieldTypes",editable:!0,type:a.grid.cells.Select},{width:"160px",field:"locationType",name:"addressFields",select:"addressTypes",editable:"true",type:a.grid.cells.Select},{width:"160px",field:"locationType",name:"locationFields",select:"locationTypes",editable:"true",hidden:!0,type:a.grid.cells.Select}],ogc:[{field:"visible",name:'\x3cinput id\x3d"_ogcCB", type\x3d"checkbox" checked/\x3e',width:"16px",editable:!0,type:a.grid.cells.Bool},{field:"title",
name:"ogcLayers",editable:!0,width:"420px"}]}})});