// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/dialog/_CreateItemUtilMixin","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-form dojo/json dojo/Deferred arcgisonline/sharing/util esri/geometry/webMercatorUtils esri/geometry/Extent dojo/i18n!arcgisonline/nls/arcgisonline".split(" "),function(v,f,m,r,s,p,h,t,u,q){return{addItem:function(a,b,c){var e={url:(c&&c.getPortalUser()).userContentUrl+"/"+(b?b+"/":"")+"addItem"},d;e[a&&("FORM"===a.tagName||"FORM"===a.nodeName)?"form":"content"]=a;return h.request(e,
{usePost:!0}).then(f.hitch(this,function(c){d=e.form?r.toObject(a):a;d.title=f.isArray(d.title)?d.title[0]:d.title;return dojo.mixin(c,d,{folderId:b})}))},updateItem:function(a,b){var c=(b&&b.getPortalUser()).userContentUrl+(a.folderId&&"/"!==a.folderId?"/"+a.folderId:"")+"/items/"+a.id+"/update";return h.request({url:c,content:a},{usePost:!0}).then(f.hitch(this,function(b){return a}))},deleteItem:function(a,b){var c=(b&&b.getPortalUser()).userContentUrl+(a.folderId&&"/"!==a.folderId?"/"+a.folderId:
"")+"/items/"+a.id+"/delete";return h.request({url:c},{usePost:!0})},publishItem:function(a,b,c){c=(c&&c.getPortalUser()).userContentUrl+"/publish";b.publishParameters=s.stringify(b.publishParameters);return h.request({url:c,content:b},{usePost:!0}).then(dojo.hitch(this,function(b){return f.mixin(a,{publishResult:b.services||[]})}))},moveItem:function(a,b,c){var e=new p;c=(c&&c.getPortalUser()).userContentUrl+(a.folderId&&"/"!==a.folderId?"/"+a.folderId:"")+"/items/"+a.id+"/move";var d={folder:b||
"/"};(a.folderId||"/")!==d.folder?h.request({url:c,content:d},{usePost:!0}).then(f.hitch(this,function(c){e.resolve(f.mixin(a,{folderId:b}))})):e.resolve(a);return e},serviceNameAvailable:function(a,b){var c=b&&b.getPortalUser();return h.request({url:b.url+"portals/"+c.accountId+"/isServiceNameAvailable",content:{name:a.title,type:a.type||"Feature Service"}})},analyzeItem:function(a,b,c){b=f.mixin({enableGlobalGeocoding:!0,sourceLocale:dojo.locale},b||{});a=f.mixin({},{analyzeParameters:b,filetype:a.type.toLowerCase(),
itemid:a.id});c=c.url+"/content/features/analyze";a.analyzeParameters=dojo.json.stringify(a.analyzeParameters);return h.request({url:c,content:a},{usePost:!0})},createTemplatedApplication:function(a,b,c,e){var d=a,l=f.isArray(b.typeKeywords)?-1<m.indexOf(b.typeKeywords,"selfConfigured"):-1<b.typeKeywords.indexOf("selfConfigured"),g,k,n,h=dojo.hitch(this,function(a){var b=new dojo.Deferred;if(a.shareWithWebMap){var c=esriGeowConfig.restBaseUrl+"content/items/"+a.id+"/share",d=e&&e.isEveryoneChecked(),
f=e&&e.isAccountChecked(),l=e&&e.getSharedGroups()||[],l=dojo.map(l,"return item.id;"),d={f:"json",everyone:d,org:f,groups:l.join(","),items:[a.id]};arcgisonline.sharing.util.request({url:c,content:d},{usePost:!0}).then(dojo.hitch(this,function(){b.resolve(a)}))}else b.resolve(a);return b});if(d)return g=arcgisonline.sharing.util.parseUrl(b.url),delete a.typeKeywords,k=window.location.protocol+"//"+g.host+(g.port&&"443"!==g.port&&"80"!==g.port?":"+g.port:"")+g.path,k="https:"===window.location.protocol?
arcgisonline.sharing.util.getSecureUrl(k):arcgisonline.sharing.util.getHttpUrl(k),d=dojo.mixin({type:"Web Mapping Application",typeKeywords:"Web Map, Map, Online Map, Mapping Site, JavaScript, Ready To Use"+(l?" ,selfConfigured":""),thumbnailURL:arcgisonline.sharing.util.getStaticImagesUrl()+"/webapp.png",url:k},d),d.text=dojo.json.stringify(dojo.mixin({},{source:b.id,folderId:d.folderId,values:a.webMapId?{webmap:a.webMapId}:a.groupId?{group:a.groupId}:{}})),this.addItem(d,d.folderId,c).then(f.hitch(this,
function(a){return h(f.mixin(d,{id:a.id})).then(dojo.hitch(this,function(b){var d=b.url.indexOf("?"),e=-1!==d?b.url.substr(d,b.url.length):"",e=e+(e&&e.length?"\x26":"?"),e=e+("appid\x3d"+a.id);k=b.url.substr(0,-1!==d?d:b.url.length)+e;return this.updateItem({id:a.id,url:k,folderId:b.folderId},c).then(f.hitch(this,function(){n=l?k+"\x26edit\x3dtrue":esriGeowConfig.baseUrl+("webmap/configureApp.html?appid\x3d"+a.id);n+=a.folderId&&"/"!==a.folderId?"\x26folderid\x3d"+a.folderId:"";return f.mixin(b,
a,{configureUrl:n,url:k})}))}))}),f.hitch(this,function(a){a&&409===a.code&&(a=d,a={title:q.addItemFrm.errors.error.title,message:esri.substitute({type:a.type,title:a.title},q.addItemFrm.errors.itemExists.message)});throw a;}))},checkStatus:function(a,b,c,e){var d=(e&&e.getPortalUser()).userContentUrl;a?h.request({url:d+"/items/"+a.id+"/status",content:{jobId:a.jobId}}).then(dojo.hitch(this,function(d){d=d||{status:"failed"};if("completed"===d.status)return b.resolve(a);if("failed"===d.status||""===
d.status)return b.reject({message:d.statusMessage});c=(c||500)+250;setTimeout(dojo.hitch(this,function(){this.checkStatus(a,b,c,e)}),c)}),f.hitch(this,function(a){b.reject(a)})):b.reject()},_getBatchGeocodeServers:function(a){if(!this._batchGeocoderServers){var b=a.getPortalUser(),c=-1<m.indexOf(b.privileges,"portal:user:createItem")&&-1<m.indexOf(b.privileges,"premium:user:geocode"),e=/(arcgis.com\/arcgis\/rest\/services\/world\/geocodeserver).*/ig,d=/(\/servers\/[\da-z\.-]+\/rest\/services\/world\/geocodeserver).*/ig,
f,g,k=[];m.forEach(a.helperServices&&a.helperServices.geocode||[],function(b){f=!!b.url.match(e);g=!!b.url.match(d);if(f&&!a.isPortal&&c||g||b.batch)k.push({isWorldGeocodeServer:f||g,isWorldGeocodeServerProxy:g,label:b.name,value:b.url,url:b.url,name:b.name})});this._batchGeocoderServers=k}return this._batchGeocoderServers},getPortalDefaultExtentAsGCS:function(a){if(a=a.defaultExtent||null){a=t.webMercatorToGeographic(new u(a));var b=a.spatialReference._getInfo();if(b){if(a.xmin>a.xmax){var c=b.valid[1]-
a.xmin,e=a.xmax-b.valid[0];c>e?a.xmax=b.valid[1]+e:a.xmin=b.valid[0]-c}return Math.round(1E4*a.xmin)/1E4+","+Math.round(1E4*a.ymin)/1E4+","+Math.round(1E4*a.xmax)/1E4+","+Math.round(1E4*a.ymax)/1E4}}return null},_getFederatedServers:function(a){return h.request({url:a.url+"portals/self/servers/"})},hasCreateLayer:function(a){var b={managed:!0},c,e,d,l,g;if(a.isPortal)return this._getFederatedServers(a).then(f.hitch(this,function(a){(e=(c=m.filter(a.servers||[],f.hitch(this,function(a){return a.isHosted})))&&
c.length?c[0]:null)?(d=e.adminUrl+"/admin/data/findItems",g=h.request({url:d,content:b},{useProxy:!0}).then(f.hitch(this,function(a){return(l=m.filter(a.items||a||[],f.hitch(this,function(a){return a&&a.provider&&"arcgis data store"===a.provider.toLowerCase()})))&&l.length}),f.hitch(this,function(a){return!1}))):(g=new p,g.resolve(!1));return g}));a=new p;a.resolve(!0);return a}}});