// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/dialog/DeleteWarningDlg",["dijit","dojo","dojox","dojo/require!dijit/Dialog,dijit/_Widget,dijit/_Templated"],function(b,a,g){a.provide("arcgisonline.sharing.dijit.dialog.DeleteWarningDlg");a.require("dijit.Dialog");a.require("dijit._Widget");a.require("dijit._Templated");a.declare("arcgisonline.sharing.dijit.dialog.DeleteWarningDlg",[b._Widget,b._Templated],{widgetsInTemplate:!0,templateString:'\x3cdiv class\x3d"widgetContent"\x3e\r\n  \x3cdiv dojotype\x3d"dijit.Dialog" id\x3d"delete-warning-dialog" title\x3d"${i18n.deleteWarningDlgTitle}" execute\x3d""\x3e\r\n    \x3cdiv style\x3d"margin-top:0 !important;" id\x3d"delete-warning-dialog-content"\x3e\r\n    \x3c/div\x3e\r\n\r\n    \x3cdiv class\x3d"esriFloatTrailing" style\x3d"clear: both; margin-top: 2em;"\x3e\r\n      \x3cspan id\x3d"delete-status" style\x3d"display:none;"\x3e${!i18n.deletingSpace}\x26nbsp;\x26nbsp;\x26nbsp;\x3c/span\x3e\r\n\t\x3c!-- "primary" / "calcite orange" used since this is a delete confirmation --\x3e\r\n      \x3cbutton id\x3d"button_delete-warning-submit" class\x3d"jevent calcite orange" dojoType\x3d"dijit.form.Button"\x3e\r\n        ${i18n.deleteLabel}\r\n      \x3c/button\x3e\r\n      \x3cbutton id\x3d"button_delete-warning-close" class\x3d"jevent cancel" dojoType\x3d"dijit.form.Button"\x3e\r\n        ${i18n.cancel}\r\n      \x3c/button\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv style\x3d"clear:both; float:none; height: 0;"\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n',
handler:null,manualHide:!1,statics:{_instance:null,getInstance:function(){null==this._instance&&(this._instance=new arcgisonline.sharing.dijit.dialog.DeleteWarningDlg);return this._instance}},postMixInProperties:function(){this.inherited(arguments);this.i18n=a.i18n.getLocalization("arcgisonline","arcgisonline").common;a.mixin(this.i18n,a.i18n.getLocalization("arcgisonline","arcgisonline").deleteWarningDlg)},postCreate:function(){this.loadConnections()},show:function(c,d,e,f){this.handler=e;this.clear();
if(null==d||""==d)d="item";b.byId("button_delete-warning-submit").set("disabled",!1);b.byId("button_delete-warning-close").set("disabled",!1);this.manualHide=f;e="";e=1==c?a.string.substitute(this.i18n.confirmDeleteItem,[d]):a.string.substitute(this.i18n.confirmDeleteItems,[c,d]);a.byId("delete-warning-dialog-content").innerHTML=e;a.byId("delete-warning-dialog_title").innerHTML=this.i18n.deleteLabel;a.byId("button_delete-warning-submit_label").innerHTML=this.i18n.deleteLabel;a.style(a.byId("delete-status"),
"display","none");b.byId("delete-warning-dialog").show()},showMsg:function(c,d){null==c||0==c.length||(this.handler=d,this.clear(),b.byId("button_delete-warning-submit").set("disabled",!1),b.byId("button_delete-warning-close").set("disabled",!1),this.manualHide=!1,a.byId("delete-warning-dialog-content").innerHTML=c,a.byId("delete-warning-dialog_title").innerHTML=this.i18n.deleteLabel,a.byId("button_delete-warning-submit_label").innerHTML=this.i18n.deleteLabel,a.style(a.byId("delete-status"),"display",
"none"),b.byId("delete-warning-dialog").show())},showMsgTitleButton:function(c,d,e,f){null==c||0==c.length||(this.handler=f,this.clear(),b.byId("button_delete-warning-submit").set("disabled",!1),b.byId("button_delete-warning-close").set("disabled",!1),this.manualHide=!1,a.byId("delete-warning-dialog-content").innerHTML=c,a.byId("delete-warning-dialog_title").innerHTML=d,a.byId("button_delete-warning-submit_label").innerHTML=e,a.style(a.byId("delete-status"),"display","none"),b.byId("delete-warning-dialog").show())},
renameDeleteButton:function(a){b.byId("button_delete-warning-submit").set("label",a)},renameCancelButton:function(a){b.byId("button_delete-warning-close").set("label",a)},clear:function(){},loadConnections:function(){a.query(".jevent").connect("onclick",function(a){a.preventDefault()});a.query("#button_delete-warning-close").connect("onclick",function(){b.byId("delete-warning-dialog").hide()});a.query("#button_delete-warning-submit").connect("onclick",a.hitch(this,"submitRequest"))},submitRequest:function(c){this.handler();
this.manualHide?(a.style(a.byId("delete-status"),"display","inline-block"),b.byId("button_delete-warning-submit").set("disabled",!0),b.byId("button_delete-warning-close").set("disabled",!0)):b.byId("delete-warning-dialog").hide()},hide:function(){b.byId("delete-warning-dialog").hide()}})});