// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
require({cache:{"url:arcgisonline/sharing/dijit/dialog/templates/InviteUsersDlg.html":'\x3cdiv\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"_dialog" data-dojo-type\x3d"dijit/Dialog" id\x3d"invite-users-dialog" title\x3d"${i18n.inviteUsersTitle}" execute\x3d""\x3e\r\n    \x3cdiv id\x3d"invite-users-search" data-dojo-attach-point\x3d"_userSelector"\r\n         data-dojo-type\x3d"arcgisonline/sharing/dijit/UserSelector"\r\n         data-dojo-props\x3d"restrictSearch: true, excludeCurrentUser: true"\x3e\x3c/div\x3e\r\n    \x3cfieldset class\x3d"admin" style\x3d"margin:1.5em 0 0 0;display:none;"\x3e\r\n      \x3cinput data-dojo-attach-point\x3d"_addNowChk" style\x3d"vertical-align: top" id\x3d"addNow" name\x3d"addNow"\r\n             type\x3d"checkbox" data-dojo-type\x3d"dijit/form/CheckBox"\x3e\r\n      \x3clabel style\x3d"vertical-align: top" for\x3d"addNow"\x3e${i18n.addNow}\x3c/label\x3e\r\n    \x3c/fieldset\x3e\r\n    \x3cbr\x3e\r\n    \x3cdiv class\x3d"esriFloatTrailing" style\x3d"padding-top:0; padding-bottom:5px;"\x3e\r\n      \x3cbutton data-dojo-attach-point\x3d"_submit" id\x3d"button_send-invite"\r\n              class\x3d"calcite blue small" data-dojo-type\x3d"dijit/form/Button"\x3e${i18n.sendInvitation}\x3c/button\x3e\r\n      \x3cbutton data-dojo-attach-point\x3d"_cancel" id\x3d"button_invite-users-close"\r\n              class\x3d"calcite transparent small" data-dojo-type\x3d"dijit/form/Button"\x3e${i18n.cancel}\x3c/button\x3e\r\n    \x3c/div\x3e\r\n    \x3cbr\x3e\x26nbsp;\x3cbr\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("arcgisonline/sharing/dijit/dialog/InviteUsersDlg","require dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/on dojo/dom dojo/dom-attr dojo/dom-style dojo/query dijit/a11yclick dojo/Deferred dojo/promise/all dijit/Dialog dijit/form/Button dijit/form/CheckBox dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin esri/lang esri/domUtils arcgisonline/sharing/util arcgisonline/sharing/geow/Account arcgisonline/sharing/geow/Group arcgisonline/sharing/dijit/UserSelector arcgisonline/sharing/dijit/dialog/GeneralDlg dojo/i18n!arcgisonline/nls/arcgisonline dojo/text!arcgisonline/sharing/dijit/dialog/templates/InviteUsersDlg.html".split(" "),
function(s,t,e,k,h,G,H,I,u,q,v,w,J,K,L,x,y,z,A,B,l,C,D,M,E,r,F){var p=t("arcgisonline.sharing.dijit.dialog.InviteUsersDlg",[x,y,z],{declaredClass:"arcgisonline.sharing.dijit.dialog.InviteUsersDlg",basePath:s.toUrl("arcgisonline/sharing/dijit/dialog"),templateString:F,widgetsInTemplate:!0,groupUsers:null,selectedUsers:[],profiles:[],postMixInProperties:function(){this.inherited(arguments);this.i18n={};e.mixin(this.i18n,r.common);e.mixin(this.i18n,r.inviteUsersDlg)},postCreate:function(){this.inherited(arguments);
this._generalDlg=E.prototype.statics.getInstance();this._loadConnections()},hide:function(){this._dialog.hide()},show:function(a,b,d){var c=this;c.clear();c.group=b;c.groupId=a;c._user=l.getUser();c.restrictToOrgMembers=d;c._dialog.show();c._user&&c._user.accountId?C.getSelf(function(a){c._setFlags();c._toggleRestrictUI(a);c._getGroupUsers()}):c._getGroupUsers()},clear:function(){this.groupUsers=null;this.selectedUsers=[];this.profiles=[];this._userSelector.set("searchLabel",this.i18n.searchByNameOrgBoth);
this._userSelector.set("usersClickLabel",this.i18n.clickName);this._userSelector.set("selectedUsersLabel",this.i18n.invitationList);this._userSelector.reset();this._addNowChk.set("value",!1);this._setSending(!1);l.isPortal()&&this._userSelector.enableRestrictSearchUI(!1)},onAddNow:function(){},_loadConnections:function(){this.own(q(this._submit,e.hitch(this,this._sendInvite)),q(this._cancel,e.hitch(this,this.hide)),h(this._addNowChk,"change",e.hitch(this,this._onAddNow)),h(this._dialog,"hide",e.hitch(this,
this.clear)),this._userSelector.on("selection-change",e.hitch(this,this._selectUsers)),this._userSelector.on("profile-load",e.hitch(this,this._profileLoaded)),h(this._userSelector._restrictSearch,"change",e.hitch(this,this._restrictSearchChanged)))},_setFlags:function(){this._isPortal=l.isPortal();this._isAdmin=esriGeowConfig.userRole&&esriGeowConfig.userRole.isAdmin();this._roleCanAssignToGroups=(this._isCustomRole=esriGeowConfig.userRole&&esriGeowConfig.userRole.isCustom())&&esriGeowConfig.userRole.canAssignUsersToOrgGroups()},
_toggleRestrictUI:function(a){if(this._isPortal)this._userSelector.enableRestrictSearchUI(!1);else if(this.restrictToOrgMembers)this._userSelector.enableRestrictSearchUI(!0),this._userSelector._restrictSearch.set("checked",!0),this._userSelector._restrictSearch.set("disabled",!0);else if(this.orgMembersOnly||a.canSearchPublic||this._user.accountId===a.id&&this._isAdmin)this._isPortal||this._userSelector.enableRestrictSearchUI(!0),this._roleCanAssignToGroups&&this.group.owner!==this._user.username?
this._userSelector._restrictSearch.set("disabled",!0):this._userSelector._restrictSearch.set("disabled",!1)},_restrictSearchChanged:function(){var a;l.isPortal()||(a=this._userSelector._restrictSearch.get("checked"),this._addNowChk.set("disabled",!a),!a&&this._addNowChk.get("checked")&&this._addNowChk.set("checked",!1))},_setSending:function(a){var b=this._addNowChk.get("checked");this._submit.set("disabled",a);a?this._submit.set("label",b?this.i18n.addingToGroup:this.i18n.sendingInvitation):this._submit.set("label",
b?this.i18n.addToGroup:this.i18n.sendInvitation)},_getGroupUsers:function(){var a=this;if(null===a.groupUsers&&(D.getGroupUsers(a.groupId,function(b){b&&b.owner&&(a.groupUsers=b)},null),a._user&&a._isAdmin||a.group&&a.group.userMembership&&"admin"===a.group.userMembership.memberType||a._roleCanAssignToGroups))u(".admin").forEach(B.show),a._roleCanAssignToGroups&&a.group.owner!==a._user.username&&(a._addNowChk.set("checked",!0),a._addNowChk.set("disabled",!0))},_selectUsers:function(a){var b=this,
d=!1;a&&a.selectedUsers&&(b.selectedUsers=a.selectedUsers||[],b._user&&b._isAdmin&&b._retrieveProfiles().then(function(a){a&&0<a.length?(d=k.some(a,function(a){return!A.isDefined(a.isInOrg)||!1===a.isInOrg}),b._addNowChk.set("checked",d?!1:b._addNowChk.get("checked")),b._addNowChk.set("disabled",d)):b._addNowChk.set("disabled",!1)}))},_profileLoaded:function(a){var b;a&&a.profile&&(b=k.some(this.profiles,function(b){return b.username===a.profile.username}),b||(a.profile.isInOrg=!!a.profile.orgId||
a.profile.orgId===this._user.accountId,this.profiles.push(e.clone(a.profile))))},_retrieveProfiles:function(){var a=this,b=new v,d=e.clone(a.selectedUsers)||[],c=[],f=[],n,h,m,g;for(g=0;g<d.length;g++)h=d[g],n=k.filter(a.profiles,function(a){return a.username===h.username}),!n||1>n.length?c.push(l.request({url:esriGeowConfig.restBaseUrl+"community/users/"+h.username})):k.forEach(n,function(a){f.push(a)});w(c).then(function(c){for(g=0;g<c.length;g++)m=c[g],m.isInOrg=!!m.orgId||m.orgId===a._user.accountId,
a.profiles.push(m),f.push(m);b.resolve(f)},function(a){b.resolve(f)});return b},_onAddNow:function(a){this._submit.set("label",a?this.i18n.addToGroup:this.i18n.sendInvitation)},_sendInvite:function(){var a=this._addNowChk.get("checked"),b=!1,d=[],c,f;if(0===this.selectedUsers.length)this._generalDlg.show({title:this.i18n.errorlabel,message:this.i18n.error.addUsers});else{for(f=0;f<this.selectedUsers.length;f++)c=this.selectedUsers[f],this.groupUsers.owner!==c.username&&-1===k.indexOf(this.groupUsers.admins,
c.username)&&-1===k.indexOf(this.groupUsers.users,c.username)?d.push(c.username):b=!0;0<d.length?(this._setSending(!0),a=esriGeowConfig.restBaseUrl+"community/groups/"+this.groupId+(a?"/addUsers":"/invite"),l.request({url:a,content:{users:d.join(",")}},{usePost:!0}).then(e.hitch(this,this._handleInvite,b),e.hitch(this,this._handleInviteError))):this.hide()}},_handleInvite:function(a,b){var d=this._addNowChk.get("checked"),c;this._setSending(!1);b&&(b.notAdded&&0<b.notAdded.length)&&(c=1===b.notAdded.length?
esri.substitute({user:b.notAdded[0]},this.i18n.error.unableToAddPrivs):esri.substitute({userList:b.notAdded.join(", ")},this.i18n.error.unableToAddMultiplePrivs),this._generalDlg.show({title:this.i18n.errorLabel,message:c}));a&&this._generalDlg.show({title:this.i18n.infoLabel,message:this.i18n.alreadyInGroup+" "+(d?this.i18n.notAdded:this.i18n.sentInvitation)});if(d)this.onAddNow();this.hide()},_handleInviteError:function(a){var b=this.i18n.error.genericMsg;this._setSending(!1);a&&(a.code&&a.messageCode&&
"COM_1049"===a.messageCode)&&(b=this.i18n.error.unableToInvitePrivs);this._generalDlg.show({title:this.i18n.errorlabel,message:b})}});p.prototype.statics={_instance:null,getInstance:function(){null==this._instance&&(this._instance=new p);return this._instance}};return p});