// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/dialog/InvitationsDlg",["dijit","dojo","dojox","dojo/require!dijit/Dialog,dijit/_Widget,dijit/_Templated,arcgisonline/sharing/dijit/InvitationsGrid,arcgisonline/sharing/util"],function(c,a,f){a.provide("arcgisonline.sharing.dijit.dialog.InvitationsDlg");a.require("dijit.Dialog");a.require("dijit._Widget");a.require("dijit._Templated");a.require("arcgisonline.sharing.dijit.InvitationsGrid");a.require("arcgisonline.sharing.util");a.declare("arcgisonline.sharing.dijit.dialog.InvitationsDlg",
[c._Widget,c._Templated],{invitations:null,widgetsInTemplate:!0,templateString:'\x3cdiv class\x3d"widgetContent" \x3e\r\n  \t\x3cdiv dojotype\x3d"dijit.Dialog" id\x3d"invitations-dialog" title\x3d"${i18n.invitationsDlgTitle}" execute\x3d""\x3e\r\n\t\t\x3clabel \x3e${i18n.invitationMsg}\x3c/label\x3e\r\n\t  \t\x3cbr /\x3e \r\n\t  \t\x3cbr /\x3e \r\n\t    \x3cdiv dojoType\x3d"arcgisonline.sharing.dijit.InvitationsGrid" jsid\x3d"invitationsGrid" style\x3d"height: 150px;"\x3e\x3c/div\x3e\r\n\t  \t\x3cbr /\x3e \r\n\t  \t\x3cdiv style\x3d"float: right; padding-top:0px; padding-bottom:5px;"\x3e\r\n\t\t  \t\x3cbutton id\x3d"button_invitations-close" class\x3d"jevent primary" dojoType\x3d"dijit.form.Button"\x3e${i18n.close}\x3c/button\x3e\r\n\t  \t\x3c/div\x3e\r\n\t \t\x3cbr /\x3e\x26nbsp;\x3cbr /\x3e \r\n  \t\x3c/div\x3e\r\n\x3c/div\x3e',
groupsUser:null,statics:{_instance:null,getInstance:function(){null==this._instance&&(this._instance=new arcgisonline.sharing.dijit.dialog.InvitationsDlg);return this._instance}},postMixInProperties:function(){this.inherited(arguments);this.i18n=a.i18n.getLocalization("arcgisonline","arcgisonline").common;a.mixin(this.i18n,a.i18n.getLocalization("arcgisonline","arcgisonline").invitationsDlg)},postCreate:function(){this.loadConnections()},show:function(a,b){if(b&&(b.username||b.email))this.groupsUser=
b;this.invitations=a;this.getGroupInfos()},update:function(a){this.invitations=a;this.getGroupInfos()},getGroupInfos:function(){for(var d=0;d<this.invitations.length;d++){var b=arcgisonline.sharing.util.getUser();if(null==b)return;var c=b.email;this.groupsUser&&(this.groupsUser.username?c=this.groupsUser.username:this.groupsUser.email&&(c=this.groupsUser.email));arcgisonline.sharing.util.getJson(esriGeowConfig.restBaseUrl+"community/users/"+c+"/invitations/"+this.invitations[d].groupId,a.hitch(this,
function(a,b,d){this.invitations[a].fromUsername=b.fromUsername.username;this.invitations[a].fromUserFullname=b.fromUsername.fullname;this.invitations[a].groupTitle=b.group.title;this.invitations[a].groupOwner=b.group.owner;this.invitations[a].groupDescription=b.group.description;this.invitations[a].groupThumbnail=b.group.thumbnail;this.groupsUser&&(this.invitations[a].asUser=c)},d))}setTimeout(a.hitch(this,"checkInvitationsGroupInfo",0),500)},checkInvitationsGroupInfo:function(d){for(var b=0,e=0;e<
this.invitations.length;e++)if(this.invitations[e].groupTitle)b++;else break;b==this.invitations.length?(c.byId("invitations-dialog").open||c.byId("invitations-dialog").show(),invitationsGrid.loadGrid(this.invitations)):5>d&&setTimeout(a.hitch(this,"checkInvitationsGroupInfo",d+1),500)},loadConnections:function(){a.query(".jevent").connect("onclick",function(a){a.preventDefault()});a.query("#button_invitations-close").connect("onclick",function(){c.byId("invitations-dialog").hide()});a.subscribe("onInvitationAccept",
this,"onInvitationAccept");a.subscribe("onInvitationDecline",this,"onInvitationDecline")},onInvitationAccept:function(){1==this.invitations.length&&c.byId("invitations-dialog").hide()},onInvitationDecline:function(){1==this.invitations.length&&c.byId("invitations-dialog").hide()},hide:function(){c.byId("invitations-dialog").hide()}})});