// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/dialog/LayerTimeSettings",["dijit","dojo","dojox","dojo/require!dijit/_WidgetBase,dijit/registry,arcgisonline/sharing/util,esri/IdentityManager,arcgisonline/sharing/dijit/dialog/GeneralDlg"],function(c,a,e){a.provide("arcgisonline.sharing.dijit.dialog.LayerTimeSettings");a.require("dijit._WidgetBase");a.require("dijit.registry");a.require("arcgisonline.sharing.util");a.require("esri.IdentityManager");a.require("arcgisonline.sharing.dijit.dialog.GeneralDlg");a.declare("arcgisonline.sharing.dijit.dialog.LayerTimeSettings",
[c._WidgetBase],{baseClass:"esriLayerTimeSettings",postMixInProperties:function(){this._util=arcgisonline.sharing.util;this._errorDlg=arcgisonline.sharing.dijit.dialog.GeneralDlg.prototype.statics.getInstance();this.i18n=a.mixin({},a.i18n.getLocalization("arcgisonline","arcgisonline").common);this.i18n=a.mixin(this.i18n,a.i18n.getLocalization("arcgisonline","arcgisonline").layerTimeSettings)},buildRendering:function(){var b=document.createDocumentFragment();a.create("p",{innerHTML:this.i18n.header},
b);this._enableTimeChk=new c.form.CheckBox({checked:!1,name:"enableTimeCheckbox"});b.appendChild(this._enableTimeChk.domNode);a.create("label",{"for":"enableTimeCheckbox","class":"esriLeadingMargin1",innerHTML:this.i18n.enableTimeLbl},b);a.create("br",{},b);a.create("p",{innerHTML:this.i18n.fieldsetLbl},b);this._fieldSet=a.create("fieldset",{"class":"esriLeadingMargin2"},b);this._timeEventsRdio=new c.form.RadioButton({name:"times",checked:!0},a.create("input",{},this._fieldSet));a.create("label",
{"for":"timeEvents","class":"esriLeadingMargin1",innerHTML:this.i18n.timeEventsLbl},this._fieldSet);a.create("br",{},this._fieldSet);this._timeEventsDiv=a.create("div",{"class":"esriLeadingMargin23"},this._fieldSet);a.create("label",{"for":"timeEventsSelect","class":"esriFloatLeading timeEvent",innerHTML:this.i18n.timeFieldLbl},this._timeEventsDiv);this._timeEventsSelect=new c.form.Select({maxHeight:200,name:"timeEventsSelect"},a.create("select",{},this._timeEventsDiv));a.create("br",{},this._fieldSet);
this._timeRangesRdio=new c.form.RadioButton({name:"times","class":"timeRangeRdio"},a.create("input",{},this._fieldSet));a.create("label",{"for":"timeRanges","class":"esriLeadingMargin1",innerHTML:this.i18n.timeRangesLbl},this._fieldSet);a.create("br",{},this._fieldSet);this._timeRangesDiv=a.create("div",{"class":"esriLeadingMargin23"},this._fieldSet);a.create("label",{"for":"startTimeSelect","class":"esriFloatLeading timeRange",innerHTML:this.i18n.startTimeLbl},this._timeRangesDiv);this._startTimeSelect=
new c.form.Select({maxHeight:200,name:"startTimeSelect","class":"timeRange",disabled:!0},a.create("select",{},this._timeRangesDiv));a.create("br",{},this._timeRangesDiv);a.create("br",{},this._timeRangesDiv);a.create("label",{"for":"endTimeSelect","class":"esriFloatLeading timeRange",innerHTML:this.i18n.endTimeLbl},this._timeRangesDiv);this._endTimeSelect=new c.form.Select({maxHeight:200,name:"endTimeSelect","class":"timeRange",disabled:!0},a.create("select",{},this._timeRangesDiv));a.create("br",
{},this._timeRangesDiv);this.inherited(arguments);this.domNode.appendChild(b)},postCreate:function(){this._loadConnects();this._loadLayerFields();this._loadTimeInfo()},_loadConnects:function(){this.connect(this._timeRangesRdio,"onChange",a.hitch(this,function(b){a.forEach(c.registry.findWidgets(this._timeRangesDiv),function(a){a.set("disabled",!b)})}));this.connect(this._timeEventsRdio,"onChange",a.hitch(this,function(b){this.options&&1<this.options.length&&a.forEach(c.registry.findWidgets(this._timeEventsDiv),
function(a){a.set("disabled",!b)})}));this.connect(this._enableTimeChk,"onChange",a.hitch(this,function(b){var d=this.options&&1<this.options.length;a.forEach(c.registry.findWidgets(this._fieldSet),function(a){b=!d&&-1<a["class"].indexOf("timeRange")?!1:b;a.set("disabled",!b)});this[this._timeRangesRdio.get("checked")?"_timeEventsRdio":"_timeRangesRdio"].onChange(!1)}))},_getValueAttr:function(){return this._enableTimeChk.get("checked")?this._timeEventsRdio.get("checked")?{timeInfo:{startTimeField:this._timeEventsSelect.get("value")}}:
{timeInfo:{startTimeField:this._startTimeSelect.get("value"),endTimeField:this._endTimeSelect.get("value")}}:{timeInfo:{}}},_setDisabledAttr:function(b){a.forEach(c.registry.findWidgets(this.domNode),function(a){a.set("disabled",b)})},_loadLayerFields:function(){this.options=a.map(this.fields,a.hitch(this,function(a){return{label:a.alias||a.name,value:a.name}}));this._timeEventsSelect.set("options",this.options);this._timeEventsSelect.set("value",this.options[0].value);this.options&&1<this.options.length&&
(this._startTimeSelect.set("options",a.clone(this.options)),this._startTimeSelect.set("value",this.options[0].value),this._endTimeSelect.set("options",a.clone(this.options)),this._endTimeSelect.set("value",this.options[1].value))},_loadTimeInfo:function(){var a=this.timeInfo||{};this._enableTimeChk.set("checked",a.startTimeField);this._timeEventsSelect.set("value",a.startTimeField);this._startTimeSelect.set("value",a.startTimeField);this._endTimeSelect.set("value",a.endTimeField||this._endTimeSelect.get("value"));
this._timeRangesRdio.set("checked",this.timeInfo.startTimeField&&this.timeInfo.endTimeField);this._timeEventsRdio.set("checked",!this.timeInfo.endTimeField)}})});