// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/dialog/RendererDlg",["dijit","dojo","dojox","dojo/require!dijit/_Widget,dijit/_Templated,dijit/Dialog,arcgisonline/sharing/dijit/dialog/SymbolDlg"],function(d,a,e){a.provide("arcgisonline.sharing.dijit.dialog.RendererDlg");a.require("dijit._Widget");a.require("dijit._Templated");a.require("dijit.Dialog");a.require("arcgisonline.sharing.dijit.dialog.SymbolDlg");a.declare("arcgisonline.sharing.dijit.dialog.RendererDlg",[d._Widget,d._Templated],{util:arcgisonline.sharing.util,
folder:arcgisonline.sharing.geow.Folder,widgetsInTemplate:!0,templateString:'\x3cdiv class\x3d"widgetContainer"\x3e\r\n  \x3cdiv dojotype\x3d"dijit.Dialog" id\x3d"renderer-dialog" title\x3d"${i18n.rendererDlgTitle}" execute\x3d""\x3e\r\n  \t\r\n    \x3cdiv\x3e\r\n      \x3ctable cellspacing\x3d"10" width\x3d"100%"\x3e\x3ctbody\x3e\r\n\t\t\t\x3ctr\x3e\x3ctd\x3e\r\n        \x3clabel\x3e${i18n.labelLabel}\x3c/label\x3e\r\n      \x3c/td\x3e\x3ctd\x3e\r\n        \x3cdiv dojoAttachPoint\x3d"rendererLabel" dojotype\x3d"dijit.form.TextBox" trim\x3d"true" required\x3d"true" style\x3d"width:100%; padding:2px;"\x3e\x3c/div\x3e\r\n      \x3c/td\x3e\x3c/tr\x3e\r\n      \x3ctr\x3e\x3ctd\x3e\r\n        \x3clabel\x3e${i18n.valueLabel}\x3c/label\x3e\r\n      \x3c/td\x3e\x3ctd\x3e\r\n        \x3clabel id\x3d"renderer-value"\x3e\x3c/label\x3e\r\n      \x3c/td\x3e\x3c/tr\x3e\r\n\t\t\t\x3c/tbody\x3e\x3c/table\x3e\r\n      \x3cdiv\x3e\r\n        \x3cbutton dojotype\x3d"dijit.form.Button" type\x3d"button" dojoAttachPoint\x3d"_rendererSymbolUpdateButton" class\x3d"default esriFloatLeading" dojoAttachEvent\x3d"onClick:_onRendererSymbolUpdateButtonClick"\x3e\r\n          \x3cspan\x3e${i18n.changeSymbolBtn}\x3c/span\x3e\r\n        \x3c/button\x3e\r\n        \x3cbutton dojoAttachEvent\x3d"onClick:_onCancelClick" dojoAttachPoint\x3d"rendererCancelBtn" class\x3d"jevent cancel esriFloatTrailing" type\x3d"cancel" dojotype\x3d"dijit.form.Button"\x3e\r\n          ${i18n.cancel}\r\n        \x3c/button\x3e\r\n        \x3cbutton dojoAttachEvent\x3d"onClick:_onOkClick" dojoAttachPoint\x3d"rendererOkBtn" class\x3d"jevent primary esriFloatTrailing" dojotype\x3d"dijit.form.Button"\x3e\r\n          ${i18n.ok}\r\n        \x3c/button\x3e\r\n\t\t\t\x3c/div\x3e\r\n      \x3cdiv style\x3d"clear:both;"\x3e\r\n      \x3c/div\x3e\r\n    \x3c/div\x3e\r\n\t\t\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n',
i18n:null,symbol:null,onRendererSymbolChangeHandler:null,onRendererSymbolChangeCancelHandler:null,applyRendererEditsHandler:null,statics:{_instance:null,getInstance:function(){null==this._instance&&(this._instance=new arcgisonline.sharing.dijit.dialog.RendererDlg);return this._instance}},postMixInProperties:function(){this.inherited(arguments);this.i18n=a.clone(a.i18n.getLocalization("arcgisonline","arcgisonline").common);a.mixin(this.i18n,a.i18n.getLocalization("arcgisonline","arcgisonline").rendererPanel);
a.mixin(this.i18n,a.i18n.getLocalization("arcgisonline","arcgisonline").rendererDlg)},postCreate:function(){this.loadConnections()},show:function(b){this.symbol=esri.symbol.fromJson(b.symbol.toJson());null===b.value?a.byId("renderer-value").innerHTML=this.i18n.other:a.byId("renderer-value").innerHTML=b.value;this.rendererLabel.set("value",b.label);this.applyRendererEditsHandler=a.subscribe("applyRendererEdits",a.hitch(this,"_onApplyEdits"));d.byId("renderer-dialog").show()},loadConnections:function(){a.query(".jevent").connect("onclick",
function(a){a.preventDefault()})},_onCancelClick:function(){a.publish("onRendererItemChange",[null,null]);d.byId("renderer-dialog").hide()},hide:function(){this.onRendererSymbolChangeHandler&&(a.unsubscribe(this.onRendererSymbolChangeHandler),a.unsubscribe(this.onRendererSymbolChangeCancelHandler));this.applyRendererEditsHandler&&a.unsubscribe(this.applyRendererEditsHandler);this.rendererCancelBtn.set("disabled",!1);this._rendererSymbolUpdateButton.set("disabled",!1);d.byId("renderer-dialog").hide()},
_onRendererSymbolUpdateButtonClick:function(b){this.onRendererSymbolChangeHandler&&(a.unsubscribe(this.onRendererSymbolChangeHandler),a.unsubscribe(this.onRendererSymbolChangeCancelHandler));this.onRendererSymbolChangeHandler=a.subscribe("onSymbolChange",a.hitch(this,"_onRendererSymbolChange"));this.onRendererSymbolChangeCancelHandler=a.subscribe("onSymbolChangeCancel",a.hitch(this,function(){this.onRendererSymbolChangeHandler&&(a.unsubscribe(this.onRendererSymbolChangeHandler),a.unsubscribe(this.onRendererSymbolChangeCancelHandler));
this.rendererCancelBtn.set("disabled",!1);this._rendererSymbolUpdateButton.set("disabled",!1)}));this.rendererCancelBtn.set("disabled",!0);this._rendererSymbolUpdateButton.set("disabled",!0);arcgisonline.sharing.dijit.dialog.SymbolDlg.prototype.statics.getInstance().showSymbol(this.symbol,{applyHandler:a.hitch(this,"_onApplyEdits"),okHandler:a.hitch(this,function(b){this._rendererSymbolUpdateButton.set("disabled",!1);this.symbol=b;a.publish("onRendererItemChange",[b,this.rendererLabel.get("value")]);
a.publish("saveRenderer",[])})})},_onRendererSymbolChange:function(a){this.rendererCancelBtn.set("disabled",!1);this._rendererSymbolUpdateButton.set("disabled",!1);var c=a.toJson();if("esriPMS"==a.type&&(0==c.url.length||"http://"==c.url))a=esri.symbol.fromJson(this.markerJson);this.symbol=a},_onOkClick:function(b){b.preventDefault();a.publish("onRendererItemChange",[esri.symbol.fromJson(this.symbol.toJson()),this.rendererLabel.get("value")]);this.hide()},_onApplyEdits:function(b){a.publish("onRendererItemChange",
[b,this.rendererLabel.get("value")]);a.publish("saveRenderer",[])},onKeyDown:function(a){var c;window.event?c=a.keyCode:a.which&&(c=a.which);13==c&&this._onOkClick(a)}})});