// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/dialog/SelectAccountUserDlg",["dijit","dojo","dojox","dojo/require!dijit/Dialog,dijit/_Widget,dijit/_Templated,dojo/store/Memory,arcgisonline/sharing/util,arcgisonline/sharing/geow/Account"],function(c,b,h){b.provide("arcgisonline.sharing.dijit.dialog.SelectAccountUserDlg");b.require("dijit.Dialog");b.require("dijit._Widget");b.require("dijit._Templated");b.require("dojo.store.Memory");b.require("arcgisonline.sharing.util");b.require("arcgisonline.sharing.geow.Account");
b.declare("arcgisonline.sharing.dijit.dialog.SelectAccountUserDlg",[c._Widget,c._Templated],{widgetsInTemplate:!0,templateString:'\x3cdiv class\x3d"widgetContent"\x3e\r\n  \x3cdiv class\x3d"${baseClass}" data-dojo-type\x3d"dijit.Dialog" id\x3d"select-account-user-dialog" title\x3d"${i18n.selectUser}" execute\x3d""\x3e\r\n    \x3cdiv style\x3d"margin-top:1em;" id\x3d"select-account-user-content"\x3e\r\n      Select a user.\r\n    \x3c/div\x3e\r\n    \x3cdiv style\x3d"margin-top:1em;"\x3e\r\n      \x3cdiv id\x3d"userList" data-dojo-attach-point\x3d"userList" data-dojo-attach-event\x3d"onChange:onUserSelect" data-dojo-type\x3d"dijit.form.ComboBox" value\x3d"${i18n.selectUserLabel}"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv style\x3d"float:right; clear:both; margin-top:2em;"\x3e\r\n      \x3cbutton id\x3d"button_select-account-user-submit" class\x3d"jevent primary" data-dojo-type\x3d"dijit.form.Button"\x3e${i18n.selectUser}\x3c/button\x3e\r\n      \x3cbutton id\x3d"button_select-account-user-close" class\x3d"jevent cancel" data-dojo-type\x3d"dijit.form.Button"\x3e${i18n.cancel}\x3c/button\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv style\x3d"clear:both; float:none; height:0;"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n',
baseClass:"esriAGOChangeOwnerDlg",util:arcgisonline.sharing.util,account:arcgisonline.sharing.geow.Account,handler:null,accountId:null,userStore:null,userList:null,maxUsers:100,selectedUser:null,currentUser:null,enterpriseProvider:"enterprise",statics:{_instance:null,getInstance:function(){null==this._instance&&(this._instance=new arcgisonline.sharing.dijit.dialog.SelectAccountUserDlg);return this._instance}},postCreate:function(){this.loadConnections()},postMixInProperties:function(){this.inherited(arguments);
this.i18n=b.i18n.getLocalization("arcgisonline","arcgisonline").common;b.mixin(this.i18n,b.i18n.getLocalization("arcgisonline","arcgisonline").selectAccountUserDlg)},show:function(a,f){this.clear();this.accountId=a.id;this.currentUser=a.currentUser;this.adminOnly=a.adminOnly;this.handler=f;if(this.util.isPortal()&&a.provider&&a.provider===this.enterpriseProvider&&a.groupId)this._getGroupUsers(a);else{var d={start:1,num:this.maxUsers};this.adminOnly&&(d.adminOnly=this.adminOnly);this.account.getAccountUsers(this.accountId,
d,b.hitch(this,this.handleGetAccountUsers))}b.byId("select-account-user-dialog_title").innerHTML=a.title;b.byId("button_select-account-user-submit_label").innerHTML=a.title;b.byId("select-account-user-content").innerHTML=a.message;c.byId("select-account-user-dialog").show()},_getGroupUsers:function(a){var c=0;this.util.request({url:esriGeowConfig.restBaseUrl+"community/groups/"+a.groupId+"/users"}).then(b.hitch(this,function(a){a&&(!a.code&&!a.message&&a.owner&&a.admins&&a.users)&&(null===this.userStore&&
(this.userStore=new b.store.Memory({idProperty:"name",data:[]}),this.userList.set("store",this.userStore)),b.forEach(a.admins,b.hitch(this,function(a){this.currentUser!==a&&(this.userStore.put({name:a,username:a}),c++)})),b.forEach(a.users,b.hitch(this,function(a){this.currentUser!==a&&(this.userStore.put({name:a,username:a}),c++)})),0===c&&this.userList.setAttribute("value",this.i18n.noUsers))}))},handleGetAccountUsers:function(a,c){if(a&&a.users&&a.total&&0<a.total){null===this.userStore&&(this.userStore=
new b.store.Memory({idProperty:"name",data:[]}),this.userList.set("store",this.userStore));for(var d=0;d<a.users.length;d++){var e=a.users[d].username,g=a.users[d].fullName+" ("+e+")";this.currentUser!==e&&this.userStore.put({name:g,username:e})}1===a.total&&this.userList.setAttribute("value",this.i18n.noUsers);-1<a.nextStart&&(d={start:a.nextStart,num:this.maxUsers},this.adminOnly&&(d.adminOnly=this.adminOnly),this.account.getAccountUsers(this.accountId,d,b.hitch(this,this.handleGetAccountUsers)))}},
loadConnections:function(){b.query(".jevent").connect("onclick",function(a){a.preventDefault()});b.query("#button_select-account-user-close").connect("onclick",function(){c.byId("select-account-user-dialog").hide()});b.query("#button_select-account-user-submit").connect("onclick",b.hitch(this,"submitRequest"))},onUserSelect:function(a){if((a=this.userStore.query({name:a}))&&0<a.length)this.selectedUser=a[0].username;this.selectedUser&&0<this.selectedUser.length&&c.byId("button_select-account-user-submit").set("disabled",
!1)},clear:function(){this.userStore=this.selectedUser=null;c.byId("button_select-account-user-submit").set("disabled",!0)},submitRequest:function(a){null!==this.selectedUser&&(this.handler(this.selectedUser),c.byId("select-account-user-dialog").hide())},hide:function(){c.byId("select-account-user-dialog").hide()}})});