// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/dialog/ShareOwnershipDlg","dojo/_base/declare dojo/on dojo/dom-attr dojo/query dojo/dom dojo/dom-style dojo/_base/lang dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/dom-construct dojo/string dojo/_base/window dojo/promise/all dojo/when dojo/Deferred dojo/_base/array dojo/cookie dojo/dom-class dojo/json dijit/registry dijit/form/Select dojox/form/TriStateCheckBox ./ConfirmDialog dijit/focus dojo/_base/event dojo/keys dgrid/OnDemandGrid dgrid/Selection dgrid/editor dojo/store/Memory dojo/store/Observable ./_CreateItemUtilMixin dojo/topic esri/Evented esri/arcgis/Portal ../../geow/Account ../../geow/Content ../../util dojo/i18n!arcgisonline/nls/arcgisonline".split(" "),
function(l,E,F,e,G,H,c,q,r,s,I,J,K,m,L,f,g,M,N,O,P,Q,t,u,k,R,S,v,w,x,y,z,T,h,A,B,C,n,D,p){return l("arcgisonline.sharing.dijit.dialog.ShareOwnershipDlg",[q,r,s,A],{baseClass:"esriSharedOwnershipDlg",templateString:'\x3cdiv data-dojo-attach-point\x3d"contentNode"\x3e\x3cp data-dojo-attach-point\x3d"_message"\x3e${i18n.sharingDlg.sharedOwnershipMsg}\x3c/p\x3e\x3cdiv class\x3d"main"\x3e\x3cdiv id\x3d"${id}-groups" class\x3d"dgrid-autoheight" data-dojo-attach-point\x3d"_groups" \x3e\x3c/div\x3e\x3c/div\x3e\x3cp data-dojo-attach-point\x3d"_footerMessage"\x3e${i18n.sharingDlg.settingsMsg}\x3c/p\x3e',
onDone:function(){},postMixInProperties:function(){this.inherited(arguments);this.i18n=c.mixin({},p)},postCreate:function(){this.inherited(arguments);C.getSelf(c.hitch(this,function(a){this._loadConnections();this._portal=new B.Portal({url:esriGeowConfig.restBaseUrl,self:a});this._connect=this._portal.on("load",c.hitch(this,function(){this._connect.remove();this._portalUser=this._portal.getPortalUser();this.set("disabled",!0,this.i18n.sharingDlg.fetchingGroups);return this._loadData().then(c.hitch(this,
function(a){this._createGrid(a);this.set("disabled",!1)}),c.hitch(this,function(a){console.log("no shared ownership groups")}))}))}))},destroy:function(){e(".dijit",this.contentNode).map(dijit.byNode).forEach(function(a){a.destroyRecursive?a.destroyRecursive():a.destroy&&a.destroy()});this._groups.destroy();this._groupsStore=this._groups=null;this._errorDlg&&(this._errorDlg.destroyRecursive(),this._errorDlg=null);this.inherited(arguments);this._portalUser=this._portal=null},_createGrid:function(a){a=
[x({field:"visible",autoSave:!0},t),{field:"title"}];this._groups=new (l([v,w]))({selectionMode:"none",store:this._groupsStore,showHeader:!1,columns:a},this._groups);this._groups.startup();this._groups.on(".dgrid-cell.field-visible:click",c.hitch(this,function(a){a=this._groups.cell(a).element.widget;"mixed"===(a&&a.get("checked")||!1)&&a.set("checked",!0)}))},_loadConnections:function(){this.own(h.subscribe("dlg/onOk",c.hitch(this,function(){this._focusNode&&setTimeout(c.hitch(this,function(){k.focus(this._focusNode)}),
250)})),h.subscribe("/esri/disable",c.hitch(this,function(a,b){this.set("disabled",a,b,!0)})))},_loadData:function(){var a=new f,b=g.map(this.items||[],c.hitch(this,function(a){return this._getGroupsItemSharedWith(a)}));this._sharedOwnershipGroups=this._getSharedOwnershipGroups(this.groups);this._groupsStore=new z(new y({idProperty:"id",data:this._sharedOwnershipGroups}));m(b).then(c.hitch(this,function(b){a[this._sharedOwnershipGroups&&this._sharedOwnershipGroups.length?"resolve":"reject"](this._sharedOwnershipGroups)}));
return a},_setValueAttr:function(a){this.items=c.clone(a.items);this.groups=c.clone(a.groups)},_getValueAttr:function(){return{selected:this._groupsStore.query({visible:"on"}).map(function(a){return a.id}),unselected:this._groupsStore.query({visible:!1}).map(function(a){return a.id})}},_setFocusAttr:function(a){a=e(a,this.domNode);k.focus(a&&a.length?a[0]:this._title.domNode)},_setDisabledAttr:function(a,b,d){this.set("readOnly",a,b,d)},_setReadOnlyAttr:function(a,b,d){e(".dijit",this.domNode).map(dijit.byNode).forEach(function(b){b.set("disabled",
a)});e("a",this.domNode)[a?"addClass":"removeClass"]("disabledLink");e("label, p, span",this.domNode)[a?"addClass":"removeClass"]("disabled");d||(a&&b&&h.publish("/dlg/busyMessage",b),h.publish("/esri/disable",a,b))},shareWithSelectedGroup:function(){var a=new f,b=g.map(this.items||[],"return item.id;").join(","),d=this.items&&this.items.length?this.items[0].owner:null,e={owner:d,items:b,groups:this.get("value").selected.join(","),confirmItemControl:!0},b={owner:d,items:b,groups:this.get("value").unselected.join(",")};
this.set("disabled",!0,this.i18n.sharingDlg.sharingItems);m([this._shareItems(e),this._unshareItems(b)]).then(c.hitch(this,function(){this.set("disabled",!1);a.resolve()}),c.hitch(this,function(b){this.set("disabled",!1);a.reject(b)}));return a},_shareItems:function(a){var b=new f;a.groups&&a.groups.length?n.shareItems(a,c.hitch(this,function(a){this.set("disabled",!1);b.resolve(a)}),c.hitch(this,function(a){b.reject(a)})):b.resolve([]);return b},_unshareItems:function(a){var b=new f;a.groups&&a.groups.length?
n.unshareItems(a,c.hitch(this,function(a){this.set("disabled",!1);b.resolve(a)}),c.hitch(this,function(a){b.reject(a)})):b.resolve([]);return b},_getGroupsItemSharedWith:function(a){a=this._portal.portalUrl+"content/items/"+a.id+"/groups";var b=this.items&&this.items.length||0,d,e=new f;D.request({url:a}).then(c.hitch(this,function(a){a=this._getSharedOwnershipGroups(a.admin).concat(this._getSharedOwnershipGroups(a.member)).concat(this._getSharedOwnershipGroups(a.other));g.forEach(a||[],c.hitch(this,
function(a){d=this._groupsStore.get(a.id);d.shareCount=d.shareCount?d.shareCount+1:1;d.visible=d.shareCount===b?"on":"mixed";this._groupsStore.put(d)}));e.resolve(a)}));return e},_getSharedOwnershipGroups:function(a){var b;return g.filter(a||[],c.hitch(this,function(a){b=a.capabilities&&a.capabilities.join(",")||"";return!1===a.isViewOnly&&-1<b.toLowerCase().indexOf("updateitemcontrol")}))},validate:function(){var a=new f,b;this._focusNode=null;b=this._checkRequired();b=b.then(c.hitch(this,function(b){a.resolve(b)}),
c.hitch(this,function(b){this._showError(b);a.reject(b)}));return a},_checkRequired:function(){var a=new f;a.resolve(!0);return a},_showError:function(a){a=c.mixin(c.mixin({},p.publishWizard.errors.error),a);this._errorDlg=new u({showCancel:!1,style:{width:"400px",height:"auto"}});this._errorDlg.show(a).then(c.hitch(this,function(){this.set("disabled",!1);this._errorDlg.hide();this._focusNode&&setTimeout(c.hitch(this,function(){k.focus(this._focusNode)}),250)}));return!1}})});