// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/dialog/UsageApp",["dijit","dojo","dojox","dojo/require!dijit/_WidgetBase,dijit/registry,dgrid/OnDemandGrid,dgrid/Keyboard,dgrid/extensions/ColumnResizer,dojo/store/Observable,dojo/store/Memory,arcgisonline/sharing/util,arcgisonline/sharing/geow/Account,arcgisonline/sharing/dijit/dialog/_UsageDlgMixin"],function(f,a,g){a.provide("arcgisonline.sharing.dijit.dialog.UsageApp");a.require("dijit._WidgetBase");a.require("dijit.registry");a.require("dgrid.OnDemandGrid");
a.require("dgrid.Keyboard");a.require("dgrid.extensions.ColumnResizer");a.require("dojo.store.Observable");a.require("dojo.store.Memory");a.require("arcgisonline.sharing.util");a.require("arcgisonline.sharing.geow.Account");a.require("arcgisonline.sharing.dijit.dialog._UsageDlgMixin");a.declare("arcgisonline.sharing.dijit.dialog.UsageApp",[f._WidgetBase,arcgisonline.sharing.dijit.dialog._UsageDlgMixin],{baseClass:"esriUsageApp",_util:arcgisonline.sharing.util,_acct:arcgisonline.sharing.geow.Account,
postMixInProperties:function(){this.inherited(arguments);this._util=arcgisonline.sharing.util;this.i18n=a.mixin({},a.i18n.getLocalization("arcgisonline","arcgisonline").common);this.i18n=a.mixin(this.i18n,a.i18n.getLocalization("arcgisonline","arcgisonline").organizationStatus);this.i18n=a.mixin(this.i18n,a.i18n.getLocalization("arcgisonline","arcgisonline").usageDlg);this._svcUrl=esriGeowConfig.restBaseUrl+(esriGeowConfig.restBaseUrl.lastIndexOf("/")===esriGeowConfig.restBaseUrl.length-1?"":"/");
this._accountsUri=this._svcUrl+"portals/";this._errorDlg=arcgisonline.sharing.dijit.dialog.GeneralDlg.prototype.statics.getInstance();this._type="credits";this.isAdmin=esriGeowConfig.userRole&&esriGeowConfig.userRole.isAdmin();this._creditStore=new a.store.Observable(new a.store.Memory({data:{identifier:"id",items:[{id:"stg_tiles",unit:"gbyte",label:this.i18n.stg_tiles},{id:"stg_features",unit:"gbyte",label:this.i18n.stg_features},{id:"stg_portal",unit:"mbyte",label:this.i18n.stg_portal},{id:"svcusg_portal",
unit:"mbyte",label:this.i18n.svcusg_portal},{id:"svcusg_tiles",unit:"gbyte",label:this.i18n.svcusg_tiles},{id:"svcusg_features",unit:"gbyte",label:this.i18n.svcusg_features},{id:"tilegencnt_tiles",unit:"tiles",label:this.i18n.tilegencnt_tiles},{id:"loading_tiles",unit:"tiles",label:this.i18n.loading_tiles},{id:"svcusg_navrproute",unit:"routes",label:this.i18n.rtmultivehicle},{id:"svcusg_natsproute",unit:"routes",label:this.i18n.rtoptimized},{id:"svcusg_nasimpleroute",unit:"routes",label:this.i18n.rtsimple},
{id:"svcusg_nacfroute",unit:"routes",label:this.i18n.rtclosestfacility},{id:"svcusg_naservicearea",unit:"routes",label:this.i18n.rtsvcareas},{id:"geocodecnt_geocode",unit:"locations",label:this.i18n.geocodecnt_geocode},{id:"svcusg_demogmaps",unit:"locations",label:this.i18n.svcusg_demogmaps},{id:"svcusg_geotrigger",unit:"locations",label:this.i18n.svcusg_geotrigger}]}}))},destroy:function(){this._orgsArr=this._orgs=null;this._customerSelect.destroy();this._selectType.destroy();this._selectDate.destroy();
this._customStart.destroy();this._customEnd.destroy();this._showBtn.destroy();this._grid.destroy();this._errorDlg.destroyRecursive();this._selectDate=this._customStart=this._customEnd=this._showBtn=this._grid=void 0;this.inherited(arguments)},buildRendering:function(){var b=document.createDocumentFragment(),c;a.create("div",{"class":"title",innerHTML:this.i18n.usageAppTitle},b);c=a.create("div",{"class":"selects"},b);a.create("label",{innerHTML:this.i18n.showLbl},c);this._selectType=new f.form.Select({style:"width:100px;",
options:[]},a.create("span",{},c));a.create("label",{"class":"customer",style:"display:none;",innerHTML:this.i18n.customerLbl},c);this._customerSelect=new f.form.Select({"class":"customer",style:"width:120px;display:none;",options:[]},a.create("span",{},c));a.create("label",{style:"text-transform:lowercase;","for":"selectDateRange",innerHTML:this.i18n.forLbl},c);this._selectDate=new f.form.Select({style:"width:120px;",options:[]},a.create("span",{},c));this._spinnerNode=a.create("span",{"class":"pleaseWaitImg"},
c);c=a.create("div",{"class":"customDate",style:{display:"none"}},b);a.create("label",{"for":"customStart",innerHTML:this.i18n.customStart},c);this._customStart=new f.form.DateTextBox({style:{width:"120px"},"class":"date"},a.create("span",{},c));a.create("label",{"for":"customEnd",innerHTML:this.i18n.customEnd},c);this._customEnd=new f.form.DateTextBox({style:{width:"120px"},"class":"date"},a.create("span",{},c));this._showBtn=new f.form.Button({type:"button",label:this.i18n.showReport},a.create("span",
{},c));a.create("div",{id:"grid","class":"grid"},b);c=a.create("div",{"class":"total esriFloatTrailing"},b);this._totalCredits=a.create("label",{innerHTML:esri.substitute({total:0},this.i18n.total)},c);this.inherited(arguments);this.domNode.appendChild(b)},postCreate:function(){this.inherited(arguments);this.connect(this._selectDate,"onChange",a.hitch(this,"onDateRangeChange"));this.connect(this._selectType,"onChange",a.hitch(this,"onTypeChange"));this.connect(this._showBtn,"onClick",a.hitch(this,
"onCustomDateClick"));this.connect(this._customerSelect,"onChange",a.hitch(this,"onCustomerChange"));this._roleCanManageMarketplace=(this._isCustomRole=esriGeowConfig.userRole&&esriGeowConfig.userRole.isCustom())&&esriGeowConfig.userRole.canManageMarketplace();this._loadData()},onDateRangeChange:function(b){"custom"!==b?(this._dateQuery=this._getDateQuery(b),this["users"===this._type?"_queryUsers":"_queryDetails"](this._dateQuery)):(this._customStart.set("value",new Date(this._dateQuery.startTime)),
this._customEnd.set("value",new Date(this._dateQuery.endTime)));a.query(".customDate").style("display","custom"===b?"inline-block":"none")},onTypeChange:function(b){a.query(".customer",this.domNode).style("display","users"===b&&this.isAdmin&&this.listed?"":"none");this._type=b;this["users"===b?"_queryUsers":"_queryDetails"](this._dateQuery)},onCustomerChange:function(a){this["users"===this._type?"_queryUsers":"_queryDetails"](this._dateQuery)},onCustomDateClick:function(){var a=new Date(this._customStart.get("value")),
c=new Date(this._customEnd.get("value")),d=Math.round(Number((c-a)/864E5+1));this._dateQuery={startTime:a.getTime(),endTime:(new Date(c.getFullYear(),c.getMonth(),c.getDate()+1,0,0,0,-1)).getTime(),period:d+(1>=d?"h":"d")};if(this._dateQuery.startTime>this._dateQuery.endTime)this._showError({message:this.i18n.invalidDateRange});else if(this._dateQuery.endTime<this._dateQuery.startTime)this._showError({message:this.i18n.invalidDateRange});else this["users"===this._type?"_queryUsers":"_queryDetails"](this._dateQuery)},
_createGrid:function(b){this._grid&&(this._grid.destroy(),this._grid=void 0);var c=a.declare([dgrid.OnDemandGrid,dgrid.extensions.ColumnResizer]),d={label:{label:this.i18n.creditName},num_total:{label:this.i18n.units,renderCell:a.hitch(this,"_formatUnits")},credits_total:{label:this.i18n.credits,formatter:a.hitch(this,"_formatCredits","esriFloatTrailing",2)}},e={customer:{label:this.i18n.organization},num_logins:{label:this.i18n.users,formatter:a.hitch(this,"_formatCredits","esriFloatLeading",0)}};
this._grid=new c({columns:"users"===this._type?e:d,sort:"users"===this._type?"num_logins":"credits_total",store:b,query:function(a){return-1<a.credits_total||-1<a.num_logins}},a.create("div",{},"grid"))},_setDisabledAttr:function(b){a.forEach(f.registry.findWidgets(this.domNode),function(a){a.set("disabled",b)});a.query(".dijitSelect",this.domNode).forEach(function(c){a[b?"addClass":"removeClass"](c,"dijitTextBoxDisabled")});a.style(this._spinnerNode,"display",!0===b?"inline-block":"none")},_formatCredits:function(a,
c,d){return'\x3cspan class\x3d"'+a+'"\x3e'+Number(d).toFixed(esri._isDefined(c)?c:2)+"\x3c/\x3e"},_formatUnits:function(b,c,d){var e=b.unit;e&&(c=b[(-1!==e.indexOf("byte")?"stg":"num")+"_total"],-1!==e.indexOf("byte")&&(c=this._formatBytes(e,c)),a.attr(d,"innerHTML",esri.substitute({units:c},this.i18n[e])))},_loadData:function(){this._fetchSelf().then(a.hitch(this,function(){this._queryTypeOptions=[{label:this.i18n.credits,value:"credits"}];this._queryTypeOptions.push({label:this.i18n.users,value:"users"});
this._usageUrl=this._accountsUri+this._organization.id+"/usage";this._prepareStores();this._prepareDateQueries(this._organization.created);this._loadCustomerSelect();this._customEnd.constraints.max=new Date;this._customEnd.constraints.min=this._startQueryDate;this._customStart.constraints.max=new Date;this._customStart.constraints.min=this._startQueryDate;this._selectDate.set("options",this._dateQueriesStore.data);this._selectType.set("options",this._queryTypeOptions);this._selectType.set("value",
"credits");this._creditFilters=a.map(this._creditFilterOptions,"return item.value");this._prepareDateQueries(this._organization.created);this._dateQuery=this._getDateQuery("last24hours");a.query(".title",this.domNode).attr("innerHTML",this.i18n.usageAppUserTitle);this.isAdmin&&this.listed&&(a.query(".customer",this.domNode).style("display",""),this._selectType.set("value","users"));this._selectDate.set("value","last24Hours")}))},_loadCustomerSelect:function(){if(this.listed&&this.isAdmin)return a.when(this._orgs||
this._fetchCustomers()).then(a.hitch(this,function(a){this._customerSelect.set("options",this._orgsArr);this._customerSelect.set("value",this._orgsArr[0].value,!1)}))},_queryDetails:function(b){var c=b.period;this._customerSelect.get("value");c={appId:this.appId,vars:"credits,num,bw",period:c,groupBy:"etype,stype"};this.set("disabled",!0);this._resetStore();return this._fetchCredits(b,c).then(a.hitch(this,function(b){a.attr(this._totalCredits,"innerHTML",esri.substitute({total:a.number.format(Number(b.creditSum||
0),{places:2})},this.i18n.total));this._createGrid(this._creditStore);this._grid.sort("credits_total","desc");return b}))},_queryUsers:function(b){var c=b.period,d=this._customerSelect.get("value"),c={appId:this.appId,vars:"num",period:c,stype:"apploginprovider",etype:"svcusg"};-1!==d&&(c.userorgid=d);this.set("disabled",!0);return this._fetchAppLogins(b,c).then(a.hitch(this,function(b){a.attr(this._totalCredits,"innerHTML","");this._createGrid(new a.store.Memory({data:b}))}))},_resetStore:function(){this._creditStore.query({}).forEach(a.hitch(this,
function(b){a.mixin(b,{credits_total:-1});this._creditStore.put(b)}))},_sumCredits:function(b,c){a.forEach(c,a.hitch(this,function(c){b[c]&&(b[c]=a.map(b[c],"return dojo.number.round(Number(item[1] || 0), 2);"),b[c+"_total"]=a.number.round(g.lang.functional.reduce(b[c],"+")||0,2))}));var d=this._creditStore.get(b.id);this._creditStore.put(a.mixin(d,b));return b},_fetchCredits:function(b,c){var d=a.mixin(a.mixin({},b),c),e;return this._request(this._usageUrl,d).then(a.hitch(this,function(b){b.data=
a.filter(b.data,function(a){return"apploginprovider"!==a.stype&&"applogin"!==a.stype});b.creditSum=0;a.forEach(b.data,a.hitch(this,function(a){a.id=a.etype+"_"+a.stype;if(e=this._sumCredits(a,["stg","num","credits"]))b.creditSum+=e.credits_total}));return b}))},_fetchAppLogins:function(b,c){var d=a.mixin(a.mixin({},b),c),e;return this._request(this._usageUrl,d).then(a.hitch(this,function(a){e=a&&a.data&&a.data[0]||{userOrgId:c.userorgid};return[{orgId:e.userOrgId,num_logins:a.data.length,customer:c.userorgid?
this._orgs[e.userOrgId]&&this._orgs[e.userOrgId].label||e.userOrgId:this.i18n.allCustomers}]}))},_fetchSelf:function(){var b=new a.Deferred;this._acct.getSelf(a.hitch(this,function(a){this._organization=a;b.resolve(a)}),a.hitch(this,function(a){b.reject(a)}));return b},_fetchCustomers:function(){var b=esriGeowConfig.restBaseUrl+"portals/self/customers";this._orgsArr=[];this._orgs={};return this._request(b,{status:"active"}).then(a.hitch(this,function(b){b=b.trials.concat(b.purchases);a.forEach(b,
a.hitch(this,function(a){!this._orgs[a.customer.id]&&a.provision.provisionedItemId===this.itemId&&(this._orgs[a.customer.id]={value:a.customer.id,label:a.customer.name},this._orgsArr.push(this._orgs[a.customer.id]))}));this._orgsArr.push(this._orgs[esriGeowConfig.userInfo.orgId]={value:esriGeowConfig.userInfo.orgId,label:esriGeowConfig.self.name});this._orgsArr.sort(function(a,b){return a.label<b.label?-1:a.label>b.label?1:0});this._orgsArr.unshift({value:-1,label:this.i18n.allCustomers});return this._orgsArr}))},
_request:function(b,c){var d=a.mixin(c||{},this._requestParams);return this._util.request({url:b,content:d}).then(a.hitch(this,function(a){this.set("disabled",!1);return a.error?this._showError(a.error):a}),a.hitch(this,function(a){this._showError(a);this.set("disabled",!1);throw Error();}))},_showError:function(b){b=b.error||b||{};b=a.mixin({},{message:b.message,code:b.code||0});b=a.mixin(a.mixin({},this.i18n.errors.error),b);this._errorDlg.show(b)},_toLink:function(a){return"\x3ca onclick\x3d'return false;' href\x3d'#'\x3e"+
a+"\x3c/a\x3e"}})});