// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/sharing/dijit/dialog/UsageDlg",["dijit","dojo","dojox","dojo/i18n!arcgisonline/nls/arcgisonline","dojo/require!dijit/_Widget,dijit/_Templated,dijit/form/Select,dijit/form/Button,dojox/validate/regexp,dojo/i18n,dijit/form/DateTextBox,arcgisonline/sharing/util,arcgisonline/sharing/geow/Account,arcgisonline/sharing/dijit/dialog/_UsageDlgMixin"],function(e,a,g){a.provide("arcgisonline.sharing.dijit.dialog.UsageDlg");a.require("dijit._Widget");a.require("dijit._Templated");a.require("dijit.form.Select");
a.require("dijit.form.Button");a.require("dojox.validate.regexp");a.require("dojo.i18n");a.require("dijit.form.DateTextBox");a.requireLocalization("arcgisonline","arcgisonline");a.require("arcgisonline.sharing.util");a.require("arcgisonline.sharing.geow.Account");a.require("arcgisonline.sharing.dijit.dialog._UsageDlgMixin");a.declare("arcgisonline.sharing.dijit.dialog.UsageDlg",[e._Widget,e._Templated,arcgisonline.sharing.dijit.dialog._UsageDlgMixin],{templateString:a.cache("arcgisonline.sharing.dijit.dialog",
"templates/UsageDlg.html",'\x3cdiv dojoAttachPoint\x3d"formNode" class\x3d"esriItemLinks"\x3e\r\n  \x3cdiv class\x3d"selects"\x3e\r\n    \x3clabel for\x3d"selectCredit" class\x3d""\x3e${i18n.showLbl}\x3c/label\x3e\r\n    \x3cspan dojoAttachPoint\x3d\'_selectCredit\'\x3e\x3c/span\x3e\r\n    \x3clabel class\x3d"customer" style\x3d"display:none;" for\x3d"selectCustomer" class\x3d""\x3e\x26nbsp;${i18n.customerLbl}\x26nbsp;\x3c/label\x3e\r\n    \x3cspan class\x3d"customer" dojoAttachPoint\x3d\'_selectCustomer\'\x3e\x3c/span\x3e\r\n    \x3clabel style\x3d"text-transform: lowercase;" for\x3d"selectDateRange"\x3e\x26nbsp;${i18n.forLbl}\x26nbsp;\x3c/label\x3e\r\n    \x3cspan dojoAttachPoint\x3d\'_selectDate\'\x3e\x3c/span\x3e\r\n    \x3cdiv class\x3d\'customdate\'\x3e\r\n      \x3clabel for\x3d"customStart"\x3e${i18n.customStart}\x3c/label\x3e\r\n      \x3cspan class\x3d"date" style\x3d"width:120px;" dojoType\x3d"dijit.form.DateTextBox" dojoAttachPoint\x3d\'_customStart\'\x3e\x3c/span\x3e\r\n      \x3clabel for\x3d"customEnd"\x3e${i18n.customEnd}\x3c/label\x3e\r\n      \x3cspan class\x3d"date" style\x3d"width:120px;" dojoType\x3d"dijit.form.DateTextBox" dojoAttachPoint\x3d\'_customEnd\'\x3e\x3c/span\x3e\r\n      \x3cbutton dojoAttachPoint\x3d\'_customDate\' class\x3d"primary" dojoType\x3d"dijit.form.Button" type\x3d"button"\x3e${i18n.showReport}\x3c/button\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"lineChart"\x3e\r\n    \x3cdiv dir\x3d"ltr" dojoAttachPoint\x3d"_lineChart"\x3e\x3c/div\x3e\r\n    \x3cdiv dojoAttachPoint\x3d"_lineLegend"\x3e\x3c/div\x3e\r\n    \x3cdiv dojoAttachPoint\x3d"_noData" class\x3d"nodata"\x3e${i18n.nodata}\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n'),
baseClass:"esriAGOUsageForm",widgetsInTemplate:!0,_requestParams:{f:"json"},_util:arcgisonline.sharing.util,_acct:arcgisonline.sharing.geow.Account,constructor:function(d){a.mixin(this,d||{})},postMixInProperties:function(){this.inherited(arguments);this.i18n=a.mixin({},a.i18n.getLocalization("arcgisonline","arcgisonline").common);this.i18n=a.mixin(this.i18n,a.i18n.getLocalization("arcgisonline","arcgisonline").organizationStatus);this.i18n.viewstooltip=this.i18n.views;this.i18n=a.mixin(this.i18n,
a.i18n.getLocalization("arcgisonline","arcgisonline").usageDlg);this._user=this._util.getUser();this.isAdmin=esriGeowConfig.userRole&&esriGeowConfig.userRole.isAdmin();this._roleCanManageMarketplace=(this._isCustomRole=esriGeowConfig.userRole&&esriGeowConfig.userRole.isCustom())&&esriGeowConfig.userRole.canManageMarketplace()},startup:function(){this.inherited(arguments);this._errorDlg=arcgisonline.sharing.dijit.dialog.GeneralDlg.prototype.statics.getInstance();this._svcUrl=esriGeowConfig.restBaseUrl+
(esriGeowConfig.restBaseUrl.lastIndexOf("/")===esriGeowConfig.restBaseUrl.length-1?"":"/");this._accountsUri=this._svcUrl+"portals/";this._type="views"===this.stype?"views":null;this._prepareStores();this._fetchSelf()},destroy:function(){a.forEach(this._connects,a.disconnect);this._selectDate.destroy();this._selectCredit.destroy();this._lineChart.destroy();this._selectDate=this._selectCredit=this._lineChart=void 0},onDateRangeChange:function(d){"custom"!==d?(this._dateQuery=this._getDateQuery(d),
this["users"===this._type?"_queryUsers":"_queryDetails"](this._dateQuery)):(this._customStart.set("value",new Date(this._dateQuery.startTime+6E4*(new Date).getTimezoneOffset())),this._customEnd.set("value",new Date(this._dateQuery.endTime+6E4*(new Date).getTimezoneOffset()-1)));a.query(".customdate").style("display","custom"===d?"inline-block":"none")},onFilterChange:function(d){this._type=d;a.query(".customer",this.domNode).style("display","users"===d?"":"none");this["users"===this._type?"_queryUsers":
"_queryDetails"](this._dateQuery)},onCustomerChange:function(a){this["users"===this._type?"_queryUsers":"_queryDetails"](this._dateQuery)},onCustomDateClick:function(a){var c=new Date(this._customStart.get("value")),b=new Date(this._customEnd.get("value")),c=Date.UTC(c.getFullYear(),c.getMonth(),c.getDate()),b=Date.UTC(b.getFullYear(),b.getMonth(),b.getDate()),b=b+864E5;5184E6<b-c&&(a&&"s"===a?(b=c+5184E6,this._customEnd.set("value",new Date(b),!0)):a&&"e"===a&&(c=b-5184E6,this._customStart.set("value",
new Date(c),!0)));this._dateQuery={startTime:c,endTime:b,period:"1d"};if(this._dateQuery.startTime>this._dateQuery.endTime)this._showError({message:this.i18n.invalidDateRange});else if(this._dateQuery.endTime<this._dateQuery.startTime)this._showError({message:this.i18n.invalidDateRange});else this["users"===this._type?"_queryUsers":"_queryDetails"](this._dateQuery)},_buildDlg:function(){this._usageUrl=this._accountsUri+this._organization.id+"/usage";this._prepareDateQueries(this._organization.created);
this._selectDate=new e.form.Select({style:"width:150px;",options:this._dateQueriesStore.data},this._selectDate);this.listed&&this._creditFilterOptions.push({label:this.i18n.users,value:"users"});this._selectCredit=new e.form.Select({style:"width:110px;",options:this._creditFilterOptions},this._selectCredit);this._creditFilters=a.map(this._creditFilterOptions,"return item.value");this._selectCredit.removeOption("stg");if(this.listed&&(this.isAdmin||this._isCustomRole&&this._roleCanManageMarketplace))this._customerSelect=
new e.form.Select({"class":"customer",style:"width:120px;display:none;",options:[]},this._selectCustomer),this._loadCustomerSelect();this._prepareDateQueries(this._organization.created);this._dateQuery=this._getDateQuery("last24hours");this.onDateRangeChange("last24hours");this._customEnd.constraints.max=new Date;this._customStart.constraints.max=new Date;this._connects=[a.connect(this._selectDate,"onChange",a.hitch(this,"onDateRangeChange")),a.connect(this._selectCredit,"onChange",a.hitch(this,"onFilterChange")),
a.connect(this._customDate,"onClick",a.hitch(this,"onCustomDateClick")),a.connect(this._customStart,"onChange",a.hitch(this,this.onCustomDateClick,"s")),a.connect(this._customEnd,"onChange",a.hitch(this,this.onCustomDateClick,"e")),a.connect(this._customerSelect,"onChange",a.hitch(this,"onCustomerChange"))];this._selectCredit.set("value",this.listed&&(this.isAdmin||this._isCustomRole&&this._roleCanManageMarketplace)?"users":"credits")},_fetchSelf:function(){this._acct.getSelf(a.hitch(this,function(a){this._organization=
a;this._buildDlg()}),a.hitch(this,function(a){throw a;}))},_loadCustomerSelect:function(){return a.when(this._orgs||this._fetchCustomers()).then(a.hitch(this,function(a){this._customerSelect.set("options",this._orgsArr);this._customerSelect.set("value",this._orgsArr[0].value,!1)}))},_queryDetails:function(d){var c=-1<d.period.indexOf("d")?"1d":"1h",c={views:{groupBy:"name",name:this.itemId,vars:"num",period:c},others:{groupBy:"etype,stype",name:this.name,vars:this._creditFilters.join(","),etype:"svcusg",
stype:this.stype||"",period:c}};return this._fetchCredits(d,"views"===this._type?c.views:c.others).then(a.hitch(this,function(b){this._creditDetails=a.mixin({},b&&b.length?b[0]:{});b&&b.length?(esri.hide(this._noData),this._item=b[0],this._createUsageChart(b,this._selectCredit.get("value"),this._dateQuery,this._lineChart)):(this._clearUsageChart(),esri.show(this._noData));return!0}))},_queryUsers:function(d){var c=d.period,b=this._customerSelect.get("value"),c={groupBy:"username",name:this.name,vars:this._creditFilters.join(","),
etype:"svcusg",stype:this.stype||"",period:c};-1!==b&&(c.userorgid=b);return this._fetchUniqueUsers(d,c).then(a.hitch(this,function(b){var c=b&&b.length?a.clone(b[0]):{};c?(1<b.length&&(c.users=a.map(c.users||[],function(a){return[a[0],"0"]}),a.forEach(b,a.hitch(this,function(b){a.forEach(b.users,a.hitch(this,function(a,b){c.users[b][1]=Number(c.users[b][1])+Number(a[1])}))}))),this._creditDetails=a.mixin({},c),esri.hide(this._noData),this._item=c,this._createUsageChart(b,this._selectCredit.get("value"),
this._dateQuery,this._lineChart)):esri.show(this._noData);return!0}))},_updateLineChart:function(a,c,b){b?esri.hide(this._noData):esri.show(this._noData);this._updateLineChartY(a,b);this._updateLineChartX(a,b);a.render();c&&c.refresh()},_updateLineChartY:function(a,c){var b=c?this._getYAxis(c.id,this._selectCredit.get("value")):{};a.addAxis("y",{min:b.min||0,max:b.max||1,vertical:!0});c&&(a.getSeries(c.id)?a.updateSeries(c.id,b.data||[]):a.addSeries(this.title||c.id,b.data||[]))},_updateLineChartX:function(a){var c=
this._getXAxis(this._dateQuery);a.addAxis("x",{min:c.min,max:c.max,labels:c.data||[]})},_fetchUniqueUsers:function(d,c){var b=a.mixin(a.mixin({},d),c),f="anon"===c.userorgid;f&&delete b.userorgid;return this._request(this._usageUrl,b).then(a.hitch(this,function(b){a.forEach(b.data||[],a.hitch(this,function(b){if(!f||f&&!b.username)b.users=a.map(b.num,a.hitch(this,function(a){return[a[0],0<a[1]?"1":"0"]}))}));return b&&b.data||[]}))},_fetchCredits:function(d,c){var b=a.mixin(a.mixin({},d),c);return this._request(this._usageUrl,
b).then(a.hitch(this,function(a){return a&&a.data||[]}))},_fetchCustomers:function(){var d=esriGeowConfig.restBaseUrl+"portals/self/customers";this._orgsArr=[];this._orgs={};return this._request(d,{status:"active"}).then(a.hitch(this,function(c){c=c.trials.concat(c.purchases);a.forEach(c,a.hitch(this,function(a){!this._orgs[a.customer.id]&&a.provision.provisionedItemId===this.itemId&&(this._orgs[a.customer.id]={value:a.customer.id,label:a.customer.name},this._orgsArr.push(this._orgs[a.customer.id]))}));
this._orgsArr.push(this._orgs[esriGeowConfig.userInfo.orgId]={value:esriGeowConfig.userInfo.orgId,label:esriGeowConfig.self.name});this._orgsArr.sort(function(a,c){return a.label<c.label?-1:a.label>c.label?1:0});this._orgsArr.unshift({value:"anon",label:this.i18n.anonymous});this._orgsArr.unshift({value:-1,label:this.i18n.allCustomers});return this._orgsArr}))},_request:function(d,c){var b=a.mixin(c||{},this._requestParams);return this._util.request({url:d,content:b}).then(a.hitch(this,function(a){return a.error?
this._showError(a.error):a}),a.hitch(this,function(a){this._showError(a);throw Error();}))},_showError:function(d){d=d.error||d||{};d=a.mixin({},{message:d.message,code:d.code||0});d=a.mixin(a.mixin({},this.i18n.errors.error),d);this._errorDlg.show(d)}})});