// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
require({cache:{"url:webSceneViewer/widgets/LayerWidget/templates/LayerItem.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"LayerItem" data-dojo-attach-point\x3d"LayerItem"\x3e\r\n    \x3clabel\x3e\r\n      \x3cinput data-dojo-attach-point\x3d"layerVisInputCheckbox"\x3e\r\n      \x3cspan data-dojo-attach-point\x3d"titleNode" class\x3d"layerItemSpan"\x3e\x3c/span\x3e\r\n    \x3c/label\x3e\r\n    \x3cbutton class\x3d"icon_frame right inactive" data-dojo-attach-point\x3d"layerFrameButton" data-dojo-attach-event\x3d"click:_layerFrameButtonClick" title\x3d"Frame layer" \x3e\x3c/button\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"statDomNode" class\x3d"status layerAdd"\x3e\r\n        \x3cdiv class\x3d"layerUpdatingPercentageContainer"\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"statDomNodeProgressbarUpper" class\x3d"progressbarUpper"\x3e \x3c/div\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"statDomNodeProgressbarLower" class\x3d"progressbarLower"\x3e \x3c/div\x3e\r\n        \x3c/div\x3e\r\n    \x3c/span\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("esri/core/declare dojo/dom-construct dojo/dom-class dojo/dom-style dojo/on dijit/_WidgetBase dijit/_TemplatedMixin dojo/text!./templates/LayerItem.html dijit/form/RadioButton dijit/form/CheckBox esri/layers/GroupLayer dojo/i18n!../nls/widgets".split(" "),function(l,f,e,d,c,m,n,p,q,r,g,h){var k=l([m,n],{name:"LayerItem",templateString:p,view:void 0,layer:void 0,_setLayerAttr:function(a){this._set("layer",a);a&&a instanceof g&&(this.isGroupLayer=!0,this.domNode&&e.add(this.domNode,"GroupLayerItem"))},
parentGroup:void 0,parentLayerItem:void 0,layerTitle:void 0,_setLayerTitleAttr:function(a){this._set("layerTitle",a);this.titleNode&&(this.titleNode.textContent=a,this.titleNode.title=a)},layerVisible:void 0,_setLayerVisibleAttr:function(a){this._set("layerVisible",a);this._layerVisDijitButton&&this._layerVisDijitButton.get("checked")!==a&&this._layerVisDijitButton.set("checked",a)},layerWidget:void 0,isGroupLayer:!1,_watchHandles:void 0,_onHandles:void 0,_layerItems:void 0,_previousProgressPercentage:-1,
_previousProgressVisible:null,constructor:function(a,b){this._watchHandles=[];this._onHandles=[];this._layerItems=[]},postMixInProperties:function(){},postCreate:function(){this.set("layerTitle",this.layer.title||this.layer.id);var a=this.layer.watch("title",function(a){this.set("layerTitle",this.layer.title)}.bind(this));this._watchHandles.push(a);this.set("layerVisible",this.layer.visible);a=this.layer.watch("visible",function(a){this.set("layerVisible",a)}.bind(this));this._watchHandles.push(a);
(void 0===this.parentGroup||"hide"===this.layer.listMode)&&e.add(this.domNode,this.layer.listMode);this._layerVisDijitButton=this.parentGroup&&"exclusive"===this.parentGroup.visibilityMode?new q({name:this.parentGroup.id+"_radiogroup_"+this.id,checked:this.layerVisible},this.layerVisInputCheckbox):new r({checked:this.layerVisible},this.layerVisInputCheckbox);a=c(this._layerVisDijitButton,"change",this._layerVisInputCheckboxChange.bind(this));this._onHandles.push(a);a=this.layer.watch("visibilityMode",
function(a){this.layerWidget.reload()}.bind(this));this._watchHandles.push(a);a=this.layer.watch("listMode",function(a){this.layerWidget.reload()}.bind(this));this._watchHandles.push(a);a=this.view.getLayerView(this.layer);if(null==a)c.once(this.layer,"layer-view-create",function(a){a.layerView.then(function(d){this.connectUpdating(d.layerView||a.layerView)}.bind(this))}.bind(this));else this.connectUpdating(a);this._init()},_addLayerItem:function(a,b){var d=new k({view:this.view,layer:a,layerWidget:this.layerWidget,
parentGroup:this.layer,parentLayerItem:this});d.placeAt(this.layersDomNode,b);this._layerItems.push(d)},_removeLayerItem:function(a){for(var b=this._layerItems.length-1;0<=b;b--)if(this._layerItems[b].layer===a){this._layerItems.splice(b,1);this._layerItems[b].destroy();break}},_init:function(){this.isGroupLayer&&"hide-children"!==this.layer.listMode&&this._initGroupLayerItems();var a=function(){e.remove(this.statDomNode,"layerAdd");this.layer.fullExtent&&e.remove(this.layerFrameButton,"inactive")}.bind(this);
if(this.layer.loaded||this.layer instanceof g)a();else c.once(this.layer,"load",function(b){a()});this.layerFrameButton.title=h.layerItemEditable.zoomToLayer},_initGroupLayerItems:function(){if(this.isGroupLayer){this.layersDomNode=f.create("div",{className:"layers"},this.domNode);f.create("div",{className:"layersLine"},this.layersDomNode);var a=c(this.layer,"layer-add",function(a){this.layerWidget.reload()}.bind(this)),b=c(this.layer,"layer-remove",function(a){this.layerWidget.reload()}.bind(this)),
d=c(this.layer,"layer-reorder",function(a){this.layerWidget.reload()}.bind(this));this._onHandles.push(a);this._onHandles.push(b);this._onHandles.push(d);for(a=this.layer.layers.get("length")-1;0<=a;a--)b=this.layer.layers.getItemAt(a),this._addLayerItem(b);0===this.layer.layers.get("length")&&(e.add(this.layersDomNode,"emptyPlaceholder"),this.layersDomNode.textContent=h.layerItemEditable.dragHere)}},destroy:function(){this._watchHandles.forEach(function(a){a.remove()});this._onHandles.forEach(function(a){a.remove()});
this._layerItems.forEach(function(a){a.destroy()});this._watchHandles.length=0;this._onHandles.length=0;this._layerItems.length=0;this._layerVisDijitButton.destroy();f.empty(this.domNode);f.destroy(this.domNode)},connectUpdating:function(a){if(null!=this.statDomNode){var b=function(){var b=a.get("updating"),c=a.get("updatingPercentage");null==c&&(c=100);b=b&&!a.suspended&&0<c;c===this._previousProgressPercentage&&b===this._previousProgressVisible||(b?(d.set(this.statDomNodeProgressbarUpper,"visibility",
"visible"),d.set(this.statDomNodeProgressbarLower,"visibility","visible"),d.set(this.statDomNodeProgressbarUpper,"height",100-c+"%"),d.set(this.statDomNodeProgressbarLower,"height",c+"%")):(d.set(this.statDomNodeProgressbarUpper,"visibility","hidden"),d.set(this.statDomNodeProgressbarLower,"visibility","hidden")),this._previousProgressVisible=b,this._previousProgressPercentage=c)}.bind(this),e=c(a,"suspend",function(){d.set(this.statDomNodeProgressbarUpper,"visibility","hidden");d.set(this.statDomNodeProgressbarLower,
"visibility","hidden")}.bind(this));this._onHandles.push(e);this._onHandles.push(c(a,"resume",b));b=a.watch(["updating","updatingPercentage"],b);this._watchHandles.push(b)}},_layerVisInputCheckboxChange:function(a){this.layer.get("visible")!==a&&this.layer.set("visible",a)},_layerFrameButtonClick:function(){this.layer.fullExtent&&this.view.animateTo(this.layer.fullExtent)}});return k});