// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/widgets/BasemapToggle/templates/BasemapToggle.html":'\x3cdiv class\x3d"${css.root}" role\x3d"presentation"\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"_containerNode" class\x3d"${css.container}"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"_toggleNode" title\x3d"${_i18n.toggle}" role\x3d"button" class\x3d"${css.toggleButton} ${css.interactive}" tabindex\x3d"0"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("../basemaps ./Widget dijit/_TemplatedMixin dijit/a11yclick ../core/declare dojo/_base/lang dojo/dom-class dojo/dom-construct dojo/on dojo/i18n!../nls/jsapi dojo/text!./BasemapToggle/templates/BasemapToggle.html".split(" "),function(d,f,g,h,k,l,c,e,m,n,p){return k([f,g],{declaredClass:"esri.widgets.BasemapToggle",templateString:p,options:{map:null,visible:!0,basemap:"hybrid",defaultBasemap:"topo",basemaps:d},constructor:function(a){a=l.mixin({},this.options,a);this._i18n=n.widgets.basemapToggle;
this.set(a);this.css={root:"esri-basemap-toggle",container:"esri-container",hidden:"esri-hidden",toggleButton:"esri-toggle",interactive:"esri-interactive",basemapImage:"esri-basemap-image",basemapImageContainer:"esri-basemap-container",basemapImageBG:"esri-basemap-bg",basemapTitle:"esri-basemap-title"}},postCreate:function(){this.inherited(arguments);this.own(m(this._toggleNode,h,this.toggle.bind(this)))},startup:function(){this.inherited(arguments);this.map?this.map.then(this._init.bind(this)):console.error(this.declaredClass+
"::map required")},toggle:function(){var a=this.map.get("basemap"),b,c;a&&this.set("defaultBasemap",a);a=this.get("defaultBasemap");b=this.get("basemap");c={previousBasemap:a,currentBasemap:b};a!==b&&(this.map.set("basemap",b),this.set("basemap",a),this._basemapChange(),this.emit("toggle",c))},_init:function(){this._visible();this._basemapChange();this.own(this.map.watch("basemap",this._basemapChange.bind(this)));this.set("loaded",!0);this.emit("load")},_setBasemapAttr:function(a){"string"===typeof a&&
(a=d[a]);this.basemap&&this.basemap.id!==a.id&&this._set("basemap",a)},_getBasemapInfo:function(a){a||(this.basemap=a=this.options.basemap);var b=this.get("basemaps");a="string"===typeof a?a:a.id;if(b&&b.hasOwnProperty(a))return b[a]},_updateImage:function(){var a=this._getBasemapInfo(this.get("basemap")),b;b=""+('\x3cdiv class\x3d"'+this.css.basemapImageContainer+'"\x3e');b+='\x3cdiv class\x3d"'+this.css.basemapImage+'"\x3e\x3cdiv class\x3d"'+this.css.basemapImageBG+'" style\x3d"background-image:url('+
a.thumbnailUrl+')" title\x3d"'+a.title+'"\x3e\x3c/div\x3e\x3c/div\x3e';b+='\x3cdiv title\x3d"'+a.title+'" class\x3d"'+this.css.basemapTitle+'"\x3e'+a.title+"\x3c/div\x3e";b+="\x3cdiv\x3e";e.empty(this._toggleNode);e.place(b,this._toggleNode,"only")},_basemapChange:function(){var a=this.map.get("basemap"),b;a&&this.set("defaultBasemap",a);a=this.get("defaultBasemap");b=this.get("basemap");this._updateImage();c.remove(this._toggleNode,a);c.add(this._toggleNode,b)},_visible:function(){c.toggle(this._containerNode,
this.css.hidden,!this.get("visible"))},_setVisibleAttr:function(a){this._set("visible",a);this._created&&this._visible()}})});