// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("../core/declare dojo/_base/lang dojo/_base/array dojo/dom-class dojo/dom-style dojo/dom-attr dojo/string dojo/on dojo/aspect dojo/has dojo/dom dojo/dom-construct dojo/mouse dojo/query dojo/parser dijit/registry dijit/TooltipDialog dijit/popup dojo/promise/all dojo/Deferred dgrid/Grid dgrid/extensions/Pagination dgrid/extensions/DijitRegistry dgrid/OnDemandGrid dgrid/Selection dgrid/Keyboard dgrid/util/touch put-selector/put dojo/store/Observable dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/form/Select ../portal/Portal ../core/PluginTarget dojo/i18n!../nls/jsapi ./_RefreshMixin dojo/NodeList-dom ../kernel ../core/lang".split(" "),
function(h,c,q,m,L,k,r,s,M,N,t,u,O,e,P,n,v,p,Q,w,x,y,z,R,A,S,T,B,C,D,E,F,G,g,H,I,J,U,l){var K=h(null,{idProperty:"id",constructor:function(a){h.safeMixin(this,a)},get:function(a,b){return g.PortalUtil.request(this.portalUrl+"content/items/"+a,b).then(function(a){return new g.PortalItem(c.mixin(a,{portal:this.portal}))})},getIdentity:function(a){return a[this.idProperty]},query:function(a,b){var d=c.isObject(a)?a:{q:a};if(b&&(d=c.mixin(d,{num:b.count,start:(b.start||0)+1}),b.sort&&b.sort.length))var f=
b.sort[0],d=c.mixin(d,{sortField:encodeURIComponent("created"===f.attribute?"uploaded":f.attribute),sortOrder:f.descending?"desc":"asc"});d=this.portal.queryItems(d,!0).then(function(a){a.results.total=a.total;return a.results});return g.PortalResult(d)}});return h([D,E,F,H],{templateString:'\x3cdiv\x3e\x3cp data-dojo-attach-point\x3d"messageNode" class\x3d"hide"\x3e\x3c/p\x3e\x3cdiv style\x3d"width:100%" class\x3d"esriLeadingMargin1"\x3e\x3cselect id\x3d"${id}_categorySelect"class\x3d"categorySelect"\x3e\x3c/select\x3e\x3cdiv id\x3d"${id}_search"class\x3d"esriTrailingMargin2 esriFloatTrailing searchBar"\x3e\x3cinput class\x3d"esriSearchBox dijitTextBox" type\x3d"text" placeholder:\'${i18n.searchFor}\'\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv id\x3d"${id}_grid"class\x3d"dgrid-autoheight"\x3e\x3c/div\x3e\x3cbr /\x3e\x3c/div\x3e',
_galleryTemplate:"\x3cdiv style\x3d'opacity:1;' class\x3d'grid-item gallery-view'\x3e${item:_formatItemTitle}${item:_formatThumbnail}\x3c/div\x3e",_popupTemplate:'\x3cdiv class\x3d"esriBrowsePopup quiet-scroll"\x3e\x3cp\x3e{summary}\x3c/p\x3e\x3c/div\x3e',baseClass:"esriBrowseItems",postMixInProperties:function(){this.inherited(arguments);this.i18n={};c.mixin(this.i18n,I.gallery)},postCreate:function(){this.inherited(arguments);this.self?(this._portal=new g.Portal({url:this.portalUrl,self:this.self}),
this._portal.on("load",c.hitch(this,this._fetchData))):(this._portal=new g.Portal(this.portalUrl),this._portal.signIn().then(c.hitch(this,this._fetchData)))},destroy:function(){this.inherited(arguments);this._grid&&this._grid.destroy();this._img_connect.remove();this._img_connect_error.remove();this._queryTimer&&clearTimeout(this._queryTimer);this._grid=this._portal=null},_setPortalUrlAttr:function(a){this.portalUrl=a},_setSelfAttr:function(a){this.self=a},_setPluginAttr:function(a){this.addPlugin(a)},
_setMessageAttr:function(a){k.set(this.messageNode,"innerHTML",a);m.remove(this.messageNode,"hide")},_setCategoriesAttr:function(a){this.items=a},_setDisabledAttr:function(a){var b=n.findWidgets(this.domNode).concat(n.findWidgets(this._content));q.forEach(b,function(b){b.set("disabled",a)});m[a?"add":"remove"](this._interval.domNode,"dijitTextBoxDisabled")},_setSortAttr:function(a){this.sortAttribute=a},_setSortDescendingAttr:function(a){this.sortDescending=a},_getSelectionAttr:function(){var a=this._grid.selection,
b;for(b in a)if(a.hasOwnProperty(b))break;return b&&this._grid.row(b).data},_setGalleryTemplateAttr:function(a){l.isDefined(a)&&(this._galleryTemplate=a)},_setFormatThumbnailAttr:function(a){l.isDefined(a)&&"function"===typeof a&&(this._formatThumbnail=a)},_setFormatItemTitleAttr:function(a){l.isDefined(a)&&"function"===typeof a&&(this._formatItemTitle=a)},_setItemsPerPageAttr:function(a){this._set("itemsPerPage",a)},_setPagingLinksAttr:function(a){this._set("pagingLinks",a)},_setCategoryTypeAttr:function(a){this._set("categoryType",
a)},_getQueryAttr:function(){return this._grid&&this._grid.get("query")},_setQueryAttr:function(a){this._grid&&this._grid.set("query",a)},_validate:function(){return!!this.get("selection")},_showPopup:function(a){this._closePopup();var b=this._grid.row(a);a=e("img",b.element)[0];if((b={summary:b.data.snippet})&&b.summary)this._tooltip=new v({content:c.replace(this._popupTemplate,b)}),p.open({className:"esriBrowsePopup",popup:this._tooltip,around:a,orient:["after-centered","before-centered"]}),this._onCloseConnect=
e(".dijitDialogCloseIcon",this._tooltip.domNode).on("click",c.hitch(this,function(a){a.preventDefault();this._closePopup()}))},_closePopup:function(){this._tooltip&&(this._onCloseConnect.remove(),p.close(this._tooltip),this._tooltip.destroyRecursive(),this._tooltip=this._onCloseConnect=void 0)},_clearQueryTimeout:function(){clearTimeout(this._queryTimer)},_createGrid:function(){var a=h([x,y,A,J,z]),b=new C(new K({portal:this._portal})),d=this._currentFilter,f=c.hitch(this,function(a){a.snippet=a.snippet||
"";var b=B("div");a=r.substitute(this._galleryTemplate,{item:a,i18n:this.i18n},null,this);u.place(a,b);return b});this._grid=new a({store:b,className:"dgrid-autoheight",query:d,selectionMode:"single",pagingLinks:this.get("pagingLinks")||2,rowsPerPage:this.get("itemsPerPage")||6,loadingMessage:"Loading items...",showLoadingMessage:!1,renderRow:f,sort:[{attribute:"title"}]},this.id+"_grid");this._grid.startup();this.categories&&0<this.categories.length&&(this._categorySelect=new G({options:this.categories,
sortByLabel:!1,"class":"categorySelect"},this.id+"_categorySelect"),this._categorySelect.set("value",this.categories[0].value),this.own(this._categorySelect.on("change",c.hitch(this,function(a){var b;this._origQuery||(this._origQuery=this._grid.get("query"));b=this._origQuery;a&&(b+=" AND ("+this.get("categoryType")+":"+a+")");this._fetchItems(b)}))));this.own(this._grid.on(mouseUtil.enterRow,c.hitch(this,function(a){this._showPopup(a)})),this._grid.on(mouseUtil.leaveRow,c.hitch(this,function(a){this._closePopup(a)})),
this._grid.on("dgrid-refresh-complete",c.hitch(this,function(a){e(".dgrid-footer",this.domNode)[this._grid._total<=this._grid.rowsPerPage?"addClass":"removeClass"]("hide")})),this._grid.on("refresh",c.hitch(this,function(){this._img_connect&&(this._img_connect.remove(),this._img_connect_error.remove(),this._img_connect_error=this._img_connect=null);this._img_connect=e(".grid-item-thumb",this._grid.domNode).on("load",c.hitch(this,function(a){(a=this._grid.row(a))&&a.element&&e(".grid-item",a.element).addClass("fadeIn").style("opacity",
"1")}));this._img_connect_error=e(".grid-item-thumb",this._grid.domNode).on("error",c.hitch(this,function(a){k.set(a.target,"src",this._portal.staticImagesUrl+"/desktopapp.png")}))})),this._grid.on("dgrid-select,dgrid-deselect",c.hitch(this,function(){var a={selection:this.get("selection")};this.emit("select-change",a)})),s(t.byId(this.id+"_search"),"keyup",c.hitch(this,function(a){a.preventDefault();this._clearQueryTimeout();this._queryTimer=setTimeout(c.hitch(this,function(){this._fetchItems(this._currentFilter,
k.get(a.target,"value"))}),this.searchKeypressDelay||250)})))},_fetchData:function(){this._user=this._portal.getPortalUser();return this.plugIn.fetchData()},_fetchItems:function(a,b){var d={sort:[{attribute:this.sortAttribute||"title",descending:this.sortDescending||!1}]},f=b?" title:"+b+"* ":"",e=new w;setTimeout(c.hitch(this,function(){this._currentFilter=a;this._grid?this._grid.set("query",this._currentFilter+f,d):this._createGrid();e.resolve(this._grid)}),60);return e},_formatThumbnail:function(a){return"\x3cimg class\x3d'grid-item-thumb' width\x3d'187px' height\x3d'125px' alt\x3d'' src\x3d'"+
(a.thumbnailUrl||this._portal.staticImagesUrl+"/desktopapp.png")+"'\x3e"},_formatItemTitle:function(a){return"\x3ch5\x3e"+(a.title||a.name||"\x3cNo Title\x3e")+"\x3c/h5\x3e"},clear:function(){this._grid.clearSelection()}})});