// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("../core/declare dojo/_base/lang dojo/_base/array dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/query ../core/lang ../core/domUtils ../geometry/support/units ../geometry/SpatialReference ../geometry/support/WKIDUnitConversion ../geometry/Point ../geometry/ScreenPoint ../geometry/Polyline ../geometry/support/geodesicUtils ../geometry/support/webMercatorUtils ../geometry/support/screenUtils ../geometry/support/normalizeUtils dojo/i18n!../nls/jsapi".split(" "),function(C,
l,k,m,n,D,r,h,s,t,u,v,p,w,x,y,z,q,A,B,E){return C(null,{declaredClass:"esri.widgets.Scalebar",map:null,mapUnit:null,scalebarUnit:null,unitsDictionary:[],domNode:null,screenPt1:null,screenPt2:null,localStrings:E.widgets.scalebar,constructor:function(a,c){this.metricScalebar=n.create("div",{innerHTML:"\x3cdiv class\x3d'esriScaleLabelDiv'\x3e\x3cdiv class\x3d'esriScalebarLabel esriScalebarLineLabel esriScalebarSecondNumber'\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarLine esriScalebarMetricLine'\x3e\x3c/div\x3e"});
this.englishScalebar=n.create("div",{innerHTML:"\x3cdiv class\x3d'esriScalebarLine esriScalebarEnglishLine'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScaleLabelDiv'\x3e\x3cdiv class\x3d'esriScalebarLabel esriScalebarLineLabel esriScalebarSecondNumber'\x3e\x3c/div\x3e\x3c/div\x3e"});this.domNode=n.create("div");a=a||{};if(a.map){if(a.scalebarUnit){if("english"!==a.scalebarUnit&&"metric"!==a.scalebarUnit&&"dual"!==a.scalebarUnit){console.error("scalebar unit only accepts english or metric or dual");return}this.scalebarUnit=
a.scalebarUnit}else this.scalebarUnit="english";if(a.scalebarStyle){if("ruler"!==a.scalebarStyle&&"line"!==a.scalebarStyle){console.error("scalebar style must be ruler or line");return}this.scalebarStyle=a.scalebarStyle}else this.scalebarStyle="ruler";this.background=a.background;switch(this.scalebarUnit){case "english":"ruler"===this.scalebarStyle&&(this.englishScalebar.innerHTML="\x3cdiv class\x3d'esriScalebarRuler'\x3e\x3cdiv class\x3d'esriScalebarRulerBlock upper_firstpiece'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarRulerBlock upper_secondpiece'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarRulerBlock lower_firstpiece'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarRulerBlock lower_secondpiece'\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d'scaleLabelDiv'\x3e\x3cdiv class\x3d'esriScalebarLabel' style\x3d'left: -3%'\x3e0\x3c/div\x3e\x3cdiv class\x3d'esriScalebarLabel esriScalebarFirstNumber'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarLabel esriScalebarSecondNumber'\x3e\x3c/div\x3e\x3c/div\x3e");
this.domNode.appendChild(this.englishScalebar);break;case "metric":"ruler"===this.scalebarStyle&&(this.metricScalebar.innerHTML="\x3cdiv class\x3d'esriScalebarRuler'\x3e\x3cdiv class\x3d'esriScalebarRulerBlock upper_firstpiece'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarRulerBlock upper_secondpiece'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarRulerBlock lower_firstpiece'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarRulerBlock lower_secondpiece'\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d'scaleLabelDiv'\x3e\x3cdiv class\x3d'esriScalebarLabel' style\x3d'left: -3%'\x3e0\x3c/div\x3e\x3cdiv class\x3d'esriScalebarLabel esriScalebarFirstNumber'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarLabel esriScalebarSecondNumber'\x3e\x3c/div\x3e\x3c/div\x3e");
this.domNode.appendChild(this.metricScalebar);break;case "dual":this.domNode.appendChild(this.metricScalebar),this.domNode.appendChild(this.englishScalebar)}this.map=a.map;c?c.appendChild(this.domNode):(this.map.container.appendChild(this.domNode),a.attachTo?m.add(this.domNode,"scalebar_"+a.attachTo):m.add(this.domNode,"scalebar_bottom-left"));m.add(this.domNode,"esriScalebar");if(this.map.loaded)this._getDistance(this.map.extent),this._checkBingMaps();else var b=this.map.on("load",function(){b.remove();
b=null;this._getDistance(this.map.extent);this._checkBingMaps()});this._mapOnPan=this.map.on("pan",this._getDistance.bind(this));this._mapOnExtentChange=this.map.on("extent-change",this._getDistance.bind(this));k.forEach(this.map.layerIds,function(a,b){if("esri.virtualearth.VETiledLayer"===this.map.getLayer(a).declaredClass)this.map.getLayer(a).on("visibility-change",l.hitch(this,function(a){this._checkBingMaps()}))},this);this._mapOnLayerAdd=this.map.on("layer-add",l.hitch(this,function(a){if("esri.virtualearth.VETiledLayer"===
a.declaredClass)a.on("visibility-change",l.hitch(this,function(a){this._checkBingMaps()}));this._checkBingMaps()}));this._mapOnLayerRemove=this.map.on("layer-remove",l.hitch(this,this._checkBingMaps))}else console.error("scalebar: unable to find the 'map' property in parameters")},hide:function(){this._hidden=!0;t.hide(this.domNode)},show:function(){this._hidden=!1;t.show(this.domNode)},destroy:function(){this._mapOnPan.remove();this._mapOnExtentChange.remove();this._mapOnLayerAdd.remove();this._mapOnLayerRemove.remove();
this.hide();this.map=null;n.destroy(this.domNode)},_checkBingMaps:function(){m.contains(this.domNode,"scalebar_bottom-left")&&(r.set(this.domNode,"left","25px"),k.forEach(this.map.layerIds,function(a,c){if("esri.virtualearth.VETiledLayer"===this.map.getLayer(a).declaredClass&&this.map.getLayer(a).visible){var b="95px";this.map._mapParams.nav&&(b="115px");r.set(this.domNode,"left",b)}},this))},_getDistance:function(a){var c=D.position(this.domNode,!0).y-this.map.position.y,c=c>this.map.height?this.map.height:
c,c=0>c?0:c,b=new x(0,c),c=new x(this.map.width,c),f,e;this.mapUnit="esriDecimalDegrees";var d=A.toMapPoint(a,this.map.width,this.map.height,b),g=A.toMapPoint(a,this.map.width,this.map.height,c),b=new w(a.xmin,(a.ymin+a.ymax)/2,this.map.spatialReference),c=new w(a.xmax,(a.ymin+a.ymax)/2,this.map.spatialReference);if(3857===this.map.spatialReference.wkid||102100===this.map.spatialReference.wkid||102113===this.map.spatialReference.wkid||this.map.spatialReference.wkt&&-1!=this.map.spatialReference.wkt.indexOf("WGS_1984_Web_Mercator"))d=
q.webMercatorToGeographic(d,!0),g=q.webMercatorToGeographic(g,!0),b=q.webMercatorToGeographic(b,!0),c=q.webMercatorToGeographic(c,!0);else if(s.isDefined(p[this.map.spatialReference.wkid])||this.map.spatialReference.wkt&&0===this.map.spatialReference.wkt.indexOf("PROJCS")){this.mapUnit="linearUnit";a=Math.abs(a.xmax-a.xmin);if(s.isDefined(p[this.map.spatialReference.wkid]))e=p.values[p[this.map.spatialReference.wkid]];else{e=this.map.spatialReference.wkt;f=e.lastIndexOf(",")+1;var h=e.lastIndexOf("]]");
e=parseFloat(e.substring(f,h))}a*=e;e=a/1609;f=a/1E3}"esriDecimalDegrees"===this.mapUnit&&(a=new y(new v({wkid:4326})),a.addPath([d,g]),d=B._straightLineDensify(a,10),a=z.geodesicLengths([d],u.KILOMETERS)[0],d=new y(new v({wkid:4326})),d.addPath([b,c]),b=B._straightLineDensify(d,10),z.geodesicLengths([b],u.KILOMETERS),e=a/1.609,f=a);"english"===this.scalebarUnit?this._getScaleBarLength(e,"mi"):"metric"===this.scalebarUnit?this._getScaleBarLength(f,"km"):"dual"===this.scalebarUnit&&(this._getScaleBarLength(e,
"mi"),this._getScaleBarLength(f,"km"))},_getScaleBarLength:function(a,c){var b=50*a/this.map.width,f=0,e=c;0.1>b&&("mi"===c?(b*=5280,e="ft"):"km"===c&&(b*=1E3,e="m"));for(;1<=b;)b/=10,f++;var d,g;0.5<b?(d=1,g=0.5):0.3<b?(d=0.5,g=0.3):0.2<b?(d=0.3,g=0.2):0.15<b?(d=0.2,g=0.15):0.1<=b&&(d=0.15,g=0.1);d=d/b>=b/g?g:d;b=50*(d/b);f=Math.pow(10,f)*d;this._drawScaleBar(b,f,e)},_drawScaleBar:function(a,c,b){var f=2*Math.round(a),e,d;"mi"===b||"ft"===b?(this.englishScalebar.style.width=f+"px",a=h(".esriScalebarFirstNumber",
this.englishScalebar),e=h(".esriScalebarSecondNumber",this.englishScalebar),d=h(".esriScalebarMetricLineBackground",this.englishScalebar)):(this.metricScalebar.style.width=f+"px",a=h(".esriScalebarFirstNumber",this.metricScalebar),e=h(".esriScalebarSecondNumber",this.metricScalebar),d=h(".esriScalebarMetricLineBackground",this.metricScalebar));k.forEach(d,function(a,b){a.style.width=f-2+"px"},this);k.forEach(a,function(a,b){a.innerHTML=c},this);k.forEach(e,function(a,d){a.innerHTML="esriUnknown"!==
this.mapUnit?2*c+this.localStrings[b]:2*c+"Unknown Unit"},this)}})});