// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/url dojo/io-query ../kernel ../config ./sniff".split(" "),function(l,n,p,g,u,t){var b={},q=u.request,m=g.appUrl.scheme+":";"file:"===m&&(m="http:");var r={};b.corsServersUrlCache=r;b.burstUrlCache=function(){b.corsServersUrlCache=r={}};b._toURL=function(a){if("string"===typeof a)return new n(b.getAbsoluteUrl(a));a.scheme||(a.scheme=g.appUrl.scheme);return a};b.urlToObject=function(a){var d={},c=new n(a),b=a.indexOf("?");null===c.query?d={path:a,query:null}:(d.path=
a.substring(0,b),d.query=p.queryToObject(c.query));c.fragment&&(d.hash=c.fragment,null===c.query&&(d.path=d.path.substring(0,d.path.length-(c.fragment.length+1))));return d};b.getProxyUrl=function(a,d){var c=l.isString(a)?0===l.trim(a).toLowerCase().indexOf("https:"):a,f=q.proxyUrl,k,e;if(l.isString(a)&&(e=b.getProxyRule(a)))f=e.proxyUrl;if(!f)throw console.log("esriConfig.request.proxyUrl is not set. If making a request to a CORS enabled server, please push the domain into esriConfig.request.corsEnabledServers."),
Error("esriConfig.request.proxyUrl is not set. If making a request to a CORS enabled server, please push the domain into esriConfig.request.corsEnabledServers.");c&&(!1!==d&&"https"===g.appUrl.scheme)&&(c=f,0!==c.toLowerCase().indexOf("http")&&(c=b.getAbsoluteUrl(c)),c=c.replace(/^http:/i,"https:"),b.canUseXhr(c)&&(f=c,k=1));f=b.urlToObject(f);f._xo=k;return f};b.addProxy=function(a){var d=b.getProxyRule(a),c;d?c=b.urlToObject(d.proxyUrl):q.forceProxy&&(c=b.getProxyUrl());c&&(d=b.urlToObject(a),a=
c.path+"?"+d.path,(c=p.objectToQuery(l.mixin(c.query||{},d.query)))&&(a+="?"+c));return a};b.addProxyRule=function(a){var d=b.urlToObject(a.urlPrefix).path.replace(/([^\/])$/,"$1/").replace(/^https?:\/\//ig,"").toLowerCase(),c=q.proxyRules,f,k=c.length,e,g=k;a.urlPrefix=d;for(f=0;f<k;f++){e=c[f].urlPrefix;if(0===d.indexOf(e)){if(d.length===e)return-1;g=f;break}0===e.indexOf(d)&&(g=f+1)}c.splice(g,0,a);return g};b.getProxyRule=function(a){var d=q.proxyRules,c=d.length,f=b.urlToObject(a).path.replace(/([^\/])$/,
"$1/").replace(/^https?:\/\//ig,"").toLowerCase(),g;for(a=0;a<c;a++)if(0===f.indexOf(d[a].urlPrefix)){g=d[a];break}return g};b.hasSameOrigin=function(a,d,c){a=b._toURL(a);d=b._toURL(d);return(c||a.scheme===d.scheme)&&a.host.toUpperCase()===d.host.toUpperCase()&&a.port===d.port};b.canUseXhr=function(a,d){var c=!!t("esri-phonegap"),f=b.hasSameOrigin,k=q.corsEnabledServers||[],e,s,m,h,p,r=-1;l.isString(a)&&(a=a.toLowerCase(),a=0===a.indexOf("http")?new n(a):g.appUrl);if(!c&&t("esri-cors")){s=0;for(m=
k.length;s<m;s++){e=k[s];h=b.corsServersUrlCache;h[e]||(0!==l.trim(e).toLowerCase().indexOf("http")?h[e]=[new n("http://"+e),new n("https://"+e)]:h[e]=[new n(e)]);e=h[e];h=0;for(p=e.length;h<p;h++)if(f(a,e[h])){r=s;c=!0;break}}}return d?r:c};b.getAbsoluteUrl=function(a){return l.isString(a)&&!/^https?:\/\//i.test(a)?0===a.indexOf("//")?m+a:0===a.indexOf("/")?m+"//"+g.appUrl.host+(g.appUrl.port?":"+g.appUrl.port:"")+a:g._appBaseUrl+a:a};b.fixUrl=function(a){return b._ensureProtocol(a).replace(/^(https?:\/\/)(arcgis\.com)/i,
"$1www.$2")};b.normalize=function(a){a=b._ensureProtocol(a);return a=b._ensureProperProtocolForAGOResource(a)};b._ensureProtocol=function(a){var b;if(!a)return a;/^\/\//i.test(a)&&(b=g.appUrl.scheme,a=("file"===b?"https":b)+":"+a);return a};b._ensureProperProtocolForAGOResource=function(a){return"https"===g.appUrl.scheme&&(/^http\:\/\/server\.arcgisonline\.com(?!:)/i.test(a)||/^http\:\/\/services\.arcgisonline\.com(?!:)/i.test(a)||/^http\:\/\/.+\.arcgis\.com(?!:)/i.test(a))?a.replace(/http:/i,"https:"):
a};return b});