// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt for details.
//>>built
define("arcgisonline/coachmarks/tours","dojo/_base/window dojo/_base/declare dojo/_base/array dojo/_base/html dojo/_base/lang dojo/_base/kernel dojo/_base/connect dojo/request/xhr dojo/Deferred dojo/json dijit/registry dojo/dom dojo/dom-construct dojo/dom-class dojo/dom-style dojo/query dojo/aspect dojo/on dojo/has dojo/i18n dojo/request/script esri/kernel esri/lang".split(" "),function(A,r,p,B,g,w,x,C,G,H,D,h,E,s,I,f,k,l,F,J,K,L,q){r={initalizedTours:!1,tourRunning:!1,str_tour_tip_prefix:"tour_tip_",
array_workflowHandlers:[],current_tour:0,current_tour_step:0,html_container_tour_coachmarks:{},div_container_tour_coachmarks:"container_tour_coachmarks",dialogLoading:{},popupWidthDefault:236,init:function(){arcgisonline.coachmarks.tours.setHTMLcontainer();arcgisonline.coachmarks.tours.initalizedTours=!0},setHTMLcontainer:function(){arcgisonline.coachmarks.tours.html_container_tour_coachmarks=E.create("div",{id:"container_tour_coachmarks","class":"tour_coachmarks"},A.body(),"last")},startTour:function(a){a=
parseInt(a);!1==arcgisonline.coachmarks.tours.initalizedTours&&arcgisonline.coachmarks.tours.init();arcgisonline.coachmarks.tours.current_tour=a;var d={},c="";switch(a){case 0:d=esri.i18nBundle.CoachMarksTours.tour0;c="tour_release_2014MarchNew.json";break;case 1:d=esri.i18nBundle.CoachMarksTours.tour1;c="tour_map_intro_makeamap.json";break;case 2:d=esri.i18nBundle.CoachMarksTours.tour2;c="tour_map_intro_styleyourmap.json";break;case 3:d=esri.i18nBundle.CoachMarksTours.tour3;c="tour_map_intro_sharemapworld.json";
break;case 4:d=esri.i18nBundle.CoachMarksTours.tour4;c="tour_map_intro_explorelayers.json";break;default:d={}}arcgisonline.coachmarks.tours.json_tour_coachmarks=arcgisonline.coachmarks.tours.loadTourJSON(c);arcgisonline.coachmarks.tours.json_tour_coachmarks&&(arcgisonline.coachmarks.tours.clearWorkflowHandlers(),arcgisonline.coachmarks.tours.parseCoachMark(a,arcgisonline.coachmarks.tours.json_tour_coachmarks,esri.i18nBundle.CoachMarksTours.instruct,d),arcgisonline.coachmarks.tours.current_tour_step=
1,arcgisonline.coachmarks.tours.setCoachMarkVisible(arcgisonline.coachmarks.tours.str_tour_tip_prefix+arcgisonline.coachmarks.tours.current_tour+"s1",arcgisonline.coachmarks.tours.json_tour_coachmarks.tour_steps[arcgisonline.coachmarks.tours.current_tour_step-1]),arcgisonline.coachmarks.tours.setCoachMarkButtonEvents(),arcgisonline.coachmarks.tours.resizeHandler||(arcgisonline.coachmarks.tours.resizeHandler=x.connect(D.byId("main-content"),"resize",function(){var a=w.query(".display_show");if(a.length){var a=
a[0].id,a=parseInt(a.substring(a.lastIndexOf("s")+1,a.length)),b=arcgisonline.coachmarks.tours.json_tour_coachmarks.tour_steps[a-1],a=h.byId(arcgisonline.coachmarks.tours.str_tour_tip_prefix+arcgisonline.coachmarks.tours.current_tour+"s"+b.id);q.isDefined(b.elementID)?(b=arcgisonline.coachmarks.tours.getCoachMarkPosition(b,a),prompt_offset_x=b.offset_x,prompt_offset_y=b.offset_y):prompt_offset_y=prompt_offset_x=10;a.style.top=prompt_offset_y+"px";a.style.left=prompt_offset_x+"px"}})))},loadTourJSON:function(a){var d=
{};C("../js/arcgisonline/coachmarks/tours/"+a,{handleAs:"json",sync:!0,preventCache:!0}).then(function(a){d=a.tour_coachmarks},function(a){},function(a){});return d},parseCoachMark:function(a,d,c,e){var b="",t="",m=arcgisonline.coachmarks.tours.html_container_tour_coachmarks,n="",y="",u="",v="",g="",z="",h=0,f=0,k=0;arcgisonline.coachmarks.tours.current_tour_step=0;arcgisonline.coachmarks.tours.tourRunning=!0;y=c.help;u=c.next;v=c.finish;d&&p.forEach(d.tour_steps,function(c,m){k=c.contentId;p.forEach(e.steps,
function(a,c){a.id==k&&(g=a.title,z=a.content)});n="showall"==d.tour_type?"display_show":"display_none";if(q.isDefined(c.elementID)){var l=arcgisonline.coachmarks.tours.getCoachMarkPosition(c);h=l.offset_x;f=l.offset_y}else f=h=10;b='\x3cdiv id\x3d"'+arcgisonline.coachmarks.tours.str_tour_tip_prefix+a+"s"+c.id+'" class\x3d"tour_tip popover fade '+c.arrowPosition+" "+c.size+" in "+n+'" style\x3d"top: '+f+"px; left: "+h+'px;"\x3e';b+='\x3cdiv class\x3d"arrow"\x3e\x3c/div\x3e';b+='\x3cdiv class\x3d"popover-inner"\x3e';
b+='\x3ch3 class\x3d"popover-title"\x3e';b+=g;c.showClose&&(b+=' \x3cdiv id\x3d"btnTourClose_'+a+"s"+c.id+'" class\x3d"tour-tip-close close" data-tourid\x3d"'+c.id+'"\x3e\u00d7\x3c/div\x3e');b+="\x3c/h3\x3e";b+='\x3cdiv class\x3d"popover-content"\x3e';b+=z;0<c.showNextID&&c.functionCall&&c.showNext?(b+='\x3cp class\x3d"button_container"\x3e',b+='\x3ca href\x3d"#" id\x3d"btnTourNext_'+a+"s"+c.id+'" class\x3d"tour-tip-next btn calcite blue" onclick\x3d"javascript:'+c.functionCall+' return false;" data-tourstepid\x3d"'+
c.id+'" data-tourstepidx\x3d"'+c.showNextID+'"\x3e'+u+' \x3ci class\x3d"icon-chevron-right icon-white"\x3e\x3c/i\x3e\x3c/a\x3e'):0<c.showNextID&&c.showNext?(b+='\x3cp class\x3d"button_container"\x3e',b+='\x3ca href\x3d"#" id\x3d"btnTourNext_'+a+"s"+c.id+'" class\x3d"tour-tip-next btn calcite blue" data-tourstepid\x3d"'+c.id+'" data-tourstepidx\x3d"'+c.showNextID+'"\x3e'+u+' \x3ci class\x3d"icon-chevron-right icon-white"\x3e\x3c/i\x3e\x3c/a\x3e'):0==c.showNextID&&c.functionCall&&!c.showNext?(b+='\x3cp class\x3d"button_container"\x3e',
b+='\x3ca href\x3d"#" id\x3d"btnTourFinish_'+a+"s"+c.id+'" class\x3d"tour-tip-finish btn calcite blue"  onclick\x3d"javascript:'+c.functionCall+' return false;" data-tourstepid\x3d"'+c.id+'" data-tourstepidx\x3d"0"\x3e'+v+"\x3c/a\x3e"):0==c.showNextID&&!c.showNext?(b+='\x3cp class\x3d"button_container"\x3e',b+='\x3ca href\x3d"#" id\x3d"btnTourFinish_'+a+"s"+c.id+'" class\x3d"tour-tip-finish btn calcite blue"  data-tourstepid\x3d"'+c.id+'" data-tourstepidx\x3d"0"\x3e'+v+"\x3c/a\x3e"):b+='\x3cp class\x3d"button_container"\x3e';
b+="\x3c/p\x3e";c.workflow&&arcgisonline.coachmarks.tours.setDelayLoader(c.id,c.showNextID,c,d.tour_steps);q.isDefined(c.helpDocURL)&&(b+='\x3cdiv class\x3d"tour-help"\x3e',b+='\x3ca href\x3d"'+c.helpDocURL+'" target\x3d"_blank"\x3e',b+='\x3cimg src\x3d"" /\x3e',b+=y,b+="\x3c/a\x3e",b+="\x3c/div\x3e");b+="\x3c/div\x3e";b+="\x3c/div\x3e";b+="\x3c/div\x3e";t+=b});m.innerHTML=t},setCoachMarkButtonEvents:function(){f(".btn.tour-tip-next").on("click",function(a){a&&a.preventDefault();arcgisonline.coachmarks.tours.current_tour_step+=
1;a=a.target.id;a=a.substring(12,a.length);arcgisonline.coachmarks.tours.setCoachMarkHidden(arcgisonline.coachmarks.tours.str_tour_tip_prefix+a);var d=a.substring(a.lastIndexOf("s")+1,a.length),d=parseInt(d)+1;a=a.substring(0,a.lastIndexOf("s")+1)+d;arcgisonline.coachmarks.tours.setCoachMarkVisible(arcgisonline.coachmarks.tours.str_tour_tip_prefix+a,arcgisonline.coachmarks.tours.json_tour_coachmarks.tour_steps[arcgisonline.coachmarks.tours.current_tour_step-1])});f(".btn.tour-tip-previous").on("click",
function(a){a&&a.preventDefault();arcgisonline.coachmarks.tours.current_tour_step-=1;a=a.target.id;a=a.substring(12,a.length);arcgisonline.coachmarks.tours.setCoachMarkHidden(arcgisonline.coachmarks.tours.str_tour_tip_prefix+a);var d=a.substring(a.lastIndexOf("s")+1,a.length),d=parseInt(d)-1;a=a.substring(0,a.lastIndexOf("s")+1)+d;arcgisonline.coachmarks.tours.setCoachMarkVisible(arcgisonline.coachmarks.tours.str_tour_tip_prefix+a,arcgisonline.coachmarks.tours.json_tour_coachmarks.tour_steps[arcgisonline.coachmarks.tours.current_tour_step-
1])});f(".tour-tip-close.close").on("click",function(a){a.preventDefault();a=a.target.id;a=a.substring(13,a.length);arcgisonline.coachmarks.tours.setCoachMarkHidden(arcgisonline.coachmarks.tours.str_tour_tip_prefix+a);arcgisonline.coachmarks.tours.tourRunning=!1;arcgisonline.coachmarks.tours.clearWorkflowHandlers()});f(".tour-tip-finish.btn").on("click",function(a){a.preventDefault();a=a.target.id;a=a.substring(14,a.length);arcgisonline.coachmarks.tours.clearWorkflowHandlers();arcgisonline.coachmarks.tours.setCoachMarkHidden(arcgisonline.coachmarks.tours.str_tour_tip_prefix+
a);arcgisonline.coachmarks.tours.tourRunning=!1;arcgisonline.coachmarks.tours.reloadViewerCoachMarksTours()})},setDelayLoader:function(a,d,c,e){if(c.workflow.then){var b=eval(c.workflow.dojoWidgetInstance);"after"===c.workflow.dojoWidgetEventType?arcgisonline.coachmarks.tours.array_workflowHandlers.push(k.after(b,c.workflow.dojoWidgetEvent,function(b){b=eval(c.workflow.then.dojoWidgetInstance);arcgisonline.coachmarks.tours.addToWorkflowHandler(b,c.workflow.then.dojoWidgetEventType,c.workflow.then.dojoWidgetEvent,
a,d,c,e)})):"before"===c.workflow.dojoWidgetEventType?arcgisonline.coachmarks.tours.array_workflowHandlers.push(k.before(b,c.workflow.dojoWidgetEvent,function(b){b=eval(c.workflow.then.dojoWidgetInstance);arcgisonline.coachmarks.tours.addToWorkflowHandler(b,c.workflow.then.dojoWidgetEventType,c.workflow.then.dojoWidgetEvent,a,d,c,e)})):"once"===c.workflow.dojoWidgetEventType?arcgisonline.coachmarks.tours.array_workflowHandlers.push(l.once(b,c.workflow.dojoWidgetEvent,function(b){b=eval(c.workflow.then.dojoWidgetInstance);
arcgisonline.coachmarks.tours.addToWorkflowHandler(b,c.workflow.then.dojoWidgetEventType,c.workflow.then.dojoWidgetEvent,a,d,c,e)})):arcgisonline.coachmarks.tours.array_workflowHandlers.push(l(b,c.workflow.dojoWidgetEvent,function(b){b=eval(c.workflow.then.dojoWidgetInstance);arcgisonline.coachmarks.tours.addToWorkflowHandler(b,c.workflow.then.dojoWidgetEventType,c.workflow.then.dojoWidgetEvent,a,d,c,e)}))}else c.workflow.dojoWidgetInstance&&(b=eval(c.workflow.dojoWidgetInstance),arcgisonline.coachmarks.tours.addToWorkflowHandler(b,
c.workflow.dojoWidgetEventType,c.workflow.dojoWidgetEvent,a,d,c,e))},addToWorkflowHandler:function(a,d,c,e,b,f,m){var n=function(a,b,c,d,e){arcgisonline.coachmarks.tours.setCoachMarkHidden(arcgisonline.coachmarks.tours.str_tour_tip_prefix+arcgisonline.coachmarks.tours.current_tour+"s"+a);a=arcgisonline.coachmarks.tours.getJsonObjById(d,b);c=h.byId(arcgisonline.coachmarks.tours.str_tour_tip_prefix+arcgisonline.coachmarks.tours.current_tour+"s"+b);e=arcgisonline.coachmarks.tours.getCoachMarkPosition(a,
c);prompt_offset_x=e.offset_x;prompt_offset_y=e.offset_y;c.style.top=prompt_offset_y+"px";c.style.left=prompt_offset_x+"px";arcgisonline.coachmarks.tours.setCoachMarkVisible(arcgisonline.coachmarks.tours.str_tour_tip_prefix+arcgisonline.coachmarks.tours.current_tour+"s"+b,a);arcgisonline.coachmarks.tours.setDelayLoader(b,a.showNextID,a,d)};"after"===d?arcgisonline.coachmarks.tours.array_workflowHandlers.push(k.after(a,c,g.partial(n,e,b,f,m))):"before"===d?arcgisonline.coachmarks.tours.array_workflowHandlers.push(k.before(a,
c,g.partial(n,e,b,f,m))):"once"===d?arcgisonline.coachmarks.tours.array_workflowHandlers.push(l.once(a,c,g.partial(n,e,b,f,m))):arcgisonline.coachmarks.tours.array_workflowHandlers.push(l(a,c,g.partial(n,e,b,f,m)))},clearWorkflowHandlers:function(){arcgisonline.coachmarks.tours.array_workflowHandlers.length&&p.forEach(arcgisonline.coachmarks.tours.array_workflowHandlers,function(a){a.remove()});arcgisonline.coachmarks.tours.resizeHandler&&(x.disconnect(arcgisonline.coachmarks.tours.resizeHandler),
arcgisonline.coachmarks.tours.resizeHandler=null)},getJsonObjById:function(a,d){var c={};p.forEach(a,function(a,b){a.id==d&&(c=a)});return c},getCoachMarkPosition:function(a,d){var c=arcgisonline.coachmarks.tours.popupWidthDefault,e={};if(a.elementID){var b=arcgisonline.coachmarks.tours.getNode(a.elementID);if(b){if(b=B.coords(b,!0),e.offset_x=esriGeowConfig.isRightToLeft?"leading"===a.arrowPosition?b.x+b.w-a.h_offset:"trailing"===a.arrowPosition?b.x-c-a.h_offset-10:"bottom"===a.arrowPosition?b.x-
c/2+a.h_offset:b.x+b.w-c-a.h_offset:"leading"===a.arrowPosition?b.x-c+a.h_offset-10:"trailing"===a.arrowPosition?b.x+b.w+a.h_offset:"bottom"===a.arrowPosition?b.x-c/2+a.h_offset:b.x+a.h_offset,e.offset_y=b.y+a.top,d&&("leading"===a.arrowPosition||"trailing"===a.arrowPosition))c=dojo.coords(d).h/2,e.offset_y-=c}else e.offset_x=5,e.offset_y=5}else e.offset_x=5,e.offset_y=5;return e},setCoachMarkHidden:function(a){s.replace(a,"display_none","display_show")},setCoachMarkVisible:function(a,d){w.query(".display_show").forEach(function(a){s.replace(a,
"display_none","display_show")});s.replace(a,"display_show","display_none");if(q.isDefined(d.elementID)){var c=dojo.byId(a);setTimeout(function(){var a=arcgisonline.coachmarks.tours.getCoachMarkPosition(d,c);c.style.top=a.offset_y+"px";c.style.left=a.offset_x+"px"},1)}},reloadViewerCoachMarksTours:function(){arcgisonline.coachmarks.tours.clearWorkflowHandlers();arcgisonline.map.leftPanel.openLeftAboutPanel(null,{showTakeATour:!0})},getNode:function(a){var d=null;if(a.startsWith("dojo.")||a.startsWith("dijit."))try{d=
h.byId(eval(a))}catch(c){d=null}else d=h.byId(a);return d}};F("extend-esri")&&g.setObject("arcgisonline.coachmarks.tours",r);return r});