// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define({root:{panes:{slides:"Slides",properties:"Properties",advancedSettings:"Advanced Settings",modifyScene:"Modify",contents:"Contents",addLayers:"Add Layers",enterLayerUrl:"Enter Layer URL",configureLayer:"Configure Layer"},buttons:{saveScene:"Save Scene",addGroup:"Create Layer Group...",save:"Save",cancel:"Cancel",add:"Add",remove:"Remove",done:"Done",importLayer:"Import",saveTooltip:"Save Scene (Ctrl+S)"},dialogs:{webSceneSaveOk:"Web Scene Saved",webSceneSaveFailed:"Saving Web Scene failed",
addLayer:"Add Layer"},messages:{webSceneSaved:"Web Scene saved successfully to 'My Content'.",webSceneSavedShared:"Web Scene saved successfully to content of ${sceneowner}.",viewItemDetails:"View item details",addLayerFailed:"Layer cannot be added",pendingChangesConfirm:"Your unsaved scene changes will be lost."},contentsPane:{newGroup:"New group"},addLayerPane:{by:"by",searchForLayer:"Search for layer...",search:"Search",myContent:"My Content",content:"Content",noResult:"No matching results found.",
featuredContent:"Esri Featured Content",more:"More..."},addLayerByUrlPane:{addingLayer:"Adding layer to map...",layerUrl:"Layer URL",layerName:"Layer Name",placeholderLayerUrl:"e.g. http://server.esri.com/water/MapServer",placeholderLayerName:"e.g. Waterways"},editBasemapPane:{basemap:"Basemap",elevation:"Elevation",elevationInBasemap:"Elevation in basemap",elevationOn:"Elevation on",elevationOff:"Elevation off"},editLayerPane:{elevation:"Elevation",elevationMode:"Elevation Mode",mode:"Mode",advancedSymbology:"Advanced Symbology",
popups:"Pop-ups",onTheGround:"On the ground",relativeToGround:"Relative to ground",absoluteHeight:"Absolute height",elevationOffsetMeters:"Elevation offset (meters)",offsetMeters:"Offset (meters)",popupsOn:"Pop-ups on",popupsOff:"Pop-ups off",labels:"Labels",labelsOn:"Labels on",labelsOff:"Labels off",layerType:"Layer type:",geometryType:"Geometry type:",point:"Point",lines:"Line",polygon:"Polygon",mesh:"Mesh",enabled:"Enabled",disabled:"Disabled",zoomTo:"Zoom to",legend:"Legend",transparency:"Transparency"},
sceneProperties:{title:"Title",summary:"Summary",tags:"Tags",thumbnail:"Thumbnail",placeholderEnterTitle:"Enter a title...",placeholderEnterSummary:"Summary of the scene (optional)",placeholderEnterTags:"Add tag(s)",copyTitle:"Copy of ${scenetitle} by ${sceneauthor}",elevation:"Elevation",updateThumbnail:"Update Thumbnail",clipping:"Clip to Extent",currentView:"Update To Current View",elevationUnsupported:"Default elevation layer does not match the basemap spatial reference and tiling scheme."},saveDialog:{saveInitialViewpoint:"Save current as initial viewpoint",
saveInitialState:"Save current state as initial scene state",saveAs:"Save as new scene",websceneTitleExists:"A Scene with this title already exists.",saveAsNewScene:"Scene needs to be saved as new item.",invalidTitle:"The title cannot contain any of these characters: \x3c or \x3e.",invalidSummary:"The summary cannot contain any of these characters: \x3c or \x3e.",owner:"owned by ${ownerName}",ownerMe:"owned by me",myContent:"My Content",otherContent:"${sceneowner}",location:"Save at",choseLocation:"Please choose a location",
overwriteScene:"This will overwrite the existing item",copyScene:"This will create a new item",confirmOverwrite:"A scene with the same name already exists.",confirmOverwrite2:"A scene with the same name already exists and will be overwritten.",confirmOverwriteQuestion:"Do you want to overwrite it?",confirmOverwriteYes:"Yes, Overwrite",confirmOverwriteCancel:"Cancel",confirmOverwriteNo:"No"},confirmDialog:{confirm:"Confirm",cancelButton:"Cancel"},navigationContainer:{closeOpen:"Close Editor",open:"Open",
back:"Back"}},ar:1,cs:1,da:1,de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,it:1,ja:1,ko:1,lt:1,lv:1,nl:1,nb:1,pl:1,"pt-br":1,"pt-pt":1,ro:1,ru:1,sv:1,th:1,tr:1,vi:1,"zh-cn":1});