// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define({root:{defaultWebSceneName:"My Scene",menu:{titleLayers:"Layers",titleEnvironmentSettings:"Environment",titleSearch:"Search",titleBasemap:"Basemap",errorSceneServiceLoad:"Scene Service load error",errorLayerName:"Layer name:",titleLegend:"Legend",titleSettings:"Settings",titleShare:"Share",moreTools:"More Tools"},dialogs:{webscene:"Web Scene",addLayer:"Add Layer",layerDidNotDrawCompletely:"Layer did not draw completely",webglCheck:"WebGL check",browserCheck:"Browser check",browserFail:"The Scene Viewer can't be opened in your browser.",
unsupportedBasemap:"Basemap is not supported"},messages:{addLayerFailed:"Layer cannot be added",layerAddedSuccess:"Layer added successfully.",layerDidNotDrawCompletely:"did not draw completely because the server transfer limit of ${limit} features was exceeded.",layerTypeNotSupported:"Layer type not supported:",onlyTiledLayerSupported:"Only Tiled Map Layers are supported.",layerItemTypeNotSupported:"Layer item type not supported:",layerItemPropertiesFromMapServer:"Display properties saved in Map Layer items are not supported.",
layerItemPropertiesNotApplied:"Display properties saved in the Layer item were not applied.",itemId:"Item ID:",itemType:"Item type:",websceneLoadFail:"Cannot load Web Scene.",websceneLoadFailNoVersion:"No version found in Web Scene.",websceneLoadFailBadVersion:"Invalid version ${websceneVersion} in Web Scene.",websceneLoadFailIncompatVersion:"Web Scene version ${websceneVersion} is not compatible with this viewer",websceneVersionRequires:"(requires ${websceneRequiredVersion})",websceneVersionMoreRecent:"Web Scene (version ${websceneVersion}) is more recent than viewer version {$viewerVersion}.",
webscenePotentiallyUnsupported:"Parts of Web Scene content might not be supported and might not display as expected.",websceneGlobalSR:"Global Web Scene needs to be in Web Mercator.",websceneGlobalEmbeddedSR:"Spatial references in global Web Scenes need to be Web Mercator or WGS84 GCS.",websceneLocalSRGCS:"Local Web Scenes in geographic coordinates are not supported.",tiledMapServicesMinVersion:"Tiled Map Layers on servers prior to 10.2.2 are not supported.",tiledMapServicesMinVersionPatch:"Tiled Map Layers from 10.2.2 servers are only supported if all server updates have been applied.",
sceneLayerVersion:"Scene Layer version is not supported.",sceneLayerSRWM:"Scene Layers need to be in Web Mercator.",sceneLayerSR:"Scene Layers need to match the scene spatial reference.",sceneLayerSRGCS:"Scene Layers in geographic coordinate systems are not supported in local scenes.",tiledMapServicesSR:"Tiled Map Layers need to be in Web Mercator.",tiledMapServicesSRGeneric:"Tiled Map Layers need to match the scene spatial reference and tiling scheme.",tiledMapServiceSRGCS:"Tiled Map Layers in geographic coordinate systems are not supported.",
tiledImageServicesSRGeneric:"Tiled Image Layers need to match the scene spatial reference and tiling scheme.",tiledImageServiceSRGCS:"Tiled Image Layers in geographic coordinate systems are not supported.",tiledElevationServicesSRGeneric:"Elevation Layers need to match the scene spatial reference and tiling scheme.",tilingSchemePowerOfTwo:"Incompatible tiling scheme: each scale must be exactly half of the scale of the preceding level.",tilingSchemeTileSize:"Incompatible tiling scheme: only tiles with width and height 256 are supported.",
tilingSchemeGaps:"Incompatible tiling scheme: gaps between levels are not supported.",tilingSchemeGeneric:"Incompatible tiling scheme.",patchRequired:"Patch(es) required:",elevationImageServicesSR:"Elevation Layers need to be in Web Mercator.",imageServicesSR:"Tiled Image Layers need to be in Web Mercator.",tiledMapServicesTilingScheme:"Tiled Map Layers need to adhere to ArcGIS Online Tiling Scheme.",tiledImageServicesTilingScheme:"Tiled Image Layers need to adhere to ArcGIS Online Tiling Scheme.",
elevationImageServicesTilingScheme:"Elevation Layers need to adhere to ArcGIS Online Tiling Scheme.",imageServicesCached:"Only cached Image Servers are supported.",elevationImageServicesCached:"Only cached Image Servers with LERC encoding are supported.",elevationBasemapTitle:"Default elevation layer cannot be added",elevationBasemapSR:"Elevation layer spatial reference does not match basemap spatial reference.",elevationBasemapTS:"Elevation layer tiling scheme is not compatible with basemap tiling scheme.",
featureServiceNotSupportedTable:"Type Table is not supported.",featureServiceNotSupportedMultipatch:"Multipatch Feature Services are not supported.",featureServiceNotSupportedNoRenderer:"Services without a renderer are not supported.",featureServiceNotSupportedRendererType:"Renderer type is not supported:",featureServiceNotSupportedMaxFeatures:"feature service exceeds max feature limit:",featureServiceNotSupportedMaxVertices:"feature service exceeds max vertices limit:",splashSignInToEdit:"Sign in to explore the world in 3D and add layers from Esri and thousands of organizations to create new scenes.",
splashShowThisOnStart:"show this on startup",splashNewToArcGIS:"New to ArcGIS? Sign up for a trial subscription today.",splashLookAtOtherScenes:"Here's a look at some of the scenes you can explore.",selectedBasemapMismatchTitle:"Selected basemap cannot be used",selectedBasemapMismatch:"The basemap's spatial reference and tiling scheme is not compatible with the scene.\nCreate a new scene to use this basemap.",serviceName:"Service name",basemapDrop:"The layer has a different spatial reference and tiling scheme than the basemap.\x3cBR\x3eDo you want to drop the basemap in order to add the layer?",
basemapDropConfirm:"Drop Basemap",basemapDropTitle:"Data Mismatch",BasemapDropWarningTitle:"Basemap was dropped",BasemapDropWarning:"The basemap's spatial reference and tiling scheme is not compatible with the layer and was therefore dropped.",sceneRejectTitle:"Scene cannot be imported",sceneRejectG2L:"A Global scene cannot be imported into a local scene.",sceneRejectL2G:"A Local scene cannot be imported into a global scene.",sceneRejectSRTS:"The selected scene's spatial reference does not match the current scene spatial reference.",
unsupportedSymbolType:"Symbol not supported",unsupportedSymbolLayerType:"Symbol layer not supported",unsupportedSymbology:"Parts of symbology not supported",layerDisplaysWithServiceSymbology:"Layer is displayed with service symbology.",layerDisplaysWithItemSymbology:"Layer is displayed with item symbology.",layerDisplaysWithDefaultSymbology:"Layer is displayed with default symbology.",layerDisplaysWithFallbackSymbology:"Layer is displayed with fallback symbology.",layerCreationErrorGeneric:"Error during layer creation.",
layerDisplaysNotAsExpected:"Layer might not display as expected.",byReferenceRendererUnsupported:"By reference renderer could not be created",geometryServiceUnavailableTitle:"Problem with Geometry Service",geometryServiceUnavailable:"Geometry service is not responding or not configured correctly. Lighting in the scene might be incorrect.",invalidUrl:"Invalid URL",unsupportedUrl:"Unsupported URL"},webglMessages:{badhardware:"Unable to create WebGL context.\x3cbr\x3ePerhaps WebGL is disabled in your browser, or your hardware does not to support WebGL.",
troubleshoot:'Troubleshoot problems at \x3ca href\x3d"http://get.webgl.org" target\x3d"_blank"\x3eget.webgl.org\x3c/a\x3e',badbrowser:"Your browser does not seem to support WebGL.",help:"Help",mobile:"Web Scene Viewer is not supported on mobile devices.",learnMore:"Learn more",layerInfo:"${LayerType} by ${Author}"},buttons:{signIn:"Sign In",tryArcGIS:"Try ArcGIS",visitGallery:"Visit The Gallery",fullScreen:"Full Screen",exitFullScreen:"Exit Full Screen"},appName:"3D Scene Viewer"},ar:1,cs:1,da:1,
de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,it:1,ja:1,ko:1,lt:1,lv:1,nl:1,nb:1,pl:1,"pt-br":1,"pt-pt":1,ro:1,ru:1,sv:1,th:1,tr:1,vi:1,"zh-cn":1,"zh-hk":1,"zh-tw":1});