// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.0beta2/esri/copyright.txt for details.
//>>built
define({panes:{slides:"Diapositivas",properties:"Propiedades",advancedSettings:"Configuraci\u00f3n avanzada",modifyScene:"Modificar",contents:"Contenido",addLayers:"Agregar capas",enterLayerUrl:"Introducir URL de capa",configureLayer:"Configurar capa"},buttons:{saveScene:"Guardar escena",addGroup:"Crear grupo de capas...",save:"Guardar",cancel:"Cancelar",add:"Agregar",remove:"Quitar",done:"Hecho",importLayer:"Importar",saveTooltip:"Guardar escena (Ctrl+S)"},dialogs:{webSceneSaveOk:"Escena web guardada",
webSceneSaveFailed:"Error al guardar escena web",addLayer:"Agregar capa"},messages:{webSceneSaved:"La escena web se ha guardado correctamente en Mi contenido.",webSceneSavedShared:"La escena web se ha guardado correctamente en el contenido de ${sceneowner}.",viewItemDetails:"Ver detalles de elemento",addLayerFailed:"No se puede agregar la capa",pendingChangesConfirm:"Los cambios en la escena que no se hayan guardado se perder\u00e1n."},contentsPane:{newGroup:"Nuevo grupo"},addLayerPane:{by:"de",searchForLayer:"Buscar capa...",
search:"Buscar",myContent:"Mi contenido",content:"Contenido",noResult:"No se han encontrado coincidencias.",featuredContent:"Contenido destacado de Esri",more:"M\u00e1s..."},addLayerByUrlPane:{addingLayer:"Agregando capa a mapa...",layerUrl:"URL de capa",layerName:"Nombre de capa",placeholderLayerUrl:"p. ej. http://server.esri.com/water/MapServer",placeholderLayerName:"p. ej. Waterways"},editBasemapPane:{basemap:"Mapa base",elevation:"Elevaci\u00f3n",elevationInBasemap:"Elevaci\u00f3n en el mapa base",
elevationOn:"Elevaci\u00f3n activada",elevationOff:"Elevaci\u00f3n desactivada"},editLayerPane:{elevation:"Elevaci\u00f3n",elevationMode:"Modo de elevaci\u00f3n",mode:"Modo",advancedSymbology:"Simbolog\u00eda avanzada",popups:"Ventanas emergentes",onTheGround:"En el suelo",relativeToGround:"En relaci\u00f3n con el suelo",absoluteHeight:"Altura absoluta",elevationOffsetMeters:"Desplazamiento de la elevaci\u00f3n (metros)",offsetMeters:"Desplazamiento (metros)",popupsOn:"Ventanas emergentes activadas",
popupsOff:"Ventanas emergentes desactivadas",labels:"Etiquetas",labelsOn:"Activar etiquetas",labelsOff:"Desactivar etiquetas",layerType:"Tipo de capa:",geometryType:"Tipo de geometr\u00eda:",point:"Punto",lines:"L\u00ednea",polygon:"Pol\u00edgono",mesh:"Malla",enabled:"Habilitado",disabled:"Deshabilitado",zoomTo:"Zoom a",legend:"Leyenda",transparency:"Transparencia"},sceneProperties:{title:"T\u00edtulo",summary:"Resumen",tags:"Etiquetas",thumbnail:"Miniatura",placeholderEnterTitle:"Introduce un t\u00edtulo...",
placeholderEnterSummary:"Resumen de la escena (opcional)",placeholderEnterTags:"Agregar etiquetas",copyTitle:"Copia de ${scenetitle} de ${sceneauthor}",elevation:"Elevaci\u00f3n",updateThumbnail:"Actualizar miniatura",clipping:"Recortar la extensi\u00f3n",currentView:"Actualizar a la vista actual",elevationUnsupported:"La capa de elevaci\u00f3n predeterminada no coincide con la referencia espacial y el esquema de ordenamiento en teselas del mapa base."},saveDialog:{saveInitialViewpoint:"Guardar el punto de vista actual como inicial",
saveInitialState:"Guardar el estado actual como estado inicial de la escena",saveAs:"Guardar como escena nueva",websceneTitleExists:"Ya existe una escena con este t\u00edtulo.",saveAsNewScene:"Es necesario guardar la escena como elemento nuevo.",invalidTitle:"El t\u00edtulo no puede contener estos caracteres: \x3c or \x3e.",invalidSummary:"El resumen no puede contener ninguno de estos caracteres: \x3c or \x3e.",owner:"propiedad de ${ownerName}",ownerMe:"de mi propiedad",myContent:"Mi contenido",otherContent:"${sceneowner}",
location:"Guardar en",choseLocation:"Elige una ubicaci\u00f3n",overwriteScene:"Esto sobrescribir\u00e1 el elemento existente",copyScene:"Esto crear\u00e1 un nuevo elemento",confirmOverwrite:"Ya existe una escena con el mismo nombre.",confirmOverwrite2:"Ya existe una escena con el mismo nombre y se sobrescribir\u00e1.",confirmOverwriteQuestion:"\u00bfDeseas sobrescribirla?",confirmOverwriteYes:"S\u00ed, sobrescribir",confirmOverwriteCancel:"Cancelar",confirmOverwriteNo:"No"},confirmDialog:{confirm:"Confirmar",
cancelButton:"Cancelar"},navigationContainer:{closeOpen:"Cerrar el editor",open:"Abrir",back:"Atr\u00e1s"}});